### ISSUE TITLE
Improve error message when git is not installed and using a git fetcher

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#1270]
### Description

When using inspec 1.2.1 I get "Unable to resolve master to a specific git commit" when attempting to run an inspec profile from a git repo when GIT binary is not installed.

### InSpec and Platform Version

1.2.1
ubuntu 14.04 no git installed

### Replication Case

Run an inspec profile from a git repo on a node that does not have git binary installed.

### Possible Solutions

If possible, can this code be changed to give a hint to the user that the git binary needs to be installed? https://github.com/chef/inspec/blob/master/lib/fetchers/git.rb#L85-L92

### Stacktrace

```
[2016-11-01T20:06:53+00:00] ERROR: Report handler Chef::Handler::AuditReport raised #<RuntimeError: Unable to resolve master to a specific git commit for https://github.com/dev-sec/ssl-benchmark.git>
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/fetchers/git.rb:89:in `resolve_ref'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/fetchers/git.rb:81:in `resolved_ref'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/fetchers/git.rb:60:in `cache_key'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/cached_fetcher.rb:32:in `cache_key'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/cached_fetcher.rb:39:in `fetch'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile.rb:39:in `for_fetcher'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile.rb:45:in `for_target'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/runner.rb:157:in `add_target'
[2016-11-01T20:06:53+00:00] ERROR: /var/chef/cache/handler/audit_report.rb:97:in `block in call'
[2016-11-01T20:06:53+00:00] ERROR: /var/chef/cache/handler/audit_report.rb:97:in `each'
[2016-11-01T20:06:53+00:00] ERROR: /var/chef/cache/handler/audit_report.rb:97:in `call'
[2016-11-01T20:06:53+00:00] ERROR: /var/chef/cache/handler/audit_report.rb:43:in `block in report'
[2016-11-01T20:06:53+00:00] ERROR: /var/chef/cache/handler/audit_report.rb:33:in `each'
[2016-11-01T20:06:53+00:00] ERROR: /var/chef/cache/handler/audit_report.rb:33:in `report'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/handler.rb:259:in `run_report_unsafe'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/handler.rb:247:in `run_report_safely'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/handler.rb:125:in `block in run_report_handlers'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/handler.rb:123:in `each'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/handler.rb:123:in `run_report_handlers'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/handler.rb:135:in `block in <class:Handler>'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:440:in `block in run_completed_successfully'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:439:in `each'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:439:in `run_completed_successfully'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:298:in `run'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:302:in `block in fork_chef_client'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork_chef_client'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:255:in `block in run_chef_client'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:243:in `run_chef_client'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `loop'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `interval_run_chef_client'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:434:in `run_application'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:60:in `run'
[2016-11-01T20:06:53+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/bin/chef-client:26:in `<top (required)>'
[2016-11-01T20:06:53+00:00] ERROR: /usr/bin/chef-client:54:in `load'
[2016-11-01T20:06:53+00:00] ERROR: /usr/bin/chef-client:54:in `<main>'
```

**Comment by chris-rock** [comment]
@jeremymv2 We will not support downloading from git on nodes that have not git installed. I agree, we should improve the error message? Is that the expected response?

**Comment by anweiss** [comment]
This also occurs when using the `chef/inspec:latest` Docker image as Git does not seemed to be added to the [Dockerfile](https://github.com/chef/inspec/blob/master/Dockerfile)

**Comment by chris-rock** [comment]
@anweiss Yes, that is correct. InSpec uses native git package. We need to add this to the Docker image.

**Comment by Vasu1105** [comment]
This is taken care I have tested with `4.26.13` 
Following is the output of running the profile from git from the system which don't have git binaries
```
$ inspec exec https://github.com/Vasu1105/test-profile.git
Profile git dependency failed for https://github.com/Vasu1105/test-profile.git - error running 'git ls-remote "https://github.com/Vasu1105/test-profile.git" "master*"': sh: git: command not found

```
Closing this.
