### ISSUE TITLE
401 error message for profile uploads

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1449]
### Description

```
inspec compliance upload myprofile
Profile is already vendored. Use --overwrite.
I, [2017-01-06T10:19:40.122775 #88774]  INFO -- : Checking profile in myprofile
I, [2017-01-06T10:19:40.122929 #88774]  INFO -- : Metadata OK.
I, [2017-01-06T10:19:42.299947 #88774]  INFO -- : Found 167 controls.
Profile is valid
/opt/inspec/embedded/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
                from /opt/inspec/embedded/lib/ruby/2.3.0/net/http.rb:933:in `connect'
                from /opt/inspec/embedded/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
                from /opt/inspec/embedded/lib/ruby/2.3.0/net/http.rb:852:in `start'
                from /opt/inspec/embedded/lib/ruby/2.3.0/net/http.rb:584:in `start'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.1/lib/bundles/inspec-compliance/http.rb:71:in `send_request'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.1/lib/bundles/inspec-compliance/http.rb:20:in `get'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.1/lib/bundles/inspec-compliance/api.rb:16:in `profiles'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.1/lib/bundles/inspec-compliance/api.rb:67:in `exist?'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.1/lib/bundles/inspec-compliance/cli.rb:164:in `upload'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
                from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.1/bin/inspec:12:in `<top (required)>'
                from /usr/local/bin/inspec:22:in `load'
                from /usr/local/bin/inspec:22:in `<main>'
```

The user was authenticated via `inspec compliance login_automate https://example.com --user admin --ent='adm' --dctoken ''`

When the token is not valid anymore, the user only sees the 401. Instead we should show that the authentication failed and the token may be invalid.

### InSpec and Platform Version

1.11.0

### Possible Solutions

Add a more helpful error message.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
