### ISSUE TITLE
inspec compliance login* should support a hostname for the SERVER argument

### ISSUE THREAD

**Issue by billmeyer** [inspec/inspec#1473]
### Description

inspec compliance login SERVER and inspec compliance login_automate SERVER don't specify if SERVER argument is a hostname or a URL.  When using a hostname, the login will fail with an exception (see below).

### InSpec and Platform Version

1.7.2

### Replication Case

$ inspec compliance login chefcompliance01.billmeyer.corp --insecure --user='bmeyer' --token='eyJh...qqpQ'

### Possible Solutions

Accept either a hostname or a URL.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

```
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/bundles/inspec-compliance/http.rb:70:in `send_request': Unable to parse URI: chefcompliance01.billmeyer.corp/api/version (RuntimeError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/bundles/inspec-compliance/http.rb:20:in `get'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/bundles/inspec-compliance/api.rb:55:in `version'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/bundles/inspec-compliance/cli.rb:298:in `store_access_token'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/bundles/inspec-compliance/cli.rb:45:in `login'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/bin/inspec:12:in `<top (required)>'
	from /opt/chefdk/embedded/bin/inspec:22:in `load'
	from /opt/chefdk/embedded/bin/inspec:22:in `<main>'
```

**Comment by arlimus** [comment]
For solution see https://github.com/chef/inspec/pull/1471

**Comment by arlimus** [comment]
Another error in the same category discovered by @billmeyer

```
Profile is valid
Start upload to bmeyer/cis-rhel6-level1
Uploading to Chef Automate
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/bundles/inspec-compliance/http.rb:42:in `post_file': Unable to parse URL: chefautomate01/compliance/profiles/bmeyer (RuntimeError)
```
