### ISSUE TITLE
cannot load such file -- nokogiri

### ISSUE THREAD

**Issue by grv87** [inspec/inspec#1562]
Looks like library uses nokogiry inside, but it isn't declared as dependency.

InSpec version 0.16.1

I use `kitchen-inspec` plugin. Stacktrace:
```
E, [2017-03-14T22:50:05.838100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: ------Exception-------
E, [2017-03-14T22:50:05.838100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: Class: LoadError
E, [2017-03-14T22:50:05.838100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: Message: cannot load such file -- nokogiri
E, [2017-03-14T22:50:05.838100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: ----------------------
E, [2017-03-14T22:50:05.838100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: ------Backtrace-------
E, [2017-03-14T22:50:05.839100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/inspec-1.16.1/lib/inspec/rspec_json_formatter.rb:803:in `require'
E, [2017-03-14T22:50:05.839100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/inspec-1.16.1/lib/inspec/rspec_json_formatter.rb:803:in `close'
E, [2017-03-14T22:50:05.839100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:201:in `block in notify'
E, [2017-03-14T22:50:05.839100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `each'
E, [2017-03-14T22:50:05.839100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `notify'
E, [2017-03-14T22:50:05.839100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:226:in `close'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:189:in `close_after'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:168:in `finish'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:79:in `report'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/inspec-1.16.1/lib/inspec/runner_rspec.rb:77:in `run'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/inspec-1.16.1/lib/inspec/runner.rb:117:in `run_tests'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/inspec-1.16.1/lib/inspec/runner.rb:101:in `run'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:94:in `call'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
E, [2017-03-14T22:50:05.840100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: C:/root/Ruby/2.2.4/w32/lib/ruby/gems/2.2.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-03-14T22:50:05.841100 #27008] ERROR -- build-environment-JenkinsSlave-UbuntuServer16042-amd64-vbox-production: ----End Backtrace-----
```

**Comment by adamleff** [comment]
Thanks for raising this bug. This is definitely an issue.

In a recent PR we accepted, we now use Nokogiri to create JUnit output. However, the nokogiri gem was added to the Gemfile instead of the gemspec.

https://github.com/chef/inspec/pull/1454/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R11

We should remove it from the Gemfile and put it in the gemspec instead for sure.

**Comment by jkerry** [comment]
I'll take care of this, as I broke it.
