### ISSUE TITLE
Inspec appears to incorrectly fail os x 10.12.3 package verification.

### ISSUE THREAD

**Issue by AndrewRussellHayes** [inspec/inspec#1574]
### Description

When running tests to verify packages currently installed on OS X, tests return failures.

### InSpec and Platform Version

This has been tested and happens with inspec versions 1.7.1 and 1.16.1
The Operating system is OS X 10.12.3

### Replication Case

I have an OSX 10.12.3 laptop. I have used the install files for this os version with packer to make a virtualbox vm to use for chef testing.

I am using a very simple chef recipe to test the vm:
```
include_recipe 'homebrew'

package 'tree' do
  action :install
end
```
as well as very simple inspec tests to do some easy verifications:
```
unless os.windows?
  describe user('root') do
    it { should exist }
  end
end

describe package('brew') do
  it { should be_installed }
end

describe package('tree') do
  it { should be_installed }
end

describe package('bash') do
  it { should be_installed }
end
```

I run kitchen create and converge

I use kitchen login to access the box and manually verify that the packages are installed (they are).

I run kitchen verify and get failures for all the packages. 
I get success for the root test.

![errorsfromhost](https://cloud.githubusercontent.com/assets/1654144/24068659/f5cc91fc-0b6a-11e7-88ba-485030c70825.jpg)

Then, to further verify the problem I use kitchen login to get back into the VM. From inside the vm I use homebrew to install inspec version 1.7.1 then i run the tests from within the vm in the event that the problem was with test kitchen. when i run it from within the VM i get similar but slightly different errors:

![errorsfromguest](https://cloud.githubusercontent.com/assets/1654144/24068684/c5c646be-0b6b-11e7-94fa-2b3af110b3fa.jpg)

To complicate matters a bit, I decided to run the same tests against my host system (with inspec 1.16.1) and in this case i get a success with tree and root but failure with the other two:

![errorsonhost](https://cloud.githubusercontent.com/assets/1654144/24068747/1b04d784-0b6d-11e7-965c-bf26188da8b7.jpg)

### Possible Solutions
I haven't got any idea. But a point in the right direction would be awesome!

### Stacktrace
This is the kitchen log output, if that's helpful:
```

mbp:laptop andrew$ cat .kitchen/logs/kitchen.log
I, [2017-03-17T23:10:33.090630 #4260]  INFO -- Kitchen: -----> Starting Kitchen (v1.15.0)
I, [2017-03-17T23:10:34.168098 #4260]  INFO -- Kitchen: -----> Verifying <default-sierra-10123>...
E, [2017-03-17T23:10:34.460415 #4260] ERROR -- Kitchen: ------Exception-------
E, [2017-03-17T23:10:34.460442 #4260] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-03-17T23:10:34.460455 #4260] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-sierra-10123>.  Please see .kitchen/logs/default-sierra-10123.log for more details
E, [2017-03-17T23:10:34.460467 #4260] ERROR -- Kitchen: ----------------------
E, [2017-03-17T23:10:34.460476 #4260] ERROR -- Kitchen: ------Backtrace-------
E, [2017-03-17T23:10:34.460485 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-03-17T23:10:34.460498 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-03-17T23:10:34.460507 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command/action.rb:36:in `block in call'
E, [2017-03-17T23:10:34.460517 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-03-17T23:10:34.460526 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command/action.rb:34:in `call'
E, [2017-03-17T23:10:34.460535 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-03-17T23:10:34.460544 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
E, [2017-03-17T23:10:34.460553 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-03-17T23:10:34.460563 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-03-17T23:10:34.460572 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-03-17T23:10:34.460616 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-03-17T23:10:34.460625 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-03-17T23:10:34.460637 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-03-17T23:10:34.460647 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-03-17T23:10:34.460656 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/bin/kitchen:13:in `<top (required)>'
E, [2017-03-17T23:10:34.460665 #4260] ERROR -- Kitchen: /usr/local/bin/kitchen:21:in `load'
E, [2017-03-17T23:10:34.460673 #4260] ERROR -- Kitchen: /usr/local/bin/kitchen:21:in `<main>'
E, [2017-03-17T23:10:34.460682 #4260] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-03-17T23:10:34.460690 #4260] ERROR -- Kitchen: -Composite Exception--
E, [2017-03-17T23:10:34.460699 #4260] ERROR -- Kitchen: Class: Kitchen::InstanceFailure
E, [2017-03-17T23:10:34.460707 #4260] ERROR -- Kitchen: Message: Verify failed on instance <default-sierra-10123>.  Please see .kitchen/logs/default-sierra-10123.log for more details
E, [2017-03-17T23:10:34.460716 #4260] ERROR -- Kitchen: ----------------------
E, [2017-03-17T23:10:34.460725 #4260] ERROR -- Kitchen: ------Backtrace-------
E, [2017-03-17T23:10:34.460733 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-03-17T23:10:34.460742 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-03-17T23:10:34.460768 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-03-17T23:10:34.460779 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-03-17T23:10:34.460788 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-03-17T23:10:34.460797 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-03-17T23:10:34.460806 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-03-17T23:10:34.460815 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-03-17T23:10:34.460824 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-03-17T23:10:34.460833 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-03-17T23:10:34.460842 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-03-17T23:10:34.460851 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-03-17T23:10:34.460860 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-03-17T23:10:34.460872 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-03-17T23:10:34.460881 #4260] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-03-17T23:10:34.460890 #4260] ERROR -- Kitchen: ---Nested Exception---
E, [2017-03-17T23:10:34.460898 #4260] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-03-17T23:10:34.460907 #4260] ERROR -- Kitchen: Message: Inspec Runner returns 1
E, [2017-03-17T23:10:34.460915 #4260] ERROR -- Kitchen: ----------------------
E, [2017-03-17T23:10:34.460924 #4260] ERROR -- Kitchen: ------Backtrace-------
E, [2017-03-17T23:10:34.460932 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-03-17T23:10:34.460941 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-03-17T23:10:34.460950 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-03-17T23:10:34.460959 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-03-17T23:10:34.460997 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-03-17T23:10:34.461007 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-03-17T23:10:34.461019 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-03-17T23:10:34.461029 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-03-17T23:10:34.461038 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-03-17T23:10:34.461053 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-03-17T23:10:34.461063 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-03-17T23:10:34.461072 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-03-17T23:10:34.461081 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-03-17T23:10:34.461090 #4260] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-03-17T23:10:34.461099 #4260] ERROR -- Kitchen: ----End Backtrace-----
mbp:laptop andrew$
```

**Comment by chris-rock** [comment]
@AndrewRussellHayes I can verify it works on 10.12.3. From your examples I see that tests for `brew` and `bash` would fail. `brew` is not a brew package. In InSpec we verify packages in brew only at this moment. You should see something like:

```
Profile: tests from trials/os-package.rb
Version: (not specified)
Target:  local://


  System Package
     ✔  automake should be installed
  System Package
     ✔  bash should be installed
```

In order to debug this issue. Could you do `kitchen login` and run `brew info --json=v1 tree `. Lets see what is happening here.

**Comment by AndrewRussellHayes** [comment]
@chris-rock 

I see about brew and bash. So, should i just come up with another way to verify they exist. Like, for example, ensuring the binary exists?

here is the result of the brew info: 

`[{"name":"tree","full_name":"tree","desc":"Display directories as trees (with optional color/HTML output)","homepage":"http://mama.indstate.edu/users/ice/tree/","oldname":null,"aliases":[],"versions":{"stable":"1.7.0","bottle":true,"devel":null,"head":null},"revision":0,"version_scheme":0,"installed":[{"version":"1.7.0","used_options":[],"built_as_bottle":true,"poured_from_bottle":true,"runtime_dependencies":null,"installed_as_dependency":false,"installed_on_request":true}],"linked_keg":"1.7.0","pinned":false,"outdated":false,"keg_only":null,"dependencies":[],"recommended_dependencies":[],"optional_dependencies":[],"build_dependencies":[],"conflicts_with":[],"caveats":null,"requirements":[],"options":[],"bottle":{"stable":{"rebuild":1,"cellar":":any_skip_relocation","prefix":"/usr/local","root_url":"https://homebrew.bintray.com/bottles","files":{"sierra":{"url":"https://homebrew.bintray.com/bottles/tree-1.7.0.sierra.bottle.1.tar.gz","sha256":"f7c8a080435445e17c254ca53b016d9012bf768851df67c3d892ba71fe98e924"},"el_capitan":{"url":"https://homebrew.bintray.com/bottles/tree-1.7.0.el_capitan.bottle.1.tar.gz","sha256":"2721bafcbe1db12e444f5025bdae81aa3c7cff6572aa7423e401baeb10a43157"},"yosemite":{"url":"https://homebrew.bintray.com/bottles/tree-1.7.0.yosemite.bottle.1.tar.gz","sha256":"c1ad4f32c4922cbd1e37aa55b8fa6e0cc8a04c96a24f0d9e7957b50b311d854d"},"mavericks":{"url":"https://homebrew.bintray.com/bottles/tree-1.7.0.mavericks.bottle.1.tar.gz","sha256":"0bcb8a1de3ed51295917d6dd997ea492048f90a5ee1084676171a39dbd489654"},"mountain_lion":{"url":"https://homebrew.bintray.com/bottles/tree-1.7.0.mountain_lion.bottle.1.tar.gz","sha256":"c3bd091797c487bb1ac5586d0e524da341c6043b0298269a9ded271646274fa3"}}}}}]`

**Comment by adamleff** [comment]
Still appears to be an issue:

```
 aleff@remaleff01  ~/projects/inspec   master ●  brew info tree
tree: stable 1.7.0 (bottled)
Display directories as trees (with optional color/HTML output)
http://mama.indstate.edu/users/ice/tree/
/usr/local/Cellar/tree/1.7.0 (7 files, 113.1KB) *
  Built from source on 2015-08-14 at 14:43:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tree.rb
 aleff@remaleff01  ~/projects/inspec   master ●  be inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  mac_os_x
    OS family:  darwin
    OS release: 10.12.5

inspec> describe package('tree') do
inspec>   it { should be_installed }
inspec> end

Profile: inspec-shell
Version: (not specified)

  System Package
     ∅  tree should be installed
     expected that `System Package tree` is installed

Test Summary: 0 successful, 1 failures, 0 skipped
```

Flagging as a bug.

**Comment by ctbarrett** [comment]
I just ran into this today as well, and it appears to be related to the command used by the `Brew` class [here](https://github.com/chef/inspec/blob/master/lib/resources/package.rb#L196):

```
  # MacOS / Darwin implementation
  class Brew < PkgManagement
    def info(package_name)
      cmd = inspec.command("brew info --json=v1 #{package_name}")
      return nil if cmd.exit_status.to_i != 0
      # parse data
      pkg = JSON.parse(cmd.stdout)[0]
      {
        name: pkg['name'],
        installed: true,
        version: pkg['installed'][0]['version'],
        type: 'brew',
      }
    rescue JSON::ParserError => _e
      return nil
    end
  end
```

The command relies on finding `/usr/local/bin/brew` in the PATH, but if using the test-kitchen defaults (vagrant / ssh), this means the inspec runner is executed in a non-interactive shell, which doesn't source the user's profile, and therefore doesn't have that directory on the PATH:

```
$ bx inspec shell -t ssh://vagrant:vagrant@localhost:2222
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  mac_os_x
    OS family:  darwin
    OS release: 10.12.6

inspec> os_env('PATH').content
=> "/usr/bin:/bin:/usr/sbin:/sbin"
inspec> command('which brew').stdout
=> ""
inspec> command('ls -l /usr/local/bin/brew').stdout
=> "lrwxr-xr-x  1 vagrant  wheel  28 Sep 11 14:32 /usr/local/bin/brew -> /usr/local/Homebrew/bin/brew\n"
inspec>
```

So... all that being said - is there a way to set the PATH for the inspec runner as called by kitchen-inspec?

**Comment by adamleff** [comment]
My [comment](https://github.com/chef/inspec/issues/1574#issuecomment-305919730) may be a red-herring because I was testing within InSpec's bundled dev environment and there's a `json` gem version conflict. When I test outside of that environment, it works correctly.

I suspect the root cause of the issues is what @ctbarrett is pointing out, and I think the easiest way to solve this it to see if `brew` is in the PATH... if it is, use it, otherwise default to `/usr/local/bin/brew` which is the default install path anyways for Homebrew. I'll put up a PR for that shortly.
