### ISSUE TITLE
Profile dependency fails if version is missing in inspec.yml

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1686]
### Description

If a profile dependency is given with a path or url, the version version should be optional for execution. This is mainly for development reasons, since profiles should have a version, once in production. 

### InSpec and Platform Version

1.20.0

### Replication Case

Create a profile and a base profile where `version` is missing in `inspec.yml`

### Possible Solutions

For mitigation, just add a version to your `inspec.yml`

### Stacktrace

```
/Users/chartmann/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/dependency.rb:226:in `match?': undefined method `name' for "base_profile":String (NoMethodError)
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/dependencies/requirement.rb:56:in `source_satisfies_spec?'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/dependencies/resolver.rb:73:in `block in resolve'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/dependencies/resolver.rb:59:in `each'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/dependencies/resolver.rb:31:in `resolve'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:385:in `generate_lockfile'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:111:in `write_lockfile'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:81:in `block in load'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:79:in `each'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:79:in `load'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:100:in `run'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/base_cli.rb:83:in `run_tests'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/cli.rb:159:in `exec'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/chartmann/Development/compliance/inspec/bin/inspec:12:in `<top (required)>'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/inspec:22:in `load'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/inspec:22:in `<main>'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please reopen the issue and continue the discussion.

Thank you!
__Chef InSpec Team__
