### ISSUE TITLE
xinetd.rb `read_content': undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by sarahbakal** [inspec/inspec#1729]
Sample of the controls:
```
control 'daytime-stream-services-not-enabled' do
  impact 0.5
  title 'Recommendation number 2.1.2'
  desc 'Ensure daytime services are not enabled'

  describe.one do
    describe xinetd_conf.services("daytime").socket_types("stream") do
      it { should_not be_enabled }
    end
    describe package("xinetd") do
      it { should_not be_installed }
    end
  end
end
```
Error:
```
D, [2017-04-27T11:10:32.863975 #28846] DEBUG -- : [SSH] vagrant@localhost<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2200, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "password", "keyboard-interactive"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil}> (cat /etc/xinetd.conf || echo -n)
/Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/resources/xinetd.rb:60:in `read_content': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/resources/xinetd.rb:68:in `read_params'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/resources/xinetd.rb:34:in `params'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/resources/xinetd.rb:108:in `service_lines'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/utils/filter.rb:177:in `call'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/utils/filter.rb:177:in `block (2 levels) in connect'
	from /Users/sbakal/Chef/optum_rhel7_standard_profile/controls/service.rb:138:in `block (2 levels) in load_with_context'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/describe.rb:19:in `instance_eval'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/describe.rb:19:in `one'
	from /Users/sbakal/Chef/optum_rhel7_standard_profile/controls/service.rb:137:in `block in load_with_context'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/rule.rb:51:in `instance_eval'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/rule.rb:51:in `initialize'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/control_eval_context.rb:71:in `new'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
	from /Users/sbakal/Chef/optum_rhel7_standard_profile/controls/service.rb:132:in `load_with_context'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/profile_context.rb:130:in `load_control_file'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/profile.rb:144:in `block in collect_tests'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/profile.rb:141:in `each'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/profile.rb:141:in `collect_tests'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/runner.rb:90:in `block in load'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/runner.rb:79:in `each'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/runner.rb:79:in `load'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/runner.rb:100:in `run'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/base_cli.rb:83:in `run_tests'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/lib/inspec/cli.rb:159:in `exec'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/sbakal/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/inspec-1.21.0/bin/inspec:12:in `<top (required)>'
	from /Users/sbakal/.rbenv/versions/2.4.0/bin/inspec:22:in `load'
	from /Users/sbakal/.rbenv/versions/2.4.0/bin/inspec:22:in `<main>'
[optum_rhel7_standard_profile-0.1.5.tar.gz](https://github.com/chef/inspec/files/962316/optum_rhel7_standard_profile-0.1.5.tar.gz)
```

**Comment by sarahbakal** [comment]
Running against a RHEL 7.3 box

**Comment by adamleff** [comment]
I have been able to reproduce this by running InSpec as a non-root user and without sudo privileges. `file.content` when reading `/etc/xinetd.conf` will return `nil` instead of an empty string and then we'll try and call `#empty?` on it.

I'll put up a PR to fix this.

**Comment by adamleff** [comment]
PR #1746 opened to correct this issue.
