### ISSUE TITLE
Issue with --shell-options

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1738]
### Description

I am trying to run inspec tests on a remote host logging in as the vagrant user then asking inspec to sudo su - postgres via the --bash and --shell-options command line options. This does not seem to be working as expected. 

My end goal is to be able to also put this in my .kitchen.yml file as well - which means kitchen-inspec and perhaps train will have to be tweaked as well.

### InSpec and Platform Version

current - 1.21.0

### Replication Case

```
➜  postgresql-baseline git:(master) ✗ inspec exec ./controls/V-73061.rb -i $SSH_KEY --sudo --sudo-command='sudo su - postgres' --shell --shell-command='bash' --shell-options='--login' -t ssh://vagrant@127.0.0.1:2222
Sudo failed:  bash: shell_options: No such file or directory
```
debug log

```
inspec exec ./controls/V-73061.rb -i $SSH_KEY --sudo --sudo-command='sudo su - postgres' --shell --shell-command='bash' --shell-options='--login' -t ssh://vagrant@127.0.0.1:2222 --log-level=debug

D, [2017-04-28T09:56:42.438316 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (uname -s)
D, [2017-04-28T09:56:42.438435 #30472] DEBUG -- : [SSH] opening connection to vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}>
D, [2017-04-28T09:56:42.695965 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (uname -r)
D, [2017-04-28T09:56:42.707502 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (uname -m)
D, [2017-04-28T09:56:42.719210 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (test -f /etc/oracle-release && cat /etc/oracle-release)
D, [2017-04-28T09:56:42.730224 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (test -f /etc/enterprise-release && cat /etc/enterprise-release)
D, [2017-04-28T09:56:42.744631 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (test -f /etc/debian_version && cat /etc/debian_version)
D, [2017-04-28T09:56:42.759371 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (test -f /etc/parallels-release && cat /etc/parallels-release)
D, [2017-04-28T09:56:42.773900 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (test -f /etc/redhat-release && cat /etc/redhat-release)
D, [2017-04-28T09:56:42.785909 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (test -f /etc/os-release && cat /etc/os-release)
D, [2017-04-28T09:56:42.802495 #30472] DEBUG -- : [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>2222, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["/Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/.kitchen/kitchen-vagrant/kitchen-postgresql-baseline-hardening-default-crunchy-95/.vagrant/machines/default/virtualbox/private_key"], :password=>"<hidden>", :forward_agent=>nil}> (echo c3VkbyBzdSAtIHBvc3RncmVzIGVjaG8= | base64 --decode | bash shell_options)
Sudo failed:  bash: shell_options: No such file or directory
➜  postgresql-baseline git:(master) ✗
```

**Comment by aaronlippold** [comment]
@arlimus @chris-rock @adamleff @atomic111 @drensby @sharmay @jasonodonnell @dmd890

This is actually a blocking issue given that the postgres stig check controls require that you execute the tests as the 'pg_owner' process owner - usually this is the 'postgres' user. 

The larger issue which I don't feel we have common agreement on for a way ahead is:

The default permissions causes issues with the current postgres.rb resource given that most of the time it will execute in the scope of the login user which could be docker or dokken or vagrant or automate etc causing the postgres.rb resource to not find the /var/lib/pgsql* directory tree.

I could use some help thinking about how we could solve this what the right 'primary assumptions' should be.  

Its also causing a blocking issue that in the RHEL family packaging the default mode for the pg_conf_dir and pg_data_dir default to mode 0700 recursive - chown pg_owner:pg_owner - which is good except that I think the default should really be:
```
/var/lib/pgsql -> 0755
/var/lib/pgsql/ver* -> 0755
/var/lib/pgsql/ver*/data -> 0755
/var/lib/pgsql/ver*/backups* -> 0740 ( 0640 -type f )
/var/lib/pgsql/ver*/data/* -> 0740 ( 0640 -type f )
/var/lib/pgsql/ver*/data/PG_VERSION -> 644
```
(*) if ver dir exists  

Giving the same security value and helping keep system information available.
( same logic structure on ubuntu&arch if this problem exists there )
see: https://github.com/chef/inspec/blob/master/lib/resources/postgres.rb#L85
see: https://github.com/chef/inspec/blob/master/lib/resources/postgres.rb#L112
in the current code base.

A secondary approach is :  
```psql --version | awk '{ print $NF }' | awk -F. '{ print $1\".\"$2 }'```  
I believe this will work regardless of which user runs it.

A third approach is a general find:  
( this could be updated to start at / and if the perms are set as above could give us data_dir as well ) 
```find #{pg_data_dir} \\\( ! -path #{pg_data_dir} -prune \\\) -type f -name \"PG_VERSION\"\`"```
( as a regular system user the above permission change would have to be true)  
 
As referenced eariler the 100% correct way is to use the formal psql commands and no matter what how or where postgres is installed we will get the right answer for the variables in question. i.e.

```
as 'pg_owner' and password
psql -t -A -p <port> -h <host> -d postgres -c 'show hba_file'; <== data_dir(-1)
psql -t -A -p <port> -h <host> -d postgres -c 'show config_file;  <== conf_dir(-1)
```

**Comment by aaronlippold** [comment]
Sorry now ^^^^ comment makes more sense

**Comment by arlimus** [comment]
@aaronlippold I would recommend you run these options in InSpec instead:

```
--sudo --sudo-options='-u postgres'
```

Thank you for submitting the bug for the other issue, we will look into it!

**Comment by adamleff** [comment]
@aaronlippold can you confirm is @arlimus's suggestion with `--sudo-options` meets your needs, pleased?

**Comment by aaronlippold** [comment]
@adamleff I am not 100% sure yet given https://github.com/chef/inspec/issues/1780. I need to deconflict where that issue is coming from.

**Comment by aaronlippold** [comment]
The profile runs fine outside kitchen

**Comment by aaronlippold** [comment]
@adamleff @arlimus  no, there seems to be a bug somewhere, which seems to trigger when I pass the --sudo option in. 

```
➜  controls git:(master) ✗ inspec exec V-72895.rb -i $SSH_KEY_H --sudo --sudo-options="-u postgres" -t ssh://vagrant@127.0.0.1:2222
WARN: Unresolved specs during Gem::Specification.reset:
      thor (~> 0.19)
      rainbow (~> 2)
      rspec (~> 3)
      addressable (~> 2.4)
      net-ssh (< 5.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      logging (< 3.0, >= 1.6.1)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/resources/postgres_conf.rb:95:in `+': no implicit conversion of Array into String (TypeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/resources/postgres_conf.rb:95:in `include_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/resources/postgres_conf.rb:86:in `read_content'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/resources/postgres_conf.rb:29:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/plugins/resource.rb:47:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/resource.rb:48:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/resource.rb:48:in `block (3 levels) in create_dsl'
	from V-72895.rb:109:in `block in load_with_context'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/rule.rb:51:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/rule.rb:51:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/control_eval_context.rb:71:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
	from V-72895.rb:52:in `load_with_context'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/profile_context.rb:130:in `load_control_file'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/profile.rb:150:in `block in collect_tests'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/profile.rb:147:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/profile.rb:147:in `collect_tests'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/runner.rb:90:in `block in load'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/runner.rb:79:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/runner.rb:79:in `load'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/runner.rb:100:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/base_cli.rb:83:in `run_tests'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/lib/inspec/cli.rb:166:in `exec'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.24.0/bin/inspec:12:in `<top (required)>'
	from /usr/local/bin/inspec:22:in `load'
	from /usr/local/bin/inspec:22:in `<main>'
```
