### ISSUE TITLE
<Zlib::DataError: invalid distance too far back> windows server running audit

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#1763]
### Description

running audit against windows server for one that uses depend on another inherit control

### InSpec and Platform Version

1.20.

### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

****

C:\windows\system32>chef-client
Starting Chef Client, version 12.18.31
resolving cookbooks for run list: ["r101_all_audit"]
Synchronizing Cookbooks:
  - r101_all_audit (0.1.0)
  - audit (3.0.0)
  - compat_resource (12.16.3)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: audit::inspec
  * inspec_gem[inspec] action install (up to date)
  Converging 1 resources
  * inspec_gem[inspec] action nothing (skipped due to action :nothing)

Running handlers:
[2017-05-04T08:48:46-04:00] ERROR: Report handler Chef::Handler::AuditReport rai
sed #<Zlib::DataError: invalid distance too far back>
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/file_provider.rb:111:in `initialize'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/file_provider.rb:111:in `open'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/file_provider.rb:111:in `initialize'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/file_provider.rb:14:in `new'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/file_provider.rb:14:in `for_path'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/profile.rb:52:in `for_path'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/profile.rb:69:in `for_fetcher'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/dependencies/requirement.rb:107:in `profile'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/dependencies/dependency_set.rb:65:in `block in eac
h'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/dependencies/dependency_set.rb:64:in `each'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/dependencies/dependency_set.rb:64:in `each'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/profile.rb:162:in `load_libraries'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/runner.rb:83:in `block in load'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/runner.rb:79:in `each'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/runner.rb:79:in `load'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/inspec-1.22.0/lib/inspec/runner.rb:100:in `run'
[2017-05-04T08:48:46-04:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/h
andler/audit_report.rb:118:in `call'
[2017-05-04T08:48:46-04:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/h
andler/audit_report.rb:45:in `report'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/handler.rb:259:in `run_report_unsa
fe'
[2017-05-04T08:48:46-04:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/h
andler/audit_report.rb:63:in `run_report_safely'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/handler.rb:125:in `block in run_re
port_handlers'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/handler.rb:123:in `each'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/handler.rb:123:in `run_report_hand
lers'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/handler.rb:135:in `block in <class
:Handler>'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:441:in `block in run_com
pleted_successfully'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:440:in `each'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:440:in `run_completed_su
ccessfully'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:299:in `run'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:277:in `run_with_gr
aceful_exit_option'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:253:in `block in ru
n_chef_client'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_c
onnectivity'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:236:in `run_chef_cl
ient'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:464:in `slee
p_then_run_chef_client'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:451:in `bloc
k in interval_run_chef_client'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:450:in `loop
'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:450:in `inte
rval_run_chef_client'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:434:in `run_
application'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:59:in `run'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/
gems/chef-12.18.31-universal-mingw32/bin/chef-client:26:in `<top (required)>'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/bin/chef-client:68:in `load'
[2017-05-04T08:48:46-04:00] ERROR: C:/opscode/chef/bin/chef-client:68:in `<main>
'
  - Chef::Handler::AuditReport
Running handlers complete
Chef Client finished, 0/2 resources updated in 49 seconds

***

**Comment by adamleff** [comment]
@chris-rock do you think this is related to #1715?

**Comment by chris-rock** [comment]
I think it is. May feeling (not confirmed) is that this happens if we have a tar in a tar on Windows. Upload and retrieval will have the same issue then. The best approach to tackle that issue is: https://github.com/chef/inspec/issues/1659

**Comment by timusmc96** [comment]
Chris I also think this is still issue with windows.   So hopefully this one is also on the plate

**Comment by timusmc96** [comment]
@chris-rock lets catch up early next week if we could.  Thanks

**Comment by timusmc96** [comment]
I am also seeing this now running inspec compliance upload for the profiles

C:\WorkSpace\Inspec\inspec-profiles [master ≡ +17 ~7 -6 !]> inspec compliance upload Company_CIS-WIN2012R2 --overwrite
Dependencies for profile Company_CIS-WIN2012R2 successfully vendored to Company_CIS-WIN2012R2/vendor
I, [2017-06-05T11:29:58.635299 #11520]  INFO -- : Checking profile in Company_CIS-WIN2012R2
I, [2017-06-05T11:29:58.636299 #11520]  INFO -- : Metadata OK.
C:/Users/trondeau/AppData/Local/chefdk/gem/ruby/2.3.0/gems/inspec-1.26.0/lib/inspec/file_provider.rb:111:in `initialize': invalid distance too far back (Zlib::DataError)


C:\WorkSpace\Inspec\inspec-profiles [master ≡ +17 ~7 -6 !]> inspec compliance upload Company_cis_rhel7 --overwrite
Dependencies for profile Company_cis_rhel7 successfully vendored to Company_cis_rhel7/vendor
I, [2017-06-05T09:22:17.018230 #15592]  INFO -- : Checking profile in Company_cis_rhel7
I, [2017-06-05T09:22:17.019186 #15592]  INFO -- : Metadata OK.
C:/Users/trondeau/AppData/Local/chefdk/gem/ruby/2.3.0/gems/inspec-1.26.0/lib/inspec/file_provider.rb:111:in `initialize': invalid distance too far back (Zlib::DataError)

**Comment by chris-rock** [comment]
This is fixed by #1906 and #1920
