### ISSUE TITLE
postgres_conf resource and the --sudo option

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1780]
### Description

A small bug seems to have crept into the postgres_conf resource

### InSpec and Platform Version

1.23

### Replication Case
Use the resource with 1.23
### Possible Solutions

Looking into it now

### Stacktrace

```Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:95:in `+': no implicit conversion of Array into String (TypeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:95:in `include_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:86:in `read_content'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:29:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/plugins/resource.rb:47:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/resource.rb:48:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/resource.rb:48:in `block (3 levels) in create_dsl'
	from ./controls/V-73061.rb:133:in `block in load_with_context'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/control_eval_context.rb:71:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
	from ./controls/V-73061.rb:59:in `load_with_context'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile_context.rb:130:in `load_control_file'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile.rb:149:in `block in collect_tests'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile.rb:146:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile.rb:146:in `collect_tests'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:90:in `block in load'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:79:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:79:in `load'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:100:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/base_cli.rb:83:in `run_tests'
	from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/cli.rb:166:in `exec'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'```

**Comment by aaronlippold** [comment]
```# encoding: utf-8
#
=begin
-----------------
Benchmark: PostgreSQL 9.x Security Technical Implementation Guide
Status: Accepted

This Security Technical Implementation Guide is published as a tool to improve
the security of Department of Defense (DoD) information systems. The
requirements are derived from the National Institute of Standards and
Technology (NIST) 800-53 and related documents. Comments or proposed revisions
to this document should be sent via email to the following address:
disa.stig_spt@mail.mil.

Release Date: 2017-01-20
Version: 1
Publisher: DISA
Source: STIG.DOD.MIL
uri: http://iase.disa.mil
-----------------
=end

PG_DBA = attribute(
   'pg_dba',
   description: 'The postgres DBA user to access the database',
   default: 'stig_dba')

PG_DBA_PASSWORD = attribute(
  'pg_dba_password',
  description: "password for the postgres dba password",
  default: 'stigD@1234#')

PG_PORT = attribute(
  'pg_port',
  description: "The port that the postgres server is listening to",
  default: '5432'
)

PG_HOST = attribute(
  'pg_host',
  description: "Hostname or ip allow to connect to the database",
  default: '127.0.0.1')

PG_DB = attribute(
    'pg_db',
    description: "the database to run the command from",
    default: 'stig_test_db')

PG_CONF_DIR= attribute(
  'pg_conf_dir',
  description: 'define path for the postgresql configuration file',
  default: '/var/lib/pgsql/9.5/data')

PG_CONF_FILE = attribute(
  'pg_conf_file',
  description: 'define path for the postgresql configuration file',
  default: "/var/lib/pgsql/9.5/data/postgresql.conf")

control "V-73061" do
  title "PostgreSQL must protect its audit configuration from unauthorized
        modification."
  desc  "Protecting audit data also includes identifying and protecting the tools
        used to view and manipulate log data. Therefore, protecting audit tools
        is necessary to prevent unauthorized operation on audit data.

        Applications providing tools to interface with audit data will leverage
        user permissions and roles identifying the user accessing the tools and
        the corresponding rights the user enjoys in order make access decisions
        regarding the modification of audit tools.

        Audit tools include, but are not limited to, vendor-provided and open source
        audit tools needed to successfully view and manipulate audit information
        system activity and records. Audit tools include custom queries and
        report generators."
  impact 0.5
  tag "severity": "medium"

  tag "gtitle": "SRG-APP-000122-DB-000203"
  tag "gid": "V-73061"
  tag "rid": "SV-87713r1_rule"
  tag "stig_id": "PGS9-00-012200"
  tag "cci": "CCI-001494"
  tag "nist": ["AU-9", "Rev_4"]

  tag "check": "All configurations for auditing and logging can be found in the
      postgresql.conf configuration file. By default, this file is owned by the
      database administrator account.

      To check that the permissions of the postgresql.conf are owned by the database
      administrator with permissions of 0600, run the following as the database
      administrator (shown here as \"postgres\"):

      $ sudo su - postgres
      $ ls -la ${PGDATA?}

      If postgresql.conf is not owned by the database administrator or does not
      have 0600 permissions, this is a finding.

      #### stderr Logging

      To check that logs are created with 0600 permissions, check the
      postgresql.conf file for the following setting:

      $ sudo su - postgres
      $ psql -c \"SHOW log_file_mode\"

      If permissions are not 0600, this is a finding.

      #### syslog Logging

      If PostgreSQL is configured to use syslog, verify that the logs are owned
      by root and have 0600 permissions. If they are not, this is a finding."

  tag "fix": "Apply or modify access controls and permissions (both within PostgreSQL
      and in the file system/operating system) to tools used to view or modify
      audit log data. Tools must be configurable by authorized personnel only.

      $ sudo su - postgres
      $ vi ${PGDATA?}/postgresql.conf
      log_file_mode = 0600

      Next, as the database administrator (shown here as \"postgres\"), change
      the ownership and permissions of configuration files in PGDATA:

      $ sudo su - postgres
      $ chown postgres:postgres ${PGDATA?}/*.conf
      $ chmod 0600 ${PGDATA?}/*.conf"

      describe command("PGPASSWORD='#{PG_DBA_PASSWORD}' psql -U #{PG_DBA} -d #{PG_DB} -h #{PG_HOST} -A -t -c \"SHOW log_file_mode\"") do
        its('stdout.strip') { should eq '0600' }
      end

      describe postgres_conf(PG_CONF_FILE) do
        its('log_file_mode') { should eq '0600' }
      end

      describe file(PG_CONF_FILE) do
        its('mode') { should cmp '0600' }
      end
    end```

**Comment by aaronlippold** [comment]
```I, [2017-05-06T15:26:10.705210 #61464]  INFO -- Kitchen: -----> Starting Kitchen (v1.16.0)
I, [2017-05-06T15:26:12.621835 #61464]  INFO -- Kitchen: -----> Verifying <crunchy-95-hardened>...
E, [2017-05-06T15:26:13.307943 #61464] ERROR -- Kitchen: ------Exception-------
E, [2017-05-06T15:26:13.307982 #61464] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-05-06T15:26:13.308005 #61464] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [no implicit conversion of Array into String] on crunchy-95-hardened
E, [2017-05-06T15:26:13.308027 #61464] ERROR -- Kitchen: ----------------------
E, [2017-05-06T15:26:13.308047 #61464] ERROR -- Kitchen: ------Backtrace-------
E, [2017-05-06T15:26:13.308068 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-05-06T15:26:13.308088 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-05-06T15:26:13.308109 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
E, [2017-05-06T15:26:13.308130 #61464] ERROR -- Kitchen: /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-05-06T15:26:13.308150 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
E, [2017-05-06T15:26:13.308171 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-05-06T15:26:13.308192 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
E, [2017-05-06T15:26:13.308213 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-05-06T15:26:13.308234 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-05-06T15:26:13.308254 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-05-06T15:26:13.308275 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-05-06T15:26:13.308296 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-05-06T15:26:13.308317 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-05-06T15:26:13.308337 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-05-06T15:26:13.308358 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
E, [2017-05-06T15:26:13.308379 #61464] ERROR -- Kitchen: /usr/local/bin/kitchen:22:in `load'
E, [2017-05-06T15:26:13.308399 #61464] ERROR -- Kitchen: /usr/local/bin/kitchen:22:in `<main>'
E, [2017-05-06T15:26:13.308419 #61464] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-05-06T15:26:13.308438 #61464] ERROR -- Kitchen: -Composite Exception--
E, [2017-05-06T15:26:13.308458 #61464] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-05-06T15:26:13.308478 #61464] ERROR -- Kitchen: Message: Failed to complete #verify action: [no implicit conversion of Array into String] on crunchy-95-hardened
E, [2017-05-06T15:26:13.308498 #61464] ERROR -- Kitchen: ----------------------
E, [2017-05-06T15:26:13.308518 #61464] ERROR -- Kitchen: ------Backtrace-------
E, [2017-05-06T15:26:13.308538 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:95:in `+'
E, [2017-05-06T15:26:13.308558 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:95:in `include_files'
E, [2017-05-06T15:26:13.308579 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:86:in `read_content'
E, [2017-05-06T15:26:13.308608 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:29:in `initialize'
E, [2017-05-06T15:26:13.308630 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/plugins/resource.rb:47:in `initialize'
E, [2017-05-06T15:26:13.308673 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/resource.rb:48:in `new'
E, [2017-05-06T15:26:13.308695 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/resource.rb:48:in `block (3 levels) in create_dsl'
E, [2017-05-06T15:26:13.308715 #61464] ERROR -- Kitchen: /Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/../postgresql-baseline/controls/V-72851.rb:101:in `block in load_with_context'
E, [2017-05-06T15:26:13.308735 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `instance_eval'
E, [2017-05-06T15:26:13.308756 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `initialize'
"kitchen.log" 112L, 16138C
E, [2017-05-06T15:26:13.309468 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:95:in `+'
E, [2017-05-06T15:26:13.309488 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:95:in `include_files'
E, [2017-05-06T15:26:13.309508 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:86:in `read_content'
E, [2017-05-06T15:26:13.309528 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/resources/postgres_conf.rb:29:in `initialize'
E, [2017-05-06T15:26:13.309548 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/plugins/resource.rb:47:in `initialize'
E, [2017-05-06T15:26:13.309568 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/resource.rb:48:in `new'
E, [2017-05-06T15:26:13.309588 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/resource.rb:48:in `block (3 levels) in create_dsl'
E, [2017-05-06T15:26:13.309608 #61464] ERROR -- Kitchen: /Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/../postgresql-baseline/controls/V-72851.rb:101:in `block in load_with_context'
E, [2017-05-06T15:26:13.309628 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `instance_eval'
E, [2017-05-06T15:26:13.309648 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/rule.rb:51:in `initialize'
E, [2017-05-06T15:26:13.309668 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/control_eval_context.rb:71:in `new'
E, [2017-05-06T15:26:13.309688 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
E, [2017-05-06T15:26:13.309708 #61464] ERROR -- Kitchen: /Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline-hardening/../postgresql-baseline/controls/V-72851.rb:40:in `load_with_context'
E, [2017-05-06T15:26:13.309734 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile_context.rb:146:in `instance_eval'
E, [2017-05-06T15:26:13.309756 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile_context.rb:146:in `load_with_context'
E, [2017-05-06T15:26:13.309776 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile_context.rb:130:in `load_control_file'
E, [2017-05-06T15:26:13.309797 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile.rb:149:in `block in collect_tests'
E, [2017-05-06T15:26:13.309817 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile.rb:146:in `each'
E, [2017-05-06T15:26:13.309837 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/profile.rb:146:in `collect_tests'
E, [2017-05-06T15:26:13.309857 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:90:in `block in load'
E, [2017-05-06T15:26:13.309878 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:79:in `each'
E, [2017-05-06T15:26:13.309898 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:79:in `load'
E, [2017-05-06T15:26:13.309918 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.23.0/lib/inspec/runner.rb:100:in `run'
E, [2017-05-06T15:26:13.309938 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.19.0/lib/kitchen/verifier/inspec.rb:94:in `call'
E, [2017-05-06T15:26:13.309959 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-05-06T15:26:13.309979 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-05-06T15:26:13.309999 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-05-06T15:26:13.310019 #61464] ERROR -- Kitchen: /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-05-06T15:26:13.310040 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-05-06T15:26:13.310060 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-05-06T15:26:13.310080 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-05-06T15:26:13.310100 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-05-06T15:26:13.310121 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-05-06T15:26:13.310167 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-05-06T15:26:13.310188 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-05-06T15:26:13.310208 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-05-06T15:26:13.310228 #61464] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-05-06T15:26:13.310248 #61464] ERROR -- Kitchen: ----End Backtrace-----```

**Comment by aaronlippold** [comment]
The profile runs fine outside kitchen

**Comment by aaronlippold** [comment]
@chris-rock @arlimus This error seems to happen when the `postgres_conf` resource is activated with the --sudo option. Could this actually be linked to something in the CLI?
