### ISSUE TITLE
Issue uploading profile to automate

### ISSUE THREAD

**Issue by tpmullan** [inspec/inspec#1847]
### Description

Inspec fails to upload to the Chef Automate server:

```
Dependencies for profile ./ successfully vendored to vendor
I, [2017-05-24T10:22:27.291829 #28867]  INFO -- : Checking profile in ./
I, [2017-05-24T10:22:27.292214 #28867]  INFO -- : Metadata OK.
I, [2017-05-24T10:22:27.439386 #28867]  INFO -- : Found 29 controls.
I, [2017-05-24T10:22:27.439519 #28867]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at /tmp/healthchk20170524-28867-17c7dbp.tar.gz
I, [2017-05-24T10:22:27.717020 #28867]  INFO -- : Generate archive /tmp/healthchk20170524-28867-17c7dbp.tar.gz.
I, [2017-05-24T10:22:27.730290 #28867]  INFO -- : Finished archive generation.
Start upload to gmit/healthchk
Uploading to Chef Automate
/home/tom/.rvm/gems/ruby-2.4.1/gems/inspec-1.25.1/lib/bundles/inspec-compliance/api.rb:206:in `is_automate_server_pre_080?': undefined method `empty?' for nil:NilClass (NoMethodError)
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/inspec-1.25.1/lib/bundles/inspec-compliance/api.rb:98:in `upload'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/inspec-1.25.1/lib/bundles/inspec-compliance/cli.rb:229:in `upload'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /home/tom/.rvm/gems/ruby-2.4.1/gems/inspec-1.25.1/bin/inspec:12:in `<top (required)>'
        from /home/tom/.rvm/gems/ruby-2.4.1/bin/inspec:22:in `load'
        from /home/tom/.rvm/gems/ruby-2.4.1/bin/inspec:22:in `<main>'
        from /home/tom/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/tom/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

```
And I believe this issue has been reported, which is why I tried to update inspec.  I feel it is worth mentioning since it somehow became the default version in chefdk.

```
Dependencies for profile ./ successfully vendored to vendor
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/train-0.23.0/lib/train.rb:122:in `validate_backend': Cannot determine backend from target configuration "./". Valid example: ssh://192.168.0.1. (Train::UserError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/backend.rb:17:in `create'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:92:in `initialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:63:in `new'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:63:in `for_path'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:69:in `for_fetcher'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:75:in `for_target'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/bundles/inspec-compliance/cli.rb:165:in `upload'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:57:in `load'
        from /usr/bin/inspec:57:in `<main>'


```
### InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using.

I am having issues with both Inspec 1.19.1 from Chefdk on ubuntu and Inspec 1.25.1

### Replication Case

Try and upload an inspec profile on ubuntu after installing the chefdk

### Possible Solutions

Install the old version of the Chefdk

**Comment by tpmullan** [comment]
A possible workaround for inspec 1.25.1 is to change lib/bundles/inspec-compliance/api.rb:206 .empty? to check .nil? first to make sure there is something there.  I found that when I was logged in with an older version the key was nil instead of an empty string. 

I also found that if I signed out of compliance with inspec 1.25.1 and signed in again it would sometimes work and other times present a new issue.
```
Dependencies for profile ./ successfully vendored to vendor
I, [2017-05-25T16:02:39.237420 #47555]  INFO -- : Checking profile in ./
I, [2017-05-25T16:02:39.238018 #47555]  INFO -- : Metadata OK.
I, [2017-05-25T16:02:39.384982 #47555]  INFO -- : Found 29 controls.
I, [2017-05-25T16:02:39.385121 #47555]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at /tmp/healthchk20170525-47555-azjbj6.tar.gz
I, [2017-05-25T16:02:39.806685 #47555]  INFO -- : Generate archive /tmp/healthchk20170525-47555-azjbj6.tar.gz.
I, [2017-05-25T16:02:39.813828 #47555]  INFO -- : Finished archive generation.
Start upload to gmit/healthchk
Uploading to Chef Automate
Error during profile upload:
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by adamleff** [comment]
This is still pending PR #1849 to be merged which should correct the initial issue reported.

**Comment by tpmullan** [comment]
Thanks for the quick fix! @adamleff
