### ISSUE TITLE
Chained InSpec Profiles use the wrong base path

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#2120]
### Description

If a dependency path is specified in an `inspec.yml` file, any relative paths should be relative to the referencing `inspec.yml` file.

### InSpec and Platform Version

Version: 1.35.2

### Replication Case

During my spec tests, I separate out the inspec profiles and external dependencies into the following directories.

```
/tmp/inspec
├── inspec_deps
│   └── inspec_profiles
│       ├── profiles
│       │   ├── disa_stig-rhel7-baseline
│       │   │   ├── controls
│       │   │   ├── docs
│       │   │   │   └── source
│       │   │   │       └── U_Red_Hat_Enterprise_Linux_7_V1R1_Manual_STIG
│       │   │   ├── files
│       │   │   ├── inspec.yml
│       │   │   ├── libraries
│       │   │   │   └── profile_helper
│       │   │   ├── tmp_fold_in_to_controls
│       │   │   └── tools
│       │   └── simp_stig-rhel7
│       │       ├── controls
│       │       └── inspec.yml
└── inspec_profiles
    └── CentOS-7-disa_stig
        ├── controls
        └── inspec.yml
```

The bottom `inspec.yml` has the following content:

```yaml
depends:
  - name: simp_stig-rhel7
    path: ../../inspec_deps/inspec_profiles/profiles/simp_stig-rhel7
```

The referenced `simp_stig-rhel7.yml` has the following content:

```yaml
depends:
  - name: disa_stig-rhel7-baseline
    path: ../disa_stig-rhel7-baseline
```

### Possible Solutions

Any relative paths should be relative to the referencing `inspec.yml`, not the top level.

### Stacktrace

The error that I recieve when running `inspec exec` on the `/tmp/inspec_profiles/CentOS-7-disa_stig` directory is as follows:

```
/opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/fetchers/local.rb:71:in `read': No such file or directory @ rb_sysopen - /tmp/inspec/inspec_profiles/disa_stig-rhel7-baseline (Errno::ENOENT)
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/fetchers/local.rb:71:in `sha256'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/fetchers/local.rb:65:in `cache_key'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cached_fetcher.rb:32:in `cache_key'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cached_fetcher.rb:39:in `fetch'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cached_fetcher.rb:22:in `resolved_source'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/requirement.rb:62:in `resolved_source'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:80:in `block in resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:59:in `resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/resolver.rb:31:in `resolve'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/profile.rb:393:in `generate_lockfile'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:110:in `write_lockfile'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:80:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:78:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:78:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/runner.rb:99:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/base_cli.rb:83:in `run_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/lib/inspec/cli.rb:159:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.35.2/bin/inspec:12:in `<top (required)>'
        from /bin/inspec:23:in `load'
        from /bin/inspec:23:in `<main>'
```

**Comment by trevor-vaughan** [comment]
Not sure why the functional tests are failing. It seems to work fine when I do everything I can think of by hand.
