### ISSUE TITLE
inspec.yml should support which version of InSpec is required for a profile

### ISSUE THREAD

**Issue by mattray** [inspec/inspec#2188]
### Description

When a new resource is added to InSpec it would be nice to be able to ensure that profiles that use it are not used with older releases of InSpec.

### Replication Case

Try using a new resource (like windows_hotfix) with an older version of InSpec

### Possible Solutions

Add ```inspec_version: '>1.39' ``` to the inspec.yml to use SemVer to check for versions.

### Stacktrace

```
./windows_hotfix_spec.rb:8:in `load_with_context': undefined method `windows_hotfix' for #<#<Class:0x007f80c6399a88>:0x007f80c6398e80> (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/profile_context.rb:130:in `load_control_file'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/profile.rb:151:in `block in collect_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/profile.rb:148:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/profile.rb:148:in `collect_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/runner.rb:89:in `block in load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/runner.rb:78:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/runner.rb:78:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/runner.rb:99:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/base_cli.rb:83:in `run_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/inspec/cli.rb:159:in `exec'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/bin/inspec:12:in `<top (required)>'
	from /opt/chefdk/bin/inspec:264:in `load'
	from /opt/chefdk/bin/inspec:264:in `<main>'
```

**Comment by jerryaldrichiii** [comment]
Good find! This is related to: https://github.com/chef/inspec/issues/521

I will label this as a bug.

**Comment by jerryaldrichiii** [comment]
After some discussion, I think this is a feature request rather than a bug.  The ability to set version restrictions in a profile is not currently available.

Relabeling as such.
