### ISSUE TITLE
syntax check on os.name.include?('Windows') failed but the code actually works

### ISSUE THREAD

**Issue by JazJas** [inspec/inspec#2237]
### Description
I have a only_if test to run a test only if the host is a windows server.
```
  only_if do
    os.name().include?('Windows Server')
  end
```
The code works, including running it in inspec shell:
```
inspec> os.name
=> "Windows 10 Pro"
inspec> os.name.include?("linux")
=> false
inspec> os.name.include?("Windows Server")
=> false
inspec> os.name.include?("Windows")
=> true
```
However, when running "inspec check", I received the following error:
```
>inspec check test.rb
test.rb:7:in `block (2 levels) in load_with_context': undefined method `include?' for nil:NilClass (NoMethodError)
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/rule.rb:103:in `only_if'
        from test.rb:6:in `block in load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/rule.rb:49:in `instance_eval'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/rule.rb:49:in `initialize'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/control_eval_context.rb:71:in `new'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
        from test.rb:1:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile_context.rb:146:in `instance_eval'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile_context.rb:146:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile_context.rb:130:in `load_control_file'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:151:in `block in collect_tests'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:148:in `each'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:148:in `collect_tests'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:454:in `load_checks_params'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:447:in `load_params'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:141:in `params'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:307:in `controls_count'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:278:in `check'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/cli.rb:69:in `check'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/bin/inspec:12:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:61:in `load'
        from C:/opscode/inspec/bin/inspec:61:in `<main>'
```
The content of the test.rb is shown below:
```
>type test.rb
control 'windows-feature' do
  impact 0.1
  title 'Collect the Windows Feature details on Windows Server'

  # the control will only run if the host is a windows server
  only_if do
    os.name().include?('Windows Server')
  end

  describe command('Get-WindowsFeature >> output.txt') do
      its('exit_status') { should eq 0 }
  end
end
```
Briefly describe the issue and the expected behavior

As the code works, the check should pass.

### InSpec and Platform Version
```
>inspec version
1.40.0
```
```
inspec> os.name
=> "Windows 10 Pro"
```
### Replication Case
```
>type test.rb
control 'windows-feature' do
  impact 0.1
  title 'Collect the Windows Feature details on Windows Server'

  # the control will only run if the host is a windows server
  only_if do
    os.name().include?('Windows Server')
  end

  describe command('Get-WindowsFeature >> output.txt') do
      its('exit_status') { should eq 0 }
  end
end
```

### Stacktrace
```
>inspec check test.rb
test.rb:7:in `block (2 levels) in load_with_context': undefined method `include?' for nil:NilClass (NoMethodError)
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/rule.rb:103:in `only_if'
        from test.rb:6:in `block in load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/rule.rb:49:in `instance_eval'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/rule.rb:49:in `initialize'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/control_eval_context.rb:71:in `new'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
        from test.rb:1:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile_context.rb:146:in `instance_eval'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile_context.rb:146:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile_context.rb:130:in `load_control_file'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:151:in `block in collect_tests'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:148:in `each'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:148:in `collect_tests'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:454:in `load_checks_params'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:447:in `load_params'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:141:in `params'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:307:in `controls_count'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/profile.rb:278:in `check'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/lib/inspec/cli.rb:69:in `check'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.40.0/bin/inspec:12:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:61:in `load'
        from C:/opscode/inspec/bin/inspec:61:in `<main>'
```

**Comment by jerryaldrichiii** [comment]
@JazJas the issue here is that `inspec check` uses a `mock://` connection for its backend. This prevents the `os` resource from gathering system details. This is related to: https://github.com/chef/inspec/issues/2175.

I will investigate possible solutions and mention this issue in my PR.
