### ISSUE TITLE
Local installation of Inspec gem doesn't work

### ISSUE THREAD

**Issue by ManishMehra** [inspec/inspec#2299]
We understand that Chef Inspec is not supported on Windows 2008 32 Bit Operating systems. Hence we tried installing Inspec gem on Ruby. We followed following steps:
 1. Installed Ruby: Version 2.4
 2. Installed all dependencies for Inspec Gem
 3. Installed Inspec Gem: 1.43.8
Now, I am expecting inspec exec command to work. But it fails with following error:

```sh
C:/Ruby24/lib/ruby/gems/2.4.0/gems/ffi-1.0.1-x86-mingw32/lib/ffi/platform.rb:27:
in `<module:Platform>': uninitialized constant FFI::Platform::Config (NameError)

Did you mean?  RbConfig
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/ffi-1.0.1-x86-mingw32/lib/ffi/pl
atform.rb:26:in `<module:FFI>'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/ffi-1.0.1-x86-mingw32/lib/ffi/pl
atform.rb:23:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/ffi-1.0.1-x86-mingw32/lib/ffi/ff
i.rb:20:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/ffi-1.0.1-x86-mingw32/lib/ffi.rb
:11:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/win32-process-0.7.1/lib/win32/pr
ocess/functions.rb:6:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/win32-process-0.7.1/lib/win32/pr
ocess.rb:1:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.0.0-x86-mingw3
2/lib/mixlib/shellout/windows.rb:21:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.0.0-x86-mingw3
2/lib/mixlib/shellout.rb:32:in `<class:ShellOut>'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.0.0-x86-mingw3
2/lib/mixlib/shellout.rb:26:in `<module:Mixlib>'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.0.0-x86-mingw3
2/lib/mixlib/shellout.rb:24:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/inspec-1.43.8/lib/fetchers/git.r
b:4:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/inspec-1.43.8/lib/inspec/fetcher
.rb:45:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/inspec-1.43.8/lib/inspec/cached_
fetcher.rb:2:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/inspec-1.43.8/lib/inspec/profile
.rb:9:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/inspec-1.43.8/lib/inspec.rb:11:i
n `<top (required)>'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/inspec-1.43.8/bin/inspec:10:in `
require_relative'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/inspec-1.43.8/bin/inspec:10:in `
<top (required)>'
        from C:/Ruby24/bin/inspec:23:in `load'
        from C:/Ruby24/bin/inspec:23:in `<main>'

```

Any suggestions?

**Comment by adamleff** [comment]
This is unfortunately outside of the scope of the InSpec project as it appears to be an issue with the `ffi` gem on your platform. Sorry we could not be of more assistance.
