### ISSUE TITLE
inspec exec/check does not work with skip exceptions properly

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#2325]
### Description

Resources are emitting skip exceptions now, but this lead to errors during execution, since we are not catching the exception properly

```
inspec exec test/unit/mock/profiles/skip-exception
/Users/chartmann/Development/compliance/inspec/lib/resources/xinetd.rb:56:in `read_content': Can't find file: /etc/xinetd.conf (Inspec::Exceptions::ResourceSkipped)
	from /Users/chartmann/Development/compliance/inspec/lib/resources/xinetd.rb:67:in `read_params'
	from /Users/chartmann/Development/compliance/inspec/lib/resources/xinetd.rb:34:in `params'
	from /Users/chartmann/Development/compliance/inspec/lib/resources/xinetd.rb:106:in `service_lines'
	from /Users/chartmann/Development/compliance/inspec/lib/utils/filter.rb:177:in `call'
	from /Users/chartmann/Development/compliance/inspec/lib/utils/filter.rb:177:in `block (2 levels) in connect'
	from test/unit/mock/profiles/skip-exception/controls/test3.rb:3:in `block (2 levels) in load_with_context'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/describe.rb:19:in `instance_eval'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/describe.rb:19:in `one'
	from test/unit/mock/profiles/skip-exception/controls/test3.rb:2:in `block in load_with_context'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/rule.rb:49:in `instance_eval'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/rule.rb:49:in `initialize'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/control_eval_context.rb:73:in `new'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/control_eval_context.rb:73:in `block (2 levels) in create'
	from test/unit/mock/profiles/skip-exception/controls/test3.rb:1:in `load_with_context'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile_context.rb:148:in `instance_eval'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile_context.rb:148:in `load_with_context'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile_context.rb:132:in `load_control_file'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:160:in `block in collect_tests'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:157:in `each'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:157:in `collect_tests'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:89:in `block in load'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:78:in `each'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:78:in `load'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:99:in `run'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/base_cli.rb:83:in `run_tests'
	from /Users/chartmann/Development/compliance/inspec/lib/inspec/cli.rb:158:in `exec'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/chartmann/Development/compliance/inspec/bin/inspec:12:in `<top (required)>'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/inspec:22:in `load'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/inspec:22:in `<main>'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/chartmann/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

### InSpec and Platform Version

1.45.12

### Replication Case

A sample profile is pushed to https://github.com/chef/inspec/tree/chris-rock/skip-exception

### Possible Solutions

Add handling for those exception, so that the control is skipped properly

**Comment by jerryaldrichiii** [comment]
This is fixed via https://github.com/chef/inspec/pull/2349
