### ISSUE TITLE
inspec check/json fails with the cis-docker-benchmark profile

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#2351]
**Before:**
```
$ inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      aws-sdk (~> 2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
1.39.1

$ inspec json https://github.com/dev-sec/cis-docker-benchmark/archive/master.tar.gz
WARN: Unresolved specs during Gem::Specification.reset:
      aws-sdk (~> 2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
{"name":"cis-docker-benchmark","title":"CIS Docker Benchmark Profile"
...
```

**Now:**
```
$ bundle exec inspec version
1.46.3

$ bundle exec inspec json https://github.com/dev-sec/cis-docker-benchmark/archive/master.tar.gz
`command(docker).exist?` is not suported on your OS: unknown
`command(docker).exist?` is not suported on your OS: unknown
`command(docker).exist?` is not suported on your OS: unknown
`command(docker).exist?` is not suported on your OS: unknown
bundler: failed to load command: inspec (/Users/apop/.chefdk/gem/ruby/2.4.0/bin/inspec)
NoMethodError: undefined method `[]' for nil:NilClass
  cis-docker-benchmark-master/controls/docker_daemon_configuration_files.rb:272:in `block in load_with_context'
  /Users/apop/git/inspec/lib/inspec/rule.rb:49:in `instance_eval'
  /Users/apop/git/inspec/lib/inspec/rule.rb:49:in `initialize'
  /Users/apop/git/inspec/lib/inspec/control_eval_context.rb:73:in `new'
  /Users/apop/git/inspec/lib/inspec/control_eval_context.rb:73:in `block (2 levels) in create'
  cis-docker-benchmark-master/controls/docker_daemon_configuration_files.rb:257:in `load_with_context'
  /Users/apop/git/inspec/lib/inspec/profile_context.rb:148:in `instance_eval'
  /Users/apop/git/inspec/lib/inspec/profile_context.rb:148:in `load_with_context'
  /Users/apop/git/inspec/lib/inspec/profile_context.rb:132:in `load_control_file'
  /Users/apop/git/inspec/lib/inspec/profile.rb:160:in `block in collect_tests'
  /Users/apop/git/inspec/lib/inspec/profile.rb:157:in `each'
  /Users/apop/git/inspec/lib/inspec/profile.rb:157:in `collect_tests'
  /Users/apop/git/inspec/lib/inspec/profile.rb:463:in `load_checks_params'
  /Users/apop/git/inspec/lib/inspec/profile.rb:456:in `load_params'
  /Users/apop/git/inspec/lib/inspec/profile.rb:150:in `params'
  /Users/apop/git/inspec/lib/inspec/profile.rb:201:in `info'
  /Users/apop/git/inspec/lib/inspec/cli.rb:43:in `json'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/apop/git/inspec/bin/inspec:12:in `<top (required)>'
  /Users/apop/.chefdk/gem/ruby/2.4.0/bin/inspec:23:in `load'
  /Users/apop/.chefdk/gem/ruby/2.4.0/bin/inspec:23:in `<top (required)>'
```

**Comment by adamleff** [comment]
Recent enhancements to the JSON resource to raise exceptions and properly handle the “command” parameter during `check` operations have made it so that a JSON resource that failed to initialize will return `nil` for params. 

This is fine for tests, but not fine for method chains outside of a describe. I will fix this later today.
