### ISSUE TITLE
Unable to target Docker containers from Windows

### ISSUE THREAD

**Issue by tpetchel** [inspec/inspec#2379]
### Description

I am unable to target Docker containers from a PowerShell session on Windows. For example, this command fails:

```
$ inspec exec https://github.com/dev-sec/linux-baseline -t docker://4e0400a7863f
```

### InSpec and Platform Version

```
$ [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.16299.0 Microsoft Windows NT 10.0.16299.0
```

```
$ inspec --version
1.47.0
```

```
$ docker --version
Docker version 17.09.0-ce, build afdb6d4
```

### Replication Case

1. Install Docker for Windows and InSpec.
2. Pull down a Linux container.
```
$ docker pull alpine
```
3. Start the container in the background.
```
$ docker run -di alpine
```
4. Get the container ID.
```
$ docker ps | findstr alpine
03c19b328ff8        alpine              "/bin/sh"           38 seconds ago      Up 37 seconds                           eager_haibt
```
5. Scan the container.
```
$ inspec exec https://github.com/dev-sec/linux-baseline -t docker://03c19b328ff8
```

The command fails. See below for stacktrace.

### Possible Solutions

We don't have ideas on how to resolve this, but we see that the error comes from the `excon` connection library. `excon` is attempting to open a Unix socket on a Windows machine.

I was able to get things working from a Bash session from Windows Subsystem for Linux.

### Stacktrace

```
$ inspec exec https://github.com/dev-sec/linux-baseline -t docker://03c19b328ff8
C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/unix_socket.rb:8:in `initialize': An address incompatible with the requested protocol was used. - socket(2) (Errno::EAFNOSUPPORT) (Excon::Error::Socket)
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/unix_socket.rb:8:in `new'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/unix_socket.rb:8:in `connect'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/socket.rb:29:in `initialize'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:402:in `new'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:402:in `socket'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:101:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/mock.rb:48:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:250:in `request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/idempotent.rb:30:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:273:in `rescue in request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:216:in `request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/idempotent.rb:30:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:273:in `rescue in request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:216:in `request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/idempotent.rb:30:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:273:in `rescue in request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.59.0/lib/excon/connection.rb:216:in `request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/docker-api-1.34.0/lib/docker/connection.rb:40:in `request'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/docker-api-1.34.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/docker-api-1.34.0/lib/docker/container.rb:346:in `get'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-0.30.0/lib/train/transports/docker.rb:61:in `initialize'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-0.30.0/lib/train/transports/docker.rb:41:in `new'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-0.30.0/lib/train/transports/docker.rb:41:in `create_new_connection'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-0.30.0/lib/train/transports/docker.rb:22:in `connection'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/backend.rb:51:in `create'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/runner.rb:63:in `configure_transport'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/runner.rb:55:in `initialize'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/base_cli.rb:83:in `new'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/base_cli.rb:83:in `run_tests'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/cli.rb:158:in `exec'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/bin/inspec:12:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:61:in `load'
        from C:/opscode/inspec/bin/inspec:61:in `<main>'
```

**Comment by megamorf** [comment]
The Windows docker daemon is listening on a named pipe by default (similar to a unix socket) and can optionally be [configured](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#configure-docker-with-configuration-file) to also listen on a given TCP port. 

But since you're trying to access the docker daemon from within the official inspec container you'd actually have to mount it into the container to be able to communicate with it.

**Comment by jerryaldrichiii** [comment]
@tpetchel, @megamorf is on the right track. The `docker-api` gem that Train uses to connect to the Docker API uses a Unix socket by default. To the best of my knowledge Unix sockets (Socket::AF_UNIX) are not supported on most Windows.

As @megamorf said, you can configure Docker to listen on a TCP socket, but the `docker-api` gem does not have handling to attempt a TCP socket connection if the default Unix socket method fails. This means that we would need to modify Train to fallback to a TCP socket. Since we currently do not support TCP sockets for Docker connections I'm going to close this bug and open a feature request on Train to support this functionality.
