### ISSUE TITLE
xml resource interpreting contents

### ISSUE THREAD

**Issue by aboutte** [inspec/inspec#2387]
### Description

XML resource interpreting contents of XML file

### InSpec and Platform Version

1.45.13
Mac 10.11.5

### Replication Case

- use the provided inspec code
- use the provided xml file

inspec:

```
  describe xml('C:\Program Files\Amazon\Ec2ConfigService\Settings\config.xml') do
    its("Ec2ConfigurationSettings/Plugins[10]/Plugin/Name/AWS.EC2.Windows.CloudWatch.PlugIn") { should eq 'Enabled' }
  end
```

xml file:

```
<?xml version="1.0" standalone="yes"?>
<Ec2ConfigurationSettings>
  <Plugins>
    <Plugin>
      <Name>Ec2SetPassword</Name>
      <State>Disabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2SetComputerName</Name>
      <State>Disabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2InitializeDrives</Name>
      <State>Enabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2EventLog</Name>
      <State>Disabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2ConfigureRDP</Name>
      <State>Disabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2OutputRDPCert</Name>
      <State>Enabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2SetDriveLetter</Name>
      <State>Enabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2WindowsActivate</Name>
      <State>Enabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2DynamicBootVolumeSize</Name>
      <State>Disabled</State>
    </Plugin>
    <Plugin>
      <Name>Ec2HandleUserData</Name>
      <State>Disabled</State>
    </Plugin>
    <Plugin>
      <Name>AWS.EC2.Windows.CloudWatch.PlugIn</Name>
      <State>Enabled</State>
    </Plugin>
  </Plugins>
  <GlobalSettings>
    <ManageShutdown>true</ManageShutdown>
    <SetDnsSuffixList>true</SetDnsSuffixList>
    <WaitForMetaDataAvailable>true</WaitForMetaDataAvailable>
    <ShouldAddRoutes>true</ShouldAddRoutes>
    <RemoveCredentialsfromSysprepOnStartup>true</RemoveCredentialsfromSysprepOnStartup>
  </GlobalSettings>
</Ec2ConfigurationSettings>
```

### Stacktrace

```
  XML C:\Program
     ∅  undefined method `EC2' for []:Array
  Json C:\Program
     ✔  Files\Amazon\SSM\Plugins\awsCloudWatch\AWS.EC2.Windows.CloudWatch.json IsEnabled should eq true
  Json C:\Program
     ✔  Files\Amazon\SSM\Plugins\awsCloudWatch\AWS.EC2.Windows.CloudWatch.json ["EngineConfiguration", "Components", 1, "Parameters", "LogGroup"] should not eq ""
  Json C:\Program
     ✔  Files\Amazon\SSM\Plugins\awsCloudWatch\AWS.EC2.Windows.CloudWatch.json ["EngineConfiguration", "Components", 1, "Parameters", "LogStream"] should not eq ""
  File C:\Program
     ✔  Files\Amazon\SSM\Plugins\awsCloudWatch\AWS.EC2.Windows.CloudWatch.json content should match /.*\/var\/log\/httpd\/mysite.com\/access_log.*/
  Service AmazonSSMAgent
     ✔  should be installed
     ✔  should be running

Test Summary: 6 successful, 1 failure, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <cldw-windows2008>.  Please see .kitchen/logs/cldw-windows2008.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

```
$ cat .kitchen/logs/kitchen.log
I, [2017-12-11T14:26:06.348281 #53091]  INFO -- Kitchen: -----> Starting Kitchen (v1.19.2)
I, [2017-12-11T14:26:12.451962 #53091]  INFO -- Kitchen: -----> Verifying <cldw-windows2008>...
E, [2017-12-11T14:26:16.112553 #53091] ERROR -- Kitchen: ------Exception-------
E, [2017-12-11T14:26:16.112621 #53091] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-12-11T14:26:16.112640 #53091] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Verify failed on instance <cldw-windows2008>.  Please see .kitchen/logs/cldw-windows2008.log for more details
E, [2017-12-11T14:26:16.112655 #53091] ERROR -- Kitchen: ----------------------
E, [2017-12-11T14:26:16.112668 #53091] ERROR -- Kitchen: ------Backtrace-------
E, [2017-12-11T14:26:16.112680 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-12-11T14:26:16.112693 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:174:in `run_action'
E, [2017-12-11T14:26:16.112706 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:36:in `block in call'
E, [2017-12-11T14:26:16.112718 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-12-11T14:26:16.112744 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:34:in `call'
E, [2017-12-11T14:26:16.112757 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:52:in `perform'
E, [2017-12-11T14:26:16.112770 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
E, [2017-12-11T14:26:16.112782 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-12-11T14:26:16.112794 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-12-11T14:26:16.112806 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-12-11T14:26:16.112818 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-12-11T14:26:16.112830 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `block in <top (required)>'
E, [2017-12-11T14:26:16.112842 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-12-11T14:26:16.112854 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `<top (required)>'
E, [2017-12-11T14:26:16.112869 #53091] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:255:in `load'
E, [2017-12-11T14:26:16.112881 #53091] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:255:in `<main>'
E, [2017-12-11T14:26:16.112892 #53091] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-12-11T14:26:16.112904 #53091] ERROR -- Kitchen: -Composite Exception--
E, [2017-12-11T14:26:16.112915 #53091] ERROR -- Kitchen: Class: Kitchen::InstanceFailure
E, [2017-12-11T14:26:16.112974 #53091] ERROR -- Kitchen: Message: Verify failed on instance <cldw-windows2008>.  Please see .kitchen/logs/cldw-windows2008.log for more details
E, [2017-12-11T14:26:16.112994 #53091] ERROR -- Kitchen: ----------------------
E, [2017-12-11T14:26:16.113007 #53091] ERROR -- Kitchen: ------Backtrace-------
E, [2017-12-11T14:26:16.113018 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.20.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-12-11T14:26:16.113031 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:443:in `block in verify_action'
E, [2017-12-11T14:26:16.113043 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2017-12-11T14:26:16.113066 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
E, [2017-12-11T14:26:16.113082 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-12-11T14:26:16.113095 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
E, [2017-12-11T14:26:16.113108 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:435:in `verify_action'
E, [2017-12-11T14:26:16.113119 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2017-12-11T14:26:16.113131 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
E, [2017-12-11T14:26:16.113143 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
E, [2017-12-11T14:26:16.113154 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:157:in `verify'
E, [2017-12-11T14:26:16.113165 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
E, [2017-12-11T14:26:16.113177 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-12-11T14:26:16.113189 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-12-11T14:26:16.113203 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2017-12-11T14:26:16.113216 #53091] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-12-11T14:26:16.113227 #53091] ERROR -- Kitchen: ---Nested Exception---
E, [2017-12-11T14:26:16.113238 #53091] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-12-11T14:26:16.113250 #53091] ERROR -- Kitchen: Message: Inspec Runner returns 1
E, [2017-12-11T14:26:16.113261 #53091] ERROR -- Kitchen: ----------------------
E, [2017-12-11T14:26:16.113272 #53091] ERROR -- Kitchen: ------Backtrace-------
E, [2017-12-11T14:26:16.113284 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.20.0/lib/kitchen/verifier/inspec.rb:96:in `call'
E, [2017-12-11T14:26:16.113296 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:443:in `block in verify_action'
E, [2017-12-11T14:26:16.113308 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2017-12-11T14:26:16.113319 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
E, [2017-12-11T14:26:16.113331 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-12-11T14:26:16.113346 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
E, [2017-12-11T14:26:16.113359 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:435:in `verify_action'
E, [2017-12-11T14:26:16.113370 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2017-12-11T14:26:16.113382 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
E, [2017-12-11T14:26:16.113397 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
E, [2017-12-11T14:26:16.113410 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:157:in `verify'
E, [2017-12-11T14:26:16.113422 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
E, [2017-12-11T14:26:16.113433 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-12-11T14:26:16.113445 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-12-11T14:26:16.113457 #53091] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2017-12-11T14:26:16.113472 #53091] ERROR -- Kitchen: ----End Backtrace-----
```

**Comment by adamleff** [comment]
Hi, @aboutte! Thanks for your issue.

The problem isn't that InSpec is evaluating the XML, but rather that it's seeing periods in your XPath parameter and trying to turn that into a Ruby method chain. I just put up PR #2389 to clarify in the docs that there is an alternate syntax where you wrap your string with `[ ]` to prevent the underlying library from seeing the periods and trying to turn them into methods.

Also, I'm not an XPath expert by any stretch, but I don't believe your parameter will get you what you're looking for because the actual plugin name is text of an element, not an element itself. I think you're going to need to do something more like this:

```ruby
describe xml('/tmp/test.xml') do
  its(["Ec2ConfigurationSettings/Plugins/Plugin/[.='AWS.EC2.Windows.CloudWatch.PlugIn']/parent::Plugin/State"]) { should cmp 'Enabled' }
end
```

Anyhow, I hope that helps!
