### ISSUE TITLE
Docker for windows

### ISSUE THREAD

**Issue by sharathj007** [inspec/inspec#2422]
### Description

Unable to switch the docker to Linux container on Windows server 2016, i have installed the windows docker community edition in my one of the Virtual Machine. I am badly struck up with this issue from couple of months, any solution provided here will be very much helpful.
Thank you in advance.

### InSpec and Platform Version

Docker version installed:
Docker Community Edition Version 17.09.0-ce-win33(13620)

### Replication Case

Steps to reproduce the issue
.  Install the Docker Community Edition Version 17.09.0-ce-win33(13620) in windows server 2016 in virtual machine.
. Run the docker 
. Right click on the docker and switch to Linux Containers.

### Possible Solutions

Windows 2010, which switch to Linux containers is working as expected, the issue seems to be with the virtual machine on Windows server 2016

### Stacktrace
Please find the Error while switching to the linux containers
The operation has timed out.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by adamleff** [comment]
I think you meant to log this issue in the Docker/Moby project. This is the InSpec project which is a compliance-as-code solution. Closing issue.
