### ISSUE TITLE
Inspec not generating result lines on large test

### ISSUE THREAD

**Issue by sarahbakal** [inspec/inspec#2424]
### Description

Control is describing 4k files x 11 tests and takes an extreme amount of time (we've waited over an hour) to generate the last two result lines.

### InSpec and Platform Version

RHEL 6.9
Inspec 1.42.3 and 1.48.0

### Replication Case

/var/log has around 4,000 files
last control describes 11 items per file.
Inspec displays the outputs of each test, but the final 2 summary lines dont generate and a force quit results in the stack trace. 

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace
```
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:149:in `hash': Interrupt
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:149:in `hash'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:149:in `hash'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:149:in `uniq'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:149:in `all_unique_controls'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:160:in `profile_summary'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:618:in `print_profile_summary'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/rspec_json_formatter.rb:412:in `close'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:206:in `block in notify'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:205:in `each'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:205:in `notify'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:238:in `close'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:193:in `close_after'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:171:in `finish'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:81:in `report'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:112:in `run_specs'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/runner_rspec.rb:77:in `run'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/runner.rb:116:in `run_tests'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/runner.rb:100:in `run'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/base_cli.rb:83:in `run_tests'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/lib/inspec/cli.rb:159:in `exec'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
    from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.42.3/bin/inspec:12:in `<top (required)>'
    from /opt/chef/embedded/bin/inspec:23:in `load'
    from /opt/chef/embedded/bin/inspec:23:in `<main>'
```

**Comment by clintoncwolfe** [comment]
Hi @sarahbakal!  I'm sorry you're experiencing some difficulties, and I'm grateful for the report so we can try to get this fixed.

The last two lines of the output are typically a summary, counting the number of controls and tests.  Depending on how your controls and tests are laid out, our implementation of the summary code may be badly performing.  I don't think the stack trace is anything unusual; if you let it run to completion (which may take hours, which is unacceptable) I suspect it would finish normally.

Two things might help us diagnose this:
1.  Could you share your control code (be sure to remove any sensitive information)?
2.  Could you let inspec run to completion, and share with us the summary lines?

Thanks!

**Comment by clintoncwolfe** [comment]
@jquick also, I see the JSON formatter in the stack, any thoughts?

**Comment by tarcinil** [comment]
@clintoncwolfe 

I remember speaking with @sarahbakal in Slack and here is a link to the thread.

https://chefcommunity.slack.com/archives/C1XB6U6MN/p1514406557000344?thread_ts=1514404153.000081&cid=C1XB6U6MN

but the control in question looks like:

```
control 'System-log-File-Perms' do
  impact 0.5
  title 'System Log File Permissions'
  desc "owner=root; group=root; perms=0600"
  command('find /var/log -type f').stdout.split.each do |repo_file|
    describe file(repo_file) do
      its('owner') { should eq 'root' }
      its('group') { should eq 'root' }
      it { should_not be_executable.by('owner') }
      it { should be_readable.by('owner') }
      it { should be_writable.by('owner') }
      it { should_not be_executable.by('group') }
      it { should_not be_readable.by('group') }
      it { should_not be_writable.by('group') }
      it { should_not be_executable.by('other') }
      it { should_not be_readable.by('other') }
      it { should_not be_writable.by('other') }
    end
  end
```

**Comment by sarahbakal** [comment]
I'm reproducing the issue with test-kitchen since the original affected VM had a session timeout which made it difficult to wait for completion. Will post when the summary lines appear.

**Comment by sarahbakal** [comment]
@clintoncwolfe @tarcinil

Profile Summary: 1 successful control, 3 control failures, 0 controls skipped
Test Summary: 55901 successful, 13658 failures, 0 skipped

Timeline:
Started at 10:22am, at 10:34 the individual test results were outputted, at 3pm Profile Summary outputted and at 7:26pm Test Summary

```
title 'Logging baselines'

control 'logging-xinetd' do
  impact 0.5
  title 'Configure Xinetd Logging'
  desc "xinetd logging config should log failures and success on correct events to the authpriv SYSLOG target"
  only_if { file('/etc/xinetd.conf').exist? }
  describe file('/etc/xinetd.conf') do
    its('content') { should match /log_on_failure\s+=\s+HOST USERID/ }
    its('content') { should match /log_on_success\s+=\s+HOST PID USERID EXIT/ }
    its('content') { should match /log_type\s+=\s+SYSLOG authpriv/ }
  end
end

control 'logging-vsftp' do
  impact 0.5
  title "DISA RHEL6 STIG (V1R2) - Enable vsftpd Additional logging"
  desc "
    vsftpd logging config should log in standard format and log
    events using the ftp protocol
    "
  only_if { file('/etc/vsftpd/vsftpd.conf').exist? }
  describe file('/etc/vsftpd/vsftpd.conf') do
    its('content') { should match /xferlog_std_format=YES/ }
    its('content') { should match /log_ftp_protocol=YES/ }
  end
end

control 'disable-remote-syslog' do
  impact 0.5
  title "Disable remote syslog"
  desc "verifies there is no -r in rsyslog"
  only_if { file('/etc/init.d/rsyslog').exist? }
  describe command("egrep 'SYSLOGD_OPTIONS.*-r|-r.*SYSLOGD_OPTIONS' /etc/init.d/rsyslog") do
    its('stdout') {should_not match /-r/}
  end
end

control 'System-log-File-Perms' do
  impact 0.5
  title 'System Log File Permissions'
  desc "owner=root; group=root; perms=0600"
  command('find /var/log -type f').stdout.split.each do |repo_file|
    describe file(repo_file) do
      its('owner') { should eq 'root' }
      its('group') { should eq 'root' }
      it { should_not be_executable.by('owner') }
      it { should be_readable.by('owner') }
      it { should be_writable.by('owner') }
      it { should_not be_executable.by('group') }
      it { should_not be_readable.by('group') }
      it { should_not be_writable.by('group') }
      it { should_not be_executable.by('other') }
      it { should_not be_readable.by('other') }
      it { should_not be_writable.by('other') }
    end
  end
end
```

```
find /var/log -type f | wc -l
6323
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
