### ISSUE TITLE
error uploading inherited profile to compliance server

### ISSUE THREAD

**Issue by raghureddy45** [inspec/inspec#2425]
### Description
created a inherited profile and skipped controls that i don't need. when i try to upload to compliance server getting following error.

### InSpec and Platform Version
chef compliance version => 1.12.1
inspec version => inspec-1.34.9

##Steps done so far
1) inspec compliance login https://chef.compfinal.com --insecure --user='hitman45' --refresh_token='xxxx'
2) inspec init profile skiplinux

inspec.yml file looks like this

name: skiplinux
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
  - name: linux
    compliance: base/linux 

 --> controls/example.rb looks like this

IT-LDR-RMODIP:skiplinux Raghureddy$ cat controls/example.rb

include_controls 'linux' do
 skip_control 'fs-1'
end

3) inspec vendor

4) inspec archive .

##then tried to upload to compliance 

5)inspec compliance upload skiplinux

Start upload to hitman45/skiplinux
Uploading to Chef Compliance
Error during profile upload:
"Failed to POST /owners/hitman45/compliance/skiplinux/tar."

### compliance log /var/log/chef-compliance/core/current

2017-12-27_22:03:04.21480 22:03:04.213 DEB => Extracting incoming tar to /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012
2017-12-27_22:03:04.21481 22:03:04.214 DEB => Extracted upload to /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012
2017-12-27_22:03:04.21481 22:03:04.214 DEB => Found compliance root folder in /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012
2017-12-27_22:03:04.21481 22:03:04.214 DEB => Run: cd /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012 && inspec [check . --format json --profiles-path /var/opt/chef-compliance/core/runtime/compliance-profiles]
2017-12-27_22:03:05.68480 WARN: Unresolved specs during Gem::Specification.reset:
2017-12-27_22:03:05.68482       net-ssh (< 5.0, >= 2.6.5, >= 2.9)
2017-12-27_22:03:05.68482       ffi (>= 1.0.1)
2017-12-27_22:03:05.68482       multi_json (~> 1.10)
2017-12-27_22:03:05.68483       rainbow (~> 2)
2017-12-27_22:03:05.68483       rspec (~> 3)
2017-12-27_22:03:05.68483       addressable (~> 2.4)
2017-12-27_22:03:05.68483 WARN: Clearing out unresolved specs.
2017-12-27_22:03:05.68483 Please report a bug if this causes problems.
2017-12-27_22:03:05.94480 /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:101:in `parse': Illformed requirement ["[]"] (Gem::Requirement::BadRequirementError)
2017-12-27_22:03:05.94481       from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `block in initialize'
2017-12-27_22:03:05.94482       from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `map!'
2017-12-27_22:03:05.94482       from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `initialize'
2017-12-27_22:03:05.94482       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:34:in `new'
2017-12-27_22:03:05.94483       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:34:in `initialize'
2017-12-27_22:03:05.94483       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:17:in `new'
2017-12-27_22:03:05.94483       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:17:in `from_lock_entry'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:19:in `block in from_lockfile'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:18:in `map'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:18:in `from_lockfile'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:398:in `load_dependencies'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:348:in `locked_dependencies'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:169:in `load_libraries'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:453:in `load_checks_params'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:447:in `load_params'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:141:in `params'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:307:in `controls_count'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:278:in `check'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/cli.rb:69:in `check'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
2017-12-27_22:03:05.94487       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/bin/inspec:12:in `<top (required)>'
2017-12-27_22:03:05.94487       from /opt/chef-compliance/embedded/bin/inspec:23:in `load'
2017-12-27_22:03:05.94487       from /opt/chef-compliance/embedded/bin/inspec:23:in `<main>'
2017-12-27_22:03:05.95766 22:03:05.957 ERR => Failed to POST /owners/hitman45/compliance/skiplinux/tar.exit status 1
2017-12-27_22:03:05.95767 [GIN] 2017/12/27 - 22:03:05 | 500 |  1.746412948s | 10.223.100.62 |   POST    /owners/hitman45/compliance/skiplinux/tar

I am using latest version of compliance server. what might be the issue?

thanks in advance!!!

**Comment by chris-rock** [comment]
Are you running inspec on Windows?

**Comment by raghureddy45** [comment]
from Mac(workstation), I was trying to uploading inherited profiles to compliance server(redhat).

**Comment by MichaelMcClanahan** [comment]
I too am hitting this issue and can reproduce with a generic InSpec profile.

**InSpec version:** `1.50.0`
**Compliance version:** `1.12.1`

**Local Mac Workstation:**
```
michaelmcclanahan$ tree test
test
├── README.md
├── controls
│   └── example.rb
├── inspec.lock
├── inspec.yml
├── libraries
└── vendor
    └── 6941027ad1955d04677893627e38aae4c2a5e813f63d8f113e1bc9f79c89ee38.tar.gz
```

```
michaelmcclanahan$ cat test/inspec.yml
name: test
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
  - name: linux
    compliance: base/linux
```
```
michaelmcclanahan$ inspec check test
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      multi_json (~> 1.10)
      winrm-fs (~> 1.0)
      docker-api (~> 1.26)
      thor (~> 0.19)
      public_suffix (< 4.0, >= 2.0.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Location:    test
Profile:     test
Controls:    2
Timestamp:   2018-02-05T15:16:43-06:00
Valid:       true

No errors or warnings
```
```
michaelmcclanahan$ inspec compliance upload test --overwrite
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      multi_json (~> 1.10)
      winrm-fs (~> 1.0)
      docker-api (~> 1.26)
      thor (~> 0.19)
      public_suffix (< 4.0, >= 2.0.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Dependencies for profile test successfully vendored to test/vendor
I, [2018-02-05T16:15:44.844508 #3166]  INFO -- : Checking profile in test
I, [2018-02-05T16:15:44.844955 #3166]  INFO -- : Metadata OK.
I, [2018-02-05T16:15:44.856367 #3166]  INFO -- : Found 2 controls.
I, [2018-02-05T16:15:44.856408 #3166]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at /var/folders/zw/456jf8jj3bddtk5f53zbmwc80000gn/T/test20180205-3166-juwqtb.tar.gz
I, [2018-02-05T16:15:45.419929 #3166]  INFO -- : Generate archive /var/folders/zw/456jf8jj3bddtk5f53zbmwc80000gn/T/test20180205-3166-juwqtb.tar.gz.
I, [2018-02-05T16:15:45.424070 #3166]  INFO -- : Finished archive generation.
Start upload to michaelmcclanahan/test
Uploading to Chef Compliance
Error during profile upload:
"Failed to POST /owners/michaelmcclanahan/compliance/test/tar."
```

**Compliance server:**
```
michaelmcclanahan$ cat /var/log/chef-compliance/core/current
2018-02-05_22:40:23.26510 [GIN] 2018/02/05 - 22:40:23 | 200 |    1.137603ms | 192.168.0.13 |   GET     /user/compliance
2018-02-05_22:40:23.81738 22:40:23.817 ERR => DB error: sql: no rows in result set
2018-02-05_22:40:23.81776 22:40:23.817 ERR => DB error: sql: no rows in result set
2018-02-05_22:40:23.81780 22:40:23.817 INF => Streaming compliance tar for base/linux
2018-02-05_22:40:23.81872 [GIN] 2018/02/05 - 22:40:23 | 200 |    2.500092ms | 192.168.0.13 |   GET     /owners/base/compliance/linux/tar
2018-02-05_22:40:24.54542 [GIN] 2018/02/05 - 22:40:24 | 200 |    1.161157ms | 192.168.0.13 |   GET     /user/compliance
2018-02-05_22:40:25.17546 22:40:25.175 ERR => DB error: sql: no rows in result set
2018-02-05_22:40:26.63255 WARN: Unresolved specs during Gem::Specification.reset:
2018-02-05_22:40:26.63258       net-ssh (< 5.0, >= 2.6.5, >= 2.9)
2018-02-05_22:40:26.63259       ffi (>= 1.0.1)
2018-02-05_22:40:26.63259       multi_json (~> 1.10)
2018-02-05_22:40:26.63259       rainbow (~> 2)
2018-02-05_22:40:26.63260       rspec (~> 3)
2018-02-05_22:40:26.63260       addressable (~> 2.4)
2018-02-05_22:40:26.63261 WARN: Clearing out unresolved specs.
2018-02-05_22:40:26.63261 Please report a bug if this causes problems.
2018-02-05_22:40:26.87916 /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:101:in `parse': Illformed requirement ["[]"] (Gem::Requirement::BadRequirementError)
2018-02-05_22:40:26.87918   from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `block in initialize'
2018-02-05_22:40:26.87919   from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `map!'
2018-02-05_22:40:26.87919   from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `initialize'
2018-02-05_22:40:26.87920   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:34:in `new'
2018-02-05_22:40:26.87920   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:34:in `initialize'
2018-02-05_22:40:26.87921   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:17:in `new'
2018-02-05_22:40:26.87921   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:17:in `from_lock_entry'
2018-02-05_22:40:26.87921   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:19:in `block in from_lockfile'
2018-02-05_22:40:26.87922   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:18:in `map'
2018-02-05_22:40:26.87922   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:18:in `from_lockfile'
2018-02-05_22:40:26.87923   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:398:in `load_dependencies'
2018-02-05_22:40:26.87923   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:348:in `locked_dependencies'
2018-02-05_22:40:26.87924   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:169:in `load_libraries'
2018-02-05_22:40:26.87924   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:453:in `load_checks_params'
2018-02-05_22:40:26.87925   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:447:in `load_params'
2018-02-05_22:40:26.87925   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:141:in `params'
2018-02-05_22:40:26.87926   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:307:in `controls_count'
2018-02-05_22:40:26.87926   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:278:in `check'
2018-02-05_22:40:26.87927   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/cli.rb:69:in `check'
2018-02-05_22:40:26.87928   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
2018-02-05_22:40:26.87928   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
2018-02-05_22:40:26.87928   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
2018-02-05_22:40:26.87929   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
2018-02-05_22:40:26.87930   from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/bin/inspec:12:in `<top (required)>'
2018-02-05_22:40:26.87931   from /opt/chef-compliance/embedded/bin/inspec:23:in `load'
2018-02-05_22:40:26.87931   from /opt/chef-compliance/embedded/bin/inspec:23:in `<main>'
2018-02-05_22:40:26.90038 22:40:26.900 ERR => Failed to POST /owners/michaelmcclanahan/compliance/test/tar.exit status 1
2018-02-05_22:40:26.90042 [GIN] 2018/02/05 - 22:40:26 | 500 |   1.72717613s | 192.168.0.13 |   POST    /owners/michaelmcclanahan/compliance/test/tar
```

**Comment by MichaelMcClanahan** [comment]
For now, I was able to work around this by uploading a profile with no dependencies. I just copied all controls from the upstream profile into my current profile.
