### ISSUE TITLE
appbundle-updater chefdk inspec <git_ref> missing rake as of version 1.47.6 of inspec

### ISSUE THREAD

**Issue by jvanlieshout** [inspec/inspec#2445]
### Description

As of Inspec version 1.47.6 `appbundle-updater chefdk inspec <git_ref>` fails with an error that rake is missing.

### InSpec and Platform Version

chefdk 1.6.11
appbundle-updater 0.5.1

### Replication Case

broken:
```bash
chef gem install appbundle-updater
sudo appbundle-updater chefdk inspec master
```

still working:
```bash
chef gem install appbundle-updater
sudo appbundle-updater chefdk inspec v1.47.5
```

### Possible Solutions

No idea... revert commit 5be9739ec1ccbd98e0573d92fbaa2afa6d1cd6de perhaps?

### Stacktrace

```bash
sudo appbundle-updater chefdk inspec master 
-----> Cleaning inspec checkout
-----> Installing Packages
[2018-01-05T11:52:40+01:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
i do not know how to install compilers and git on this platform...
-----> Cloning inspec from https://github.com/chef/inspec.git
    running: git clone https://github.com/chef/inspec.git /opt/chefdk/embedded/apps/inspec
-----> Checking out inspec to master
    running: git checkout master
-----> Installing dependencies
    running: /opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle install --without test integration tools maintenance deploy
-----> Installing gem
    running: /opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle exec /opt/chefdk/embedded/bin/rake install
/Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:58:in `run': Command [/opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle exec /opt/chefdk/embedded/bin/rake install] failed! (RuntimeError)

---BEGIN OUTPUT--
bundler: failed to load command: /opt/chefdk/embedded/bin/rake (/opt/chefdk/embedded/bin/rake)
Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:458:in `block in replace_bin_path'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:478:in `block in replace_bin_path'
  /opt/chefdk/embedded/bin/rake:23:in `<top (required)>'

---END OUTPUT--
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:269:in `ruby'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:245:in `block in start'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:244:in `chdir'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:244:in `start'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:317:in `<top (required)>'
	from /Users/######/.chefdk/gem/ruby/2.3.0/bin/appbundle-updater:23:in `load'
	from /Users/######/.chefdk/gem/ruby/2.3.0/bin/appbundle-updater:23:in `<main>'
```

```bash
sudo appbundle-updater chefdk inspec v1.47.6
-----> Cleaning inspec checkout
-----> Installing Packages
[2018-01-05T11:59:11+01:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
i do not know how to install compilers and git on this platform...
-----> Cloning inspec from https://github.com/chef/inspec.git
    running: git clone https://github.com/chef/inspec.git /opt/chefdk/embedded/apps/inspec
-----> Checking out inspec to v1.47.6
    running: git checkout v1.47.6
-----> Installing dependencies
    running: /opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle install --without test integration tools maintenance deploy
-----> Installing gem
    running: /opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle exec /opt/chefdk/embedded/bin/rake install
/Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:58:in `run': Command [/opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle exec /opt/chefdk/embedded/bin/rake install] failed! (RuntimeError)

---BEGIN OUTPUT--
bundler: failed to load command: /opt/chefdk/embedded/bin/rake (/opt/chefdk/embedded/bin/rake)
Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:458:in `block in replace_bin_path'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:478:in `block in replace_bin_path'
  /opt/chefdk/embedded/bin/rake:23:in `<top (required)>'

---END OUTPUT--
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:269:in `ruby'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:245:in `block in start'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:244:in `chdir'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:244:in `start'
	from /Users/######/.chefdk/gem/ruby/2.3.0/gems/appbundle-updater-0.5.0/bin/appbundle-updater:317:in `<top (required)>'
	from /Users/######/.chefdk/gem/ruby/2.3.0/bin/appbundle-updater:23:in `load'
	from /Users/######/.chefdk/gem/ruby/2.3.0/bin/appbundle-updater:23:in `<main>'
```

```bash
sudo appbundle-updater chefdk inspec v1.47.5
-----> Cleaning inspec checkout
-----> Installing Packages
[2018-01-05T11:57:53+01:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
i do not know how to install compilers and git on this platform...
-----> Cloning inspec from https://github.com/chef/inspec.git
    running: git clone https://github.com/chef/inspec.git /opt/chefdk/embedded/apps/inspec
-----> Checking out inspec to v1.47.5
    running: git checkout v1.47.5
-----> Installing dependencies
    running: /opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle install --without test integration tools maintenance deploy
-----> Installing gem
    running: /opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/bundle exec /opt/chefdk/embedded/bin/rake install
-----> Updating appbundler binstubs for inspec
    running: /opt/chefdk/embedded/bin/ruby /opt/chefdk/embedded/bin/appbundler /opt/chefdk/embedded/apps/inspec /opt/chefdk/bin
-----> Finished!
```

**Comment by NickRycar** [comment]
I was able to reproduce this on my end on both MacOS and Windows. 

To validate whether updating the Gemfile would solve, I modified my local appbundle-updater to remove "test" from the ignored groups, since that's where rake seems to be defined, and was able to successfully install InSpec2 via the same command. Bundling without test seems like a reasonable default in that project. Should we move 'rake' out of the test group, since the install command for inspec calls for a "bundle exec rake"?

Reference of changed line in my local testing: https://github.com/chef/appbundle-updater/blob/master/bin/appbundle-updater#L172

**Comment by llibicpep** [comment]
Even though I managed to workaround this `Gemfile` issue, it doesn't seem working:

```
jenkins@fd8792d0493a:~$ chef --version
Chef Development Kit Version: 3.0.23
chef-client version: 14.0.202
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 7.0.0
kitchen version: 1.21.1
inspec version: 2.1.0
```

But

```
jenkins@fd8792d0493a:~$ chef exec inspec --version
1.48.0

Your version of InSpec is out of date! The latest version is 2.1.59.
```

Seems like `/opt/chefdk/bin/inspec` have not been changed.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
