### ISSUE TITLE
Is Remote/Standalone access via Atlasssian Stash supported?

### ISSUE THREAD

**Issue by cjbischoff** [inspec/inspec#2482]
### Description

Is the remote execute only supported from Github?

### InSpec and Platform Version

 1.51.0.

### Replication Case

Profile is located on Atlassian Stash repo

inspec.yml

```
depends:
  - name: inspec-pf-win-base
    url: https://stash.domain.com/projects/KIT/repos/pf-inspec
```

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace
```
       Loaded inspec-pf-win-base
[2018-01-26T00:29:05+00:00] WARN: Unrecognized content type: text/html;charset=UTF-8. Assuming tar.gz
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [not in gzip format] on default-win-core-2016
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by kmf** [comment]
@cjbischoff I would say it's a problem .... 
I imported a profile to my gitlab account and got the same error ...
```
 kmf  piggy  ~  $  inspec exec https://gitlab.com/kmf/linux-baseline
[2018-01-26T18:04:12+02:00] WARN: Unrecognized content type: text/html; charset=utf-8. Assuming tar.gz
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/file_provider.rb:160:in `initialize': not in gzip format (Zlib::GzipFile::Error)
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/file_provider.rb:160:in `open'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/file_provider.rb:160:in `walk_tar'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/file_provider.rb:139:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/file_provider.rb:14:in `new'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/file_provider.rb:14:in `for_path'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/profile.rb:55:in `for_path'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/profile.rb:72:in `for_fetcher'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/profile.rb:78:in `for_target'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/runner.rb:170:in `add_target'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/base_cli.rb:82:in `block in run_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/base_cli.rb:82:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/base_cli.rb:82:in `run_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/lib/inspec/cli.rb:158:in `exec'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.45.13/bin/inspec:12:in `<top (required)>'
	from /opt/chefdk/bin/inspec:255:in `load'
	from /opt/chefdk/bin/inspec:255:in `<main>'
```


However when I ran it like this .... it worked ...
```
inspec exec https://gitlab.com/kmf/linux-baseline/repository/master/archive.tar.gz
.
.
.
Profile Summary: 25 successful controls, 27 control failures, 2 controls skipped
Test Summary: 67 successful, 52 failures, 2 skipped
```

**Comment by cjbischoff** [comment]
I will test, but Stash does allow for this method to download in a compressed format - ```/archive?format=zip'```

**Comment by tarcinil** [comment]
InSpec url fetcher is only configured for GitHub and Bitbucket (bitbucket.org) for transforming to the gzip formats for those sites.
Source: https://github.com/chef/inspec/blob/master/lib/fetchers/url.rb#L65

The error that is posted above says that the mime type is `text/html` is being returned, and the url fetcher only supports the following mime types.
```
      'application/x-zip-compressed' => '.zip',
      'application/zip' => '.zip',
      'application/x-gzip' => '.tar.gz',
      'application/gzip' => '.tar.gz',
```
The URL fetcher will work as long as a zip/tar.gz format is returned as seen in @kmf example.  tar.gz is the preferred fallback mime type.  The gitlab url returns an octet-stream which is able to be uncompressed.

**Comment by adamleff** [comment]
Hi friends, and thanks @tarcinil for chiming in with what I was going to say :)

If we can detect a public GitHub or Bitbucket repo URL, we'll translate it automatically to the right thing. This obviously doesn't work for private GH/Bitbucket servers, or other git implementations InSpec does not understand.

The best thing to do is supply a direct URL to a compressed archive (either .tar.gz or .zip) that InSpec can download and explode accordingly rather than assuming InSpec will translate it for you.

Thanks!
