### ISSUE TITLE
Windows service: Add More Matchers

### ISSUE THREAD

**Issue by haidangwa** [inspec/inspec#2483]
### Description

I tried using the service resource to test Windows services. The only one that seems to work is `should be_installed`.

### InSpec and Platform Version

- Windows 2012 Server R2 running in a openstack VM
- kitchen-inspec 0.20.0
- inspec 1.45.13
- chefdk 2.4.17

### Replication Case

My inspec file contains this stanza, which is verifying that the Symantec Intrusion Detection services are disabled.

```
  %w[SISIPSUtil SISIPSService SISIDSService].each do |srvc|
    describe service(srvc) do
      it { should be_installed }
      it { should be_stopped }
      it { should be_disabled }
    end
  end
```
### Workaround

This code works, but it's not as clean as it probably could be.

```
  %w[SISIPSUtil SISIPSService SISIDSService].each do |srvc|
    ps_cmd = "Get-WmiObject -Class Win32_Service -Filter  \"name = '#{srvc}'\" |fl * -Force"
    regex = {
      disabled: /StartMode\s*:\sDisabled/,
      stopped: /State\s*:\sStopped/
    }
    describe powershell(ps_cmd) do
      its('exit_status') { should eq 0 }
      its('stdout') { should match(regex[:disabled]) }
      its('stdout') { should match(regex[:stopped]) }
    end
    describe service(srvc) do
      it { should be_installed }
    end
  end
```

This also works, but I'm not sure about the correctness of `should_not be_running`:
```
  %w[SISIPSUtil SISIPSService SISIDSService].each do |srvc|
    ps_cmd = 'Get-WmiObject -Class Win32_Service -Filter ' \
     "\"name = '#{srvc}'\" |fl * -Force"
    regex = /StartMode\s*:\sDisabled/
    describe powershell(ps_cmd) do
      its('exit_status') { should eq 0 }
      its('stdout') { should match(regex) }
    end
    describe service(srvc) do
      it { should be_installed }
      it { should_not be_running }
    end
```

### Stacktrace

The inspec report results in this:
```
  ∅  Windows service disabled: test Windows is disabled (6 failed)
     ✔  System Package Symantec Data Center Security Server Agent should be installed
     ✔  Service SISIPSUtil should be installed
     ×  Service SISIPSUtil should be stopped
     expected Service SISIPSUtil to respond to `stopped?`
     ×  Service SISIPSUtil should be disabled
     expected Service SISIPSUtil to respond to `disabled?`
     ✔  Service SISIPSService should be installed
     ×  Service SISIPSService should be stopped
     expected Service SISIPSService to respond to `stopped?`
     ×  Service SISIPSService should be disabled
     expected Service SISIPSService to respond to `disabled?`
     ✔  Service SISIDSService should be installed
     ×  Service SISIDSService should be stopped
     expected Service SISIDSService to respond to `stopped?`
     ×  Service SISIDSService should be disabled
     expected Service SISIDSService to respond to `disabled?`
```

and with debug:
```
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:183:in `report_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:174:in `run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:36:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:34:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:52:in `perform'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `block in <top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `<top (required)>'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/bin/kitchen:23:in `load'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/bin/kitchen:23:in `<top (required)>'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/bin/bundle:23:in `load'
D      /Users/nguyd106/.chefdk/gem/ruby/2.4.0/bin/bundle:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Verify failed on instance <disable-chef13-win2012>.  Please see .kitchen/logs/disable-chef13-win2012.log for more details
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.20.0/lib/kitchen/verifier/inspec.rb:96:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:443:in `block in verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:435:in `verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:157:in `verify'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Inspec Runner returns 1
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.20.0/lib/kitchen/verifier/inspec.rb:96:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:443:in `block in verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:435:in `verify_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:157:in `verify'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

I've RDP'ed into the VM and have verified that the services have status `Stopped` and starttype is `disabled`.

**Comment by adamleff** [comment]
Thanks! I'll log this as a feature request. I appreciate you showing how you'd solve this as it might be a great way for us to implement this in InSpec.

**Comment by srb3** [comment]
I have a customer who really wants this to be implemented, can we get this added to the roadmap?

**Comment by clintoncwolfe** [comment]
@kekaichinose

**Comment by sjsadowski** [comment]
I'm guessing there's no progress on this yet, but I'm going to add my +1

**Comment by zenspider** [comment]
This is blocked by #4249

**Comment by PowerSchill** [comment]
With the blocker closed can progress be made on this?

**Comment by usan-systems** [comment]
I, too, would like to make use of the service resource on Windows.
