### ISSUE TITLE
`inspec check` on a non-virtualized host stacktraces if referencing virtualization.system

### ISSUE THREAD

**Issue by woneill** [inspec/inspec#2532]
### Description

Running `inspec check` on a non-virtualized host results in a stack trace if the test has a conditional block such as:

```
if virtualization.system != 'docker'
 ...
end
```

### InSpec and Platform Version

```
$ bundle exec inspec --version
1.51.0
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

### Replication Case

Run `inspec init profile testcase` and copy this in place of `example.rb`:
```
if virtualization.system != 'docker'

  control 'testcase-1' do
    impact 0.7
    title 'Recreate stack trace'
    desc 'Recreate stack trace'

    describe file('/etc/passwd') do
      it { should exist }
    end
  end
end
```

Then run `inspec check testcase` and you'll get a stacktrace 

### Possible Solutions

Add some error checking to virtualization.rb so it doesn't throw an undefined method error when not on a virtualized platform

### Stacktrace

```
/usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/resources/virtualization.rb:39:in `block (2 levels) in <class:Virtualization>': undefined method `[]' for nil:NilClass (NoMethodError)
	from testcase/controls/example.rb:1:in `load_with_context'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile_context.rb:157:in `instance_eval'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile_context.rb:157:in `load_with_context'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile_context.rb:141:in `load_control_file'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:167:in `block in collect_tests'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:164:in `each'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:164:in `collect_tests'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:470:in `load_checks_params'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:463:in `load_params'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:157:in `params'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:323:in `controls_count'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/profile.rb:294:in `check'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/lib/inspec/cli.rb:70:in `check'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/var/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-1.51.0/bin/inspec:12:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.4.1/bin/inspec:22:in `load'
	from /usr/local/var/rbenv/versions/2.4.1/bin/inspec:22:in `<main>'
```

**Comment by jquick** [comment]
@woneill - Thanks for letting us know about this!

**Comment by jerryaldrichiii** [comment]
@woneill Thanks for this issue. I think I know how this is happening and will try to resolve it in the `virtualization` resource.

In the meantime, I recommend you use `only_if` instead of `if`.  We created `only_if` so we can control it's behavior instead of using Ruby's `if`.

In the case of `inspec check`, `only_if` blocks are not evaluated.

For more info see: https://www.inspec.io/docs/reference/dsl_inspec/#exclude-specific-test

Example (skip one control):
```
control 'testcase-1' do
  impact 0.7
  title 'Recreate stack trace'
  desc 'Recreate stack trace'

  only_if { virtualization.system != 'docker' }

  describe file('/etc/passwd') do
    it { should exist }
  end
end
```

Example (skip all controls in file):
```
only_if { virtualization.system != 'docker' }

control 'testcase-1' do
  impact 0.7
  title 'Recreate stack trace'
  desc 'Recreate stack trace'

  describe file('/etc/passwd') do
    it { should exist }
  end
end
```
