### ISSUE TITLE
InSpec 1.51.6 - Chef::Handler::AuditReport raised #<NoMethodError: undefined method `empty?' for nil:NilClass>

### ISSUE THREAD

**Issue by MichaelMcClanahan** [inspec/inspec#2597]
### Description

When using InSpec `1.51.6`, the Audit cookbook is unable to access the Chef Compliance server. If I downgrade to InSpec `1.51.0` there are no issues.

### InSpec and Platform Version

InSpec version `1.51.6`
Chef Compliance `1.12.1`
Audit Cookbook `6.0.1`
Chef `12.21.31`
MacOS

### Replication Case

Run `chef-client` with the Audit cookbook using similar attributes:

```
default['audit']['reporter'] = 'chef-compliance'
default['audit']['inspec_version'] = '1.51.6'
default['audit']['server'] = 'ADD_API_HERE'
default['audit']['owner'] = 'ADD_USER_HERE'
default['audit']['refresh_token'] = 'ADD_REFRESH_TOKEN_HERE'
default['audit']['insecure'] = false

default['audit']['profiles'] = [
  {
    'name' => 'cis-ubuntu14.04lts-level2',
    'compliance' => 'cis/cis-ubuntu14.04lts-level2'
  },
]
```

### Possible Solutions

Downgrade to InSpec `1.51.0`. You can do this via Audit attribute:
`default['audit']['inspec_version'] = '1.51.0'`

### Stacktrace

Error comes from here: https://github.com/chef-cookbooks/audit/blob/v6.0.1/files/default/handler/audit_report.rb#L69

```
[2018-02-09T16:41:46+00:00] DEBUG: Audit Report
[2018-02-09T16:41:46+00:00] ERROR: Report handler Chef::Handler::AuditReport raised #<NoMethodError: undefined method `empty?' for nil:NilClass>
[2018-02-09T16:41:46+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:69:in `report'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/handler.rb:259:in `run_report_unsafe'
[2018-02-09T16:41:46+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:84:in `run_report_safely'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/handler.rb:125:in `block in run_report_handlers'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/handler.rb:123:in `each'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/handler.rb:123:in `run_report_handlers'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/handler.rb:135:in `block in <class:Handler>'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/client.rb:443:in `block in run_completed_successfully'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/client.rb:442:in `each'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/client.rb:442:in `run_completed_successfully'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/client.rb:301:in `run'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application.rb:295:in `block in fork_chef_client'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application.rb:283:in `fork'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application.rb:283:in `fork_chef_client'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application.rb:248:in `block in run_chef_client'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application.rb:236:in `run_chef_client'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application/client.rb:450:in `loop'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application/client.rb:434:in `run_application'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/lib/chef/application.rb:59:in `run'
[2018-02-09T16:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.31/bin/chef-client:26:in `<top (required)>'
[2018-02-09T16:41:46+00:00] ERROR: /usr/bin/chef-client:57:in `load'
[2018-02-09T16:41:46+00:00] ERROR: /usr/bin/chef-client:57:in `<main>'
  - Chef::Handler::AuditReport
```

**Comment by jquick** [comment]
@MichaelMcClanahan  - Hey, I think this one should also be resolved with version 1.51.18. Thanks for the report.

**Comment by MichaelMcClanahan** [comment]
Thanks @jquick!

**Comment by jdgoins** [comment]
@jquick - I'm on Inspec 1.51.18, chef client 13.6.4 and am also receiving this error.

```
[2018-02-15T15:27:39-07:00] ERROR: Report handler Chef::Handler::AuditReport raised #<NoMethodError: undefined method `content' for RSpec::ExampleGroups::FileEtcMotd:Class>
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:733:in `method_missing'
[2018-02-15T15:27:39-07:00] ERROR: controls/setup.rb:79:in `block (2 levels) in load_with_context'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/rule.rb:232:in `instance_exec'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/rule.rb:232:in `block in with_dsl'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:386:in `module_exec'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:386:in `subclass'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:259:in `block in define_example_group_method'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner_rspec.rb:27:in `example_group'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:321:in `add_resource'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:271:in `get_check_example'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:279:in `block in register_rule'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:278:in `each'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:278:in `flat_map'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:278:in `register_rule'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:97:in `block in load'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:96:in `each'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:96:in `load'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/runner.rb:103:in `run'
[2018-02-15T15:27:39-07:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:148:in `call'
[2018-02-15T15:27:39-07:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:63:in `report'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:259:in `run_report_unsafe'
[2018-02-15T15:27:39-07:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:81:in `run_report_safely'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:125:in `block in run_report_handlers'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:123:in `each'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:123:in `run_report_handlers'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:135:in `block in <class:Handler>'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:443:in `block in run_completed_successfully'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:442:in `each'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:442:in `run_completed_successfully'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:301:in `run'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:291:in `block in fork_chef_client'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:279:in `fork'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:279:in `fork_chef_client'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:244:in `block in run_chef_client'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:232:in `run_chef_client'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:457:in `loop'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:457:in `interval_run_chef_client'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:441:in `run_application'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:59:in `run'
[2018-02-15T15:27:39-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/chef-client:26:in `<top (required)>'
[2018-02-15T15:27:39-07:00] ERROR: /usr/bin/chef-client:58:in `load'
[2018-02-15T15:27:39-07:00] ERROR: /usr/bin/chef-client:58:in `<main>'
  - Chef::Handler::AuditReport
```

**Comment by jquick** [comment]
@jdgoins - Thanks for this report, this seems to be a different issue. Looks like its blowing up when running your tests. Do you mind testing to see if this is working correctly on inspec 1.51.0? If not it may be a test syntax issue.

**Comment by jdgoins** [comment]
@jquick You're right, duh me. This is related to the content matcher of the file resource. Either this is a bug or the code's just written incorrectly. Regardless, IGNORE ME!
