### ISSUE TITLE
Scanning with a supermarket profile against a remote target produces an parameter error

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2664]
### Description

Executing a scan with a supermarket profile against a remote target returns an error in the `diagnose` method.

`inspec supermarket exec dev-sec/linux-baseline -t ssh://root:password@target`

Despite the generic names for the user, password, and target system I promise you they are real in my environment.

![image](https://user-images.githubusercontent.com/244426/36321816-c4b2de92-1310-11e8-9c39-c86ed9bf0a8e.png)

### InSpec and Platform Version

```
$ bin/inspec version
2.0.1
$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
```
commit: https://github.com/chef/inspec/commit/b0bcc35fda8cf97d51098676aae15419c08cb5e8

### Stacktrace

```
$ inspec supermarket exec dev-sec/linux-baseline -t ssh://root:password@target
/opt/inspec2/lib/inspec/base_cli.rb:176:in `diagnose': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /opt/inspec2/lib/bundles/inspec-supermarket/cli.rb:36:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/bin/inspec:12:in `<main>'
```

**Comment by burtlo** [comment]
Perhaps this is not an issue. I saw it locally but then removed my `Gemfile.lock` and then performed a `bundle install`.

**Comment by burtlo** [comment]
I was incorrect. I mistakenly ran `inspec` and not `bin/inspec` or `bundle exec bin/inspec`.

**Comment by burtlo** [comment]
Sounds like this is covered in Issue #2668
