### ISSUE TITLE
Inspec is failing even if everything is ok

### ISSUE THREAD

**Issue by artem-sidorenko** [inspec/inspec#2773]
### 🎛 Description

**Choose one:** 🐛 bug report

It might be also related to the kitchen-inspec. Inspec fails even if everything is okay.

```
$ kitchen test default-ubuntu-16
....
Profile Summary: 50 successful controls, 0 control failures, 2 controls skipped
Test Summary: 107 successful, 0 failures, 2 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-ubuntu-16-04>.  Please see .kitchen/logs/default-ubuntu-16-04.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
$ cat .kitchen/logs/default-ubuntu-16-04.log                                                                                                                                                    [master]
I, [2018-03-02T21:02:51.693856 #54175]  INFO -- default-ubuntu-16-04: -----> Verifying <default-ubuntu-16-04>...
I, [2018-03-02T21:02:52.108637 #54175]  INFO -- default-ubuntu-16-04: Loaded os-hardening-integration-tests
E, [2018-03-02T21:02:55.855847 #54175] ERROR -- default-ubuntu-16-04: Verify failed on instance <default-ubuntu-16-04>.
E, [2018-03-02T21:02:55.856006 #54175] ERROR -- default-ubuntu-16-04: ------Exception-------
E, [2018-03-02T21:02:55.856045 #54175] ERROR -- default-ubuntu-16-04: Class: Kitchen::ActionFailed
E, [2018-03-02T21:02:55.856078 #54175] ERROR -- default-ubuntu-16-04: Message: Inspec Runner returns 101
E, [2018-03-02T21:02:55.856109 #54175] ERROR -- default-ubuntu-16-04: ----------------------
E, [2018-03-02T21:02:55.856140 #54175] ERROR -- default-ubuntu-16-04: ------Backtrace-------
E, [2018-03-02T21:02:55.856170 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/kitchen-inspec-0.23.0/lib/kitchen/verifier/inspec.rb:97:in `call'
E, [2018-03-02T21:02:55.856258 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:443:in `block in verify_action'
E, [2018-03-02T21:02:55.856314 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-03-02T21:02:55.856347 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-03-02T21:02:55.856378 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-03-02T21:02:55.856409 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:497:in `action'
E, [2018-03-02T21:02:55.856440 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:435:in `verify_action'
E, [2018-03-02T21:02:55.856472 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-03-02T21:02:55.856503 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `each'
E, [2018-03-02T21:02:55.856535 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-03-02T21:02:55.856566 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:157:in `verify'
E, [2018-03-02T21:02:55.856598 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-03-02T21:02:55.856629 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-03-02T21:02:55.856661 #54175] ERROR -- default-ubuntu-16-04: /Users/artem/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-03-02T21:02:55.856710 #54175] ERROR -- default-ubuntu-16-04: ----End Backtrace-----
```

### 🌍 InSpec and Platform Version

```
$ inspec --version 
2.0.32
```

### 🤔 Replication Case

```
$ git clone https://github.com/dev-sec/chef-os-hardening.git
$ cd chef-os-hardening
$ bundle install
$ kitchen test default-ubuntu-16-04
```

/cc @chris-rock FYI, I'm noticed that after inspec update to 2.0.32 in https://github.com/dev-sec/chef-os-hardening/pull/199

**Comment by jerryaldrichiii** [comment]
I was able to verify that this occurs.

I see failures when I run the below, but no failures when running `kitchen verify`

```
inspec exec test/integration/default -t ssh://vagrant:vagrant@localhost:2222
```

I'm marking this as a bug.

**Comment by jquick** [comment]
This is probably due to the new exit codes introduced into inspec 2.0. If you have skipped tests you return 101 instead of 0 now. If we want this to return green still we would want to update kitchen-inspec.

**Comment by frezbo** [comment]
+1 on this, kitchen-inspec has not been updated in quite a long time

**Comment by jquick** [comment]
Hey @artem-sidorenko - The new kitchen-inspec 0.23.1 resolves this issue. Thanks for the report.

**Comment by artem-sidorenko** [comment]
@jquick many thanks!
