### ISSUE TITLE
undefined method `map' for "Can't find file. \"/etc/hosts\"":String

### ISSUE THREAD

**Issue by Wolfsrudel** [inspec/inspec#2828]
### 🎛 Description

**Choose one:** is this a 🐛 bug report

/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/resources/etc_hosts.rb:54; in `parse_conf': undefined methoed `map' for "Can't find file. \"/etc/hosts\"":String ...

### 🌍 InSpec and Platform Version

Oracle Enterprise Linux 7.4; Inspec Version 2.0.49

### 🤔 Replication Case

Dunno.

### 💁 Possible Solutions

The error is happening with `inspec check`... `inspec exec` is executing the control correctly.

### 💻 Stacktrace
```
inspec check ../app/inspec/profiles/00-operating-system/controls/network.rb 
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/resources/etc_hosts.rb:54:in `parse_conf': undefined method `map' for "Can't find file. \"/etc/hosts\"":String (NoMethodError)
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/resources/etc_hosts.rb:50:in `read_content'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/resources/etc_hosts.rb:28:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/plugins/resource.rb:68:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/resource.rb:51:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/resource.rb:51:in `block (3 levels) in create_dsl'
        from ../app/inspec/profiles/00-operating-system/controls/network.rb:65:in `block in load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/rule.rb:50:in `instance_eval'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/rule.rb:50:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/control_eval_context.rb:75:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
        from ../app/inspec/profiles/00-operating-system/controls/network.rb:36:in `load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile_context.rb:157:in `instance_eval'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile_context.rb:157:in `load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile_context.rb:141:in `load_control_file'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:167:in `block in collect_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:164:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:164:in `collect_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:470:in `load_checks_params'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:463:in `load_params'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:157:in `params'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:323:in `controls_count'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/profile.rb:294:in `check'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/lib/inspec/cli.rb:76:in `check'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.49/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:72:in `load'
        from /usr/bin/inspec:72:in `<main>'
```

**Comment by jquick** [comment]
Thanks for this report @Wolfsrudel !

**Comment by pwelch** [comment]
Notes for reproducing the error for debugging:
```
# Pull linux container and start it in the background
docker pull oraclelinux:7.4
docker run -td oraclelinux:7.4

# Add a test control to reproduce error
cat <<EOF > test.rb
describe etc_hosts('/etc/not_hosts_file').where { primary_name == 'localhost' } do
  its('ip_address') { should cmp '127.0.1.154' }
end
EOF

# Get test container ID
export OLCONTAINER_ID=`docker ps | grep oraclelinux | awk '{ print $1 }'`

# Run InSpec to reproduce the error
bin/inspec exec test.rb -t docker://$OLCONTAINER_ID
```
