### ISSUE TITLE
Bug: when using reporter argument the path does not work correctly with exec

### ISSUE THREAD

**Issue by MrWong99** [inspec/inspec#2833]
InSpec version: 2.0.45
Operating system: CentOS 7.4

When using the --reporter argument as last argument before specifying a path to the profiles a **NotImplementedError** `'<PATH>' is not a valid reporter type.` is thrown.

Example output that fails:
```bash
inspec exec --no-color -i id_rsa_2 -t ssh://root@some-system --reporter json-min jobs/CustomerProject.job.1
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/base_cli.rb:163:in `block in validate_reporters': 'jobs/CustomerProject.job.1' is not a valid reporter type. (NotImplementedError)
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/base_cli.rb:162:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/base_cli.rb:162:in `validate_reporters'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/base_cli.rb:144:in `parse_reporters'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/base_cli.rb:255:in `merged_opts'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/base_cli.rb:220:in `opts'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/cli.rb:161:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:72:in `load'
        from /usr/bin/inspec:72:in `<main>'
```

The same command with different argument placement:
```bash
inspec exec --no-color -i id_rsa_2 --reporter json-min -t ssh://root@some-system jobs/CustomerProject.job.1
```
This works and gives the expected output.

**Comment by jquick** [comment]
The `--reporter` flag takes an array of reporters, so you will want to put the path before that to make sure it does not get confused.

**Comment by jquick** [comment]
If you really need the profile to be last you can put the `--no-color` after the `--reporter xyz` which will close the reporter array. And then put your profiles after.

**Comment by MrWong99** [comment]
Thanks @jquick for the fast response!  I did solve the issue by placing the arguments differently, but maybe a hint in the docs helps others to avoid the issue, too.
