### ISSUE TITLE
enable tags not only within control blocks but also within describe blocks

### ISSUE THREAD

**Issue by markeggman** [inspec/inspec#2836]
### 🎛 Description

🙋 feature request

Currently it is only possible to include tags within a control block but not within a describe block. It would be helpful to be able to also somehow tag single tests. 

### 🌍 InSpec and Platform Version

inspec version : 2.0.32
Operating System : centos 7.2.1511

### 🤔 Replication Case

```
control "linux-1.0-req1" do
  impact 1.0
  title "IPv4 Redirects"
  desc "IPv4 redirects must not be accepted."
  tag controltag: 'control-tag-1'
  describe ini('./sysctl') do
    its(['net.ipv4.conf.all.accept_redirects']) { should cmp '0' }
    tag testtag: 'test-tag-1'
  end
  describe ini('./sysctl') do
    its(['net.ipv4.conf.default.accept_redirects']) { should cmp '0' }
    tag testtag: 'test-tag-2'
  end
end
```

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.
Sorry, I'm just an Inspec user ...

### 💻 Stacktrace

```
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:733:in `method_missing': undefined method `tag' for RSpec::ExampleGroups::INISysctl:Class (NoMethodError)
        from linux_v2.rb:8:in `block (2 levels) in load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/rule.rb:232:in `instance_exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/rule.rb:232:in `block in with_dsl'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:386:in `module_exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:386:in `subclass'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:259:in `block in define_example_group_method'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner_rspec.rb:27:in `example_group'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:324:in `add_resource'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:274:in `get_check_example'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:282:in `block in register_rule'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:281:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:281:in `flat_map'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:281:in `register_rule'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:97:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:96:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:96:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:103:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/cli.rb:168:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:76:in `load'
        from /usr/bin/inspec:76:in `<main>'
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
