### ISSUE TITLE
yaml load does not work when using AWS/Azure transports

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#2846]
### 🎛 Description

🐛 bug report

This is taken from:
https://discourse.chef.io/t/inspec-profile-files-being-ignored/12680

There is an issue when trying to load file attributes when using aws/azure transports. Other transports and local seem to be fine.
`iam_roles = yaml(content: inspec.profile.file('roles.yml')).params`

### 💻 Stacktrace
```
jquick@Jareds-MBP:~/Chef/inspec/_test
(master)> inspec exec aws_account_profile/ -t aws://us-east-1
Contents of iam_roles:

End of iam_roles.
aws_account_profile/controls/iam_spec.rb:4:in `load_with_context': undefined method `each' for nil:NilClass (NoMethodError)
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/profile_context.rb:157:in `instance_eval'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/profile_context.rb:157:in `load_with_context'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/profile_context.rb:141:in `load_control_file'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/profile.rb:167:in `block in collect_tests'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/profile.rb:164:in `each'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/profile.rb:164:in `collect_tests'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/runner.rb:93:in `block in load'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/runner.rb:82:in `each'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/runner.rb:82:in `load'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/runner.rb:103:in `run'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/lib/inspec/cli.rb:168:in `exec'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /Users/jquick/.gem/ruby/2.4.3/gems/inspec-2.0.17/bin/inspec:12:in `<top (required)>'
        from /Users/jquick/.gem/ruby/2.4.3/bin/inspec:23:in `load'
        from /Users/jquick/.gem/ruby/2.4.3/bin/inspec:23:in `<main>'

*** working in local mode ***

jquick@Jareds-MBP:~/Chef/inspec/_test
(master)> inspec exec aws_account_profile/
Contents of iam_roles:
{"role"=>"adfs-cloudadministrators", "policy"=>"CloudAdministrator"}
{"role"=>"adfs-developers", "policy"=>"Developer"}
{"role"=>"adfs-platformengineers", "policy"=>"PlatformEngineers"}
{"role"=>"adfs-security", "policy"=>"SecOps"}
{"role"=>"adfs-supportadmins", "policy"=>"SupportAdministrator"}
End of iam_roles.

Profile: InSpec Profile (aws_account_profile)
Version: 0.1.0
Target:  local://

  ↺  aws-account-1-1: adfs-cloudadministrators role exists
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-2: CloudAdministrator policy exists
     ↺  Resource Aws_iam_policy is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-3: adfs-developers role exists
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-4: Developer policy exists
     ↺  Resource Aws_iam_policy is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-5: adfs-platformengineers role exists
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-6: PlatformEngineers policy exists
     ↺  Resource Aws_iam_policy is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-7: adfs-security role exists
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-8: SecOps policy exists
     ↺  Resource Aws_iam_policy is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-9: adfs-supportadmins role exists
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.2.0.
  ↺  aws-account-1-10: SupportAdministrator policy exists
     ↺  Resource Aws_iam_policy is not supported on platform mac_os_x/17.2.0.


Profile Summary: 0 successful controls, 0 control failures, 10 controls skipped
Test Summary: 0 successful, 0 failures, 10 skipped
```

**Comment by jquick** [comment]
So the issue here is the YAML resource binds supports on: 
```
    supports platform: 'unix'
    supports platform: 'windows'
    supports platform: 'esx'
    supports platform: 'cisco'
```

We should remove supports from yaml as it can be used by everything.

**Comment by jquick** [comment]
We should remove support from general resources: yaml, json, cvs.
