### ISSUE TITLE
Cannot load YAML files from profile when targetting AWS

### ISSUE THREAD

**Issue by senorcinco** [inspec/inspec#2847]
### 🎛 Description

bug report

When targetting AWS, YAML files fail to load from within the profile.  However, local and SSH targets can load the YAML files.

### 🌍 InSpec and Platform Version

```
$ inspec version
2.1.0

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47
```

### 🤔 Replication Case

AWS Target (see full stacktrace below):

```
$ inspec exec attr-test -t aws://
attr-test/controls/example2.rb:14:in `block in load_with_context': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/rule.rb:50:in `instance_eval'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/rule.rb:50:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/control_eval_context.rb:75:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
	from attr-test/controls/example2.rb:4:in `load_with_context'
```

Local Target:

```
$ inspec exec attr-test

Profile: InSpec Profile (attr-test)
Version: 0.1.0
Target:  local://

  ↺  role-checks: role-checks (6 skipped)
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.4.0.
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.4.0.
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.4.0.
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.4.0.
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.4.0.
     ↺  Resource Aws_iam_role is not supported on platform mac_os_x/17.4.0.
  ✔  http-url-checks: http-url-checks
     ✔  http GET on https://www.google.com status should cmp == 200
     ✔  http GET on https://www.baidu.com status should cmp == 200


Profile Summary: 1 successful control, 0 control failures, 1 control skipped
Test Summary: 2 successful, 0 failures, 6 skipped
```

SSH Target:

```
$ inspec exec attr-test -i ~/.ssh/rsa_id -t ssh://192.168.0.5


Profile: InSpec Profile (attr-test)
Version: 0.1.0
Target:  ssh://192.168.0.5:22

  ↺  role-checks: role-checks (6 skipped)
     ↺  Resource Aws_iam_role is not supported on platform ubuntu/16.04.
     ↺  Resource Aws_iam_role is not supported on platform ubuntu/16.04.
     ↺  Resource Aws_iam_role is not supported on platform ubuntu/16.04.
     ↺  Resource Aws_iam_role is not supported on platform ubuntu/16.04.
     ↺  Resource Aws_iam_role is not supported on platform ubuntu/16.04.
     ↺  Resource Aws_iam_role is not supported on platform ubuntu/16.04.
  ✔  http-url-checks: http-url-checks
     ✔  http GET on https://www.google.com status should cmp == 200
     ✔  http GET on https://www.baidu.com status should cmp == 200


Profile Summary: 1 successful control, 0 control failures, 1 control skipped
Test Summary: 2 successful, 0 failures, 6 skipped
```

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

```
$ inspec exec attr-test -t aws://
attr-test/controls/example2.rb:14:in `block in load_with_context': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/rule.rb:50:in `instance_eval'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/rule.rb:50:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/control_eval_context.rb:75:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
	from attr-test/controls/example2.rb:4:in `load_with_context'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/profile_context.rb:157:in `instance_eval'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/profile_context.rb:157:in `load_with_context'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/profile_context.rb:141:in `load_control_file'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/profile.rb:167:in `block in collect_tests'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/profile.rb:164:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/profile.rb:164:in `collect_tests'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/runner.rb:93:in `block in load'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/runner.rb:82:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/runner.rb:82:in `load'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/runner.rb:103:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/lib/inspec/cli.rb:168:in `exec'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/inspec-2.1.0/bin/inspec:12:in `<top (required)>'
	from /usr/local/bin/inspec:22:in `load'
	from /usr/local/bin/inspec:22:in `<main>'
```

### Attachments

The attached file is an extended example which originally came from @jerry in the #inspec channel on chefcommunity.slack.com on March 1, 2018.

[attr-test-0.1.0.tar.gz](https://github.com/chef/inspec/files/1830202/attr-test-0.1.0.tar.gz)

**Comment by senorcinco** [comment]
Duplicate of https://github.com/chef/inspec/issues/2846
