### ISSUE TITLE
Inspec shell explodes in Chef 13.8.5

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#2852]
Running the inspec shell from 13.8.5's install explodes with the following error:

```
vagrant@default-opensuse-leap-42:~> /opt/chef/embedded/bin/inspec shell
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 1.0.1)
      addressable (~> 2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform: opensuse
    OS family: suse
    OS release: 42.3

Error: No such file or directory - infocmp
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:199:in `block in input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:115:in `interruptible_region'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:198:in `input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:184:in `block in read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:129:in `handle_read_errors'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:170:in `read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:98:in `read'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:68:in `block in repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/core_extensions.rb:43:in `pry'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/shell.rb:24:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/cli.rb:224:in `shell_func'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/bin/inspec:12:in `<top (required)>'
/opt/chef/embedded/bin/inspec:23:in `load'
/opt/chef/embedded/bin/inspec:23:in `<main>'
Error: No such file or directory - infocmp
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:199:in `block in input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:115:in `interruptible_region'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:198:in `input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:184:in `block in read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:129:in `handle_read_errors'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:170:in `read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:98:in `read'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:68:in `block in repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/core_extensions.rb:43:in `pry'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/shell.rb:24:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/cli.rb:224:in `shell_func'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/bin/inspec:12:in `<top (required)>'
/opt/chef/embedded/bin/inspec:23:in `load'
/opt/chef/embedded/bin/inspec:23:in `<main>'
Error: No such file or directory - infocmp
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:199:in `block in input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:115:in `interruptible_region'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:198:in `input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:184:in `block in read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:129:in `handle_read_errors'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:170:in `read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:98:in `read'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:68:in `block in repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/core_extensions.rb:43:in `pry'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/shell.rb:24:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/cli.rb:224:in `shell_func'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/bin/inspec:12:in `<top (required)>'
/opt/chef/embedded/bin/inspec:23:in `load'
/opt/chef/embedded/bin/inspec:23:in `<main>'
Error: No such file or directory - infocmp
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:199:in `block in input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:115:in `interruptible_region'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:198:in `input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:184:in `block in read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:129:in `handle_read_errors'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:170:in `read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:98:in `read'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:68:in `block in repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/core_extensions.rb:43:in `pry'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/shell.rb:24:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/cli.rb:224:in `shell_func'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/bin/inspec:12:in `<top (required)>'
/opt/chef/embedded/bin/inspec:23:in `load'
/opt/chef/embedded/bin/inspec:23:in `<main>'
Error: No such file or directory - infocmp
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:199:in `block in input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:115:in `interruptible_region'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:198:in `input_readline'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:184:in `block in read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:129:in `handle_read_errors'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:170:in `read_line'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:98:in `read'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:68:in `block in repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/pry-0.11.3/lib/pry/core_extensions.rb:43:in `pry'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/shell.rb:24:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/lib/inspec/cli.rb:224:in `shell_func'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.21/bin/inspec:12:in `<top (required)>'
/opt/chef/embedded/bin/inspec:23:in `load'
/opt/chef/embedded/bin/inspec:23:in `<main>'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry
```

**Comment by jquick** [comment]
@tas50 - Thanks for this report.  Note this is using a older version `1.51.21` but it may also be an issue in 2+

**Comment by jquick** [comment]
may be related https://github.com/ConnorAtherton/rb-readline/issues/5

**Comment by tas50** [comment]
It's an older version, but as far as Chef users are concerned that's current.

**Comment by miah** [comment]
I think this issue is caused by a minimal opensuse installation that is missing the `infocmp` binary which is provided by the `ncurses-devel` package.

How did you get inspec installed into your chef omnibus?

I created a opensuse vm and installed InSpec using `gem` inside the chef omnibus. I was actually unable to install InSpec without first installing devel_basis `zypper install --recommends -t pattern devel_basis` and `inspec shell` works as expected.

```
bash-4.3# inspec shell
WARN: Unresolved specs during Gem::Specification.reset:
      multi_json (~> 1.10)
      excon (>= 0.47.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      opensuse
    Families:  suse, linux, unix, os
    Release:   42.3
    Arch:      x86_64

InSpec>
```

**Comment by tas50** [comment]
It's a docker container and the chef docker image, which a lot of our users are using for cookbook development at this point.

**Comment by tas50** [comment]
I added ncurses-devel to the image we build for chef testing https://github.com/someara/dokken-images/commit/6067d7250fcd1e2835035bced9d68fed55eb1ec3

**Comment by miah** [comment]
Thanks! Because rb-readline uses infocmp to gather terminal details its a hidden requirement. Every Linux distribution puts infocmp into their ncurses package, except OpenSuSE who puts it into ncurses-devel =)

http://fr2.rpmfind.net/linux/rpm2html/search.php?query=infocmp&system=&arch=
