### ISSUE TITLE
Using config resources for profile file parsing does not work when you target unsupported platforms

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2858]
### 🎛 Description

This a 🐛 bug report.

The documentation for profile file demonstrates using the `yaml` resource to parse the contents of a profile file. This resource and other configuration resources (e.g. `json`) do not support all platforms. The resource will return a `nil` for the parsed content when targetting an unsupported platform even when the content is being retrieved from a profile file.

### 🌍 InSpec and Platform Version

InSpec 2.0.32, Mac OSX 10.13.3

### 🤔 Replication Case

Create a control file that uses the `json` resource parsing content supplied by a profile file.

```ruby
terraform_results = json(content: inspec.profile.file('terraform.json'))
describe terraform_results do
  its('raw_content') { should_not be_nil }
end
```

Target the AWS platform (or another unsupported platform):

```shell
$ inspec exec two_tier -t aws://us-east-1
JSON content
     ↺  Resource Json is not supported on platform aws/aws-sdk-v2.11.7.
```

Define a control that uses the JSON content to supply the id for an `aws_ec2_instance`.

```ruby
terraform_results = json(content: inspec.profile.file('terraform.json'))

describe terraform_results do
  its('raw_content') { should_not be_nil }
end

describe aws_ec2_instance(terraform_results['ec2_instance.database']['value']) do
  it { should be_running }
end
```

Running the scan again results in a stacktrack because the `terraform_results` variable is `nil`.

### 💁 Possible Solutions

* Remove the example provided in the documentation @ [https://www.inspec.io/docs/reference/profiles/](https://www.inspec.io/docs/reference/profiles/)

```ruby
my_services = yaml(content: inspec.profile.file('services.yml')).params

my_services.each do |s|
  describe service(s['service_name']) do
    it { should be_running }
  end

  describe port(s['port']) do
    it { should be_listening }
  end
end
```

* Update all the configuration resources to ignore platforms when the content is provided.

This effects: `csv`; `ini`; `json`; `parse_config`; `toml`; `xml`; `yml`. 

There may be others that are affected.

I like the idea of using the resources instead of having to write out the Ruby code version of the parsers as they all do not define a consistent interface:

```
# ...
JSON.parse(inspec.profile.file('terraform.json'))
YAML.parse(inspec.profile.file('terraform.yml'))
require 'rexml/document'
REXML::Document.new(inspec.profile.file('terraform.xml'))
Tomlrb.parse(inspec.profile.file('terraform.toml'))
# ...
```

### 💻 Stacktrace

```shell
$ inspec exec two_tier -t aws://us-east-1
two_tier/controls/example.rb:10:in `load_with_context': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/profile_context.rb:157:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/profile_context.rb:157:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/profile_context.rb:141:in `load_control_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/profile.rb:167:in `block in collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/profile.rb:164:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/profile.rb:164:in `collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:93:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:82:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:82:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:103:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/cli.rb:168:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/bin/inspec:12:in `<top (required)>'
	from /opt/inspec/bin/inspec:76:in `load'
	from /opt/inspec/bin/inspec:76:in `<main>'
```

**Comment by clintoncwolfe** [comment]
I like the idea of changing the `supports` declaration based on whether the `content:` was provided.  However, I think that the `supports` property is class-level (ie, constant for the resource type), whereas here we'd need it to vary from instantiation.  We might we able to work around that - perhaps by making a "late declaration".
