### ISSUE TITLE
Exception raised in an only_if block will cause the scan to fail.

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2868]
### 🎛 Description

This a 🐛 bug report

When a resource is used within an `only_if` and it raises an exception the entire scan will fail.

### 🌍 InSpec and Platform Version

InSpec 2.1.0
Workstation: 10.13.3

### 🤔 Replication Case

Define an `only_if` with a method that generates an exception. I chose the `file` resource and the `exists?` method or it is `exist?` #2779 

```ruby
control 'project-linux' do
  only_if do
    file('/home/chef/apache/.git').exists?
  end

  describe command('git --git-dir /home/chef/apache/.git branch') do
    its('stdout') { should match /\* master/ }
    its('exit_status') { should eq 0 }
  end
end
```

### 💁 Possible Solutions

When code executed in an `only_if` block raises an exception:

* The tests could fail with the exception.
* The scan could return an error return code, display the error, and mark the failing tests as skipped.

### 💻 Stacktrace

```
workstation/controls/source_code.rb:8:in `block (2 levels) in load_with_context': undefined method `exists?' for File /home/chef/apache/.git:#<Class:0x00007ff2f22c07d0> (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/rule.rb:110:in `only_if'
	from workstation/controls/source_code.rb:7:in `block in load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/rule.rb:50:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/rule.rb:50:in `initialize'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/control_eval_context.rb:75:in `new'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
	from workstation/controls/source_code.rb:6:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/profile_context.rb:157:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/profile_context.rb:157:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/profile_context.rb:141:in `load_control_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/profile.rb:167:in `block in collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/profile.rb:164:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/profile.rb:164:in `collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/runner.rb:93:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/runner.rb:82:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/runner.rb:82:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/runner.rb:103:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/lib/inspec/cli.rb:168:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.0/bin/inspec:12:in `<top (required)>'
	from /opt/inspec/bin/inspec:72:in `load'
	from /opt/inspec/bin/inspec:72:in `<main>'
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
