### ISSUE TITLE
Unable to install Inspec 2.X on AIX via gem install via audit_cookbook

### ISSUE THREAD

**Issue by sarahbakal** [inspec/inspec#2873]
### 🎛 Description

🐛 bug report

Inspec 2.x Gem fails to install on aix via the audit cookbook

### 🌍 InSpec and Platform Version

Any Inspec 2.0
Chef-client 12.21.x

### 🤔 Replication Case

Installing Inspec 2.0 on aix and possibly solaris

### 💁 Possible Solutions

This PR is potentially for this issue but it's been open for 2 weeks
https://github.com/knu/ruby-unf_ext/pull/39

### 💻 Stacktrace

```

Error Log & Stacktrace

inspec_gem[inspec] (audit::inspec line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: chef_gem[inspec] (/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install inspec -q --no-rdoc --no-ri -v "2.1.10" ----
STDOUT: Building native extensions.  This could take a while...
STDERR: ERROR:  Error installing inspec:
	ERROR: Failed to build gem native extension.

    current directory: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext
/opt/chef/embedded/bin/ruby -r ./siteconf20180323-13500448-1ipyscj.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:552:in `try_link0'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:567:in `try_link'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:776:in `try_func'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1008:in `block in have_library'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:953:in `block in checking_for'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:952:in `checking_for'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1003:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/powerpc-aix-6/2.3.0/unf_ext-0.0.7.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.5 for inspection.
Results logged to /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/powerpc-aix-6/2.3.0/unf_ext-0.0.7.5/gem_make.out
---- End output of /opt/chef/embedded/bin/gem install inspec -q --no-rdoc --no-ri -v "2.1.10" ----
Ran /opt/chef/embedded/bin/gem install inspec -q --no-rdoc --no-ri -v "2.1.10" returned 1


Mixlib::ShellOut::ShellCommandFailed
----------------------------------------------------
chef_gem[inspec] (/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install inspec -q --no-rdoc --no-ri -v "2.1.10" ----
STDOUT: Building native extensions.  This could take a while...
STDERR: ERROR:  Error installing inspec:
	ERROR: Failed to build gem native extension.

    current directory: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext
/opt/chef/embedded/bin/ruby -r ./siteconf20180323-13500448-1ipyscj.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:552:in `try_link0'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:567:in `try_link'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:776:in `try_func'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1008:in `block in have_library'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:953:in `block in checking_for'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:952:in `checking_for'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1003:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/powerpc-aix-6/2.3.0/unf_ext-0.0.7.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.5 for inspection.
Results logged to /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/powerpc-aix-6/2.3.0/unf_ext-0.0.7.5/gem_make.out
---- End output of /opt/chef/embedded/bin/gem install inspec -q --no-rdoc --no-ri -v "2.1.10" ----
Ran /opt/chef/embedded/bin/gem install inspec -q --no-rdoc --no-ri -v "2.1.10" returned 1


Cookbook Trace:
----------------------------------------------------
/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb:43:in `install_inspec_gem'
/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb:31:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb:30:in `block in class_from_file'
/var/chef/cache/cookbooks/audit/recipes/inspec.rb:24:in `from_file'
/var/chef/cache/cookbooks/audit/recipes/default.rb:30:in `from_file'
/var/chef/cache/cookbooks/compliance_base/recipes/default.rb:58:in `from_file'
/var/chef/cache/cookbooks/infrastructure_base/recipes/safe.rb:14:in `from_file'
/var/chef/cache/cookbooks/infrastructure_base/recipes/default.rb:7:in `from_file'


Resource Declaration:
----------------------------------------------------
# In /var/chef/cache/cookbooks/audit/recipes/inspec.rb

 20: inspec_gem 'inspec' do
 21:   version node['audit']['inspec_version']
 22:   source node['audit']['inspec_gem_source']
 23:   action :nothing
 24: end.run_action(:install)


Compiled Resource:
----------------------------------------------------
# Declared in /var/chef/cache/cookbooks/audit/recipes/inspec.rb:20:in `from_file'

inspec_gem("inspec") do
  action [:nothing]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :inspec_gem
  cookbook_name "audit"
  recipe_name "inspec"
  gem_name "inspec"
end


Backtrace
----------------------------------------------------
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/shell_out.rb:118:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider/package.rb:637:in `shell_out_with_timeout!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider/package/rubygems.rb:546:in `install_via_gem_command'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider/package/rubygems.rb:527:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider/package.rb:114:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider/package.rb:272:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider/package.rb:113:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider/package.rb:112:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/resource/chef_gem.rb:43:in `block in after_created'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/resource/chef_gem.rb:42:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/resource/chef_gem.rb:42:in `after_created'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/resource_builder.rb:92:in `build'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/dsl/declare_resource.rb:291:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/dsl/declare_resource.rb:248:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/dsl/resources.rb:39:in `chef_gem'
/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb:43:in `install_inspec_gem'
/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb:31:in `block (2 levels) in class_from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:176:in `converge_by'
/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb:30:in `block in class_from_file'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/resource.rb:622:in `run_action'
/var/chef/cache/cookbooks/audit/recipes/inspec.rb:24:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/audit/recipes/default.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/compliance_base/recipes/default.rb:58:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/infrastructure_base/recipes/safe.rb:14:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:293:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/infrastructure_base/recipes/default.rb:7:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/run_context.rb:187:in `load'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.3/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'

```

**Comment by jeremymv2** [comment]
This issue is being actively worked on.

In the interim, Inspec 1.x versions continue to work, including latest: `1.51.21`

**Comment by jquick** [comment]
Yes, you will be able to install via omnibus without issue but the gem version of inspec i think still has issues. We currently do not support inspec as a AIX as a standalone gem install.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please reopen the issue and continue the discussion, making sure to provide stack trace or repro data that is relevant to the current version.

Thank you!
__Chef InSpec Team__
