### ISSUE TITLE
inspec detect behaves inconsistent

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#2881]
### 🎛 Description

**Choose one:** 🐛 bug report

`inspec detect` returns different exit codes based on the selected platform. The use case here is to verify if a connection is working or not. If we cannot establish a connection we should return a non-zero exit code. At this point, this is not the case for aws and azure.

While we are at it, the stacktrace is also not super helpful. A short user-friendly message would be delightful :-)

```
[root@439526838ebb /]# inspec detect -t aws://

== Platform Details

Name:      aws
Families:  cloud, api
Release:   aws-sdk-v2.11.19
[root@439526838ebb /]# echo $?
0
[root@439526838ebb /]# inspec detect -t docker://1213
/opt/inspec/embedded/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock': No such file or directory - connect(2) for/var/run/docker.sock (Errno::ENOENT) (Excon::Error::Socket)
        from /opt/inspec/embedded/lib/ruby/2.4.0/socket.rb:1198:in `connect_nonblock'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/unix_socket.rb:15:in `connect'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/socket.rb:30:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:427:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:427:in `socket'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:111:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/mock.rb:48:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:16:in `request_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:260:in `request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:283:in `rescue in request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:225:in `request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:283:in `rescue in request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:225:in `request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/middlewares/base.rb:11:in `error_call'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:283:in `rescue in request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/excon-0.61.0/lib/excon/connection.rb:225:in `request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/docker-api-1.34.2/lib/docker/connection.rb:40:in `request'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/docker-api-1.34.2/lib/docker/container.rb:346:in `get'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/docker.rb:61:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/docker.rb:41:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/docker.rb:41:in `create_new_connection'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/docker.rb:22:in `connection'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/backend.rb:51:in `create'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:67:in `configure_transport'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:59:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/cli.rb:270:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/cli.rb:270:in `run_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/cli.rb:182:in `detect'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:72:in `load'
        from /usr/bin/inspec:72:in `<main>'
[root@439526838ebb /]# echo $?
1
inspec detect -t ssh://user:password@test
/opt/inspec/embedded/lib/ruby/2.4.0/socket.rb:227:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
        from /opt/inspec/embedded/lib/ruby/2.4.0/socket.rb:227:in `foreach'
        from /opt/inspec/embedded/lib/ruby/2.4.0/socket.rb:617:in `tcp'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:70:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/ssh_connection.rb:153:in `establish_connection'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/ssh_connection.rb:236:in `session'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/ssh_connection.rb:191:in `run_command_via_connection'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/plugins/base_connection.rb:108:in `run_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/helpers/os_common.rb:36:in `command_output'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/helpers/os_common.rb:43:in `unix_uname_s'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/specifications/os.rb:35:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/scanner.rb:45:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/scanner.rb:27:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect/scanner.rb:27:in `scan'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/platforms/detect.rb:9:in `scan'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/plugins/base_connection.rb:100:in `platform'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/extras/command_wrapper.rb:128:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/ssh_connection.rb:46:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/ssh.rb:195:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/ssh.rb:195:in `create_new_connection'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.2.0/lib/train/transports/ssh.rb:75:in `connection'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/backend.rb:51:in `create'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:67:in `configure_transport'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:59:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/cli.rb:270:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/cli.rb:270:in `run_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/cli.rb:182:in `detect'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:72:in `load'
        from /usr/bin/inspec:72:in `<main>'
echo $?
1
```

### 🌍 InSpec and Platform Version

```
inspec version
2.1.10
```

### 🤔 Replication Case

Install inspec without any configuration.

### 💁 Possible Solutions

Fix inspec detect behavior

### 💻 Stacktrace

see above

**Comment by chris-rock** [comment]
Related to #2976

**Comment by jquick** [comment]
Closing in favor of https://github.com/inspec/inspec/issues/2976
