### ISSUE TITLE
undefined method `azure_resource_group_resource_counts'

### ISSUE THREAD

**Issue by mpostument** [inspec/inspec#2936]
### 🎛 Description

🐛 bug report

undefined method `azure_resource_group_resource_counts'

### 🌍 InSpec and Platform Version

inspec --version
2.1.30
Ubuntu 16.04

### 🤔 Replication Case
```ruby
describe azure_resource_group_resource_counts(name: 'Azure-test') do
    its('total') { should eq 7 }
    its('vm_count') { should eq 2 }
    its('nic_count') { should eq 2 }
    its('public_ip_count') { should eq 1 }
    its('sa_count') { should eq 1 }
    its('vnet_count') { should eq 1 }
end
```
### 💻 Stacktrace
```
inspec exec azure-security -t azure://subscription_id
azure-security/controls/resource_group.rb:1:in `load_with_context': undefined method `azure_resource_group_resource_counts' for #<#<Class:0x00000000025e2f20>:0x00000000025e03d8> (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/profile_context.rb:158:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/profile_context.rb:158:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/profile_context.rb:142:in `load_control_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/profile.rb:170:in `block in collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/profile.rb:167:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/profile.rb:167:in `collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/runner.rb:93:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/runner.rb:82:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/runner.rb:82:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/runner.rb:103:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/lib/inspec/cli.rb:168:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.30/bin/inspec:12:in `<top (required)>'
	from /usr/bin/inspec:72:in `load'
	from /usr/bin/inspec:72:in `<main>'
```

**Comment by jquick** [comment]
Hey @Infectsoldier - I think this is a documentation issue, I believe you want to use `azure_resource_group` which should have the counts on it.

**Comment by clintoncwolfe** [comment]
It's wrong in the [docs](https://www.inspec.io/docs/reference/resources/azure_resource_group/)
