### ISSUE TITLE
Backport shadow improvements from 2.x to 1.x

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2980]
### 🎛 Description

🙋 feature request

Various changes to the `shadow` resource, including stabilizing the use of the FilterTable backend and updating some properties.  @miah, @james-stocks , @chris-rock are getting mentioned :-)

### 🌍 InSpec and Platform Version

2.1.54 or some point earlier has the changes; 1.51.21 needs it

### 🤔 Replication Case

Try running a shadow.where filter on inspec 1.51.21

### 💁 Possible Solutions

Re-wire FilterTable bindings to match 2.0 series.

### 💻 Stacktrace

```
Traceback (most recent call last):
--
  | 24: from /workdir/vendor/bundle/ruby/2.5.0/bin/inspec:23:in `<main>'
  | 23: from /workdir/vendor/bundle/ruby/2.5.0/bin/inspec:23:in `load'
  | 22: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/bin/inspec:12:in `<top (required)>'
  | 21: from /workdir/vendor/bundle/ruby/2.5.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  | 20: from /workdir/vendor/bundle/ruby/2.5.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  | 19: from /workdir/vendor/bundle/ruby/2.5.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  | 18: from /workdir/vendor/bundle/ruby/2.5.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  | 17: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/cli.rb:76:in `check'
  | 16: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:294:in `check'
  | 15: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:323:in `controls_count'
  | 14: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:157:in `params'
  | 13: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:463:in `load_params'
  | 12: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:470:in `load_checks_params'
  | 11: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:164:in `collect_tests'
  | 10: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:164:in `each'
  | 9: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile.rb:167:in `block in collect_tests'
  | 8: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile_context.rb:141:in `load_control_file'
  | 7: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile_context.rb:157:in `load_with_context'
  | 6: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/profile_context.rb:157:in `instance_eval'
  | 5: from controls/translated-controls.rb:3753:in `load_with_context'
  | 4: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
  | 3: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/control_eval_context.rb:75:in `new'
  | 2: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/rule.rb:50:in `initialize'
  | 1: from /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.21/lib/inspec/rule.rb:50:in `instance_eval'
  | controls/translated-controls.rb:3767:in `block in load_with_context': undefined method `where' for /etc/shadow:#<Class:0x0000000001af68c8> (NoMethodError)


```

**Comment by zenspider** [comment]
1.x is unsupported at this point. Closing.
