### ISSUE TITLE
Rename `name` method in lib/utils/plugin_registry

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3055]
### 🎛 Description

See https://github.com/pry/pry/issues/1535

`binding.pry` fails if `lib/utils/plugin_registry` is loaded, because it defines a `self.name` method

### 🌍 InSpec and Platform Version

2.1.72 from gem

### 💁 Possible Solutions

 * Because the method's purpose is "Register a new plugin by name" it might be better to rename it to `self.register` OR
 * `byebug` seems to work where pry doesn't here. It could be kept as a known issue that a contributor needs to use byebug in some cases. 

### 💻 Stacktrace

```
ArgumentError: wrong number of arguments (given 0, expected 1) 
from /home/user/.rvm/gems/ruby-2.4.3/gems/inspec-2.1.72/lib/utils/plugin_registry.rb:49:in 'name' 
[9] pry(unknown)> wtf 
Exception: ArgumentError: wrong number of arguments (given 0, expected 1) 
0: /home/user/.rvm/gems/ruby-2.4.3/gems/inspec-2.1.72/lib/utils/plugin_registry.rb:49:in 'name'
1: /home/user/.rvm/gems/ruby-2.4.3/gems/pry-0.11.3/lib/pry/wrapped_module.rb:150:in 'method_missing'
2: /home/user/.rvm/gems/ruby-2.4.3/gems/pry-0.11.3/lib/pry/wrapped_module.rb:100:in 'nonblank_name' 
3: /home/user/.rvm/gems/ruby-2.4.3/gems/pry-0.11.3/lib/pry/wrapped_module.rb:87:in 'method_prefix' 
4: /home/user/.rvm/gems/ruby-2.4.3/gems/pry-0.11.3/lib/pry/method.rb:271:in 'name_with_owner' 
```

**Comment by james-stocks** [comment]
I think this is a valid bug, but it can be closed while there is no pressing need to fix it. This issue can be re-opened if it happens to block someone.
