### ISSUE TITLE
Inspec-core fails to require `resource_support/aws` when `aws-sdk` gem is installed

### ISSUE THREAD

**Issue by teknofire** [inspec/inspec#3161]
### 🎛 Description

🐛 bug report

`inspec-core` will attempt to [require `resource_support/aws`](https://github.com/inspec/inspec/blob/master/lib/inspec/resource.rb#L89) if it detects that an `aws-sdk` gem is installed.  This of course fails because `inspec-core` does not include any of the aws resource files.

`ERROR: Report handler Chef::Handler::AuditReport raised #<LoadError: cannot load such file -- resource_support/aws> `

In this case `inspec-core` is getting installed using the Audit 7.0.0 cookbook and the Inspec version is set to 2.2.16.  The `aws-sdk` gem is installed as part of another cookbook and is using v3 which is not compatible with the full `inspec` gem.  

### 🌍 InSpec and Platform Version

Inspec-core 2.2.16, Ubuntu 16.04

### 🤔 Replication Case

1. Using the audit 7.0.0 cookbookk Install `inspec-core` specifying version 2.2.16
2. Install `aws-sdk` gem using `chef_gem 'aws-sdk'; require 'aws-sdk'`
3. Configure the audit cookbook to run any profile.

### 💁 Possible Solutions

Instead of testing for just the presence of the `awk-sdk` gem it should also test if this is running from `inspec` or `inspec-core` to determine if those files should be required.

### 💻 Stacktrace

```
[2018-06-21T10:11:04+00:00] ERROR: Report handler Chef::Handler::AuditReport rai 
sed #<LoadError: cannot load such file -- resource_support/aws> 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/inspec-core-2.2.16/lib/inspec/resource.rb:89:in `<top (required)>' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/inspec-core-2.2.16/lib/inspec/profile_context.rb:6:in `<top (required)>' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/inspec-core-2.2.16/lib/inspec/profile.rb:16:in `<top (required)>' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:59:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/inspec-core-2.2.16/lib/inspec.rb:11:in `<top (required)>' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:135:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:135:in `rescue in require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.5.0/rubyg 
ems/core_ext/kernel_require.rb:39:in `require' 
[2018-06-21T10:11:04+00:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/h 
andler/audit_report.rb:105:in `load_needed_dependencies' 
[2018-06-21T10:11:04+00:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/h 
andler/audit_report.rb:39:in `report' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/handler.rb:257:in `run_report_unsaf 
e' 
[2018-06-21T10:11:04+00:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/h 
andler/audit_report.rb:84:in `run_report_safely' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/handler.rb:123:in `block in run_rep 
ort_handlers' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/handler.rb:121:in `each' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/handler.rb:121:in `run_report_handl 
ers' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/handler.rb:133:in `block in <class: 
Handler>' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/client.rb:442:in `block in run_comp 
leted_successfully' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/client.rb:441:in `each' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/client.rb:441:in `run_completed_suc 
cessfully' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/client.rb:298:in `run' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/application.rb:303:in `run_with_gra 
ceful_exit_option' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/application.rb:279:in `block in run 
_chef_client' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_co 
nnectivity' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/application.rb:261:in `run_chef_cli 
ent' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/application/client.rb:441:in `run_a 
pplication' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/lib/chef/application.rb:66:in `run' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/ 
gems/chef-14.1.12-universal-mingw32/bin/chef-client:26:in `<top (required)>' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/bin/chef-client:75:in `load' 
[2018-06-21T10:11:04+00:00] ERROR: C:/opscode/chef/bin/chef-client:75:in `<main>
```

**Comment by clintoncwolfe** [comment]
refs #2571  refs #3001

**Comment by clintoncwolfe** [comment]
:100: on a great issue report, @teknofire !
