### ISSUE TITLE
Update inspec version (1.34.9) that comes with Chef Compliance 

### ISSUE THREAD

**Issue by shelld0n** [inspec/inspec#3182]
### 🎛 Description

This a :bug: bug report

When trying to upload a profile containing controls related to firewalld resource to **Chef Compliance**, i got an Error during profile upload. I investigated a little and i found this 
`2018-06-28_09:31:52.43720 /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.7.0/lib/rspec/matchers.rb:960:in 'method_missing': undefined local variable or method 'firewalld' for #<#<Class:0x0000000288bf38>:0x000000027c37e0> (NameError)`

i believe that the inspec version in Chef compliance does not support newer resources like firewalld 

### :tipping_hand_woman:  Possible Solutions

Update the inspec version (1.34.9) to support new Inspec Resources

Can i update the version of inspec manually or wait for a new Chef Compliance Release ?

### 🌍 InSpec and Platform Version

Inspec Version used for creating the profile: 2.1.72
Chef Compliance Version: 1.12.1
Inpec Version bundled with Chef Compliance : 1.34.9

### :thinking: Replication Case

Create a control using firewalld resource, for example : 
```
control 'test_firewalld' do
  impact 1.0
  title 'Firewalld rules in node are enabled'
  desc 'Checks if firewalld ensures specific rules'
  describe firewalld do
    it { should be_running }
    it { should have_zone('admin') }
  end
```
Then try to upload it to Chef Compliance instance with : `inspec compliance upload PROFILE`

### :computer: Stacktrace

```
2018-06-28_09:31:52.18750 Please report a bug if this causes problems.
2018-06-28_09:31:52.43720 /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.7.0/lib/rspec/matchers.rb:960:in 'method_missing': undefined local variable or method 'firewalld' for #<#<Class:0x0000000288bf38>:0x000000027c37e0> (NameError)
2018-06-28_09:31:52.43811 	from ./controls/confluent_firewalld.rb:17:in 'block in load_with_context'
2018-06-28_09:31:52.43811 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/rule.rb:49:in 'instance_eval'
2018-06-28_09:31:52.43811 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/rule.rb:49:in 'initialize'
2018-06-28_09:31:52.43812 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/control_eval_context.rb:71:in 'new'
2018-06-28_09:31:52.43812 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/control_eval_context.rb:71:in 'block (2 levels) in create'
2018-06-28_09:31:52.43812 	from ./controls/confluent_firewalld.rb:13:in 'load_with_context'
2018-06-28_09:31:52.43812 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile_context.rb:146:in 'instance_eval'
2018-06-28_09:31:52.43813 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile_context.rb:146:in 'load_with_context'
2018-06-28_09:31:52.43813 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile_context.rb:130:in 'load_control_file'
2018-06-28_09:31:52.43813 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:151:in 'block in collect_tests'
2018-06-28_09:31:52.43813 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:148:in 'each'
2018-06-28_09:31:52.43813 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:148:in 'collect_tests'
2018-06-28_09:31:52.43814 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:454:in 'load_checks_params'
2018-06-28_09:31:52.43814 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:447:in 'load_params'
2018-06-28_09:31:52.43814 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:141:in 'params'
2018-06-28_09:31:52.43814 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:307:in 'controls_count'
2018-06-28_09:31:52.43815 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:278:in 'check'
2018-06-28_09:31:52.43815 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/cli.rb:69:in 'check'
2018-06-28_09:31:52.43816 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
2018-06-28_09:31:52.43816 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
2018-06-28_09:31:52.43816 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
2018-06-28_09:31:52.43816 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
2018-06-28_09:31:52.43817 	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/bin/inspec:12:in '<top (required)>'
2018-06-28_09:31:52.43817 	from /opt/chef-compliance/embedded/bin/inspec:23:in 'load'
2018-06-28_09:31:52.43817 	from /opt/chef-compliance/embedded/bin/inspec:23:in '<main>'
2018-06-28_09:31:52.46017 09:31:52.460 ERR => Failed to POST /owners/XXXXXXXX/compliance/Confluent%!C(MISSING)ontrol%!C(MISSING)enter%!S(MISSING)TET%!C(MISSING)ompliance%!P(MISSING)rofile/tar.exit status 1 
2018-06-28_09:31:52.46019 [GIN] 2018/06/28 - 09:31:52 | 500 |  1.651195682s | 10.01.10.01 |   POST    /owners/XXXXXXX/compliance/XXXXXXXXXXXX Compliance Profile/tar
```

**Comment by shelld0n** [comment]
Can you please confirm that it is possible to update manually the Inspec version of Chef Compliance ?? i need to upload new inspec profiles as soon as possible :pray: :pray: Thanks.

**Comment by clintoncwolfe** [comment]
@arlimus you were mentioned as the person to definitively answer this :)

**Comment by shelld0n** [comment]
i am sorry to ask again but is it possible or not ? :pray: :pray: :pray:

**Comment by arlimus** [comment]
Hi @Aminekanane , sorry for the late response. I have not tried updating InSpec on Chef Compliance to 2.x. It may lead to conflicts with the gems if it fails. I also highly recommend updating to Chef Automate (2.x) which has all the functionality we had in Chef Compliance + up to date profiles and InSpec. Since this is a commercially supported tool by Chef, I'd recommend reaching out to our support or sales team directly. I'm sure we can help you move to the new product! :)

I'm closing this issue for now.

**Comment by shelld0n** [comment]
@arlimus Thank you for your comprehensive response, and your time.
