### ISSUE TITLE
Unable to find train plugin 'mock' error

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#3210]
### 🎛 Description

🐛 bug report

seeing issue when inspec is running, which is wrapped with the audit cookbook

### 🌍 InSpec and Platform Version

rhel 7.5
inspec 2.1.72  (trace shows 2.1.84)
chef dk 3.1

### 🤔 Replication Case

run profiles with wrapper audit and getting this missing

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

```

2018-07-12T13:30:46-04:00] ERROR: Report handler Chef::Handler::AuditReport raised #<Train::UserError: Can't find train plugin "mock". Please install it first.>
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/train-core-1.4.11/lib/train.rb:47:in `rescue in load_transport'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/train-core-1.4.11/lib/train.rb:39:in `load_transport'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/train-core-1.4.11/lib/train.rb:20:in `create'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/backend.rb:46:in `create'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/dsl.rb:54:in `filter_included_controls'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/dsl.rb:47:in `load_spec_files_for_profile'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/dsl.rb:10:in `require_controls'
[2018-07-12T13:30:46-04:00] ERROR: controls/rhel7-cismitre1.rb:1:in `load_with_context'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/profile_context.rb:158:in `instance_eval'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/profile_context.rb:158:in `load_with_context'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/profile_context.rb:142:in `load_control_file'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/profile.rb:170:in `block in collect_tests'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/profile.rb:167:in `each'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/profile.rb:167:in `collect_tests'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/runner.rb:93:in `block in load'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/runner.rb:82:in `each'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/runner.rb:82:in `load'
[2018-07-12T13:30:46-04:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-2.1.84/lib/inspec/runner.rb:103:in `run'
[2018-07-12T13:30:46-04:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:158:in `call'
[2018-07-12T13:30:46-04:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:66:in `report'
```
EDIT: (@clintoncwolfe) place stacktrace in code block, move stacktrace to end

**Comment by clintoncwolfe** [comment]
Hrm, I can't replicate this.  Is this still an issue for you?

**Comment by zenspider** [comment]
No response. Closing.
