### ISSUE TITLE
Unexpected EOF errors when uploading valid profile tarball on windows

### ISSUE THREAD

**Issue by NickRycar** [inspec/inspec#3222]
### 🎛 Description

🐛 bug report

Encountering unexpected errors when uploading profile tarballs via `inspec compliance upload` on windows. Both `inspec check MYPROFILE.tar.gz` and manual upload via the Chef Automate UI work as expected -- behavior is limited to upload via the CLI.
 
### 🌍 InSpec and Platform Version

InSpec Version: 2.1.72 (installed via  https://packages.chef.io/files/stable/chefdk/3.1.0/windows/2016/chefdk-3.1.0-1-x64.msi )
OS Version: Windows Server 2016

### 🤔 Replication Case

Tested with the linux_baseline profile (as well as a wrapper profile that depends upon it)

Profile used: https://github.com/dev-sec/linux-baseline/archive/2.2.0.tar.gz

### 💻 Stacktrace

CLI Output:

```
 inspec compliance upload C:\Users\chef\Downloads\linux-baseline-2.2.0.tar.gz
I, [2018-07-16T19:25:34.078908 #3112]  INFO -- : Checking profile in C:\Users\chef\Downloads\linux-baseline-2.2.0.tar.gz
I, [2018-07-16T19:25:34.080112 #3112]  INFO -- : Metadata OK.
I, [2018-07-16T19:25:34.273404 #3112]  INFO -- : Found 54 controls.
I, [2018-07-16T19:25:34.274061 #3112]  INFO -- : Control definitions OK.
Profile is valid
Start upload to leela/linux-baseline
Uploading to Chef Automate
Error during profile upload:
rpc error: code = InvalidArgument desc = Check InSpec check failed for /hab/svc/compliance-service/data/profiles/.tmp/inspec-upload715567944.tar.gz with message: exit status 1
/hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `read': unexpected end of file (Zlib::GzipFile::Error)
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `from'
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:59:in `each'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/file_provider.rb:140:in `find_all'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/file_provider.rb:140:in `block in initialize'
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:29:in `new'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/file_provider.rb:160:in `walk_tar'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/file_provider.rb:139:in `initialize'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/file_provider.rb:14:in `new'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/file_provider.rb:14:in `for_path'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/profile.rb:55:in `for_path'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/profile.rb:72:in `for_fetcher'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/profile.rb:78:in `for_target'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/lib/inspec/cli.rb:75:in `check'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /hab/pkgs/chef/inspec/2.2.34/20180705203952/lib/gems/inspec-2.2.34/bin/inspec:12:in `<main>'
```

**Comment by shelld0n** [comment]
Maybe try to upload the extracted archive ? I mean Extract manually the profile then : 

`inspec compliance upload C:\Users\chef\Downloads\linux-baseline-2.2.0\`

I don't know if this will work or not, but give it a try.

**Comment by jerryaldrichiii** [comment]
I think this is fixed. See:
  - https://github.com/inspec/inspec/issues/3245
  - https://github.com/inspec/inspec/pull/3369

Please let us know if updating doesn't fix your issue @ChefRycar (feel free to reopen this as well).
