### ISSUE TITLE
inspec compliance upload - upload error

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#3245]
### 🎛 Description

🐛 bug report

Hi 

I'm attempting to upload a profile to my A2 server.  I've been able to logon to a2 through inspec and can query profiles etc.  Yet it seems to error at the uploading stage.  The error reports that I should run inspec check but I know my profile is good, inspec check passes and using the gui I can upload the file that inspec created and it uploads fine.

### 🌍 InSpec and Platform Version

2.2.42 on windows 10

### 🤔 Replication Case

```
 bundle exec ruby .\bin\inspec compliance upload C:\git-repo\niu\microsoft-windows-server
Profile is already vendored. Use --overwrite.
I, [2018-07-23T14:05:23.429696 #20836]  INFO -- : Checking profile in C:\DevOps\git-repo\niu\microsoft-windows-server
I, [2018-07-23T14:05:23.430697 #20836]  INFO -- : Metadata OK.
I, [2018-07-23T14:05:23.497744 #20836]  INFO -- : Found 6 controls.
I, [2018-07-23T14:05:23.497744 #20836]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at C:/Users/gbright/AppData/Local/Temp/microsoft-windows-server20180723-20836-1u0qn39.tar.gz
I, [2018-07-23T14:05:23.789103 #20836]  INFO -- : Generate archive C:/Users/gbright/AppData/Local/Temp/microsoft-windows-server20180723-20836-1u0qn39.tar.gz.
I, [2018-07-23T14:05:23.800126 #20836]  INFO -- : Finished archive generation.
Start upload to admin/microsoft-windows-server
Uploading to Chef Automate
Error during profile upload:
rpc error: code = InvalidArgument desc = Check InSpec check failed for /hab/svc/compliance-service/data/profiles/.tmp/inspec-upload727119151.tar.gz with message: exit status 1
/hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `read': unexpected end of file (Zlib::GzipFile::Error)
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `from'
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:59:in `each'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:140:in `find_all'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:140:in `block in initialize'
        from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:29:in `new'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:160:in `walk_tar'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:139:in `initialize'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:14:in `new'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/file_provider.rb:14:in `for_path'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/profile.rb:55:in `for_path'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/profile.rb:72:in `for_fetcher'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/profile.rb:78:in `for_target'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/lib/inspec/cli.rb:75:in `check'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /hab/pkgs/chef/inspec/2.2.35/20180709175844/lib/gems/inspec-2.2.35/bin/inspec:12:in `<main>'
```

### 💁 Possible Solutions

If I use the file that was created ``` C:/Users/gbright/AppData/Local/Temp/microsoft-windows-server20180723-20836-1u0qn39.tar.gz ``` and logon to the gui I can upload the profile fine

**Comment by jquick** [comment]
This is interesting. Would it be possible to get a copy of the created tarball? I would like to dig in and test this out. You can post or email jquick@chef.io.

**Comment by jerryaldrichiii** [comment]
I believe this is the same issue as https://github.com/inspec/inspec/issues/3222

If so, trying to upload any profile on Windows I think will fail.

**Comment by atomic111** [comment]
Hi,
i got the same error with uploading a profile via cli. But if i upload it via the automate gui everthing works fine:

~~~
I, [2018-09-06T11:48:15.576895 #15396]  INFO -- : Checking profile in lb-inspec-profile-0.6.2.tar.gz
I, [2018-09-06T11:48:15.578404 #15396]  INFO -- : Metadata OK.
I, [2018-09-06T11:48:45.560692 #15396]  INFO -- : Found 60 controls.
W, [2018-09-06T11:48:45.560951 #15396]  WARN -- : Control verify-kb has no description
W, [2018-09-06T11:48:45.561082 #15396]  WARN -- : Control important-count has no description
W, [2018-09-06T11:48:45.561187 #15396]  WARN -- : Control important-patches has no description
W, [2018-09-06T11:48:45.561281 #15396]  WARN -- : Control important-patches has no tests defined
W, [2018-09-06T11:48:45.561641 #15396]  WARN -- : Control optional-count has no description
W, [2018-09-06T11:48:45.561762 #15396]  WARN -- : Control optional-patches has no description
W, [2018-09-06T11:48:45.561869 #15396]  WARN -- : Control optional-patches has no tests defined
W, [2018-09-06T11:48:45.561964 #15396]  WARN -- : Control windows-base-100 has no description
W, [2018-09-06T11:48:45.562058 #15396]  WARN -- : Control windows-base-102 has no description
W, [2018-09-06T11:48:45.562148 #15396]  WARN -- : Control windows-base-103 has no description
W, [2018-09-06T11:48:45.562239 #15396]  WARN -- : Control windows-base-104 has no description
W, [2018-09-06T11:48:45.562332 #15396]  WARN -- : Control windows-base-202 has no description
W, [2018-09-06T11:48:45.562421 #15396]  WARN -- : Control windows-base-203 has no description
W, [2018-09-06T11:48:45.562515 #15396]  WARN -- : Control windows-account-100 has no description
W, [2018-09-06T11:48:45.562603 #15396]  WARN -- : Control windows-account-101 has no description
W, [2018-09-06T11:48:45.562682 #15396]  WARN -- : Control windows-account-102 has no description
W, [2018-09-06T11:48:45.562783 #15396]  WARN -- : Control windows-ie-101 has no description
W, [2018-09-06T11:48:45.562847 #15396]  WARN -- : Control windows-ie-102 has no description
W, [2018-09-06T11:48:45.562933 #15396]  WARN -- : Control windows-rdp-100 has no description
W, [2018-09-06T11:48:45.562998 #15396]  WARN -- : Control windows-rdp-101 has no description
Profile is valid
Start upload to admin/lb-inspec-profile
Uploading to Chef Automate
Error during profile upload:
rpc error: code = InvalidArgument desc = Check InSpec check failed for /tmp/inspec-upload698580074.tar.gz with message: exit status 1
/hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `read': unexpected end of file (Zlib::GzipFile::Error)
	from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:101:in `from'
	from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:59:in `each'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/file_provider.rb:140:in `find_all'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/file_provider.rb:140:in `block in initialize'
	from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:29:in `new'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/file_provider.rb:160:in `walk_tar'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/file_provider.rb:139:in `initialize'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/file_provider.rb:14:in `new'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/file_provider.rb:14:in `for_path'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/profile.rb:55:in `for_path'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/profile.rb:72:in `for_fetcher'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/profile.rb:78:in `for_target'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/cli.rb:76:in `check'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/bin/inspec:12:in `<main>'
~~~

**Comment by chris-rock** [comment]
I can confirm this bug for Windows in combination with Automate 2
