### ISSUE TITLE
InSpec failes when using VSTS InSpec Execute build runner

### ISSUE THREAD

**Issue by khaljimbo** [inspec/inspec#3290]
### 🎛 Description

Using the Execute InSpec build task in VSTS against an Azure environment I get errors. 

### 🌍 InSpec and Platform Version

The Version of InSpec that the "Install InSpec" build runner installs is 2.2.62 and it is on the Microsoft Hosted Linux agents

### 🤔 Replication Case

This is the command line that it is running:

inspec exec . AZURE_SUBSCRIPTION_ID=*** AZURE_CLIENT_ID=*** AZURE_CLIENT_SECRET=*** AZURE_TENANT_ID=*** inspec exec /home/vsts/work/r1/a/KhalJimbo-CI/tests -t azure:// --reporter cli junit:/home/vsts/work/r1/a/KhalJimbo-CI/tests/junit.xml

### 💻 Stacktrace

This is the output that is gives me:

2018-08-11T19:25:22.6477597Z /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:143:in `initialize': Cannot assign requested address - connect(2) for "localhost" port 50342 (Errno::EADDRNOTAVAIL)
2018-08-11T19:25:22.6493979Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:143:in `new'
2018-08-11T19:25:22.6507954Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:143:in `block in port_open?'
2018-08-11T19:25:22.6522565Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
2018-08-11T19:25:22.6536159Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
2018-08-11T19:25:22.6550299Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
2018-08-11T19:25:22.6564188Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
2018-08-11T19:25:22.6577269Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
2018-08-11T19:25:22.6591203Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:141:in `port_open?'
2018-08-11T19:25:22.6605572Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:64:in `connect'
2018-08-11T19:25:22.6619127Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:50:in `initialize'
2018-08-11T19:25:22.6633168Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:23:in `new'
2018-08-11T19:25:22.6647225Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:23:in `connection'
2018-08-11T19:25:22.6661670Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/backend.rb:51:in `create'
2018-08-11T19:25:22.6675156Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/runner.rb:66:in `configure_transport'
2018-08-11T19:25:22.6689405Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/runner.rb:58:in `initialize'
2018-08-11T19:25:22.6703341Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/cli.rb:169:in `new'
2018-08-11T19:25:22.6717633Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/cli.rb:169:in `exec'
2018-08-11T19:25:22.6731625Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
2018-08-11T19:25:22.6745334Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
2018-08-11T19:25:22.6759150Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
2018-08-11T19:25:22.6773567Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
2018-08-11T19:25:22.6786697Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/bin/inspec:12:in `<top (required)>'
2018-08-11T19:25:22.6800757Z 	from /usr/bin/inspec:102:in `load'
2018-08-11T19:25:22.6813961Z 	from /usr/bin/inspec:102:in `<main>'
2018-08-11T19:25:22.6820199Z 
2018-08-11T19:25:22.6833669Z /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:143:in `initialize': Cannot assign requested address - connect(2) for "localhost" port 50342 (Errno::EADDRNOTAVAIL)
2018-08-11T19:25:22.6847174Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:143:in `new'
2018-08-11T19:25:22.6860509Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:143:in `block in port_open?'
2018-08-11T19:25:22.6874025Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
2018-08-11T19:25:22.6887574Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
2018-08-11T19:25:22.6900206Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
2018-08-11T19:25:22.6913323Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
2018-08-11T19:25:22.6925826Z 	from /opt/inspec/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
2018-08-11T19:25:22.6938567Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:141:in `port_open?'
2018-08-11T19:25:22.6952122Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:64:in `connect'
2018-08-11T19:25:22.6965606Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:50:in `initialize'
2018-08-11T19:25:22.6978696Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:23:in `new'
2018-08-11T19:25:22.6992085Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.25/lib/train/transports/azure.rb:23:in `connection'
2018-08-11T19:25:22.7004890Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/backend.rb:51:in `create'
2018-08-11T19:25:22.7018397Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/runner.rb:66:in `configure_transport'
2018-08-11T19:25:22.7045446Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/runner.rb:58:in `initialize'
2018-08-11T19:25:22.7059754Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/cli.rb:169:in `new'
2018-08-11T19:25:22.7073124Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/lib/inspec/cli.rb:169:in `exec'
2018-08-11T19:25:22.7086093Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
2018-08-11T19:25:22.7100194Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
2018-08-11T19:25:22.7113849Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
2018-08-11T19:25:22.7128533Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
2018-08-11T19:25:22.7141725Z 	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.62/bin/inspec:12:in `<top (required)>'
2018-08-11T19:25:22.7154712Z 	from /usr/bin/inspec:102:in `load'
2018-08-11T19:25:22.7167601Z 	from /usr/bin/inspec:102:in `<main>'
2018-08-11T19:25:22.7174166Z 
2018-08-11T19:25:22.7186747Z undefined
2018-08-11T19:25:22.7272495Z ##[error]InSpec tests failed. Please review errors and try again.

Any help would be greatly appreciated.

**Comment by khaljimbo** [comment]
Closing as I raised this in the wrong project
