### ISSUE TITLE
no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by tomqwu** [inspec/inspec#3326]
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

### 🌍 InSpec and Platform Version

 02.2.69

== Platform Details

Name:      gcp
Families:  cloud, api
Release:   google-api-client-v0.19.8
[Pipeline] sh
[tests] Running shell script
+ inspec detect
EXITCODE   0
== Platform Details

### 🤔 Replication Case

`GOOGLE_APPLICATION_CREDENTIALS=gcloud.json inspec exec acceptance/gcp -t gcp://`

### 💁 Possible Solutions

This is due to upstream train library having issue parsing the gcp service account, update to latest `inspec/train` version Ensure unique_identifier returns something meaningful for service acc… 

https://github.com/inspec/train/blob/v1.4.35/CHANGELOG.md#v1435-2018-08-23

### 💻 Stacktrace

```
GOOGLE_APPLICATION_CREDENTIALS=/Users/twu/Downloads/terraform-sa.json inspec exec acceptance/gcp -t gcp:// --attrs acceptance/attributes.yml --reporter junit:junit-gcp.xml html:acceptance-gcp.html cli
Traceback (most recent call last):
	29: from /Users/twu/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	28: from /Users/twu/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	27: from /Users/twu/.rvm/gems/ruby-2.5.1/bin/inspec:23:in `<main>'
	26: from /Users/twu/.rvm/gems/ruby-2.5.1/bin/inspec:23:in `load'
	25: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/bin/inspec:12:in `<top (required)>'
	24: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	23: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	22: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	21: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	20: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/lib/inspec/cli.rb:173:in `exec'
	19: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/lib/inspec/runner.rb:103:in `run'
	18: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/lib/inspec/runner.rb:132:in `run_tests'
	17: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/lib/inspec/runner_rspec.rb:77:in `run'
	16: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
	15: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
	14: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
	13: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
	12: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:172:in `block in finish'
	11: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:199:in `stop'
	10: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
	 9: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `each'
	 8: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:in `block in notify'
	 7: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/lib/inspec/formatters/base.rb:72:in `stop'
	 6: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/lib/inspec/formatters/base.rb:190:in `platform'
	 5: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/inspec-2.2.64/lib/resources/platform.rb:41:in `[]'
	 4: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/train-1.4.25/lib/train/platforms/platform.rb:52:in `[]'
	 3: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/train-1.4.25/lib/train/platforms/platform.rb:45:in `uuid'
	 2: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/train-1.4.25/lib/train/platforms/detect/uuid.rb:19:in `find_or_create_uuid'
	 1: from /Users/twu/.rvm/gems/ruby-2.5.1/gems/train-1.4.25/lib/train/platforms/detect/helpers/os_common.rb:137:in `uuid_from_string'
/Users/twu/.rvm/gems/ruby-2.5.1/gems/train-1.4.25/lib/train/platforms/detect/helpers/os_common.rb:137:in `update': no implicit conversion of nil into String (TypeError)
```

**Comment by tomqwu** [comment]
Made a PR via https://github.com/inspec/inspec/pull/3331
