### ISSUE TITLE
Docker container creates reporter files with root permission

### ISSUE THREAD

**Issue by marcomancuso** [inspec/inspec#3344]
### 🎛 Description

**Choose one:**  🐛 bug report

Running inspec with the Docker container and the **--reporter** will create a file with root permission

### 🌍 InSpec and Platform Version

**Docker container**:
`chef/inspec:latest`

```
/share # inspec --version
2.2.70

/share # cat /etc/*release
3.7.0
NAME="Alpine Linux"
ID=alpine
```

Host:

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

### 🤔 Replication Case

with a **non root** user run:

```
 docker run --rm \
-v /var/lib/jenkins/workspace/myspace:/share \
chef/inspec:latest myinspecprofile \
-b azure \
--attrs inspec_attributes.yml \
--reporter junit:junit/my_junit.xml
```

Result:

folder junit with my_junit.xml have root permissions and user cannot read it.

### 💁 Possible Solutions

N/A

### 💻 Stacktrace

N/A

**Comment by frezbo** [comment]
@marcomancuso this is not an inspec bug and how inherently docker containers work. Since the container is run as root this is an expected behaviour. You could circumvent this by running as:
```
docker run --rm \
-v /var/lib/jenkins/workspace/myspace:/share \
--user ${USER} \
chef/inspec:latest myinspecprofile \
-b azure \
--attrs inspec_attributes.yml \
--reporter junit:junit/my_junit.xml
```

**Comment by marcomancuso** [comment]
@frezbo that does not work because Inspec has root permission. 
These are the container users:
```
/share # cat /etc/passwd
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/bin/sh
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
```

I tried to run with **--user postgres** and I had a permission issue:
```
/usr/local/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Permission denied @ dir_s_mkdir - /var/lib/postgresql (Errno::EACCES)
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from /usr/local/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from /usr/local/bundle/gems/inspec-2.2.70/lib/inspec/dependencies/cache.rb:22:in `initialize'
	from /usr/local/bundle/gems/inspec-2.2.70/lib/inspec/runner.rb:43:in `new'
	from /usr/local/bundle/gems/inspec-2.2.70/lib/inspec/runner.rb:43:in `initialize'
	from /usr/local/bundle/gems/inspec-2.2.70/lib/inspec/cli.rb:170:in `new'
	from /usr/local/bundle/gems/inspec-2.2.70/lib/inspec/cli.rb:170:in `exec'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/inspec-2.2.70/bin/inspec:12:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:23:in `load'
	from /usr/local/bundle/bin/inspec:23:in `<main>'
```

**Comment by frezbo** [comment]
Arrgggg, right. The only solution is to change the files owner. The reason being docker runs as root. I usually run containers in userspace as rootless. so it will be always mapped to the user being run.

**Comment by marcomancuso** [comment]
The user does not have the right to change the owner of the file, so it can't be done.
I think it's a bug that Inspec run as root in the container and it should have a specific user

**Comment by frezbo** [comment]
That will not still solve the problem, lets say that that the uid inside the container is `100` so the files will be created as uid `100` on the host making it still in-accessible

**Comment by marcomancuso** [comment]
yes, right. I think it would be easier to just output the command to a file:

```
docker run --rm \
-v /var/lib/jenkins/workspace/myspace:/share \
chef/inspec:latest myinspecprofile \
-b azure \
--attrs inspec_attributes.yml \
--reporter junit > /path/junit.xml
```

**Comment by zenspider** [comment]
Workaround seems sufficient. Closing.
