### ISSUE TITLE
Postgresql 10 versioning on ubuntu + version_from_psql

### ISSUE THREAD

**Issue by pmav99** [inspec/inspec#3349]
### 🎛 Description

 🐛 bug report

I am trying to run [postgres-baseline](https://github.com/dev-sec/postgres-baseline) on ubuntu while using Postgresql 10 but I get a stacktrace
```
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/resources/postgres.rb:122:in `cluster_from_dir': undefined method `chomp' for nil:NilClass (NoMethodError)
```

### 🌍 InSpec and Platform Version
Inspec was installed via
```
curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
```
```
$ inspec version
2.2.78

$ uname -a
Linux test 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
I also installed Postgres 9.6 for comparison:
```
$ psql --version
psql (PostgreSQL) 10.5 (Ubuntu 10.5-1.pgdg16.04+1)

$ /usr/lib/postgresql/10/bin/psql --version    # this is the same psql as the previous one
psql (PostgreSQL) 10.5 (Ubuntu 10.5-1.pgdg16.04+1)

$ /usr/lib/postgresql/9.6/bin/psql --version
psql (PostgreSQL) 9.6.10

$ ls /etc/postgresql/*
/etc/postgresql/9.6:
main

/etc/postgresql/10:
main

$ sudo ls /var/lib/postgresql/*
/var/lib/postgresql/9.6:
main

/var/lib/postgresql/10:
main
```

Finally:
```
postgres-baseline commit: 1040ac93abe68dd92b2c4e80608c078dc4586684
postgresql deb package version: 10+192.pgdg16.04+1
```

### 💁 Possible Solutions

My ruby foo is not that great, but I think that the culprit is `version_from_psql` which can't handle the output of `psql --version`:

```
$ psql --version
psql (PostgreSQL) 10.5 (Ubuntu 10.5-1.pgdg16.04+1)
```
I added a `puts` in the code and I can see that the version that gets parsed is `10.5-1` which causes line 122 (i.e. `        dirs = inspec.command("ls -d #{dir}/*/").stdout.lines`) to return an empty list. Judging from the directory structure, `version_from_psql` should return `9.X` for Postgresql 9 and `10` for version 10+.

### 💻 Stacktrace

```
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/resources/postgres.rb:122:in `cluster_from_dir': undefined method `chomp' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/resources/postgres.rb:20:in `initialize'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/plugin/v1/plugin_types/resource.rb:68:in `initialize'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/resource.rb:51:in `new'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/resource.rb:51:in `block (3 levels) in create_dsl'
	from postgres-baseline/controls/postgres_spec.rb:40:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/profile_context.rb:158:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/profile_context.rb:158:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/profile_context.rb:142:in `load_control_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/profile.rb:171:in `block in collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/profile.rb:168:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/profile.rb:168:in `collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/runner.rb:92:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/runner.rb:81:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/runner.rb:81:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/runner.rb:102:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/cli.rb:173:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/bin/inspec:12:in `<top (required)>'
	from /usr/bin/inspec:103:in `load'
	from /usr/bin/inspec:103:in `<main>'
```

**Comment by pmav99** [comment]
More info WRT postgresql versioning: https://www.postgresql.org/support/versioning/

**Comment by pmav99** [comment]
Maybe instead of relying on awk using a ruby regex would be a better idea: http://rubular.com/r/yEW71p2lph

**Comment by aaronlippold** [comment]
Given I was the author of this or at least one of the contributors, I will try to work up a PR unless others on the team have already picked it up

**Comment by ericlake** [comment]
I can report that this is affecting me as well with postgresql 10 and the following version of inspec.
```bash
$ inspec --version  
2.2.112
```

**Comment by malagant** [comment]
Current inspec 3.0.46 is also affected with postgresql 10

**Comment by Themercee** [comment]
Is there any way to fit it? I still can't run the postgres test with inspec version 3.9.3
