### ISSUE TITLE
Undefined method passwords in shadow from 2.0.45 to 2.2.78 (latest stable)

### ISSUE THREAD

**Issue by grantbee** [inspec/inspec#3353]
### 🎛 Description
🐛 bug report

Hi guys, have run into an inspec issue which is present from version 2.0.45. Seems related to the issues around 3136 and 3140. However this is still a problem when using version 2.2.78.

Was hoping I could get some help here, as am looking to upgrade envr to chef-14 client which currently includes inspec version 2.2.70, and which is causing this test to fail (I have a bunch of others which are all fine).

Note: The following tests were performed on RHEL7.5 using the binary inspec RPMs.

TEST:

```
control 'AD.1.1.1.2 Password Requirements' do
  impact 0.5
  title 'PASS_MAX_DAYS'
  desc  '
   Per-userid password age setting, in days, via field 5 of each record, in /etc/shadow
   Note: This setting in /etc/shadow is not required on userids without a password, nor is it required on userids that meet the requirements in "Exemptions to password rules"
  '
  passwd.entries.each do |user|
    if %w(/usr/sbin/nologin /sbin/nologin /bin/false).include? user.shell
      describe user do
        skip "No shell defined for #{user.user}. Setting not required. See exemptions to password rules."
      end
    else
      shadow.users(user.user).entries.each do |shad|
        if (shad.passwords & %w(* ! !!)).any?
          describe shad do
            skip "No password defined for #{user.user}. Setting not required. See exemptions to password rules."
          end
        else
          describe shad do
            its('max_days') { should cmp <= 60 }
          end
        end
      end
    end
  end
end
```

Working VERSION:

```
[root@gbtsrh7chef131 ~]# /opt/inspec/bin/inspec —version
2.0.32

[root@gbtsrh7chef131 ~]# /usr/bin/inspec exec --no-color inspec_ad1112.rb > gbtsrh7chef131-linux-techspec-baseline.txt && cat gbtsrh7chef131-linux-techspec-baseline.txt

Profile: tests from inspec_ad1112.rb (tests from inspec_ad1112.rb)
Version: (not specified)
Target:  local://

  ↺  AD.1.1.1.2 Password Requirements: PASS_MAX_DAYS (16 skipped)
     ✔  /etc/shadow with user = "root" on entry user=root max_days should cmp <= 60
     ↺  No shell defined for bin. Setting not required. See exemptions to password rules.
     ↺  No shell defined for daemon. Setting not required. See exemptions to password rules.
     ↺  No shell defined for adm. Setting not required. See exemptions to password rules.
     ↺  No password defined for sync. Setting not required. See exemptions to password rules.
     ↺  No password defined for shutdown. Setting not required. See exemptions to password rules.
     ↺  No password defined for halt. Setting not required. See exemptions to password rules.
     ↺  No shell defined for mail. Setting not required. See exemptions to password rules.
     ↺  No shell defined for operator. Setting not required. See exemptions to password rules.
     ↺  No shell defined for nobody. Setting not required. See exemptions to password rules.
     ↺  No shell defined for systemd-bus-proxy. Setting not required. See exemptions to password rules.
     ↺  No shell defined for systemd-network. Setting not required. See exemptions to password rules.
     ↺  No shell defined for dbus. Setting not required. See exemptions to password rules.
     ↺  No shell defined for ntp. Setting not required. See exemptions to password rules.
     ↺  No shell defined for postfix. Setting not required. See exemptions to password rules.
     ↺  No shell defined for sshd. Setting not required. See exemptions to password rules.
     ↺  No shell defined for polkitd. Setting not required. See exemptions to password rules.


Profile Summary: 0 successful controls, 0 control failures, 1 control skipped
Test Summary: 1 successful, 0 failures, 16 skipped
```

FAILED Version:

```
[root@gbtsrh7chef131 ~]# /opt/inspec/bin/inspec --version
2.0.45

[root@gbtsrh7chef131 ~]# /usr/bin/inspec exec --no-color inspec_ad1112.rb > gbtsrh7chef131-linux-techspec-baseline.txt
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.
inspec_ad1112.rb:15:in `block (3 levels) in load_with_context': undefined method `passwords' for #<#<Class:0x0000000004374318>:0x00000000026ef2b0> (NoMethodError)
        from inspec_ad1112.rb:14:in `each'
        from inspec_ad1112.rb:14:in `block (2 levels) in load_with_context'
        from inspec_ad1112.rb:8:in `each'
        from inspec_ad1112.rb:8:in `block in load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/rule.rb:50:in `instance_eval'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/rule.rb:50:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/control_eval_context.rb:75:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
        from inspec_ad1112.rb:1:in `load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/profile_context.rb:157:in `instance_eval'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/profile_context.rb:157:in `load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/profile_context.rb:141:in `load_control_file'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/profile.rb:167:in `block in collect_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/profile.rb:164:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/profile.rb:164:in `collect_tests'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/runner.rb:93:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/runner.rb:82:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/runner.rb:82:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/runner.rb:103:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/lib/inspec/cli.rb:168:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.45/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:72:in `load'
        from /usr/bin/inspec:72:in `<main>’
```

LATEST Version:

```
[root@gbtsrh7chef131 ~]# /opt/inspec/bin/inspec --version
2.2.78
```

LATEST Version Failure:

```
[root@gbtsrh7chef131 ~]# /opt/inspec/bin/inspec --version
2.2.78
[root@gbtsrh7chef131 ~]# /usr/bin/inspec exec --no-color inspec_ad1112.rb > gbtsrh7chef131-linux-techspec-baseline.txt
[root@gbtsrh7chef131 ~]# echo $?
100
[root@gbtsrh7chef131 ~]# cat gbtsrh7chef131-linux-techspec-baseline.txt

Profile: tests from inspec_ad1112.rb (tests from inspec_ad1112.rb)
Version: (not specified)
Target:  local://

  ×  AD.1.1.1.2 Password Requirements: PASS_MAX_DAYS
     ×  Control Source Code Error inspec_ad1112.rb:1
     undefined method `passwords' for #<#<Class:0x00000000030e45b8>:0x0000000004a2a400>


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
```

### 🌍 InSpec and Platform Version
Tested 2.0.32 (OK), 2.0.45 (Fails) and 2.2.78 (Fails) on a RHEL7.5 VM using Inspec installed from binary RPMs.

### 🤔 Replication Case
Details in description.

### 💁 Possible Solutions
This seems to be related to previous issues outlined in 3136 and 3140, however is still an issue with version 2.2.78.

### 💻 Stacktrace
Let me know if more detail is required over and above that provided in the description above.

**Comment by grantbee** [comment]
The following inspec code was written to work around this error, and is probably a better way of achieving the same outcome.

```
control 'AD.1.1.1.2 Password Requirements' do
  impact 0.5
  title 'PASS_MAX_DAYS'
  desc  '
   Per-userid password age setting, in days, via field 5 of each record, in /etc/shadow
   Note: This setting in /etc/shadow is not required on userids without a password, nor is it required on userids that meet the requirements in "Exemptions to password rules"
  '
  passwd.entries.each do |user|
    if %w(/usr/sbin/nologin /sbin/nologin /bin/false).include? user.shell
      describe user do
        skip "No shell defined for #{user.user}. Setting not required. See exemptions to password rules."
      end
    else
      shad = shadow.users(user.user)
      if (shad.passwords & %w(* ! !!)).any?
        describe shad do
          skip "No password defined for #{user.user}. Setting not required. See exemptions to password rules."
        end
      else
        describe shad do
          its('max_days') { should cmp <= 60 }
        end
      end
    end
  end
end 
```
