### ISSUE TITLE
ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError) error

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3375]
### 🎛 Description

When I try to upload a profile to Automate, I receive an Encoding::Undefined message:

```
...
Uploading to Chef Automate
Error during profile upload:
rpc error: code = Internal desc = Could not gather profile json for /tmp/inspec-upload332321933.tar.gz caused by: exit status 1
/hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/2.5.0/json/common.rb:224:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/2.5.0/json/common.rb:224:in `generate'
	from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/2.5.0/json/common.rb:224:in `generate'
	from /hab/pkgs/core/ruby/2.5.1/20180702162818/lib/ruby/2.5.0/json/common.rb:394:in `dump'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/lib/inspec/cli.rb:51:in `json'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /hab/pkgs/chef/inspec/2.2.70/20180823210516/lib/gems/inspec-2.2.70/bin/inspec:12:in `<main>'
```

### 🌍 InSpec and Platform Version

InSpec 2.x

### 🤔 Replication Case

Use ASCII-8BIT codes in UTF files 

### 💁 Possible Solutions

Only use UTF character sets

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
You can use the following grep command to identify the characters:

```
$ grep --color='auto' -P -n '[^\x00-\x7F]' trials/aws/controls/*.rb
01-iam.rb:241:        An IAM role is conceptually “a container of permissions resembling a user account which cannot be directly logged into, but which must instead be assumed from an existing user account which has appropriate permissions to do so, in the manner of roles in Unix Role-Based Access Control (RBAC).
```

Change the highlighted characters and the upload to Automate will work fine.

**Comment by atty-stripe** [comment]
For folks finding this issue on Google, `-P` is only supported on certain distributions of `grep`. Alternatives here: https://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters.
