### ISSUE TITLE
inspec shell fails to run on Windows Docker container fails(Windows 2016 Core Docker)

### ISSUE THREAD

**Issue by lmayorga1980** [inspec/inspec#3506]
I was trying to execute `inspec shell` but seems like there is an issue. However, it works when running it from a regular ruby script.

```
PS C:\> inspec shell -c 'describe package("Node.js") do it {should be_installed} end'
[1mTraceback[m (most recent call last):                                                                                113: from C:/tools/ruby25/bin/inspec:23:in `<main>'
12: from C:/tools/ruby25/bin/inspec:23:in `load'
11: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/bin/inspec:12:in `<top (required)>'
10: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
 9: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
 8: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
 7: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
 6: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/cli.rb:239:in `shell_func'
 5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/cli.rb:289:in `run_command'
 4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:241:in `eval_with_virtual_profile'
 3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/profile_context.rb:144:in `load_control_file

 2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/profile_context.rb:158:in `load_with_context

 1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/profile_context.rb:158:in `instance_eval'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/profile_context.rb:158:in `instance_eval': [1muniniti'lized constant #<Class:#<#<Class:0x00000000071c5d98>:0x00000000071c52f8>>::Node ([1;4mNameError[m[1m)
[m                                                                                                                     'PS C:\>
PS C:\> cd .\choco\
PS C:\choco> cp .\test.rb C:\test.rb                                                                                   aPS C:\choco> cd ..
PS C:\> inspec exec .\test.rb

Profile: tests from .\test.rb (tests from ..test.rb)
Version: (not specified)
Target:  local://

  System Package Node.js
     [PASS]  should be installed

Test Summary: 1 successful, 0 failures, 0 skipped
PS C:\>
```

**Comment by jerryaldrichiii** [comment]
Interesting...your command seems to work for me on Linux. I'm wondering if it's a quoting issue.

Can you try:

```
inspec shell -c 'describe package(\"Node.js\") do it {should be_installed} end'
```

and other similar escapes?

**Comment by lmayorga1980** [comment]
**As your example**
```
PS C:\> inspec shell -c 'describe package(\"Node.js\") do it {should be_installed} end'

Profile: inspec-shell
Version: (not specified)
Target:  local://

  System Package Node.js
     [PASS]  should be installed

Test Summary: 1 successful, 0 failures, 0 skipped
```
**Without Escape**
```
PS C:\> inspec shell -c 'describe package("Node.js") do it {should be_installed} end'
[1mTraceback[m (most recent call last):
13: from C:/tools/ruby25/bin/inspec:23:in `<main>'
12: from C:/tools/ruby25/bin/inspec:23:in `load'
11: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/bin/inspec:12:in `<top (required)>'
10: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
 9: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
 8: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
 7: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
 6: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/cli.rb:237:in `shell_func'
 5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/cli.rb:287:in `run_command'
 4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/runner.rb:245:in `eval_with_virtual_profile'
 3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_context.rb:144:in `load_control_file'
 2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_context.rb:158:in `load_with_context'
 1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_context.rb:158:in `instance_eval'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_context.rb:158:in `instance_eval': [1muninitialized constant #<Class:#<#<Class:0x00000000052c29c8>:0x00000000052c1aa0>>::Node ([1;4mNameError[m[1m)
[m

```

**CMD.exe withou Escape**
```

PS C:\> cmd
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>inspec shell -c 'describe package("Node.js") do it {should be_installed} end '

Profile: inspec-shell
Version: (not specified)
Target:  local://

  System Package Node.js
     [PASS]  should be installed

Test Summary: 1 successful, 0 failures, 0 skipped
```
**On the mounted volume Path**
```
C:\>cd choco

C:\choco>dir
 Volume in drive C has no label.
 Volume Serial Number is 7C0B-ADB7

 Directory of C:\choco

10/25/2018  02:59 PM    <DIR>          .
10/25/2018  02:59 PM    <DIR>          ..
10/25/2018  02:59 PM    <DIR>          6.10.2
10/25/2018  03:08 PM    <DIR>          8.12.0
               0 File(s)              0 bytes
               4 Dir(s)   5,497,745,408 bytes free

C:\choco>cd 8.12.0

C:\choco\8.12.0>inspec shell -c 'describe package("Node.js") do it {should be_installed} end '
Traceback (most recent call last):
        9: from C:/tools/ruby25/bin/inspec:23:in `<main>'
        8: from C:/tools/ruby25/bin/inspec:23:in `load'
        7: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/bin/inspec:10:in `<top (required)>'
        6: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/bin/inspec:10:in `require_relative'
        5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec.rb:23:in `<top (required)>'
        4: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/plugin/v2.rb:29:in `<top (required)>'
        1: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': Invalid argument @ rb_readlink - C:/choco (Errno::EINVAL)
```

**Comment by lmayorga1980** [comment]
@jerryaldrichiii Maybe the failure on **inspec** within the mounted scenario can be targeted in another issue.
