### ISSUE TITLE
No way to write a control with shadow resource that's both 1.x and 2.x compatible

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3570]
### 🎛 Description

 🐛 bug report 

CIS compliance requires this control:

```
describe shadow.where { user =~ /.+/ and password =~ /^[^!*]/ and (max_days.nil? or max_days.to_i > 365) } do
    its("raw_data") { should be_empty }
  end
```

I need control code that is compatible across Inspec 1.x 2.x and 3.x

The control above does not work in Inspec 1.x as there is no `where` method. The 1.x docs suggest I need to use the [filter method](https://github.com/inspec/inspec/blob/1-stable/docs/resources/shadow.md.erb) instead. I don't think I can use `filter` as it only filters on equality and I cannot query for `max_days.to_i > 365` for example.

### 🌍 InSpec and Platform Version

1.51.25 and all newer versions up to 3.0

### 💁 Possible Solutions

1. Iterate on `entries`
e.g. 

```
shadow.users(/.+/).entries.each do |entry|
  describe.one do
    describe entry do
      its("passwords") { should_not match(/^[^!*]/) }
    end
    describe entry do
      its("inactive_days") { should_not cmp > 30 }
    end
  end
```

This is not ideal because `entries` isn't intended to be part of the DSL. It also doesn't work because the `passwords` property might be `password` or `passwords` depending on the Inspec version.

2. Include multiple versions of the control code and branch which one is included using `Inspec::VERSION`

3. Backport `where` to 1.x

### 💻 Stacktrace

```

bundle exec inspec check my-profile.tar.gz
--
  | bundler: failed to load command: inspec (/workdir/vendor/bundle/ruby/2.5.0/bin/inspec)
  | NoMethodError: undefined method `where' for /etc/shadow:#<Class:0x000056424b48f128>
  | controls/my-controls.rb:3272:in `block in load_with_context'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/rule.rb:50:in `instance_eval'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/rule.rb:50:in `initialize'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/control_eval_context.rb:75:in `new'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
  | controls/my-controls.rb:3261:in `load_with_context'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile_context.rb:157:in `instance_eval'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile_context.rb:157:in `load_with_context'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile_context.rb:141:in `load_control_file'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:167:in `block in collect_tests'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:164:in `each'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:164:in `collect_tests'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:470:in `load_checks_params'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:463:in `load_params'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:157:in `params'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:323:in `controls_count'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/profile.rb:294:in `check'
  | /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-1.51.25/lib/inspec/cli.rb:76:in `check'

```

**Comment by james-stocks** [comment]
I spoke to @chris-rock about this - it is best to handle this with custom resource code in our profiles, and not change anything in Inspec.
