### ISSUE TITLE
InSpec 3 fails to fetch profiles from compliance server

### ISSUE THREAD

**Issue by alex-w-k** [inspec/inspec#3598]
### 🎛 Description

🐛 bug report

### 🌍 InSpec and Platform Version

InSpec 3.0.12 from ChefDK3.4.38 on macOS 10.14.1

### 🤔 Replication Case

When attempting to vendor dependent InSpec profiles to a cookbook's InSpec profile using InSpec 3.0.12 and Compliance server version 1.11.1, vendoring doesn't work.

Running `inspec compliance exec kalexander/tomcat-default` does work.
Running `inspec compliance download kalexander/tomcat-default` also works.

### 💁 Possible Solutions

InSpec version 2.1.72 from ChefDK 3.0.36 does vendor the InSpec profiles as expected.

### 💻 Stacktrace

```bash
[2018-11-08T12:51:02-07:00] DEBUG: Option backend_cache is disabled
[2018-11-08T12:51:02-07:00] DEBUG: Resolve /cookbook_path/test/integration/default/ into cache /cookbook_path/test/integration/default/vendor
[2018-11-08T12:51:02-07:00] DEBUG: Dependency does not exist in the cache  /cookbook_path/test/integration/default/
[2018-11-08T12:51:02-07:00] DEBUG: Starting traversal of dependencies ["tomcat-default", "base_repos", "zodiac_repos"]
Traceback (most recent call last):
	20: from /opt/chefdk/bin/inspec:296:in `<main>'
	19: from /opt/chefdk/bin/inspec:296:in `load'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/bin/inspec:12:in `<top (required)>'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/cli.rb:129:in `vendor'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/base_cli.rb:358:in `vendor_deps'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_vendor.rb:15:in `vendor!'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_vendor.rb:58:in `vendor_dependencies'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile.rb:494:in `generate_lockfile'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:31:in `resolve'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:59:in `each'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/requirement.rb:80:in `resolved_source'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/requirement.rb:102:in `fetcher'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/requirement.rb:102:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/cached_fetcher.rb:15:in `initialize': Could not fetch inspec profile in {:cwd=>" /cookbook_path/test/integration/default/", :backend=>Inspec::Backend::Class @transport=Train::Transports::Mock::Connection, :name=>"tomcat-default", :compliance=>"kalexander/tomcat-default"}. (RuntimeError)
```

EDIT:(@clintoncwolfe) - update title to reflect diagnosis

**Comment by jquick** [comment]
I am able to reproduce this. Working on a fix.
