### ISSUE TITLE
attribute() doest not work inside describe.one 

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#3650]
### 🎛 Description

This is a 🐛 bug report

Pulling attribute values using attribute() does not work inside a describe.one block

### 🌍 InSpec and Platform Version

3.0.61

### 🤔 Replication Case

The following defenition will fail
```
  describe.one do
  	describe http("http://#{attribute('application_url')}", enable_remote_worker: true) do
  	  its('status') { should cmp 200 }
  	end


  	describe http("https://#{attribute('application_url')}", enable_remote_worker: true) do
  	  its('status') { should cmp 200 }
  	end
  end
```
Error:
```
     ×  Control Source Code Error ./controls/example.rb:8
     undefined method `attribute' for #<#<Class:0x00007ff13543abd8>:0x00007ff13543a408>

```

However this works fine:

```
	describe http("http://#{attribute('application_url')}", enable_remote_worker: true) do
	  its('status') { should cmp 200 }
	end
```

### 💻 Stacktrace

```
Traceback (most recent call last):
	23: from /Users/rxavier/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	22: from /Users/rxavier/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	21: from /Users/rxavier/.rvm/gems/ruby-2.5.1/bin/inspec:23:in `<main>'
	20: from /Users/rxavier/.rvm/gems/ruby-2.5.1/bin/inspec:23:in `load'
	19: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/bin/inspec:12:in `<top (required)>'
	18: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	17: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/cli.rb:245:in `exec'
	13: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/runner.rb:110:in `run'
	12: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/runner.rb:81:in `load'
	11: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/runner.rb:81:in `each'
	10: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/runner.rb:99:in `block in load'
	 9: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/profile.rb:192:in `collect_tests'
	 8: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/profile.rb:192:in `each'
	 7: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/profile.rb:195:in `block in collect_tests'
	 6: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/profile_context.rb:144:in `load_control_file'
	 5: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/profile_context.rb:160:in `load_with_context'
	 4: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/profile_context.rb:160:in `instance_eval'
	 3: from ./controls/example.rb:1:in `load_with_context'
	 2: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/describe.rb:19:in `one'
	 1: from /Users/rxavier/.rvm/gems/ruby-2.5.1/gems/inspec-3.0.61/lib/inspec/describe.rb:19:in `instance_eval'
./controls/example.rb:2:in `block in load_with_context': undefined method `attribute' for #<#<Class:0x00007fb219111930>:0x00007fb219111638> (NoMethodError)
```

**Comment by jquick** [comment]
Thanks for reporting this @rx294. We are in the process of converting attributes to a internal plugin so we will add this to our test cases. @clintoncwolfe

**Comment by aaronlippold** [comment]
Was this resoved in v4 or do we need to resource it again in our next patch release?

**Comment by aaronlippold** [comment]
@clintoncwolfe @miah can we review this one at the next community meeting?

**Comment by clintoncwolfe** [comment]
I think about this one a lot, and would like to fix it.

**Comment by clintoncwolfe** [comment]
I've spent some cycles looking at this, and unfortunately, I'm not sure this is practical to fix at this time until #4127 and (preferably) #4199 are fixed. 

Traced to 
https://github.com/inspec/inspec/blob/f47d5057b253ab66e157a68d19dd40bf458afc18/lib/inspec/describe.rb#L13

I'll bang on it a bit more.

**Comment by clintoncwolfe** [comment]
I think it is clear that the DSL is only being partially set up here:
https://github.com/inspec/inspec/blob/f47d5057b253ab66e157a68d19dd40bf458afc18/lib/inspec/rule.rb#L159
but for now this pretty intractable.

**Comment by clintoncwolfe** [comment]
Failing test case pushed on cw/input-in-describe-one branch
