### ISSUE TITLE
Inspec broken after upgrade.

### ISSUE THREAD

**Issue by g1ps** [inspec/inspec#3652]
### 🎛 Description

**🐛 bug report

Inspec doesn't work after upgrading to 3.0.61. Worse still, it breaks all usage of Inspec. I tried repairing, and rebooting. Both failed After reverting to 3.0.52 that now won't run and fails with the same error. Inspec is now dead on this machine.

### 🌍 InSpec and Platform Version

^
Windows 7 Pro

### 🤔 Replication Case

upgrade and run the tool.

### 💻 Stacktrace

````
e:\temp\****>inspec exec .\****\controls\validation.rb
Traceback (most recent call last):
        19: from C:/opscode/inspec/bin/inspec:108:in `<main>'
        18: from C:/opscode/inspec/bin/inspec:108:in `load'
        17: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/bin/inspec:12:in
`<top (required)>'
        16: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:46
6:in `start'
        15: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in
`dispatch'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation
.rb:126:in `invoke_command'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb
:27:in `run'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/cli.rb
:245:in `exec'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/runner
.rb:110:in `run'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/runner
.rb:81:in `load'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/runner
.rb:81:in `each'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/runner
.rb:99:in `block in load'
         7: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/profil
e.rb:192:in `collect_tests'
         6: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/profil
e.rb:192:in `each'
         5: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/profil
e.rb:195:in `block in collect_tests'
         4: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/profil
e_context.rb:144:in `load_control_file'
         3: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/profil
e_context.rb:160:in `load_with_context'
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/profil
e_context.rb:160:in `instance_eval'
         1: from ./****/controls/validation.rb:6:in `load_with_context'
C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.61/lib/inspec/dsl.rb:49:in `method_mi
ssing': undefined local variable or method `here' for #<#<Class:0x0000000006f9c378>:0x0000000007f379
68> (NameError)
````

`exec` fails with similar errors. I gave up after that.

**Comment by g1ps** [comment]
My mistake. It turned out to be an uncommented comment causing an issue. The excessive amount of unhelpful output misled me. I'd offer that as a reason to improve what's reported.
