### ISSUE TITLE
Inspec omnibus version doesn't work with ED25519 based ssh keys missing dependencies

### ISSUE THREAD

**Issue by tvigers** [inspec/inspec#3711]
### 🎛 Description

🐛 Bug report

When trying to run an inspec profile against a remote host using SSH as a backend inspec produces the error below (under Stacktrace).

Command ran is the following:

`inspec exec -t ssh://user@example.com ~/Documents/Development/inspec/linux-baseline -i ~/.ssh/serversumo`

### 🌍 InSpec and Platform Version

**Inspec Version:** 3.2.6
**OS Version:** Mac OS X 10.14.2 Mojave

### 🤔 Replication Case

1. Generate an ssh key:

`ssh-keygen -t rsa`

2. Install inspec using homebrew:

`brew cask install inspec`

3. Run inspec against remote server:

`inspec exec linux-baseline/ -t ssh://user@example.com -i ~/.ssh/id_rsa`

### 💁 Possible Solutions

Include the following gems in the omnibus release:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)

### 💻 Stacktrace

```inspec exec ~/Documents/Development/inspec/linux-baseline -t ssh://username@host -i ~/.ssh/id_rsa
Traceback (most recent call last):
    47: from /usr/local/bin/inspec:122:in `<main>'
    46: from /usr/local/bin/inspec:122:in `load'
    45: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/bin/inspec:12:in `<top (required)>'
    44: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
    43: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    42: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    41: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    40: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/cli.rb:248:in `exec'
    39: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/cli.rb:248:in `new'
    38: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/runner.rb:58:in `initialize'
    37: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/runner.rb:66:in `configure_transport'
    36: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/backend.rb:51:in `create'
    35: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/transports/ssh.rb:81:in `connection'
    34: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/transports/ssh.rb:208:in `create_new_connection'
    33: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/transports/ssh.rb:208:in `new'
    32: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/transports/ssh_connection.rb:53:in `initialize'
    31: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/extras/command_wrapper.rb:128:in `load'
    30: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/plugins/base_connection.rb:109:in `platform'
    29: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect.rb:9:in `scan'
    28: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/scanner.rb:27:in `scan'
    27: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/scanner.rb:27:in `each'
    26: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
    25: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
    24: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/scanner.rb:45:in `each'
    23: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
    22: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
    21: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/specifications/os.rb:41:in `block in load'
    20: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/helpers/os_common.rb:43:in `unix_uname_s'
    19: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/platforms/detect/helpers/os_common.rb:36:in `command_output'
    18: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/plugins/base_connection.rb:117:in `run_command'
    17: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/transports/ssh_connection.rb:216:in `run_command_via_connection'
    16: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/transports/ssh_connection.rb:277:in `session'
    15: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.6.3/lib/train/transports/ssh_connection.rb:178:in `establish_connection'
    14: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:241:in `start'
    13: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
    12: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
    11: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
    10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
     9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
     8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
     7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
     6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
     5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
     4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
     3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/key_factory.rb:43:in `load_private_key'
     2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/key_factory.rb:52:in `load_data_private_key'
     1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/key_factory.rb:112:in `classify_key'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/ed25519_loader.rb:19:in `raiseUnlessLoaded': OpenSSH keys only supported if ED25519 is available (NotImplementedError)
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information
Gem::MissingSpecError : "Could not find 'rbnacl' (< 5.0, >= 3.2.0) among 127 total gem(s)
Checked in 'GEM_PATH=/Users/username/.gem/ruby/2.5.0:/opt/inspec/embedded/lib/ruby/gems/2.5.0:/Users/username/.inspec/gems/2.5.0', execute `gem env` for more information"```

**Comment by frezbo** [comment]
@tvigers I saw the conversation in the slack channel, just including these gems is not going to solve the issue with ED25519 keys, `net-ssh` library still cannot parse these keys. I had an open issue there. Seems they have fixed it. Ref: https://github.com/net-ssh/net-ssh/issues/633

**Comment by clintoncwolfe** [comment]
Duplicates #2472 and https://github.com/inspec/train/issues/353 , though I think the repro steps here are excellent.  

I'm going to close this as a duplicate, as we have this covered on the train repo.

**Comment by paulcalabro** [comment]
Just FYI, I resolved this particular issue following the instruction here:

https://github.com/net-ssh/net-ssh/issues/478#issuecomment-275113659
