### ISSUE TITLE
Investigate failing test when using `m` and `test/unit/profiles/profile_context_test.rb`

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3721]
Running the below

```
bundle exec m test/unit/profiles/profile_context_test.rb --line 114 
```

Errors with:

```
Inspec::ProfileContext::its default DSL#test_0007_does not provide the expect keyword in the global DLS [/home/jerry/Projects/github.com/inspec/inspec/test/unit/profiles/profile_context_test.rb:114]:
[NoMethodError] exception expected, not
Class: <NameError>
Message: <"uninitialized constant Inspec::Plugin\nDid you mean?  Inspec::Plugins">
---Backtrace---
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:158:in `instance_eval'
(eval):1:in `load_with_context'
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:158:in `instance_eval'
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:158:in `load_with_context'
/home/jerry/Projects/github.com/inspec/inspec/lib/inspec/profile_context.rb:144:in `load_control_file'
/home/jerry/Projects/github.com/inspec/inspec/test/unit/profiles/profile_context_test.rb:69:in `block in load'
---------------
```

This works when doing `bundle exec rake` so I suspect there is a path through the code that fails to load something but I couldn't find it after searching for 20 minutes.

**Comment by clintoncwolfe** [comment]
Looks like a missing require.
