### ISSUE TITLE
Unhandled exception for inspec check with invalid tar.gz files

### ISSUE THREAD

**Issue by teknofire** [inspec/inspec#3765]
### 🎛 Description

🐛 bug report

The `inspec check` doesn't validate if it's given a valid profile archive file.  Given the following scenario where a user downloads or creates an invalid `.tar.gz` profile archive then you will get the following error:

```
$ touch foo.tar.gz # create empty file
$ inspec check foo.tar.gz
Traceback (most recent call last):
	15: from /opt/chef-workstation/embedded/bin/inspec:23:in `<main>'
	14: from /opt/chef-workstation/embedded/bin/inspec:23:in `load'
	13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/bin/inspec:12:in `<top (required)>'
	12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/cli.rb:85:in `check'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/profile.rb:79:in `for_target'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/profile.rb:73:in `for_fetcher'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/profile.rb:56:in `for_path'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:14:in `for_path'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:14:in `new'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:155:in `initialize'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:197:in `walk_tar'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:197:in `ensure in walk_tar': undefined method `close' for nil:NilClass (NoMethodError)
```

Essentially in the `walk_tar` method in https://github.com/inspec/inspec/blob/master/lib/inspec/file_provider.rb#L193-L198 if `Zlib::GzipFile` throws an error and the `tar_file` variable never gets set and is then nil for the ensure block.  So on line 196 it tries to call `tar_file.close` with a nil `tar_file` and throws the above exception.

If I update `walk_tar` to not call close when `tar_file` is nil, then we get the exception from `Zlib::GzipFile` about the file being an invalid gzip format.

Modified https://github.com/inspec/inspec/blob/master/lib/inspec/file_provider.rb#L193-L198 
```
    def walk_tar(path, &callback)
      tar_file = Zlib::GzipReader.open(path)
      Gem::Package::TarReader.new(tar_file, &callback)
    ensure
      tar_file.close unless tar_file.nil?
    end
```

Output after applying the above changes
```
$ inspec check foo.tar.gz
Traceback (most recent call last):
	16: from /opt/chef-workstation/embedded/bin/inspec:23:in `<main>'
	15: from /opt/chef-workstation/embedded/bin/inspec:23:in `load'
	14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/bin/inspec:12:in `<top (required)>'
	13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/cli.rb:85:in `check'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/profile.rb:79:in `for_target'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/profile.rb:73:in `for_fetcher'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/profile.rb:56:in `for_path'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:14:in `for_path'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:14:in `new'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:155:in `initialize'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:194:in `walk_tar'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:194:in `open'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.6/lib/inspec/file_provider.rb:194:in `initialize': not in gzip format (Zlib::GzipFile::Error)
```

### 🌍 InSpec and Platform Version

This was tested with inspec 3.2.6 but master also has the same code so should be having the same problem as well.

### 🤔 Replication Case

```
$ touch foo.tar.gz
$ inspec check foo.tar.gz
```

### 💁 Possible Solutions

Ensure that close is not called if `tar_file` is nil and also had some additional handling for the Zlib::Gzip class to detect if an invalid file is passed in and present a better error message to the user.

**Comment by james-stocks** [comment]
See also https://github.com/inspec/inspec/issues/3465 - I hesitate to call these 2 issues duplicates because the cause of #3465 is unconfirmed

**Comment by clintoncwolfe** [comment]
Thanks for the extensive diagnostics!
