### ISSUE TITLE
issue with custom aws library - execution expired

### ISSUE THREAD

**Issue by prashanthbgoud** [inspec/inspec#3768]
### 🎛 Description

🐛 bug report

I have a library folder in a profile as below:
**aws\libraries\aws_tg.rb**

```
class AwsTG < Inspec.resource(1)
  name 'aws_tg'
  desc 'Verifies settings for AWS TargetGroup'

  example <<-EOX
    describe aws_tg(names: ['mytg_name']) do
      it { should exist }
      its('target_health_state') { should eq 'healthy' }
      its('target_hosts') { should include 'host_name' }
    end
EOX
  supports platform: 'aws'
  supports platform: 'windows'

  def initialize(opts, conn = nil)
    @opts = opts
    @opts.is_a?(Hash) ? @display_name = @opts[:names][0] : @display_name = opts
    @elbv2_client = conn ? conn.elbv2_client : inspec_runner.backend.aws_client(Aws::ElasticLoadBalancingV2::Client)
    @ec2_resource = conn ? conn.ec2_resource : inspec_runner.backend.aws_resource(Aws::EC2::Resource, {})
  end

  def catch_aws_errors
    yield
  rescue Aws::Errors::MissingCredentialsError
    # The AWS error here is unhelpful:
    # "unable to sign request without credentials set"
    Inspec::Log.error "It appears that you have not set your AWS credentials.  You may set them using environment variables, or using the 'aws://region/aws_credentials_profile' target.  See https://www.inspec.io/docs/reference/platforms for details."
    fail_resource('No AWS credentials available')
  rescue Aws::Errors::ServiceError => e
    fail_resource e.message
  rescue Aws::ElasticLoadBalancingV2::Errors::TargetGroupNotFoundException => e
    fail_resource e.message
  end

  def inspec_runner
    inspec if respond_to?(:inspec)
  end

  def tg_hash
  return @tg_hash if defined?(@tg_hash)
    catch_aws_errors do
      @tg_hash = @opts
    end
  end

  def exists?
    return false if target_group.include? "not found"
    return true
  end

  def to_s
    "AWS TG #{@display_name}"
  end

  private

  def target_group
    catch_aws_errors { @target_group ||= @elbv2_client.describe_target_groups(tg_hash) }
  end

  def target_health
    catch_aws_errors { @target_health ||= @elbv2_client.describe_target_health(tg_hash)}
  end

  def target_health_state
    @host_state_array = []
    instance_obj = nil
    @target_group_arn = target_group.first.target_groups.first.target_group_arn.to_s
    catch_aws_errors { @target_health ||= @elbv2_client.describe_target_health({target_group_arn: @target_group_arn})}
    if target_health.to_h[:target_health_descriptions].any?
      target_health.to_h[:target_health_descriptions].each do |instance|
        @host_state_array.push(instance[:target_health][:state]) if instance[:target_health][:state] != 'healthy'
      end
      return "One or more host are not healthy" if @host_state_array.any?
      return "healthy"
    else
      return "No instances found under the target group"
    end
  end

  def target_hosts
    @host_array = []
    instance_obj = nil
    @target_group_arn = target_group.first.target_groups.first.target_group_arn.to_s
    catch_aws_errors { @target_health ||= @elbv2_client.describe_target_health({target_group_arn: @target_group_arn})}
    if target_health.to_h[:target_health_descriptions].any?
      target_health.to_h[:target_health_descriptions].each do |instance|
        catch_aws_errors { instance_obj = @ec2_resource.instance(instance[:target][:id]) }
        catch_aws_errors do
          instance_obj.tags.each do |tag|
            @host_array.push(tag.value) if tag.key == 'Name'
          end
        end
      end
      return @host_array
    else
      return "No instances found under the target group"
    end
  end
end

  
```

**test:**

**aws\controls\test_tg.rb**

```
control 'test_targetgroup' do
  impact 1.0
  desc "This test is for target group"
    describe aws_tg(names: ["mytargetgroup"]) do
      it { should exist }
    end
end
```

**output:**
**command: inspec exec aws -t aws://us-east-1**

```
Target:  aws://us-east-1

  AWS TG mytargetgroup
     [FAIL]  should exist
     execution expired

Test Summary: 0 successful, 1 failure, 0 skipped

```

I get execution expired, I also see all the inspec aws resources have the same issue except s3.

sometimes I see the **exception**:
```

1
Traceback (most recent call last):
        67: from C:/opscode/inspec/bin/inspec:124:in `<main>'
        66: from C:/opscode/inspec/bin/inspec:124:in `load'
        65: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/bin/inspec:12:in `<top (required)>'
        64: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3
/lib/thor/base.rb:466:in `start'
        63: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3
/lib/thor.rb:387:in `dispatch'
        62: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3
/lib/thor/invocation.rb:126:in `invoke_command'
        61: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3
/lib/thor/command.rb:27:in `run'
        60: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/cli.rb:251:in `exec'
        59: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/runner.rb:110:in `run'
        58: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/runner.rb:81:in `load'
        57: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/runner.rb:81:in `each'
        56: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/runner.rb:99:in `block in load'
        55: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/profile.rb:192:in `collect_tests'
        54: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/profile.rb:192:in `each'
        53: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/profile.rb:195:in `block in collect_tests'
        52: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/profile_context.rb:144:in `load_control_file'
        51: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/profile_context.rb:160:in `load_with_context'
        50: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/profile_context.rb:160:in `instance_eval'
        49: from aws/controls/test_tg.rb:11:in `load_with_context'
        48: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/resource.rb:51:in `block (3 levels) in create_dsl'
        47: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/resource.rb:51:in `new'
        46: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/inspec/plugin/v1/plugin_types/resource.rb:96:in `initialize'
        45: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/resource_support/aws/aws_resource_mixin.rb:6:in `initialize'
        44: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/resource_support/aws/aws_resource_mixin.rb:57:in `catch_aws_errors'
        43: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.2.
6/lib/resource_support/aws/aws_resource_mixin.rb:7:in `block in initialize'
        42: from libraries/aws_new_tg.rb:42:in `fetch_from_api'
        41: from libraries/aws_new_tg.rb:81:in `describe_target_groups'
        40: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operat
ion_methods'
        39: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/request.rb:70:in `send_request'
        38: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        37: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
        36: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        35: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
        34: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
        33: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        32: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
        31: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
        30: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/endpoint_discovery.rb:67:in `call'
        29: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/endpoint_pattern.rb:27:in `call'
        28: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
        27: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/query/handler.rb:27:in `call'
        26: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
        25: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
        24: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
        23: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
        22: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
        21: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
        20: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
        19: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
        18: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
        17: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/retry_errors.rb:108:in `call'
        16: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
        15: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/plugins/request_signer.rb:88:in `call'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/plugins/content_length.rb:12:in `call'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/net_http/handler.rb:45:in `call'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/net_http/handler.rb:119:in `session'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/aws-sdk-cor
e-2.11.195/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session
'
         7: from C:/opscode/inspec/embedded/lib/ruby/2.5.0/delegate.rb:83:in `me
thod_missing'
         6: from C:/opscode/inspec/embedded/lib/ruby/2.5.0/net/http.rb:915:in `s
tart'
         5: from C:/opscode/inspec/embedded/lib/ruby/2.5.0/net/http.rb:920:in `d
o_start'
         4: from C:/opscode/inspec/embedded/lib/ruby/2.5.0/net/http.rb:935:in `c
onnect'
         3: from C:/opscode/inspec/embedded/lib/ruby/2.5.0/timeout.rb:103:in `ti
meout'
         2: from C:/opscode/inspec/embedded/lib/ruby/2.5.0/net/http.rb:937:in `b
lock in connect'
         1: from C:/opscode/inspec/embedded/lib/ruby/2.5.0/net/http.rb:937:in `o
pen'
C:/opscode/inspec/embedded/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execu
tion expired (Seahorse::Client::NetworkingError)
```

### 🌍 InSpec and Platform Version

inspec version: 3.2.6
OS: Windows 2008 R2
the instance has no access to the internet but has an endpoint.

**Comment by clintoncwolfe** [comment]
Looks like it is blocking on accessing the internet (see frame 3 of your stacktrace) and that is being triggered by the AWS SDK as it is listing the names of the methods it can call (see frames 39-42).

Whatever alternate endpoint you are using, you need to to tell the AWS client about it, because I would think it is using the default endpoint, which would require internet access.

This is an issue with your network setup and how your custom resource works, not with InSpec. Thanks though!

**Comment by prashanthbgoud** [comment]
Thanks for the response.
we use s3 endpoint, it works and aws does not have endpoints to all of its resources, any suggestions/work around?

**Comment by clintoncwolfe** [comment]
I think this is a question for AWS support.

**Comment by prashanthbgoud** [comment]
:) thanks for the help, closing this.
