### ISSUE TITLE
Docker resources fail on Inspec 3.7.1

### ISSUE THREAD

**Issue by lmayorga1980** [inspec/inspec#3862]
### 🎛 Description

I am trying to use the Inspec Resources as declared

```ruby
describe docker_container(name: 'an-echo-server') do
  it { should exist }
  it { should be_running }
end
```

### 🌍 InSpec and Platform Version

**3.7.1** 

### 🤔 Replication Case

`docker ps`

CONTAINER ID        IMAGE                                     COMMAND             CREATED             STATUS              PORTS               NAMES
a2d89209d1b2        my-regystry/my-dir/container:latest   "/bin/cinder"       7 minutes ago       Up 7 minutes                            container-1
```

```ruby
describe docker_container(name: 'container-1') do
  it { should exist }
  it { should be_running }
end
```

     ×  Docker Container container-1 should exist
     expected Docker Container container-1 to exist
     ×  Docker Container container-1 should be running
     expected that `Docker Container container-1` is running

### 💻 Stacktrace
```
E, [2019-03-04T13:58:36.896279 #74530] ERROR -- example-ubuntu: ---Nested Exception---
E, [2019-03-04T13:58:36.896295 #74530] ERROR -- example-ubuntu: Class: Kitchen::Terraform::Error
E, [2019-03-04T13:58:36.896311 #74530] ERROR -- example-ubuntu: Message: InSpec Runner exited with 1
E, [2019-03-04T13:58:36.896327 #74530] ERROR -- example-ubuntu: ----------------------
E, [2019-03-04T13:58:36.896342 #74530] ERROR -- example-ubuntu: ------Backtrace-------
E, [2019-03-04T13:58:36.896358 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:91:in `rescue in call'
E, [2019-03-04T13:58:36.896383 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:85:in `call'
E, [2019-03-04T13:58:36.896433 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:458:in `block in verify_action'
E, [2019-03-04T13:58:36.896466 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2019-03-04T13:58:36.896501 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:513:in `block in action'
E, [2019-03-04T13:58:36.896560 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-03-04T13:58:36.896617 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:512:in `action'
E, [2019-03-04T13:58:36.896655 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:450:in `verify_action'
E, [2019-03-04T13:58:36.896697 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-03-04T13:58:36.896727 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-03-04T13:58:36.896759 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-03-04T13:58:36.896788 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
E, [2019-03-04T13:58:36.896828 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-03-04T13:58:36.896882 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:162:in `verify'
E, [2019-03-04T13:58:36.896911 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
E, [2019-03-04T13:58:36.896949 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2019-03-04T13:58:36.896975 #74530] ERROR -- example-ubuntu: /Users/user1/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-03-04T13:58:36.897002 #74530] ERROR -- example-ubuntu: ----End Backtrace-----
```

**Comment by lmayorga1980** [comment]
Closing the issue. The current user does not have `sudo` permissions.
