### ISSUE TITLE
inspec compliance exec command fails after successful login

### ISSUE THREAD

**Issue by rybons** [inspec/inspec#3891]
### 🎛 Description

Unable to run `inspec compliance exec <profile>` for a variety of profiles I have stored in Automate 2.

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🐛 report

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

### 🌍 InSpec and Platform Version

Mac OS 10.14.3
Inspec 3.7.1

### 🤔 Replication Case

1. Log into an automate server:

```
me$ inspec compliance login https://automate.server.com --insecure true --user admin --token <token>`
Stored configuration for Chef Automate2: https://automate.server.com/api/v0' with user: 'admin'
```

2. Get a list of profiles:

```
me$ inspec compliance profiles
 ──────────────────────────── Available profiles: ──────────────────────────── 

• DevSec Linux Security Baseline v2.2.2 (admin/linux-baseline)
[...]
```

3. Try to execute a profile:

```
me$ inspec compliance exec admin/linux-baseline
Traceback (most recent call last):
        12: from /usr/local/bin/inspec:121:in `<main>'
        11: from /usr/local/bin/inspec:121:in `load'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/bin/inspec:12:in `<top (required)>'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/lib/plugins/inspec-compliance/lib/inspec-compliance/cli.rb:75:in `exec': undefined method `opts' for #<InspecPlugins::Compliance::CLI:0x00007faf39a59b88> (NoMethodError)
```

### 💁 Possible Solutions

A colleague who is not on MacOS was unable to reproduce this.

### 💻 Stacktrace

```
Traceback (most recent call last):
        12: from /usr/local/bin/inspec:121:in `<main>'
        11: from /usr/local/bin/inspec:121:in `load'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/bin/inspec:12:in `<top (required)>'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/lib/plugins/inspec-compliance/lib/inspec-compliance/cli.rb:75:in `exec': undefined method `opts' for #<InspecPlugins::Compliance::CLI:0x00007faf39a59b88> (NoMethodError)
```

**Comment by johnypony3** [comment]
im having this issue with 4.16 and 4.17 on both osx (4.17.17) and the chef/chefdk container (4.16.0). This bug has been opened since 3/14

**Comment by clintoncwolfe** [comment]
Verified on 58d9a975c v4.18.15
