### ISSUE TITLE
inspec shell: readline throws stacktrace on SLES 12 SP3 

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#3922]
### 🎛 Description
When running `inspec shell` on a `SLES 12 sp 3` I get errors

### 🌍 InSpec and Platform Version
`InSpec 3.9.0`
```
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 3
```

### 🤔 Replication Case
`inspec shell`

### 💻 Stacktrace
```
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      suse
    Families:  suse, linux, unix, os
    Release:   12.3
    Arch:      x86_64

Error: No such file or directory - infocmp
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/core_extensions.rb:43:in `pry'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/shell.rb:24:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/cli.rb:315:in `shell_func'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/bin/inspec:12:in `<top (required)>'
/usr/bin/inspec:123:in `load'
/usr/bin/inspec:123:in `<main>'
Error: No such file or directory - infocmp
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/core_extensions.rb:43:in `pry'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/shell.rb:24:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/cli.rb:315:in `shell_func'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/bin/inspec:12:in `<top (required)>'
/usr/bin/inspec:123:in `load'
/usr/bin/inspec:123:in `<main>'
Error: No such file or directory - infocmp
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/core_extensions.rb:43:in `pry'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/shell.rb:24:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/cli.rb:315:in `shell_func'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/bin/inspec:12:in `<top (required)>'
/usr/bin/inspec:123:in `load'
/usr/bin/inspec:123:in `<main>'
Error: No such file or directory - infocmp
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/core_extensions.rb:43:in `pry'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/shell.rb:24:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/cli.rb:315:in `shell_func'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/bin/inspec:12:in `<top (required)>'
/usr/bin/inspec:123:in `load'
/usr/bin/inspec:123:in `<main>'
Error: No such file or directory - infocmp
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in ``'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1815:in `get_term_capabilities'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2027:in `_rl_init_terminal_io'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:2564:in `readline_initialize_everything'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:3849:in `rl_initialize'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4868:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:45:in `readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/core_extensions.rb:43:in `pry'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/shell.rb:24:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/lib/inspec/cli.rb:315:in `shell_func'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.0/bin/inspec:12:in `<top (required)>'
/usr/bin/inspec:123:in `load'
/usr/bin/inspec:123:in `<main>'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry
```

**Comment by clintoncwolfe** [comment]
I'm not sure we'll be able to reproduce or fix this; InSpec is just a dumb consumer of pry, which is a consumer of rb-readline. We might be able to determine a working version and pin to it.

**Comment by clintoncwolfe** [comment]
Just to verify, this appears to be an omnibus install of inspec - is that correct?

**Comment by kmf** [comment]
this is from the RPM on downloads.chef.io
