### ISSUE TITLE
Plugin installer unit tests require network connectivity

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4032]
```
2451 % SLOW=1 minitest -Ilib:test test/unit/plugin/v2/installer_test.rb
Run options: --seed 61004

# Running:

...Successfully uninstalled inspec-test-fixture-0.2.0
Successfully uninstalled ordinal_array-0.2.0
..Successfully uninstalled inspec-test-fixture-0.1.0
...E..FFE.......E.EF.FFF

Finished in 0.753270s, 38.4988 runs/s, 102.2210 assertions/s.

  1) Error:
PluginInstallerInstallationTests#test_install_a_gem_from_rubygems_org:
Inspec::Plugin::V2::InstallError: Unable to resolve dependency: user requested 'inspec-test-fixture (> 0)'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:293:in `rescue in install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:287:in `install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:277:in `install_from_remote_gems'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:68:in `install'
    /Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:161:in `test_install_a_gem_from_rubygems_org'

  2) Failure:
PluginInstallerInstallationTests#test_install_a_gem_with_invalid_depends_from_rubygems_org [/Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:229]:
Expected "Unable to resolve dependency: user requested 'inspec-test-fixture (= 0.1.2)'" to include "Could not find 'fake_plugin_dependency' (>= 0)".

  3) Failure:
PluginInstallerInstallationTests#test_install_a_gem_with_conflicting_depends_from_rubygems_org [/Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:218]:
Expected "Unable to resolve dependency: user requested 'inspec-test-fixture (= 0.1.1)'" to include "can't activate rake-0.4.8, already activated rake-".

  4) Error:
PluginInstallerInstallationTests#test_install_a_pinned_gem_from_rubygems_org:
Inspec::Plugin::V2::InstallError: Unable to resolve dependency: user requested 'inspec-test-fixture (= 0.1.0)'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:293:in `rescue in install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:287:in `install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:277:in `install_from_remote_gems'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:68:in `install'
    /Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:195:in `test_install_a_pinned_gem_from_rubygems_org'

  5) Error:
PluginInstallerUpdaterTests#test_update_to_specified_later_version:
Inspec::Plugin::V2::InstallError: Unable to resolve dependency: user requested 'inspec-test-fixture (= 0.2.0)'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:293:in `rescue in install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:287:in `install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:277:in `install_from_remote_gems'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:89:in `update'
    /Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:340:in `test_update_to_specified_later_version'

  6) Error:
PluginInstallerUpdaterTests#test_update_to_latest_version:
Inspec::Plugin::V2::InstallError: Unable to resolve dependency: user requested 'inspec-test-fixture (> 0)'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:293:in `rescue in install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:287:in `install_gem_to_plugins_dir'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:277:in `install_from_remote_gems'
    /Users/ryan/Work/git/chef/inspec/lib/inspec/plugin/v2/installer.rb:89:in `update'
    /Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:317:in `test_update_to_latest_version'

  7) Failure:
PluginInstallerSearchTests#test_search_for_plugin_by_wildard [/Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:488]:
Search results should have a key for at least one plugin

  8) Failure:
PluginInstallerSearchTests#test_search_omits_train_gem_on_the_reject_list [/Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:512]:
Expected false to be truthy.

  9) Failure:
PluginInstallerSearchTests#test_search_for_plugin_by_exact_name [/Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:473]:
Search results should have a key for the sought plugin

 10) Failure:
PluginInstallerSearchTests#test_search_omits_inspec_gem_on_the_reject_list [/Users/ryan/Work/git/chef/inspec/test/unit/plugin/v2/installer_test.rb:496]:
Expected false to be truthy.

29 runs, 77 assertions, 6 failures, 4 errors, 0 skips
2452 % 
```

**Comment by clintoncwolfe** [comment]
Rather than simply pasting a run trace, could you provide a description of the problem and what you expect to be different, as well as InSpec version information?  Thanks!

**Comment by clintoncwolfe** [comment]
Refs #3297

**Comment by zenspider** [comment]
Version is 4.4.0 (current master), but probably all versions.
