### ISSUE TITLE
InSpec check crashes on tarball

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#408]
```
inspec check profile.tar.gz 
/Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:30:in `initialize': Cannot find directory profile.tar.gz (RuntimeError)
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:15:in `new'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile.rb:15:in `from_path'
    from /Users/chartmann/Development/compliance/inspec/bin/inspec:151:in `check'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/chartmann/Development/compliance/inspec/bin/inspec:228:in `<top (required)>'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/inspec:23:in `load'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/inspec:23:in `<main>'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by srenatus** [comment]
Hm. `Inspec::Runner#add_tests` does use the target helpers, but all of Inspec::Profile expects to talk to files present.
