### ISSUE TITLE
inspec 4.3.2 centos 7, inspec-iggy cannot resolve

### ISSUE THREAD

**Issue by krystan** [inspec/inspec#4120]
I have tried to install inspec 4.3.2 on centos 7 and fail to get it to run

# Describe the problem

tried to run inspec profile with inspec -exec <profile>

after installing inspec via:

gem install inspec -v 4.3.2
gem install inspec-bin -v 4.3.2

received error:
ERROR could not load plugin inspec-iggy (< 4.0.0, >=2.3)

Ruby version: 2.5.1p57
RubyGem version: 2.7.7

After removing the gems and trying to install the redhat rpm I get the same error, so cleaned up and went back to using the gem.

## Possible Solution
Appears dependencies are not correctly installed, installing iggy manually doesn't help as it's tied to a previous version of inspec

**Comment by burtlo** [comment]
To add a little more to this issue with an tangentially related one:

`inspec plugin install inspec-iggy` and any other plugin tied to a previous version of InSpec, when using `InSpec 4.3.2`, raises an exception when the `net-scp` gem versions collide.

**Comment by iveskins** [comment]
Here is the error i am getting 
looks like  it wants to use net-scp-1.2.1 but  net-scp-2.0.0 is already activated

```
me@myMac ~/D/p/g/i/I/folder> inspec plugin install inspec-iggy --log-level=debug
[2019-05-22T16:41:36+09:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-supermarket': an existing plugin with that name was loaded via bundle-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/bundles/inspec-supermarket.rb
[2019-05-22T16:41:36+09:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-plugin-manager-cli': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli.rb
[2019-05-22T16:41:36+09:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-artifact': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-artifact/lib/inspec-artifact.rb
[2019-05-22T16:41:36+09:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-habitat': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-habitat/lib/inspec-habitat.rb
[2019-05-22T16:41:36+09:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-init': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-init/lib/inspec-init.rb
[2019-05-22T16:41:36+09:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-compliance': an existing plugin with that name was loaded via core-loading from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-compliance/lib/inspec-compliance.rb
Traceback (most recent call last):
	21: from /usr/local/bin/inspec:150:in `<main>'
	20: from /usr/local/bin/inspec:150:in `load'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:98:in `install'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:320:in `install_from_remote_gem'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:362:in `install_attempt_install'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:68:in `install'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:277:in `install_from_remote_gems'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:308:in `install_gem_to_plugins_dir'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:308:in `each'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:310:in `block in install_gem_to_plugins_dir'
	 1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1414:in `activate'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2292:in `check_version_conflict': can't activate net-scp-1.2.1, already activated net-scp-2.0.0 (Gem::LoadError)
	18: from /usr/local/bin/inspec:150:in `<main>'
	17: from /usr/local/bin/inspec:150:in `load'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:98:in `install'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:320:in `install_from_remote_gem'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:362:in `install_attempt_install'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:68:in `install'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:277:in `install_from_remote_gems'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:307:in `install_gem_to_plugins_dir'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.3.2/lib/inspec/plugin/v2/installer.rb:316:in `rescue in install_gem_to_plugins_dir': can't activate net-scp-1.2.1, already activated net-scp-2.0.0 (Inspec::Plugin::V2::InstallError)
me@myMac ~/D/p/g/i/I/folder> inspec -v
4.3.2
```

**Comment by zenspider** [comment]
This is a problem with `inspec-iggy`, not with `inspec`. Please file an issue on that project instead. Closing.
