### ISSUE TITLE
Add integration testing between InSpec and Train-AWS plugin

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4203]
### 🎛 Description

This is a process issue where we do not have integration testing setup between InSpec and the new Train-AWS plugin. The result is that any changes made to either Train-AWS or InSpec projects won't vet their changes with each other before being pushed out.

### 🌍 InSpec and Platform Version

All versions of InSpec; all platforms

### 🤔 Replication Case

If you run inspec exec using the train-aws plugin, it is completely broken at this point. Example error:

```
`Scotts-MBP:aws_inspec_test svidmar$ inspec exec . -t aws://
Traceback (most recent call last):
	13: from /usr/local/bin/inspec:71:in '<main>'
	12: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:67:in 'gem'
	11: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:67:in 'synchronize'
	10: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:68:in 'block in gem'
	 9: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1420:in 'activate'
	 8: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1438:in 'activate_dependencies'
	 7: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1438:in 'each'
	 6: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1452:in 'block in activate_dependencies'
	 5: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1420:in 'activate'
	 4: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1438:in 'activate_dependencies'
	 3: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1438:in 'each'
	 2: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1452:in 'block in activate_dependencies'
	 1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1418:in 'activate'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2302:in 'raise_if_conflicts': Unable to activate aws-sdk-autoscaling-1.22.0, because aws-sdk-core-3.48.6 conflicts with aws-sdk-core (~> 3, >= 3.52.1) (Gem::ConflictError)`
```

### 💁 Possible Solutions

TBD; working through that right now.

[ETA: formatting for backtrace]

**Comment by clintoncwolfe** [comment]
That stacktrace above was the result of an unsupported installation method: installing from omnibus, then performing a gem (not plugin) upgrade of a plugin. Our omnibus system promises to keep dependencies sane; the fix here was to release a fresh omnibus build on Monday, v4.6.3 . 

The larger problem was that train-aws was released with a missing dependency.
Affected versions were only inspec v 4.3.2 and train 0.1.0. I agree integration testing would help that, but it is already present - but only the Belfast team has access to running it.
