### ISSUE TITLE
File resource source_path 'undefined method `source_path`'

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4208]
```
sudo inspec exec . -t aws://
Traceback (most recent call last):
	26: from /usr/local/bin/inspec:153:in `<main>'
	25: from /usr/local/bin/inspec:153:in `load'
	24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.3/bin/inspec:11:in `<top (required)>'
	23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/cli.rb:297:in `exec'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:121:in `run'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:114:in `load'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:114:in `each'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:115:in `block in load'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:272:in `register_rule'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:272:in `flat_map'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:272:in `each'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:273:in `block in register_rule'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:261:in `get_check_example'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner.rb:287:in `rspec_failed_block'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/runner_rspec.rb:25:in `example_group'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/example_group.rb:386:in `subclass'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/example_group.rb:422:in `set_it_up'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/metadata.rb:258:in `create'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/metadata.rb:133:in `populate'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.1/lib/rspec/core/metadata.rb:180:in `build_description_from'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/resources/file.rb:167:in `to_s'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.3/lib/inspec/resources/file.rb:53:in `block (2 levels) in <class:FileResource>': undefined method `source_path' for nil:NilClass (NoMethodError)
```

**Comment by zenspider** [comment]
I'm starting to think that `@supports = Inspec::Resource.supports[name]` should have something in place for platform? or we should default to false.

**Comment by clintoncwolfe** [comment]
Could someone post an actual repro case to this issue? With a profile?
`inspec exec .` doesn't explain what is in the profile. If I run against a profile containing a `file()` resource on 4.6.3 and target aws, I get no error.

**Comment by zenspider** [comment]
@clintoncwolfe something as simple as this:

```ruby
describe file('/tmp/foo') do
  it { should exist }
end
```

either in a profile w/o any metadata about platform or just running the `.rb` file directly.

**Comment by clintoncwolfe** [comment]
Thanks - I was using the profile generated by `inspec init profile`, which includes an `os` support declaration in the metadata - hence it didn't repro for me!

**Comment by xacaxulu** [comment]
+1
