### ISSUE TITLE
InSpec plugin list returning nil class error when train-aws installed.

### ISSUE THREAD

**Issue by scottvidmar** [inspec/inspec#4248]
# Summary:
After installing the latest MacOSX 10.4 installation .dmg, I found that a profile doing a very generic scan of AWS is returning an error with train-aws installed. It looks like there's a version coming back as nil and not being handled, but it's hard to tell.

# Context and data:

```
Scotts-MacBook-Pro-2:aws_inspec_test svidmar$ inspec plugin list
 Plugin Name                   Version   Via     ApiVer
-------------------------------------------------------
Traceback (most recent call last):
    15: from /usr/local/bin/inspec:155:in `<main>'
    14: from /usr/local/bin/inspec:155:in `load'
    13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.4/bin/inspec:11:in `<top (required)>'
    12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
    11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
     9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
     8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
     7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
     6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
     5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
     4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
     3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `list'
     2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `each'
     1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:30:in `block in list'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:438:in `make_pretty_version': undefined method `version' for nil:NilClass (NoMethodError)
```

Normally, I'd expect the list of plugins to show train-aws as installed, with its version in a simple table output to the command line. 

Version, profile and control information:

```
$ inspec version; cat ../aws_inspec_test/aws_inspec_test/inspec.yml; cat ../aws_inspec_test/aws_inspec_test/controls/example.rb 
4.6.4
name: aws_inspec_test
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.1
inspec_version: '>= 2.2.7'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
  platform: aws


describe aws_cloudtrail_trails do
  its('entries.count') { should cmp 0 }
end
```

**Comment by scottvidmar** [comment]
Looks like somehow the configuration directory and where plugins are stored is not quite in lockstep?

https://github.com/inspec/inspec/blob/a0475c5069a14f39da7d2613777fc96d2563a865/lib/inspec/globals.rb#L3

This seems like a potential location of interest. Since it's using that to figure out where to look for plugins:

https://github.com/inspec/inspec/blob/a35d37043e65ce5fd528d58cd48ecb369c74a432/lib/inspec/plugin/v2/loader.rb#L125

Which references:

https://github.com/inspec/inspec/blob/a35d37043e65ce5fd528d58cd48ecb369c74a432/lib/inspec/plugin/v2/loader.rb#L125

Which, is where that references:

https://github.com/inspec/inspec/blob/a35d37043e65ce5fd528d58cd48ecb369c74a432/lib/inspec/globals.rb#L2

Testing this with a fresh setup on CentOS did not show the issue.

**Comment by scottvidmar** [comment]
Testing further, I think this is an issue with brew cask install, and the MacOSX installer. CentOS RPM based installation works fine on a CentOS machine. The customer report comes from InSpec on an Amazon Linux machine. I'll test that next.

 ```
inspec plugin list

 Plugin Name                   Version   Via     ApiVer
-------------------------------------------------------
Traceback (most recent call last):
	16: from /usr/local/bin/inspec:155:in `<main>'
	15: from /usr/local/bin/inspec:155:in `load'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.9/bin/inspec:11:in `<top (required)>'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/base_cli.rb:31:in `start'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `list'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `each'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:30:in `block in list'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:438:in `make_pretty_version': undefined method `version' for nil:NilClass (NoMethodError)
Scotts-MacBook-Pro-2:vagrant svidmar$ inspec plugin lis
Scotts-MacBook-Pro-2:vagrant svidmar$ brew cask uninstall inspec
==> Uninstalling Cask inspec
==> Uninstalling packages:
com.getchef.pkg.inspec
==> Removing files:
/opt/inspec/
==> Purging files for version 4.6.9 of Cask inspec
Scotts-MacBook-Pro-2:vagrant svidmar$ inspec plugin list
-bash: /usr/local/bin/inspec: No such file or directory
Scotts-MacBook-Pro-2:vagrant svidmar$ inspec plugin list

 Plugin Name                   Version   Via     ApiVer
-------------------------------------------------------
Traceback (most recent call last):
	15: from /usr/local/bin/inspec:155:in `<main>'
	14: from /usr/local/bin/inspec:155:in `load'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.4/bin/inspec:11:in `<top (required)>'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `list'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `each'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:30:in `block in list'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:438:in `make_pretty_version': undefined method `version' for nil:NilClass (NoMethodError)
Scotts-MacBook-Pro-2:vagrant svidmar$ brew cask uninstall inspec

```

**Comment by scottvidmar** [comment]
This happens on Amazon Linux 2, as well, with a downloaded rpm install for centos7 (not sure if that's the right one...):

```
[ec2-user@ip-10-0-0-78 ~]$ sudo inspec plugin install train-aws
+---------------------------------------------+
            Chef License Acceptance

Before you can continue, 1 product license
must be accepted. View the license at
https://www.chef.io/end-user-license-agreement/

License that need accepting:
  * Chef InSpec

Do you accept the 1 product license (yes/no)?

> yes

Persisting 1 product license...
✔ 1 product license persisted.

+---------------------------------------------+
Parsing documentation for aws-eventstream-1.0.3
Installing ri documentation for aws-eventstream-1.0.3
Parsing documentation for aws-sigv4-1.1.0
Installing ri documentation for aws-sigv4-1.1.0
Parsing documentation for aws-partitions-1.182.0
Installing ri documentation for aws-partitions-1.182.0
Parsing documentation for jmespath-1.4.0
Installing ri documentation for jmespath-1.4.0
Parsing documentation for aws-sdk-core-3.57.0
Installing ri documentation for aws-sdk-core-3.57.0
Parsing documentation for aws-sdk-sqs-1.17.0
Installing ri documentation for aws-sdk-sqs-1.17.0
Parsing documentation for aws-sdk-sns-1.17.0
Installing ri documentation for aws-sdk-sns-1.17.0
Parsing documentation for aws-sdk-kms-1.22.0
Installing ri documentation for aws-sdk-kms-1.22.0
Parsing documentation for aws-sdk-s3-1.43.0
Installing ri documentation for aws-sdk-s3-1.43.0
Parsing documentation for aws-sdk-rds-1.60.0
Installing ri documentation for aws-sdk-rds-1.60.0
Parsing documentation for aws-sdk-organizations-1.17.0
Installing ri documentation for aws-sdk-organizations-1.17.0
Parsing documentation for aws-sdk-iam-1.26.0
Installing ri documentation for aws-sdk-iam-1.26.0
Parsing documentation for aws-sdk-elasticloadbalancing-1.16.0
Installing ri documentation for aws-sdk-elasticloadbalancing-1.16.0
Parsing documentation for aws-sdk-eks-1.22.0
Installing ri documentation for aws-sdk-eks-1.22.0
Parsing documentation for aws-sdk-ecs-1.42.0
Installing ri documentation for aws-sdk-ecs-1.42.0
Parsing documentation for aws-sdk-ecr-1.18.0
Installing ri documentation for aws-sdk-ecr-1.18.0
Parsing documentation for aws-sdk-ec2-1.97.0
Installing ri documentation for aws-sdk-ec2-1.97.0
^[[DParsing documentation for aws-sdk-dynamodb-1.32.0
Installing ri documentation for aws-sdk-dynamodb-1.32.0
Parsing documentation for aws-sdk-costandusagereportservice-1.14.0
Installing ri documentation for aws-sdk-costandusagereportservice-1.14.0
Parsing documentation for aws-sdk-configservice-1.31.0
Installing ri documentation for aws-sdk-configservice-1.31.0
Parsing documentation for aws-sdk-cloudwatchlogs-1.22.0
Installing ri documentation for aws-sdk-cloudwatchlogs-1.22.0
Parsing documentation for aws-sdk-cloudwatch-1.24.0
Installing ri documentation for aws-sdk-cloudwatch-1.24.0
Parsing documentation for aws-sdk-cloudtrail-1.15.0
Installing ri documentation for aws-sdk-cloudtrail-1.15.0
Parsing documentation for aws-sdk-autoscaling-1.22.0
Installing ri documentation for aws-sdk-autoscaling-1.22.0
Parsing documentation for inifile-3.0.0
Installing ri documentation for inifile-3.0.0
Parsing documentation for jwt-2.2.1
Installing ri documentation for jwt-2.2.1
Parsing documentation for multi_json-1.13.1
Installing ri documentation for multi_json-1.13.1
Parsing documentation for multipart-post-2.1.1
Installing ri documentation for multipart-post-2.1.1
Parsing documentation for faraday-0.15.4
Installing ri documentation for faraday-0.15.4
Parsing documentation for public_suffix-3.1.1
Installing ri documentation for public_suffix-3.1.1
Parsing documentation for addressable-2.6.0
Installing ri documentation for addressable-2.6.0
Parsing documentation for signet-0.11.0
Installing ri documentation for signet-0.11.0
Parsing documentation for os-1.0.1
Installing ri documentation for os-1.0.1
Parsing documentation for memoist-0.16.0
Installing ri documentation for memoist-0.16.0
Parsing documentation for googleauth-0.6.7
Installing ri documentation for googleauth-0.6.7
Parsing documentation for httpclient-2.8.3
Installing ri documentation for httpclient-2.8.3
Parsing documentation for mime-types-data-3.2019.0331
Installing ri documentation for mime-types-data-3.2019.0331
Parsing documentation for mime-types-3.2.2
Installing ri documentation for mime-types-3.2.2
Parsing documentation for retriable-3.1.2
Installing ri documentation for retriable-3.1.2
Parsing documentation for declarative-option-0.1.0
Installing ri documentation for declarative-option-0.1.0
Parsing documentation for declarative-0.0.10
Installing ri documentation for declarative-0.0.10
Parsing documentation for uber-0.1.0
Installing ri documentation for uber-0.1.0
Parsing documentation for representable-3.0.4
Installing ri documentation for representable-3.0.4
Parsing documentation for google-api-client-0.23.9
Installing ri documentation for google-api-client-0.23.9
Parsing documentation for concurrent-ruby-1.1.5
Installing ri documentation for concurrent-ruby-1.1.5
Parsing documentation for timeliness-0.3.10
Installing ri documentation for timeliness-0.3.10
Parsing documentation for ms_rest-0.7.4
Installing ri documentation for ms_rest-0.7.4
Parsing documentation for unf_ext-0.0.7.2
Installing ri documentation for unf_ext-0.0.7.2
Parsing documentation for unf-0.1.4
Installing ri documentation for unf-0.1.4
Parsing documentation for domain_name-0.5.20180417
Installing ri documentation for domain_name-0.5.20180417
Parsing documentation for http-cookie-1.0.3
Installing ri documentation for http-cookie-1.0.3
Parsing documentation for faraday-cookie_jar-0.0.6
Installing ri documentation for faraday-cookie_jar-0.0.6
Parsing documentation for ms_rest_azure-0.11.1
Installing ri documentation for ms_rest_azure-0.11.1
Parsing documentation for azure_mgmt_key_vault-0.17.4
Installing ri documentation for azure_mgmt_key_vault-0.17.4
Parsing documentation for azure_graph_rbac-0.17.1
Installing ri documentation for azure_graph_rbac-0.17.1
Parsing documentation for azure_mgmt_resources-0.17.5
Installing ri documentation for azure_mgmt_resources-0.17.5
Parsing documentation for excon-0.64.0
Installing ri documentation for excon-0.64.0
Parsing documentation for docker-api-1.34.2
Installing ri documentation for docker-api-1.34.2
Parsing documentation for rubyntlm-0.6.2
Installing ri documentation for rubyntlm-0.6.2
Parsing documentation for nori-2.6.0
Installing ri documentation for nori-2.6.0
Parsing documentation for little-plugger-1.1.4
Installing ri documentation for little-plugger-1.1.4
Parsing documentation for logging-2.2.2
Installing ri documentation for logging-2.2.2
Parsing documentation for builder-3.2.3
Installing ri documentation for builder-3.2.3
Parsing documentation for gyoku-1.3.1
Installing ri documentation for gyoku-1.3.1
Parsing documentation for ffi-1.11.1
Installing ri documentation for ffi-1.11.1
Parsing documentation for gssapi-1.3.0
Installing ri documentation for gssapi-1.3.0
Parsing documentation for erubis-2.7.0
Installing ri documentation for erubis-2.7.0
Parsing documentation for winrm-2.3.2
Installing ri documentation for winrm-2.3.2
Parsing documentation for rubyzip-1.2.3
Installing ri documentation for rubyzip-1.2.3
Parsing documentation for winrm-fs-1.3.2
Installing ri documentation for winrm-fs-1.3.2
Parsing documentation for net-ssh-4.2.0
Installing ri documentation for net-ssh-4.2.0
Parsing documentation for net-scp-2.0.0
Installing ri documentation for net-scp-2.0.0
Parsing documentation for mixlib-shellout-2.4.4
Installing ri documentation for mixlib-shellout-2.4.4
Parsing documentation for json-2.2.0
Installing ri documentation for json-2.2.0
Parsing documentation for train-2.1.13
Installing ri documentation for train-2.1.13
Parsing documentation for train-aws-0.1.5
Installing ri documentation for train-aws-0.1.5
Done installing documentation for aws-eventstream, aws-sigv4, aws-partitions, jmespath, aws-sdk-core, aws-sdk-sqs, aws-sdk-sns, aws-sdk-kms, aws-sdk-s3, aws-sdk-rds, aws-sdk-organizations, aws-sdk-iam, aws-sdk-elasticloadbalancing, aws-sdk-eks, aws-sdk-ecs, aws-sdk-ecr, aws-sdk-ec2, aws-sdk-dynamodb, aws-sdk-costandusagereportservice, aws-sdk-configservice, aws-sdk-cloudwatchlogs, aws-sdk-cloudwatch, aws-sdk-cloudtrail, aws-sdk-autoscaling, inifile, jwt, multi_json, multipart-post, faraday, public_suffix, addressable, signet, os, memoist, googleauth, httpclient, mime-types-data, mime-types, retriable, declarative-option, declarative, uber, representable, google-api-client, concurrent-ruby, timeliness, ms_rest, unf_ext, unf, domain_name, http-cookie, faraday-cookie_jar, ms_rest_azure, azure_mgmt_key_vault, azure_graph_rbac, azure_mgmt_resources, excon, docker-api, rubyntlm, nori, little-plugger, logging, builder, gyoku, ffi, gssapi, erubis, winrm, rubyzip, winrm-fs, net-ssh, net-scp, mixlib-shellout, json, train, train-aws after 243 seconds
train-aws plugin, version , installed from rubygems.org
[ec2-user@ip-10-0-0-78 ~]$ inspec plugin list

 Plugin Name                   Version   Via     ApiVer
-------------------------------------------------------
-------------------------------------------------------
 0 plugin(s) total

[ec2-user@ip-10-0-0-78 ~]$ sudo inspec plugin list

 Plugin Name                   Version   Via     ApiVer
-------------------------------------------------------
Traceback (most recent call last):
	16: from /bin/inspec:155:in `<main>'
	15: from /bin/inspec:155:in `load'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.9/bin/inspec:11:in `<top (required)>'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/base_cli.rb:31:in `start'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `list'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:29:in `each'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:30:in `block in list'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:438:in `make_pretty_version': undefined method `version' for nil:NilClass (NoMethodError)
[ec2-user@ip-10-0-0-78 ~]$ uname -a
Linux ip-10-0-0-78.us-west-2.compute.internal 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by clintoncwolfe** [comment]
Just FYI - and perhaps you're aware of this angle - there is a bad UX experience lurking here. InSpec **always** ships with train-aws installed as a "system plugin" (that is, the train-aws gem is a dependency of the inspec gem and is thus installed as part of the omnibus or gem installs - so you already have it) but `inspec plugin ...` only manages user-installed plugins. Refs #4277

**Comment by clintoncwolfe** [comment]
To be clear on the reproduction steps, this is:
1. Start with a clean system, one of the affected OSes
2. Perform an omnibus install of inspec 4.6.4
3. Run `sudo inspec plugin install train-aws` (which will cause license acceptance on the first execution) (* see below)
4. Run `inspec plugin list` and *see a stacktrace*

Is that correct?

* If you don't run with sudo, it will fail when trying to write docs under `/opt`; but it shouldn't be doing that anyway, see #3799. Running under `sudo` is not the intended use of `inspec plugin install` - it expects to be running as a regular user.

**Comment by kekaichinose** [comment]
@scottvidmar do you have an updated stack trace for us to look at, per @clintoncwolfe's ask?
