### ISSUE TITLE
LoadError with AWS Resource Pack

### ISSUE THREAD

**Issue by drmmarsunited** [inspec/inspec#4268]
Deprecation warnings received when using AWS resources in my profile while just using Inspec core.  However, if I create a dependency as described in the documentation, I encounter a LoadError from Inspec against an AWS SDK.

# Describe the problem
When creating a new profile with v4.6.9 for testing AWS resources (just using core Inspec), I am met with the following deprecation warning:

`[2019-07-05T20:58:22-05:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_security_group' (used at launchpad-severe/controls/restricted_global_ports.rb:16)`

If I update my inspec.yml file to create a dependency as described on the [inspec-aws repo readme](https://github.com/inspec/inspec-aws) and re-vendor the profile, I am now met with the following erro (w/ stack trace):

``` 
$ inspec exec launchpad-severe -t aws://

Traceback (most recent call last):
        30: from /usr/local/bin/inspec:155:in `<main>'
        29: from /usr/local/bin/inspec:155:in `load'
        28: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.9/bin/inspec:11:in `<top (required)>'
        27: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/base_cli.rb:31:in `start'
        26: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        25: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/cli.rb:297:in `exec'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:121:in `run'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:93:in `load'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:93:in `each'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:99:in `block in load'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `load_libraries'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `each_with_index'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `each'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:248:in `block in load_libraries'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:256:in `load_libraries'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:134:in `load_libraries'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:134:in `each'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:136:in `block in load_libraries'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:149:in `load_library_file'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:160:in `load_with_context'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:160:in `instance_eval'
         6: from libraries/aws_alb.rb:3:in `load_with_context'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:26:in `require'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:26:in `eval'
         3: from libraries/aws_backend.rb:4:in `create'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:13:in `require'
         1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk-cloudformation (LoadError)
```

I'm far from being an expert in Ruby, so I'm not sure where I've gone wrong here.  Can't find a whole lot of direction from trying to search down an answer.  I'm sure there is just something super stupid I'm missing here, but would appreciate an assist.

Thanks!

**Comment by drmmarsunited** [comment]
Relevant snippet from inspec.yml file:

```
supports:
  - platform: aws
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
```

Same error exists if I attempt to use the Git repo:

```
supports:
  - platform: aws
depends:
  - name: inspec-aws
    git: git@github.com:inspec/inspec-aws.git
```

**Comment by rmoles** [comment]
Hi, @drmmarsunited thanks for raising this issue.
We are aware of this issue and have recently updated the dependencies within `train-aws`, see: https://github.com/inspec/train-aws/pull/17/files#diff-3f46477e9114fd86ba45806d676a8c7aR65
We are working to release a new train gem very soon.

In the meantime, it is possible for you to pull in the newest dependencies by adding this to your Gemfile.
```
gem 'train-aws', :git => 'https://github.com/inspec/train-aws.git', :branch => 'master'
```
I hope this helps.

**Comment by drmmarsunited** [comment]
Cheers!

**Comment by clintoncwolfe** [comment]
Duplicate with #4278

**Comment by pburkholder** [comment]
I get the same deprecation warnings -- how do I make them stop?

I've tried latest inspec in both Docker and Mac HomeBrew, version `4.18.108`

My inspec.yml is:

```
name: MFA
title: Test AWS MVA
version: 0.1.0
license: CC0
summary: Demonstrates the use of an InSpec Compliance Profile on AWS
supports:
  - platform: aws
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
```

But I keep getting:

```
inspec exec -t aws:// inspec-aws-mfa/ --controls /1.3/
[2020-04-30T14:21:57-04:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_iam_user' (used at inspec-aws-mfa/controls/mfa.rb:55)
[2020-04-30T14:21:58-04:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_iam_user' (used at inspec-aws-mfa/controls/mfa.rb:55)
[2020-04-30T14:21:59-04:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_iam_group' (used at inspec-aws-mfa/controls/mfa.rb:75)
```

Can you help make it stop? The error message is not going to inspire confidence when I demonstrate this to skeptical assessors. 

Thanks!

**Comment by Schwad** [comment]
Hi @pburkholder , as this original issue seems to be related to something I think has been resolved ( per @rmoles ' comment), would you be willing to file a separate issue for this so we don't lose track of it? It's easy for comments on closed issues to get lost in the fold. Thanks!
