### ISSUE TITLE
InSpec 4.6.9 - cannot load such file -- aws-sdk-cloudformation

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#4278]
# Using
- InSpec 4.6.9

# Describe the problem
added a basic check `aws_vpc`

```
describe aws_vpc do
    it { should exist }
end
```
`inspec.yml`

```
name: aws-summit
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
  platform: aws
```

# Debug 
```
[2019-07-09T21:07:57+02:00] DEBUG: Option backend_cache is enabled
[2019-07-09T21:07:57+02:00] DEBUG: Resolve aws-summit into cache /Users/kmf/.inspec/cache
[2019-07-09T21:07:57+02:00] DEBUG: Dependency does not exist in the cache aws-summit
[2019-07-09T21:07:57+02:00] DEBUG: Starting run with targets: ["Inspec::Profile<aws-summit>"]
[2019-07-09T21:07:57+02:00] DEBUG: Creating lockfile: aws-summit/inspec.lock
[2019-07-09T21:07:57+02:00] DEBUG: Starting traversal of dependencies ["inspec-aws"]
[2019-07-09T21:07:57+02:00] DEBUG: Fetching URL: https://github.com/inspec/inspec-aws/archive/master.tar.gz
[2019-07-09T21:08:00+02:00] DEBUG: Archive stored at temporary location: /var/folders/_3/yr1wpz2960b6cx0q218h0q2r0000gn/T/inspec-dl-20190709-45373-aro2dr.tar.gz
[2019-07-09T21:08:00+02:00] DEBUG: Using cached dependency for {:cwd=>"aws-summit", :backend=>Inspec::Backend::Class @transport=TrainPlugins::Aws::Connection, :name=>"inspec-aws", :url=>"https://github.com/inspec/inspec-aws/archive/master.tar.gz"}
[2019-07-09T21:08:00+02:00] DEBUG: Adding dependency inspec-aws ({:url=>"https://github.com/inspec/inspec-aws/archive/master.tar.gz", :sha256=>"5e70c21d93812fe2d7f61160332596ed58299a8b4790db2f3960b99a82350ebf"})
[2019-07-09T21:08:00+02:00] DEBUG: Using cached dependency for {:cwd=>"aws-summit", :backend=>Inspec::Backend::Class @transport=TrainPlugins::Aws::Connection, :name=>"inspec-aws", :url=>"https://github.com/inspec/inspec-aws/archive/master.tar.gz"}
[2019-07-09T21:08:01+02:00] DEBUG: Dependency traversal complete.
[2019-07-09T21:08:01+02:00] DEBUG: Starting traversal of dependencies ["inspec-aws"]
[2019-07-09T21:08:01+02:00] DEBUG: Fetching URL: https://github.com/inspec/inspec-aws/archive/master.tar.gz
[2019-07-09T21:08:04+02:00] DEBUG: Archive stored at temporary location: /var/folders/_3/yr1wpz2960b6cx0q218h0q2r0000gn/T/inspec-dl-20190709-45373-18dsll3.tar.gz
[2019-07-09T21:08:04+02:00] DEBUG: Using cached dependency for {:cwd=>"aws-summit", :backend=>Inspec::Backend::Class @transport=TrainPlugins::Aws::Connection, :name=>"inspec-aws", :url=>"https://github.com/inspec/inspec-aws/archive/master.tar.gz"}
[2019-07-09T21:08:04+02:00] DEBUG: Adding dependency inspec-aws ({:url=>"https://github.com/inspec/inspec-aws/archive/master.tar.gz", :sha256=>"5e70c21d93812fe2d7f61160332596ed58299a8b4790db2f3960b99a82350ebf"})
[2019-07-09T21:08:04+02:00] DEBUG: Using cached dependency for {:cwd=>"aws-summit", :backend=>Inspec::Backend::Class @transport=TrainPlugins::Aws::Connection, :name=>"inspec-aws", :url=>"https://github.com/inspec/inspec-aws/archive/master.tar.gz"}
[2019-07-09T21:08:05+02:00] DEBUG: Dependency traversal complete.
[2019-07-09T21:08:05+02:00] DEBUG: Using cached dependency for {:url=>"https://github.com/inspec/inspec-aws/archive/master.tar.gz", :sha256=>"5e70c21d93812fe2d7f61160332596ed58299a8b4790db2f3960b99a82350ebf", :backend=>Inspec::Backend::Class @transport=TrainPlugins::Aws::Connection, :inputs=>nil}
[2019-07-09T21:08:05+02:00] DEBUG: Loading libraries/aws_alb.rb into #<Inspec::ProfileContext:0x00007fcaf2a4bae0>
Traceback (most recent call last):
	30: from /usr/local/bin/inspec:155:in `<main>'
	29: from /usr/local/bin/inspec:155:in `load'
	28: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.9/bin/inspec:11:in `<top (required)>'
	27: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/base_cli.rb:31:in `start'
	26: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	25: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/cli.rb:297:in `exec'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:121:in `run'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:93:in `load'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:93:in `each'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/runner.rb:99:in `block in load'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `load_libraries'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `each_with_index'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:233:in `each'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:248:in `block in load_libraries'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile.rb:256:in `load_libraries'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:134:in `load_libraries'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:134:in `each'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:136:in `block in load_libraries'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:149:in `load_library_file'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:160:in `load_with_context'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/profile_context.rb:160:in `instance_eval'
	 6: from libraries/aws_alb.rb:3:in `load_with_context'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:26:in `require'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:26:in `eval'
	 3: from libraries/aws_backend.rb:4:in `create'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.9/lib/inspec/dsl_shared.rb:13:in `require'
	 1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk-cloudformation (LoadError)
```

**Comment by kmf** [comment]
added a work around to `inspec.yml`
```
name: aws-summit
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/inspec-4.6.9.tar.gz
supports:
  platform: aws
```

Hard coded version 
```
   url: https://github.com/inspec/inspec-aws/archive/inspec-4.6.9.tar.gz
```

**Comment by clintoncwolfe** [comment]
Hi! Let us know how the profile-pinning workaround works for you - long term, that may be how semver is implemented for profiles. In the meantime, train-aws 0.1.7 has been released, which includes the fixes needed; now we just need to release a new InSpec with train-aws 0.1.7 included, which we are working right now.

**Comment by clintoncwolfe** [comment]
InSpec 4.7.3 was released yesterday evening, which contains a fix for this and also several future AWS SDK dependencies. Please verify 4.7.3 works for you! 

Thanks!

**Comment by kmf** [comment]
It's working great.

**Comment by clintoncwolfe** [comment]
Great - I'm going to go ahead and close this, then.
