### ISSUE TITLE
Simplify error output

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#437]
```
$ inspec exec examples/profile/controls/example.rb
.F

Failures:

  1) File /tmp should not be directory
     Failure/Error: with.run_specs(tests)
       expected `File /tmp.directory?` to return false, got true
     # examples/profile/controls/example.rb:19:in `block (2 levels) in load'
     # ./lib/inspec/runner_rspec.rb:55:in `run'
     # ./lib/utils/base_cli.rb:52:in `run_tests'

Finished in 0.01847 seconds (files took 0.46605 seconds to load)
2 examples, 1 failure

Failed examples:

rspec  # File /tmp should not be directory
```

**Comment by vjeffrey** [comment]
@chris-rock, got any other examples of running into this?  i'm trying to reproduce, but this is what i'm getting:
![screen shot 2016-09-26 at 1 01 13 pm](https://cloud.githubusercontent.com/assets/10341541/18844003/6cccc786-83e9-11e6-8ca8-c5172879c58f.png)

**Comment by arlimus** [comment]
The new formatters create nice output, thank you for checking @vjeffrey
