### ISSUE TITLE
inspec detect ignores --sudo parameter

### ISSUE THREAD

**Issue by donvipre** [inspec/inspec#4384]
The inspec detect -t ssh://user@somehost does not properly run detect commands with "sudo" when using the parameter "--sudo"

# inspec detect does not respect "--sudo" parameter

target host shell needs sudo as prefix to any command issued on that host.
starting
```
inspec detect -t ssh://user@somehost
Traceback (most recent call last):
        20: from /usr/bin/inspec:123:in `<main>'
        19: from /usr/bin/inspec:123:in `load'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/bin/inspec:12:in `<top (required)>'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/cli.rb:279:in `detect'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/cli.rb:367:in `run_command'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/cli.rb:367:in `new'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/runner.rb:64:in `initialize'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/runner.rb:72:in `configure_transport'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/backend.rb:52:in `create'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/transports/ssh.rb:81:in `connection'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/transports/ssh.rb:208:in `create_new_connection'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/transports/ssh.rb:208:in `new'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/transports/ssh_connection.rb:53:in `initialize'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/extras/command_wrapper.rb:128:in `load'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/plugins/base_connection.rb:110:in `platform'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/platforms/detect.rb:9:in `scan'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.6/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```
target host is SUSE SLES 12 SP2 LTSS and when doing this as root user it properly detects as such. However it is required that inspec respects to login as normal user and use sudo to do its tasks. This does work, but not for the commands provided within detect.
As detect fails, it is not able to apply service or package resources to this system, as the os.family is unknown and results in a stack trace.

## Possible Solution

```inspec detect``` for remote targets should respect the --sudo parameter correctly to also apply sudo prefix to all OS commands used within the detect option.

**Comment by zenspider** [comment]
This has been addressed via inspec/train#544.
