### ISSUE TITLE
Unstable tests

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4423]
```
./misc/run_buildkite.sh -n "/^(?:Inspec::Resources::Package#(?:test_0012_returns \\{\\} when .brew. exits non-zero)|Inspec::Plugins::Resource::supported platform#(?:test_0002_loads a profile which supports multiple names)|Inspec::ProfileContext::its default DSL::global only_if#(?:test_0004_alters controls when positive|test_0005_alters non-controls when positive|test_0008_doesnt overwrite falsy only_ifs|test_0009_doesnt overwrite falsy only_ifs|test_0010_allows specifying a message with true only_if)|Inspec::ProfileContext::rule DSL::with only_if#(?:test_0002_skips with only_if == false|test_0004_doesnt overwrite falsy only_ifs|test_0005_doesnt overwrite falsy only_ifs)|Inspec::Resources::Group#(?:test_0006_actually verifies group on mac))$/" --seed 58304
Run options: -n "/^(?:Inspec::Resources::Package#(?:test_0012_returns \\{\\} when .brew. exits non-zero)|Inspec::Plugins::Resource::supported platform#(?:test_0002_loads a profile which supports multiple names)|Inspec::ProfileContext::its default DSL::global only_if#(?:test_0004_alters controls when positive|test_0005_alters non-controls when positive|test_0008_doesnt overwrite falsy only_ifs|test_0009_doesnt overwrite falsy only_ifs|test_0010_allows specifying a message with true only_if)|Inspec::ProfileContext::rule DSL::with only_if#(?:test_0002_skips with only_if == false|test_0004_doesnt overwrite falsy only_ifs|test_0005_doesnt overwrite falsy only_ifs)|Inspec::Resources::Group#(?:test_0006_actually verifies group on mac))$/" --seed 58304

# Running:

.......E...

Fabulous run in 1.417869s, 7.7581 runs/s, 25.3902 assertions/s.

  1) Error:
Inspec::Resources::Group#test_0006_actually verifies group on mac:
ArgumentError: Unsupported resource/backend combination: os / mac_os_x. Exiting.
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/plugin/v1/plugin_types/resource.rb:99:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/backend.rb:89:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/backend.rb:89:in `block (3 levels) in create'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/resources/groups.rb:100:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/plugin/v1/plugin_types/resource.rb:104:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/resource.rb:50:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/resource.rb:50:in `block (3 levels) in create_dsl'
    /Users/ryan/Work/git/inspec/inspec/test/unit/resources/group_test.rb:54:in `block (3 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:157:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:157:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:145:in `load_control_file'
    /Users/ryan/Work/git/inspec/inspec/test/unit/resources/group_test.rb:49:in `unmock'
    /Users/ryan/Work/git/inspec/inspec/test/unit/resources/group_test.rb:54:in `block (2 levels) in <top (required)>'

11 runs, 36 assertions, 0 failures, 1 errors, 0 skips
10025 % ./misc/run_buildkite.sh -n "/Inspec::Resources::Group#(?:test_0006_actually verifies group on mac)/" --seed 58304
Run options: -n "/Inspec::Resources::Group#(?:test_0006_actually verifies group on mac)/" --seed 58304

# Running:

.

Fabulous run in 0.562024s, 1.7793 runs/s, 8.8964 assertions/s.

1 runs, 5 assertions, 0 failures, 0 errors, 0 skips
```

This is causing sporadic failures on BK

**Comment by zenspider** [comment]
Nope! Got it down further:

```
./misc/run_buildkite.sh -n "/Inspec::Plugins::Resource::supported platform#test_0002_loads a profile which supports multiple names|Inspec::Resources::Group#test_0006_actually verifies group on mac/" --seed 58304
Run options: -n "/Inspec::Plugins::Resource::supported platform#test_0002_loads a profile which supports multiple names|Inspec::Resources::Group#test_0006_actually verifies group on mac/" --seed 58304

# Running:

.E

Fabulous run in 0.435920s, 4.5880 runs/s, 2.2940 assertions/s.

  1) Error:
Inspec::Resources::Group#test_0006_actually verifies group on mac:
ArgumentError: Unsupported resource/backend combination: os / mac_os_x. Exiting.
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/plugin/v1/plugin_types/resource.rb:99:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/backend.rb:89:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/backend.rb:89:in `block (3 levels) in create'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/resources/groups.rb:100:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/plugin/v1/plugin_types/resource.rb:104:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/resource.rb:50:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/resource.rb:50:in `block (3 levels) in create_dsl'
    /Users/ryan/Work/git/inspec/inspec/test/unit/resources/group_test.rb:54:in `block (3 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:157:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:157:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:145:in `load_control_file'
    /Users/ryan/Work/git/inspec/inspec/test/unit/resources/group_test.rb:49:in `unmock'
    /Users/ryan/Work/git/inspec/inspec/test/unit/resources/group_test.rb:54:in `block (2 levels) in <top (required)>'

2 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by clintoncwolfe** [comment]
We haven't seen this instability in the last year, closing
