### ISSUE TITLE
Can't debug with pry in some areas

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4450]
After putting pry in lib/fetchers/local.rb at the top of `fetch`:

```
10033 % ./misc/run.sh exec --log-level=debug --reporter=json -- wtf-0.1.0.tar.gz
[2019-09-05T13:43:51-07:00] DEBUG: Option backend_cache is enabled
[2019-09-05T13:43:51-07:00] DEBUG: Resolve wtf-0.1.0.tar.gz into cache /Users/ryan/.inspec/cache
[2019-09-05T13:43:51-07:00] DEBUG: Dependency does not exist in the cache wtf-0.1.0.tar.gz
before_session hook failed: ArgumentError: wrong number of arguments (given 0, expected 1)
/Users/ryan/Work/git/inspec/inspec/lib/inspec/plugin/v1/registry.rb:45:in `name'
(see _pry_.hooks.errors to debug)
>>> whereami
ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/ryan/Work/git/inspec/inspec/lib/inspec/plugin/v1/registry.rb:45:in `name'
```

**Comment by james-stocks** [comment]
In https://github.com/inspec/inspec/issues/3055 I pondered if `name` should be renamed to `register`
