### ISSUE TITLE
Symbol conversion errors with certain resources

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4474]
# Describe the problem
Not sure how widespread this is, but you can get a stacktrace if you run this valid InSpec code:

```
describe sys_info do
  its("manufacturer") { should cmp "Apple, Inc." }
end
```

Running that under `inspec shell` or `inspec exec` both result in conversion errors, with slightly different stacktraces.

Shell:
```
inspec> describe sys_info do
inspec>   its('manufacturer') { should cmp 'foo' }
inspec> end
after_eval hook failed: TypeError: no implicit conversion of Symbol into String
/Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:850:in `+'
(see _pry_.hooks.errors to debug)
inspec> sys_info.manufacturer
=> "Apple Inc."
inspec> Inspec::VERSION
=> "4.16.10"
```

Exec:
```
[cwolfe@lodi inspec-review]$ be inspec exec try.rb
bundler: failed to load command: inspec (/Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/inspec)
TypeError: no implicit conversion of Symbol into String
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:850:in `+'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:850:in `base_name_for'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:827:in `assign_const'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:431:in `set_it_up'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:386:in `subclass'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner_rspec.rb:25:in `example_group'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:308:in `add_resource'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:274:in `get_check_example'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:282:in `block in register_rule'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:281:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:281:in `flat_map'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:281:in `register_rule'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:121:in `block in load'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:120:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:120:in `load'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/runner.rb:127:in `run'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/cli.rb:286:in `exec'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-review/lib/inspec/base_cli.rb:33:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-review/inspec-bin/bin/inspec:11:in `<top (required)>'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/inspec:23:in `load'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/inspec:23:in `<top (required)>'
```

**Comment by clintoncwolfe** [comment]
OK, traced to a missing `to_s` definition, which was easy to add.  In lib/inspec/resources, these also don't have to_s:

```
[cwolfe@lodi resources]$ grep -L to_s *.rb
aide_conf.rb               # Fix needed, added to_s
docker_object.rb           # Utility class
etc_fstab.rb               # Fix needed, added to_s
etc_hosts.rb               # Fix needed, added to_s
firewalld.rb               # Fix needed, added to_s
postfix_conf.rb            # Fix needed, added to_s
script.rb                  # just an alias
security_identifier.rb     # Fix needed, added to_s
user.rb                    # just an alias
```
