### ISSUE TITLE
Missing require for Psych reader

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4477]
# Describe the problem

If you run:
```
bundle exec inspec shell -c "describe(security_identifier(group: 'foo') { it { should exist } } "
```

(on inspec 4.16)

you get:

```
bundler: failed to load command: inspec (/Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/inspec)
NameError: uninitialized constant SourceReaders::InspecReader::Psych
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/source_readers/inspec.rb:37:in `rescue in load_metadata'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/source_readers/inspec.rb:31:in `load_metadata'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/source_readers/inspec.rb:23:in `initialize'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/source_readers/inspec.rb:10:in `new'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/source_readers/inspec.rb:10:in `resolve'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/plugin/v1/registry.rb:14:in `block in resolve'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/plugin/v1/registry.rb:13:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/plugin/v1/registry.rb:13:in `resolve'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/source_reader.rb:10:in `resolve'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:55:in `for_path'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:67:in `for_fetcher'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:73:in `for_target'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:190:in `add_target'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:230:in `eval_with_virtual_profile'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/cli.rb:391:in `run_command'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/cli.rb:339:in `shell_func'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/base_cli.rb:33:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-incident/inspec-bin/bin/inspec:11:in `<top (required)>'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/inspec:23:in `load'
  /Users/cwolfe/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/inspec:23:in `<top (required)>'
```

**Comment by clintoncwolfe** [comment]
Oddly, I think this was a red herring; I can't repro this. CLosing.
