### ISSUE TITLE
Unknown random failure on inspec_vendor_test.rb

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4503]
```

# test/functional/inspec_vendor_test.rb:
--
  | Run options: --seed 38491
  |  
  | # Running:
  |  
  | .....F......
  |  
  | Finished in 20.673943s, 0.5804 runs/s, 3.8212 assertions/s.
  |  
  | 1) Failure:
  | example inheritance profile#test_0008_use lockfile in tarball [test/functional/inspec_vendor_test.rb:170]:
  | expected | 0s
  | actual | 1s
  | @@ -1 +1,29 @@
  | -""
  | +"/usr/local/lib/ruby/2.6.0/fileutils.rb:529:in `rename': No such file or directory @ rb_file_s_rename - (/tmp/inspec-dl-20190918-3994-az79lp.tar.gz, /tmp/d20190918-3758-1mt3jw7/old-examples/meta-profile/vendor/cf43acbe903f9fff832e0a1cb62ac5db19f2d92586c4eb9871e323207d673b35.tar.gz) (Errno::ENOENT)
  | +\tfrom /usr/local/lib/ruby/2.6.0/fileutils.rb:529:in `block in mv'
  | +\tfrom /usr/local/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
  | +\tfrom /usr/local/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
  | +\tfrom /usr/local/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
  | +\tfrom /usr/local/lib/ruby/2.6.0/fileutils.rb:520:in `mv'
  | +\tfrom /workdir/lib/fetchers/url.rb:223:in `download_archive'
  | +\tfrom /workdir/lib/fetchers/url.rb:106:in `fetch'
  | +\tfrom /workdir/lib/inspec/cached_fetcher.rb:43:in `fetch'
  | +\tfrom /workdir/lib/inspec/profile.rb:66:in `for_fetcher'
  | +\tfrom /workdir/lib/inspec/dependencies/requirement.rb:127:in `profile'
  | +\tfrom /workdir/lib/inspec/dependencies/requirement.rb:61:in `name'
  | +\tfrom /workdir/lib/inspec/dependencies/requirement.rb:112:in `to_s'
  | +\tfrom /workdir/lib/inspec/dependencies/resolver.rb:53:in `map'
  | +\tfrom /workdir/lib/inspec/dependencies/resolver.rb:53:in `resolve'
  | +\tfrom /workdir/lib/inspec/dependencies/resolver.rb:30:in `resolve'
  | +\tfrom /workdir/lib/inspec/dependencies/dependency_set.rb:90:in `vendor'
  | +\tfrom /workdir/lib/inspec/profile.rb:537:in `generate_lockfile'
  | +\tfrom /workdir/lib/inspec/profile_vendor.rb:56:in `vendor_dependencies'
  | +\tfrom /workdir/lib/inspec/profile_vendor.rb:13:in `vendor!'
  | +\tfrom /workdir/lib/inspec/base_cli.rb:281:in `vendor_deps'
  | +\tfrom /workdir/lib/inspec/cli.rb:188:in `archive'
  | +\tfrom /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  | +\tfrom /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  | +\tfrom /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  | +\tfrom /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  | +\tfrom /workdir/lib/inspec/base_cli.rb:33:in `start'
  | +\tfrom /workdir/inspec-bin/bin/inspec:11:in `<main>'
  | +"

```

**Comment by clintoncwolfe** [comment]
This has not been seen recently.
