### ISSUE TITLE
Inspec upload of wrapper profile fails

### ISSUE THREAD

**Issue by sanchihb** [inspec/inspec#4510]
Inspec upload of wrapper profile fails while loading the dependent profiles controls

I am new to Inspec. I want to create and upload an example of wrapper inspec over ther cis-rhel7-level2-server. Locally executing the server works like charm. But when I try to upload the profile to the automate server, it fails. These are the following steps are followed:
1. inspec login automate server -> successful
2. inspec vendor <profile> -> successful
3. inspec archive <profile> -> successful, loaded all the 223 controls from the dependent profile
4. inspec upload <profile> -> failure with the below error:

```
[2019-09-24T04:58:56+00:00] WARN: DEPRECATION: The 'default' option for attributes is being replaced by 'value' - please use it instead. attribute name: 'Inspec::Input' (used at /root/.inspec/cache/2df62d453bff88521be93370dfa2d5e7c06f19ed212ca801b0ce0f4a1404dce0/controls/translated-controls.rb:3)
[2019-09-24T04:58:56+00:00] WARN: Input  created using both :default and :value options - ignoring :default
[2019-09-24T04:58:56+00:00] WARN: DEPRECATION: The 'default' option for attributes is being replaced by 'value' - please use it instead. attribute name: 'Inspec::Input' (used at /root/.inspec/cache/2df62d453bff88521be93370dfa2d5e7c06f19ed212ca801b0ce0f4a1404dce0/controls/translated-controls.rb:10)
[2019-09-24T04:58:56+00:00] WARN: Input  created using both :default and :value options - ignoring :default
[2019-09-24T04:58:56+00:00] WARN: DEPRECATION: The 'default' option for attributes is being replaced by 'value' - please use it instead. attribute name: 'Inspec::Input' (used at /root/.inspec/cache/2df62d453bff88521be93370dfa2d5e7c06f19ed212ca801b0ce0f4a1404dce0/controls/translated-controls.rb:17)
[2019-09-24T04:58:56+00:00] WARN: Input  created using both :default and :value options - ignoring :default
[2019-09-24T04:58:56+00:00] WARN: DEPRECATION: The 'default' option for attributes is being replaced by 'value' - please use it instead. attribute name: 'Inspec::Input' (used at /root/.inspec/cache/2df62d453bff88521be93370dfa2d5e7c06f19ed212ca801b0ce0f4a1404dce0/controls/translated-controls.rb:24)
[2019-09-24T04:58:56+00:00] WARN: Input  created using both :default and :value options - ignoring :default
[2019-09-24T04:58:56+00:00] WARN: DEPRECATION: The 'default' option for attributes is being replaced by 'value' - please use it instead. attribute name: 'Inspec::Input' (used at /root/.inspec/cache/2df62d453bff88521be93370dfa2d5e7c06f19ed212ca801b0ce0f4a1404dce0/controls/translated-controls.rb:36)
[2019-09-24T04:58:56+00:00] WARN: Input  created using both :default and :value options - ignoring :default
[2019-09-24T04:58:56+00:00] WARN: DEPRECATION: The 'default' option for attributes is being replaced by 'value' - please use it instead. attribute name: 'Inspec::Input' (used at /root/.inspec/cache/2df62d453bff88521be93370dfa2d5e7c06f19ed212ca801b0ce0f4a1404dce0/controls/translated-controls.rb:43)
[2019-09-24T04:58:56+00:00] WARN: Input  created using both :default and :value options - ignoring :default
Traceback (most recent call last):
        10274: from /bin/inspec:186:in `<main>'
        10273: from /bin/inspec:186:in `load'
        10272: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.16.0/bin/inspec:11:in `<top (required)>'
        10271: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/base_cli.rb:33:in `start'
        10270: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        10269: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        10268: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        10267: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         ... 10262 levels...
            4: from libraries/shadow.rb:10:in `initialize'
            3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/resource.rb:57:in `block (3 levels) in create_dsl'
            2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/resource.rb:57:in `new'
            1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/plugin/v1/plugin_types/resource.rb:94:in `initialize'
libraries/shadow.rb:10:in `initialize': stack level too deep (SystemStackError)
```

Please look into the issue.

**Comment by sanchihb** [comment]
I also tried with the recent current version available 4.17.4

**Comment by sanchihb** [comment]
Faced the same issue uploading the tar.gz file as well.

**Comment by clintoncwolfe** [comment]
@sanchihb, if you can post a minimal version of you profile that causes the error, we can investigate further and consider it a bug. 

Otherwise, this looks to be support-related. We use GitHub issues to track bugs and feature requests. If you need support help (i.e. with using Chef InSpec), we recommend that if you are a:

* Chef customer:
  * Please reach out to your Customer Success manager and they can assist you
* Chef community member:
  * Please post to our Mailing List or join the Chef Community Slack
    * Chef Mailing List: https://discourse.chef.io/
    * Chef Community Slack: http://community-slack.chef.io/

Support issues opened here will be assumed to be from community members, and therefore closed and redirected to our Mailing List. 

To read up more on how to file a support issue, check out:
https://github.com/inspec/.github/blob/master/SUPPORT.md

Thank you!
__Chef InSpec Team__
