### ISSUE TITLE
4.17.7 breaks all `*_service` resources

### ISSUE THREAD

**Issue by baurmatt** [inspec/inspec#4521]
# Describe the problem
We're using kitchen to test Puppet module. After upgrading to inspec 4.17.7, `systemd_service` throws the following error:

```
Kitchen::ActionFailed: Failed to complete #verify action: [undefined method `systemd_service' for #<#<Class:0x0000556951442090>:0x00005569513e3dd8>]
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:69:in `rescue in method_missing'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:66:in `method_missing'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/site/sys11elasticsearch/test/integration/sys11elasticsearch-clusternode-5/inspec/sys11elasticsearch.rb:56:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `instance_eval'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:145:in `load_control_file'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:208:in `block in collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:116:in `block in load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:127:in `run'
/usr/local/bundle/gems/kitchen-inspec-1.2.0/lib/kitchen/verifier/inspec.rb:94:in `call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:459:in `block in verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:552:in `synchronize_or_call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:514:in `block in action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:513:in `action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:451:in `verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:381:in `block in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `each'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:162:in `verify'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:191:in `block in test'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:187:in `test'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:147:in `block (3 levels) in <top (required)>'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `chdir'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
NoMethodError: undefined method `systemd_service' for #<#<Class:0x0000556951442090>:0x00005569513e3dd8>
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:69:in `rescue in method_missing'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:66:in `method_missing'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/site/sys11elasticsearch/test/integration/sys11elasticsearch-clusternode-5/inspec/sys11elasticsearch.rb:56:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `instance_eval'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:145:in `load_control_file'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:208:in `block in collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:116:in `block in load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:127:in `run'
/usr/local/bundle/gems/kitchen-inspec-1.2.0/lib/kitchen/verifier/inspec.rb:94:in `call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:459:in `block in verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:552:in `synchronize_or_call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:514:in `block in action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:513:in `action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:451:in `verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:381:in `block in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `each'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:162:in `verify'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:191:in `block in test'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:187:in `test'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:147:in `block (3 levels) in <top (required)>'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `chdir'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
LoadError: cannot load such file -- resources/aws/systemd_service
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:40:in `require'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:40:in `rescue in method_missing_resource'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:37:in `method_missing_resource'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:67:in `method_missing'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/site/sys11elasticsearch/test/integration/sys11elasticsearch-clusternode-5/inspec/sys11elasticsearch.rb:56:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `instance_eval'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:145:in `load_control_file'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:208:in `block in collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:116:in `block in load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:127:in `run'
/usr/local/bundle/gems/kitchen-inspec-1.2.0/lib/kitchen/verifier/inspec.rb:94:in `call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:459:in `block in verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:552:in `synchronize_or_call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:514:in `block in action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:513:in `action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:451:in `verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:381:in `block in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `each'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:162:in `verify'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:191:in `block in test'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:187:in `test'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:147:in `block (3 levels) in <top (required)>'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `chdir'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
LoadError: cannot load such file -- inspec/resources/systemd_service
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:38:in `require'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:38:in `method_missing_resource'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/dsl.rb:67:in `method_missing'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/site/sys11elasticsearch/test/integration/sys11elasticsearch-clusternode-5/inspec/sys11elasticsearch.rb:56:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `instance_eval'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:161:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile_context.rb:145:in `load_control_file'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:208:in `block in collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/profile.rb:204:in `collect_tests'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:116:in `block in load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `each'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:99:in `load'
/usr/local/bundle/gems/inspec-4.17.7/lib/inspec/runner.rb:127:in `run'
/usr/local/bundle/gems/kitchen-inspec-1.2.0/lib/kitchen/verifier/inspec.rb:94:in `call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:459:in `block in verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:552:in `synchronize_or_call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:514:in `block in action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:513:in `action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:451:in `verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:381:in `block in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `each'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:162:in `verify'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:191:in `block in test'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:187:in `test'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:147:in `block (3 levels) in <top (required)>'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `chdir'
/builds/57c2b40c/0/puppet-manifests/syseleven-control/Rakefile:137:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => kitchen:test
```

The following code triggers this:
```ruby
describe systemd_service('elasticsearch-instance') do
  it { should be_installed }
  it { should be_running }
  it { should be_enabled }
end
```

## Possible Solution
Downgrading to 4.16.0 works for us as a workaround.

I'm actually not sure if we're doing something wrong, we missed a breaking change or this is really a bug in inspec. Can you please help us figure this out? Thanks in advance! :)

**Comment by clintoncwolfe** [comment]
We've verifified this and confirmed that in fact it extends to other platforms and service infras, like runit_service, etc.
