### ISSUE TITLE
"group" resource stub missing

### ISSUE THREAD

**Issue by baurmatt** [inspec/inspec#4536]
# Describe the problem
```
describe group('additionalgroup') do
  it { should exist }
end
```

fails with:

```
Caused by:
LoadError: cannot load such file -- inspec/resources/group
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/dsl.rb:38:in `require'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/dsl.rb:38:in `method_missing_resource'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/dsl.rb:67:in `method_missing'
/builds/547bb737/0/puppet-manifests/syseleven-control/site/accounts/test/integration/accounts/inspec/accounts.rb:13:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/profile_context.rb:161:in `instance_eval'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/profile_context.rb:161:in `load_with_context'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/profile_context.rb:145:in `load_control_file'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/profile.rb:208:in `block in collect_tests'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/profile.rb:204:in `each'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/profile.rb:204:in `collect_tests'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/runner.rb:116:in `block in load'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/runner.rb:99:in `each'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/runner.rb:99:in `load'
/usr/local/bundle/gems/inspec-4.17.11/lib/inspec/runner.rb:127:in `run'
/usr/local/bundle/gems/kitchen-inspec-1.2.0/lib/kitchen/verifier/inspec.rb:94:in `call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:459:in `block in verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:552:in `synchronize_or_call'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:514:in `block in action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:513:in `action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:451:in `verify_action'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:381:in `block in transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `each'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:380:in `transition_to'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:162:in `verify'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:191:in `block in test'
/usr/local/bundle/gems/test-kitchen-2.3.3/lib/kitchen/instance.rb:187:in `test'
/builds/547bb737/0/puppet-manifests/syseleven-control/Rakefile:147:in `block (3 levels) in <top (required)>'
/builds/547bb737/0/puppet-manifests/syseleven-control/Rakefile:137:in `chdir'
/builds/547bb737/0/puppet-manifests/syseleven-control/Rakefile:137:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
```

## Possible Solution
This looks like the same as #4521 and should be an easy solve. Will add a PR for this soon.

**Comment by kekaichinose** [comment]
@baurmatt Thanks for the catch! We're finishing up PR and will look to get a hot fix release out by EOD.
