### ISSUE TITLE
Inspec fails on profile archives with empty file, resulting in undefined method error

### ISSUE THREAD

**Issue by stevendanna** [inspec/inspec#4562]
# Describe the problem

It appears that sometime after `v4.16.0`, inspec incorrectly handles profile tar archives that include empty files.  The following command:

```
inspec check 'https://github.com/vjeffrey/try-inspec-aws-profile/archive/master.tar.gz'
```

works on v4.16.0 but fails on v4.17.17 with the following error:

```
Traceback (most recent call last):
	17: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-bin-4.17.17/bin/inspec:11:in `<main>'
	16: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/base_cli.rb:33:in `start'
	15: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	14: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	13: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	11: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/cli.rb:116:in `check'
	10: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/profile.rb:73:in `for_target'
	 9: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/profile.rb:67:in `for_fetcher'
	 8: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/profile.rb:49:in `for_path'
	 7: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/file_provider.rb:14:in `for_path'
	 6: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/file_provider.rb:14:in `new'
	 5: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/file_provider.rb:160:in `initialize'
	 4: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/file_provider.rb:205:in `walk_tar'
	 3: from /hab/pkgs/core/ruby/2.5.5/20190416223112/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:29:in `new'
	 2: from /hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/file_provider.rb:161:in `block in initialize'
	 1: from /hab/pkgs/core/ruby/2.5.5/20190416223112/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:65:in `each'
/hab/pkgs/chef/inspec/4.17.17/20191002041201/lib/gems/inspec-4.17.17/lib/inspec/file_provider.rb:176:in `block (2 levels) in initialize': undefined method `force_encoding' for nil:NilClass (NoMethodError)
```

Some well places printf's tell me this is happening on the first empty file in the archive `libraries/.gitkeep`

## Possible Solution

A quick fix would be to nil-check `res` here before doing the force_encoding trick:

https://github.com/inspec/inspec/blob/90961d3cf73446b5f040f40a8dac48b4f6202cd5/lib/inspec/file_provider.rb#L175-L177

**Comment by zenspider** [comment]
This should be fixed. Thanks!
