### ISSUE TITLE
InSpec fails when unicode characters are in the path

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4596]
In the example below the users home directory is `🌊`:

```
root@5c322673c874:~/🌊# inspec --version
Traceback (most recent call last):
	10: from /opt/chefdk/bin/inspec:351:in `<main>'
	 9: from /opt/chefdk/bin/inspec:351:in `load'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.16.0/bin/inspec:10:in `<top (required)>'
	 7: from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/cli.rb:428:in `<top (required)>'
	 4: from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.16.0/lib/inspec/plugin/v2.rb:30:in `<top (required)>'
	 1: from /opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': stack level too deep (SystemStackError)
```

ref: https://github.com/chef/chef-dk/issues/2243

**Comment by zenspider** [comment]
Can't repro at all... waiting for feedback.
