### ISSUE TITLE
Website is unbuildable

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4613]
The readme hints that if there is a problem rendering CSS that it is because node is missing. I installed node, and still get the same error. There is a disconnect between what the Rakefile is doing and what needs to be available to do it.

**Comment by zenspider** [comment]
```
2522 % bundle exec middleman build --bail --verbose
== Activating: file_watcher
== Activating: front_matter
...
== Running manipulator: routing (130)
== Prerendering CSS
== Request: /stylesheets/vendor/fontawesome.min.css
== Request: /stylesheets/site.css
== Finishing Request: stylesheets/site.css (0.0s)
== Finishing Request: stylesheets/vendor/fontawesome.min.css (0.0s)
       error  build/stylesheets/site.css
Error: File to import not found or unreadable: vendor/foundation-min.
        on line 2:1 of stdin
>> @import "vendor/foundation-min";

   ^

stdin:2
/Users/ryan/.gem/repos/inspecwww/gems/sassc-2.2.1/lib/sassc/engine.rb:49:in `render'
/Users/ryan/.gem/repos/inspecwww/gems/middleman-core-4.3.5/lib/middleman-core/extensions/minify_css.rb:31:in `compress'
/Users/ryan/.gem/repos/inspecwww/gems/middleman-core-4.3.5/lib/middleman-core/extensions/minify_css.rb:114:in `minify'
/Users/ryan/.gem/repos/inspecwww/gems/memoist-0.16.0/lib/memoist.rb:214:in `minify'
/Users/ryan/.gem/repos/inspecwww/gems/middleman-core-4.3.5/lib/middleman-core/extensions/minify_css.rb:73:in `call'
/Users/ryan/.gem/repos/inspecwww/gems/middleman-autoprefixer-2.10.1/lib/middleman-autoprefixer/extension.rb:55:in `call'
...
```
