### ISSUE TITLE
inspec json fails for tar archives with empty files

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#4616]
There is a blank file in this dev-sec profile:
https://github.com/dev-sec/cis-docker-benchmark/blob/master/libraries/.gitkeep

It probably shouldn't be there, but it's recently started failing `inspec json` due to the fix we did for character encoding with tar files.

NOTE: (@clintoncwolfe): The profile here should be archived using `inspec archive`, then the repro invocation is `inspec json profile-1.2.3.tar.gz` - you are inflating and exporting the profile as JSON from a tarball.

```

Generate inspec json for cis-docker-benchmark-2.1.0.tar.gz ...
--
  | Traceback (most recent call last):
  | 17: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-bin-4.18.0/bin/inspec:11:in `<main>'
  | 16: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/base_cli.rb:33:in `start'
  | 15: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  | 14: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  | 13: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  | 12: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  | 11: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/cli.rb:79:in `json'
  | 10: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/profile.rb:73:in `for_target'
  | 9: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/profile.rb:67:in `for_fetcher'
  | 8: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/profile.rb:49:in `for_path'
  | 7: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/file_provider.rb:14:in `for_path'
  | 6: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/file_provider.rb:14:in `new'
  | 5: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/file_provider.rb:160:in `initialize'
  | 4: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/file_provider.rb:205:in `walk_tar'
  | 3: from /hab/pkgs/core/ruby/2.5.7/20191007205439/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:29:in `new'
  | 2: from /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/file_provider.rb:161:in `block in initialize'
  | 1: from /hab/pkgs/core/ruby/2.5.7/20191007205439/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:65:in `each'
  | /hab/pkgs/chef/inspec/4.18.0/20191010204024/lib/gems/inspec-4.18.0/lib/inspec/file_provider.rb:176:in `block (2 levels) in initialize': undefined method `force_encoding' for nil:NilClass (NoMethodError)


```

## Possible Solution
I opened PR https://github.com/inspec/inspec/pull/4615

**Comment by clintoncwolfe** [comment]
On a minimal profile - just that generated by `inspec init`, with two empty files added in `controls/` and `libraries/`, I can't reproduce this.

**Comment by clintoncwolfe** [comment]
I also cloned https://github.com/dev-sec/cis-docker-benchmark and ran inspec's master@72ed84d2 against it - it again succeeded.

**Comment by clintoncwolfe** [comment]
UPDATE - it does repro when starting from a tarball.

**Comment by james-stocks** [comment]
Closing as duplicate of https://github.com/inspec/inspec/issues/4562
