### ISSUE TITLE
Error running inspec vendor

### ISSUE THREAD

**Issue by wyardley** [inspec/inspec#4774]
# Describe the problem

We've started getting an error like the following on a set of tests we run in CI. I've tried updating to latest inspec (4.18.x), but still getting the error. Not sure if this is related to, e.g., #3286 

```
% bundle exec inspec vendor --overwrite --log-level=debug --chef-license=accept-silent test/integration/default 
[2019-12-10T12:46:24-08:00] DEBUG: Option backend_cache is enabled
[2019-12-10T12:46:24-08:00] DEBUG: Resolve /Users/wby/git/terraform/test/integration/default into cache /Users/wby/git/terraform/test/integration/default/vendor
[2019-12-10T12:46:24-08:00] DEBUG: Dependency does not exist in the cache /Users/wby/git/terraform/test/integration/default
[2019-12-10T12:46:24-08:00] DEBUG: Starting traversal of dependencies ["inspec-gcp"]
[2019-12-10T12:46:24-08:00] DEBUG: Fetching URL: https://github.com/inspec/inspec-gcp/archive/master.tar.gz
[2019-12-10T12:46:25-08:00] DEBUG: Archive stored at temporary location: /var/folders/4v/kfpm4dxx6qb8dvk4thtz8mq80000gn/T/inspec-dl-20191210-5108-uzppxt.tar.gz
[2019-12-10T12:46:25-08:00] DEBUG: Dependency does not exist in the cache {:cwd=>"/Users/wby/git/terraform/test/integration/default", :backend=>Inspec::Backend::Class @transport=Train::Transports::Mock::Connection, :name=>"inspec-gcp", :url=>"https://github.com/inspec/inspec-gcp/archive/master.tar.gz"}
[2019-12-10T12:46:25-08:00] DEBUG: Fetched archive moved to: /Users/wby/git/terraform/test/integration/default/vendor/cb2686a2df2dd7813aa9af32f643fcab655f15667af8d732f197292a1ab07b78.tar.gz
[2019-12-10T12:46:25-08:00] DEBUG: Adding dependency inspec-gcp ({:url=>"https://github.com/inspec/inspec-gcp/archive/master.tar.gz", :sha256=>"cb2686a2df2dd7813aa9af32f643fcab655f15667af8d732f197292a1ab07b78"})
[2019-12-10T12:46:25-08:00] DEBUG: Using cached dependency for {:cwd=>"/Users/wby/git/terraform/test/integration/default", :backend=>Inspec::Backend::Class @transport=Train::Transports::Mock::Connection, :name=>"inspec-gcp", :url=>"https://github.com/inspec/inspec-gcp/archive/master.tar.gz"}
bundler: failed to load command: inspec (/usr/local/bin/inspec)
RuntimeError: Don't understand inspec profile in /Users/wby/git/terraform/test/integration/default/vendor/cb2686a2df2dd7813aa9af32f643fcab655f15667af8d732f197292a1ab07b78.tar.gz, it doesn't look like a supported profile structure.
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile.rb:57:in `for_path'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile.rb:67:in `for_fetcher'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/requirement.rb:131:in `profile'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/requirement.rb:110:in `dependencies'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:77:in `block in resolve'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:59:in `each'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:59:in `resolve'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:30:in `resolve'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/dependency_set.rb:90:in `vendor'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile.rb:538:in `generate_lockfile'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile_vendor.rb:56:in `vendor_dependencies'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile_vendor.rb:13:in `vendor!'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/base_cli.rb:285:in `vendor_deps'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/cli.rb:163:in `vendor'
  /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Library/Ruby/Gems/2.6.0/gems/inspec-4.18.39/lib/inspec/base_cli.rb:33:in `start'
  /Library/Ruby/Gems/2.6.0/gems/inspec-bin-4.18.39/bin/inspec:11:in `<top (required)>'
  /usr/local/bin/inspec:23:in `load'
  /usr/local/bin/inspec:23:in `<top (required)>'
```

## Possible Solution

**Comment by wyardley** [comment]
Turns out to be related to https://github.com/inspec/inspec-gcp/issues/217

That said, not sure if anything can / should be done in inspec itself to make it easier to figure out what's going on here, or to display a more helpful message in the case where this happens?

**Comment by miah** [comment]
Fixed in https://github.com/inspec/inspec-gcp/issues/217
