### ISSUE TITLE
InSpec in Habitat fails to run as an ad-hoc task

### ISSUE THREAD

**Issue by TheLunaticScripter** [inspec/inspec#4801]
# Describe the problem
One the requirements for the effortless pattern is to be able to run an InSpec profile as part of an image build process. This requires us to be able to run the profile without starting the Habitat Supervisor as the Supervisor will require additional clean up steps once it has been started. With the packages created by Stuart Preston the way we ran packages was by adding the binaries to the `PATH` environment variable and then executing the profile that was bundled in the build. This doesn't work with the current InSpec packages and gives this error. 

```
PS C:\Users\Administrator> inspec --version
Traceback (most recent call last):
        3: from C:/hab/pkgs/chef/chef-infra-client/15.6.17/20191217012848/bin/inspec:20:in `<main>'
        2: from C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        1: from C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'addressable' (= 2.7.0) among 44 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=C:/Users/Administrator/.gem/ruby/2.6.0;C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/gems/2.6.0', execute `gem env` for more information
```

This is because the `GEM_PATH` doesn't contain the vendor directory that is packaged with the InSpec build

I attempted to add the `GEM_PATH` and also added the `$env:APPBUNDLER_ALLOW_RVM = "true"` environment variable but get a different error

```
Traceback (most recent call last):
        3: from C:/hab/pkgs/chef/chef-infra-client/15.6.17/20191217012848/bin/inspec:25:in `<main>'
        2: from C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        1: from C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'binding_of_caller' (= 0.8.0) among 231 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor;C:/hab/pkgs/chef/ruby-plus-devkit/2.6.5/20191017152652/lib/ruby/gems/2.6.0', execute `gem env` for more information
```

I have also tried the `hab pkg exec chef/inspec inspec.bat exec <path_to_profile>` this fail with a train error that train isn't able to detect the platform.

```
Traceback (most recent call last):
        19: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/bin/inspec:221:in `<main>'
        18: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/bin/inspec:221:in `load'
        17: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/inspec-bin-4.18.51/bin/inspec:11:in `<top (required)>'
        16: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in `start'
        15: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `exec'
        10: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `new'
         9: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/inspec-4.18.51/lib/inspec/runner.rb:78:in `initialize'
         8: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/inspec-4.18.51/lib/inspec/runner.rb:86:in `configure_transport'
         7: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/inspec-4.18.51/lib/inspec/backend.rb:53:in `create'
         6: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/train-3.2.0/lib/train/transports/local.rb:17:in `connection'
         5: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/train-3.2.0/lib/train/transports/local.rb:17:in `new'
         4: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/train-3.2.0/lib/train/transports/local.rb:27:in `initialize'
         3: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/train-3.2.0/lib/train/transports/local.rb:42:in `select_runner'
         2: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/train-3.2.0/lib/train/plugins/base_connection.rb:116:in `platform'
         1: from C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/train-3.2.0/lib/train/platforms/detect.rb:9:in `scan'
C:/hab/pkgs/chef/inspec/4.18.51/20191212003018/vendor/gems/train-3.2.0/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```

## Possible Solution
@miah suggested that maybe there is a way to add the vendor directory to the `GEM_PATH` during the build of the `inspec` binary.

**Comment by TheLunaticScripter** [comment]
I ran another test and this works if inspec is bin linked using the following command `hab pkg install chef/inspec --binlink` this adds the binaries to the `c:\hab\bin` directory and preserves the `GEM_PATH`. I think this is still not an ideal situation but perhaps a valid work around.

**Comment by miah** [comment]
I install via --binlink in my artifact tests:

https://github.com/inspec/inspec/blob/master/.expeditor/buildkite/artifact.habitat.test.ps1

I think the 'fix' for this really needs to live in appbundler though.
