### ISSUE TITLE
can't find executable inspec for gem inspec (Gem::Exception)

### ISSUE THREAD

**Issue by juju4** [inspec/inspec#4812]
Migration from inspec 3 to 4 in travis-ci
test failing with above error.

# Describe the problem
I'm reviewing a syslog baseline fixing some deprecations.
Initial travis-ci is based on linux-baseline and others which are still on inspec3 (https://github.com/dev-sec/linux-baseline/blob/master/Gemfile).

when forcing Gemfile with inspec4
```https://travis-ci.org/juju4/inspec-syslog/jobs/630654034#L488
$ bundle exec rake
Generate changelog for version 0.2.0
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /home/travis/build/juju4/inspec-syslog/vendor/bundle/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
Running RuboCop...
Inspecting 3 files
...
3 files inspected, no offenses detected
bundle exec inspec check /home/travis/build/juju4/inspec-syslog
Traceback (most recent call last):
	4: from /home/travis/build/juju4/inspec-syslog/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	3: from /home/travis/build/juju4/inspec-syslog/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
	2: from /home/travis/build/juju4/inspec-syslog/vendor/bundle/ruby/2.6.0/bin/inspec:23:in `<main>'
	1: from /home/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
/home/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable inspec for gem inspec (Gem::Exception)
rake aborted!
Command failed with status (1): [bundle exec inspec check /home/travis/buil...]
/home/travis/build/juju4/inspec-syslog/Rakefile:24:in `block (2 levels) in <top (required)>'
/home/travis/build/juju4/inspec-syslog/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/travis/build/juju4/inspec-syslog/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
/home/travis/build/juju4/inspec-syslog/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => default => test:check
(See full trace by running task with --trace)
The command "bundle exec rake" exited with 1.
```

previous iteration was failing on input (attribute replacement)
https://travis-ci.org/juju4/inspec-syslog/jobs/630653269#L381
and previous one was fine
https://travis-ci.org/juju4/inspec-syslog/jobs/630639243

## Possible Solution
it seems for a binary for inspec but not installed by Gem.
Not sure if specific option is needed

**Comment by zenspider** [comment]
For 3 to 4, I think you want to install the `inspec-bin` gem. This has the executable (and licensing requirements).

**Comment by juju4** [comment]
Thanks @zenspider !

Working with Ruby 2.6 + environment license acceptance
https://travis-ci.org/juju4/inspec-syslog/jobs/632641005#L628

Failing on ruby-head/2.8.0 but rubocop level
https://travis-ci.org/juju4/inspec-syslog/jobs/632641006#L643

ok with 2.7
https://travis-ci.org/juju4/inspec-syslog/jobs/632642754#L625

Ok closing on my side
