### ISSUE TITLE
inspec exec --insecure not working with profile

### ISSUE THREAD

**Issue by jujugrrr** [inspec/inspec#4873]
# Describe the problem
Passing `--insecure` doesn't allow to bypass SSL verification when downloading profiles over https

```
inspec --version
4.18.39

inspec exec https://self-signed.badssl.com/test.tar.gz  --insecure --chef-license=accept --diagnose
+---------------------------------------------+
✔ 1 product license accepted.
+---------------------------------------------+
InSpec version: 4.18.39
Train version: 3.2.14
Command line configuration:
{"enable_telemetry"=>false,
 "winrm_transport"=>"negotiate",
 "insecure"=>true,
 "distinct_exit"=>true,
 "chef_license"=>"accept",
 "diagnose"=>true}
JSON configuration file:
{"version"=>"1.2"}
Merged configuration:
{"reporter"=>["cli"],
 "show_progress"=>false,
 "color"=>true,
 "create_lockfile"=>true,
 "backend_cache"=>true,
 "enable_telemetry"=>false,
 "winrm_transport"=>"negotiate",
 "insecure"=>true,
 "distinct_exit"=>true,
 "chef_license"=>"accept",
 "diagnose"=>true}

Traceback (most recent call last):
        33: from /usr/bin/inspec:23:in `<main>'
        32: from /usr/bin/inspec:23:in `load'
        31: from /usr/lib/ruby/gems/2.5.0/gems/inspec-bin-4.18.39/bin/inspec:11:in `<top (required)>'
        30: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/base_cli.rb:33:in `start'
        29: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        28: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        27: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        26: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        25: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/cli.rb:285:in `exec'
        24: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/cli.rb:285:in `each'
        23: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/cli.rb:285:in `block in exec'
        22: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/runner.rb:192:in `add_target'
        21: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/profile.rb:73:in `for_target'
        20: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/profile.rb:66:in `for_fetcher'
        19: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/cached_fetcher.rb:38:in `fetch'
        18: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/inspec/cached_fetcher.rb:31:in `cache_key'
        17: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/fetchers/url.rb:114:in `cache_key'
        16: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/fetchers/url.rb:130:in `sha256'
        15: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/fetchers/url.rb:150:in `temp_archive_path'
        14: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/fetchers/url.rb:197:in `download_archive_to_temp'
        13: from /usr/lib/ruby/gems/2.5.0/gems/inspec-4.18.39/lib/fetchers/url.rb:215:in `open_via_uri'
        12: from /usr/lib/ruby/2.5.0/open-uri.rb:35:in `open'
        11: from /usr/lib/ruby/2.5.0/open-uri.rb:735:in `open'
        10: from /usr/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
         9: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
         8: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
         7: from /usr/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
         6: from /usr/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
         5: from /usr/lib/ruby/2.5.0/open-uri.rb:337:in `open_http'
         4: from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
         3: from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
         2: from /usr/lib/ruby/2.5.0/net/http.rb:985:in `connect'
         1: from /usr/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError)

```
## Possible Solution
It looks like https://github.com/inspec/inspec/blob/master/lib/inspec/fetcher/url.rb#L239 doesn't work because https://github.com/inspec/inspec/blob/master/lib/inspec/fetcher/url.rb#L98 is `nil` despite the diagnose showing the option

**Comment by jfaulkner** [comment]
Ran into this issue recently where SSL verification options couldn't be overwritten. Any action on this?

**Comment by aaronlippold** [comment]
this is a large blocker for many teams behind the firewall
