### ISSUE TITLE
Missing platform information for winrm connection to Windows 10

### ISSUE THREAD

**Issue by coding-blip** [inspec/inspec#4915]
# Problem

I have seen the following issue with all of the following InSpec versions:
- 4.18.85
- 4.18.51
- 4.18.38

I first noticed the issue when a kitchen verify failed on a node when checking for an installed package. When logging into the node directly and checking the packages were installed, it showed that they were indeed installed as expected.

I then ran inspec shell locally on the node in question and found that the exact same tests worked and showed that the package was installed properly. So basically the tests fail on a remote InSpec test, but work on a local one.

After some digging I decided to check the code found at /lib/inspec/resources/package.rb to see how it was checking if a package was installed. I found that it looks in the registry and that if it detects x86_64 it searches in 2 additional location. My packages that are failing are the ones there. 

I did some more digging and eventually I got to the fact that my os and arch details were not being retrieved correctly. 

When running inspec shell as well as inspec detect locally this is what I got back:
```
PS C:\Users\kitchen> inspec detect

 ────────────────────────────── Platform Details ──────────────────────────────

Name:      windows_server_2016_datacenter
Families:  windows, os
Release:   10.0.14393
Arch:      x86_64
```
When running a remote connection for the inspec shell as well as inspec detect (which is what a kitchen verify would see) this is what I got back:
```
PS C:\WINDOWS\system32> inspec detect -t winrm://HOSTNAME:5985 --user 'kitchen' --passwo
rd """PASSWORD"""

 ────────────────────────────── Platform Details ──────────────────────────────

Name:      windows_10.0.14393
Families:  windows, os
Release:   10.0.14393
Arch:      unknown
```

## Possible Thoughts

I tried figuring out where these values may be coming from but I am not too familiar with the InSpec code base (this was my first time looking at it). I have a hunch that it may be coming from /lib/inspec/backend.rb since the /lib/inspec/resources/platform.rb is built off of that.

Also while in the inspec shell and running `inspec.backend` on the local machine I get back `=> Train::Transports::Local::Connection[local]` while running it on the remote machine via remote inspec shell I get this back: `=> TrainPlugins::WinRM::Connection[Unknown]`. 

If anyone who is more familiar with this and may have some ideas for me it would be great so that my InSpec tests work again as they should.

**Comment by clintoncwolfe** [comment]
I encountered the same symptom recently on a Windows Nano container that did not have the deprecated executable `wmic.exe` installed, which is how `train` performs architecture detection. I believe that is the fundamental issue.

**Comment by wdower** [comment]
I'm running into an issue trying to connect to a Windows EC2 even though it does have wmic.exe installed.

```
$> inspec detect -t winrm://<ip> --client-cert=winrm.crt --client-key=wimrm.key --ca-trust-file=<trustfile> --ssl -l debug --self-signed
D, [2023-04-27T23:13:38.300671 #30865] DEBUG -- : winrm-fs requested, loading WinRM::FS gem (~> 1.0)
D, [2023-04-27T23:13:38.308853 #30865] DEBUG -- : winrm-fs library loaded
D, [2023-04-27T23:13:38.308902 #30865] DEBUG -- : winrm-elevated requested, loading WinRM-elevated gem (~> 1.2.2)
D, [2023-04-27T23:13:38.310667 #30865] DEBUG -- : winrm-elevated library loaded
[2023-04-27T23:13:38+00:00] DEBUG: Option backend_cache is disabled
[2023-04-27T23:13:38+00:00] DEBUG: Resolve {"inspec.yml"=>"name: inspec-shell"} into cache /home/wdower/.inspec/cache
[2023-04-27T23:13:38+00:00] DEBUG: Dependency does not exist in the cache {"inspec.yml"=>"name: inspec-shell"}
D, [2023-04-27T23:13:38.317406 #30865] DEBUG -- : [WinRM] @<ip><{:transport=>:negotiate, :disable_sspi=>false, :basic_auth_only=>false, :endpoint=>"https://<ip>5986/wsman", :user=>"administrator", :password=>"<hidden>", :no_ssl_peer_verification=>true, :realm=>nil, :service=>nil, :ca_trust_file=>"<trustfile>", :ssl_peer_fingerprint=>nil, :client_cert=>"winrm.crt", :client_key=>"wimrm.key", :key_pass=>nil}> (cmd.exe /c ver)
D, [2023-04-27T23:13:38.361676 #30865] DEBUG -- : [WinRM] opening remote shell on https://<ip>:5986/wsman
[2023-04-27T23:13:38+00:00] DEBUG: Loading <anonymous content> into #<Inspec::ProfileContext:0x00007f23ec4477c8>
D, [2023-04-27T23:13:38.386155 #30865] DEBUG -- : [WinRM] @<ip><{:transport=>:negotiate, :disable_sspi=>false, :basic_auth_only=>false, :endpoint=>"https://<ip>:5986/wsman", :user=>"administrator", :password=>"<hidden>", :no_ssl_peer_verification=>true, :realm=>nil, :service=>nil, :ca_trust_file=>"<trustfile>", :ssl_peer_fingerprint=>nil, :client_cert=>"winrm.crt", :client_key=>"wimrm.key", :key_pass=>nil}> (cmd.exe /c ver)
D, [2023-04-27T23:13:38.386267 #30865] DEBUG -- : [WinRM] opening remote shell on https://<ip>5986/wsman
/opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/resources/platform.rb:38:in `name': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/resources/platform.rb:61:in `params'
        from (eval):1:in `load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/profile_context.rb:169:in `instance_eval'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/profile_context.rb:169:in `load_with_context'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/profile_context.rb:155:in `load_control_file'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/runner.rb:279:in `eval_with_virtual_profile'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/cli.rb:520:in `run_command'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/cli.rb:384:in `detect'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/base_cli.rb:35:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-bin-5.21.29/bin/inspec:11:in `<top (required)>'
        from /usr/bin/inspec:258:in `load'
        from /usr/bin/inspec:258:in `<main>'
$>
```
For me the command simply dies.
