### ISSUE TITLE
error when connecting to cisco ios xe (csr1000v)

### ISSUE THREAD

**Issue by calloes** [inspec/inspec#4982]
inspec detect fails against Cisco IOS XE on csr 1000v 16.12.02.

confirmed the ssh session establishes it seems it's failing inside detection during the windows checks.

have also tried 

inspec detect --backend=ssh --host=10.1.1.29 --user=vagrant --password=vagrant --enable-password=vagrant

/share # inspec detect --backend=ssh --target ssh://vagrant:vagrant@10.1.1.29
Traceback (most recent call last):
        32: from /usr/local/bundle/bin/inspec:23:in `<main>'
        31: from /usr/local/bundle/bin/inspec:23:in `load'
        30: from /usr/local/bundle/gems/inspec-bin-4.18.104/bin/inspec:11:in `<top (required)>'
        29: from /usr/local/bundle/gems/inspec-core-4.18.104/lib/inspec/base_cli.rb:35:in `start'
        28: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        27: from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        26: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        25: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        24: from /usr/local/bundle/gems/inspec-core-4.18.104/lib/inspec/cli.rb:306:in `detect'
        23: from /usr/local/bundle/gems/inspec-core-4.18.104/lib/inspec/cli.rb:408:in `run_command'
        22: from /usr/local/bundle/gems/inspec-core-4.18.104/lib/inspec/cli.rb:408:in `new'
        21: from /usr/local/bundle/gems/inspec-core-4.18.104/lib/inspec/runner.rb:78:in `initialize'
        20: from /usr/local/bundle/gems/inspec-core-4.18.104/lib/inspec/runner.rb:86:in `configure_transport'
        19: from /usr/local/bundle/gems/inspec-core-4.18.104/lib/inspec/backend.rb:38:in `create'
        18: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/transports/ssh.rb:82:in `connection'
        17: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/transports/ssh.rb:240:in `create_new_connection'
        16: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/transports/ssh.rb:240:in `new'
        15: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/transports/ssh_connection.rb:57:in `initialize'
        14: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/extras/command_wrapper.rb:188:in `load'
        13: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/plugins/base_connection.rb:124:in `platform'
        12: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect.rb:9:in `scan'
        11: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/scanner.rb:27:in `scan'
        10: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/scanner.rb:27:in `each'
         9: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
         8: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
         7: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/scanner.rb:45:in `each'
         6: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
         5: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
         4: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/specifications/os.rb:20:in `block in load_windows'
         3: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/helpers/os_windows.rb:4:in `detect_windows'
         2: from /usr/local/bundle/gems/train-core-3.2.26/lib/train/platforms/detect/helpers/os_windows.rb:38:in `check_powershell'
         1: from /usr/local/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at 'Line has invalid autocommand "Get-WmiObject Win32_OperatingSystem | Select Caption,Version | ConvertTo-Json"' (JSON::ParserError)

**Comment by calloes** [comment]
Also forgot to mention running docker image of inspec latest version.
