### ISSUE TITLE
Large control result backtraces in report

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#4988]
While investigating large inspec reports, I've found an example where this profile:

```json
"name": "cis-rhel7-level2-server",
"version": "2.2.0-25",
"sha256": "a76798bcb92290eed37c44d50d0f7a51d059642ceb3531689733e990f6503d77",
"title": "CIS Red Hat Enterprise Linux 7 Benchmark Level 2 - Server",
```

had **57** ruby stacktraces like the one below, increasing the size of the report by **239.4 KB** 

```json
 {
  "id": "xccdf_org.cisecurity.benchmarks_rule_4.1.4_Ensure_events_that_modify_date_and_time_information_are_collected",
  "title": "Ensure events that modify date and time information are collected",
  "results": [
    {
      "status": "failed",
      "code_desc": "Auditd Rules ",
      "run_time": 0.000075805,
      "start_time": "2020-02-12T08:28:52+00:00",
      "message": "Command `/sbin/auditctl -l` failed with error: You must be root to run this program.\n",
      "exception": "Inspec::Exceptions::ResourceFailed",
      "backtrace": [
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:302:in `block (2 levels) in rspec_failed_block'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `instance_exec'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:257:in `block in run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `block in run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:610:in `run_around_example_hooks_for'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/hooks.rb:472:in `run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:460:in `with_around_example_hooks'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example.rb:254:in `run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:633:in `block in run_examples'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `map'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:629:in `run_examples'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:595:in `run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `map'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:116:in `block in run_specs'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:74:in `report'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115:in `run_specs'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/runner_rspec.rb:82:in `run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:159:in `run_tests'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:130:in `run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:287:in `exec'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in `start'",
        "/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.51/bin/inspec:11:in `<top (required)>'",
        "/usr/bin/inspec:349:in `load'",
        "/usr/bin/inspec:349:in `<main>'"
      ]
    },
    {
      "status": "failed",
      "code_desc": "File /etc/audit/audit.rules content is expected to match /-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change/",
      "run_time": 0.000249518,
      "start_time": "2020-02-12T08:28:52+00:00",
      "message": "expected nil to match /-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change/"
    }
```

Are these large backtraces necessary since the `message` contains the result error? For example: `Command /sbin/auditctl -l failed with error: You must be root to run this program.`

**Comment by clintoncwolfe** [comment]
@james-stocks can this be closed with the new message limiting features?

**Comment by alexpop** [comment]
Yes, thank you Clinton. This has been fixed with this PR https://github.com/inspec/inspec/pull/4994
