### ISSUE TITLE
Inspec does not appear to run on Fedora (32) with a package or gem install

### ISSUE THREAD

**Issue by mykelalvis** [inspec/inspec#5021]
# Inspec does not work on my Fedora 32 install.

When installing 4.18.111 via RPM (el7) or `gem install inspec-bin` there is what appears to be an issue
```
$ sudo dnf install ~/Downloads/inspec-4.18.111-1.el7.x86_64.rpm
 # ...omitted for clarity pasted at bottom of issue
$ sha1sum /opt/inspec/bin/inspec /usr/bin/inspec
ae253b3cff68a0c73f41e7eea8044a48f6d2a74c  /opt/inspec/bin/inspec
ae253b3cff68a0c73f41e7eea8044a48f6d2a74c  /usr/bin/inspec
$ which inspec
/usr/bin/inspec
$ uname -a
Linux f32.local 5.6.10-300.fc32.x86_64 #1 SMP Mon May 4 14:29:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ inspec --version
4.18.111
```
# Ruby reports an error executing `resolver.rb`

```
$ inspec --version
4.18.111

$ inspec vendor
Traceback (most recent call last):
	18: from /usr/bin/inspec:210:in `<main>'
	17: from /usr/bin/inspec:210:in `load'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.111/bin/inspec:11:in `<top (required)>'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/base_cli.rb:35:in `start'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/cli.rb:163:in `vendor'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/base_cli.rb:287:in `vendor_deps'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/profile_vendor.rb:13:in `vendor!'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/profile_vendor.rb:58:in `vendor_dependencies!'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/profile.rb:540:in `generate_lockfile'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/dependency_set.rb:90:in `vendor'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:26:in `resolve'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:26:in `map'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:26:in `each'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:27:in `block in resolve'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/requirement.rb:15:in `from_metadata': no implicit conversion of Symbol into Integer (TypeError)
```

---

# dnf install

```
$ sudo dnf install ~/Downloads/inspec-4.18.111-1.el7.x86_64.rpm 
Dependencies resolved.
===============================================================================================================================================================================================
 Package                                   Architecture                              Version                                             Repository                                       Size
===============================================================================================================================================================================================
Installing:
 inspec                                    x86_64                                    4.18.111-1.el7                                      @commandline                                     29 M

Transaction Summary
===============================================================================================================================================================================================
Install  1 Package

Total size: 29 M
Installed size: 169 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                       1/1 
  Running scriptlet: inspec-4.18.111-1.el7.x86_64                                                                                                                                          1/1 
You're about to install InSpec!

  Installing       : inspec-4.18.111-1.el7.x86_64                                                                                                                                          1/1 
  Running scriptlet: inspec-4.18.111-1.el7.x86_64                                                                                                                                          1/1 
Thank you for installing InSpec!
```

**Comment by james-stocks** [comment]
Hi @mykelalvis -

If I'm reading your output correctly; you have been able to install InSpec OK but get an error when attempting the `inspec vendor` command? 
What is the contents of `inspec.yml` in the directory you're running this command in?

Fedora isn't officially supported (https://docs.chef.io/platforms/#chef-inspec) so this won't get fixed by this project's maintainers if it turns out to be Fedora specific. But from the output you've pasted, this is possibly not a Fedora-specific issue.

**Comment by mykelalvis** [comment]
Actually, this happens with `inspec check` as well.
```
$ cat inspec.yml 
name: IT
title: IT 
maintainer: Somebody
copyright: abc
copyright_email: abc123@gmail.com
license: Apache-2.0
summary: IT Compliance Checks
version: 0.1.0
depends:
  name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/v1.14.2.tar.gz
supports:
  platform: azure
```

**Comment by james-stocks** [comment]
You have a slight YAML syntax issue there. `depends` needs to be an array of dependencies (even if there's only one).

Try 

```
name: IT
title: IT 
maintainer: Somebody
copyright: abc
copyright_email: abc123@gmail.com
license: Apache-2.0
summary: IT Compliance Checks
version: 0.1.0
depends:
- name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/v1.14.2.tar.gz
supports:
  platform: azure
```

We should keep this issue open to improve the validation of the metadata YAML

**Comment by james-stocks** [comment]
Actually @mykelalvis - to avoid confusion with the original Fedora bug report; do you mind if we close this issue, and I will raise a fresh issue for the need to validate inspec.yml better?

**Comment by mykelalvis** [comment]
That's what I get for doing a copypasta 😁
