### ISSUE TITLE
inspec.yml should be validated

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#5023]
https://github.com/inspec/inspec/issues/5021 was a bug report about InSpec not working correctly on Fedora.

It turned out that the YAML structure in `inspec.yml` wasn't quite right, and that caused unhandled crashes.

Example `inspec.yml`:

```
$ cat inspec.yml 
name: IT
title: IT 
maintainer: Somebody
copyright: abc
copyright_email: abc123@gmail.com
license: Apache-2.0
summary: IT Compliance Checks
version: 0.1.0
depends:
  name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/v1.14.2.tar.gz
supports:
  platform: azure
```

This causes errors like:

```
$ inspec --version
4.18.111

$ inspec vendor
Traceback (most recent call last):
	18: from /usr/bin/inspec:210:in `<main>'
	17: from /usr/bin/inspec:210:in `load'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.111/bin/inspec:11:in `<top (required)>'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/base_cli.rb:35:in `start'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/cli.rb:163:in `vendor'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/base_cli.rb:287:in `vendor_deps'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/profile_vendor.rb:13:in `vendor!'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/profile_vendor.rb:58:in `vendor_dependencies!'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/profile.rb:540:in `generate_lockfile'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/dependency_set.rb:90:in `vendor'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:26:in `resolve'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:26:in `map'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:26:in `each'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/resolver.rb:27:in `block in resolve'
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.111/lib/inspec/dependencies/requirement.rb:15:in `from_metadata': no implicit conversion of Symbol into Integer (TypeError)
```

This is because the `depends` metadata does not contain a list.
This metadata should either handle the single dependency not being a list; or fail fast with an error that complains about the inspec.yml content.

**Comment by clintoncwolfe** [comment]
Metadata has a validator in place today - see [here](https://github.com/inspec/inspec/blob/b3e2a4a46b1aeffa55744f660f2a11d4a7ba9121/lib/inspec/metadata.rb#L72) - but it is not opinionated enough about the structure of the YAML that is loaded.

**Comment by clintoncwolfe** [comment]
Can probably close #1284; it is either a duplicate or is outdated. I'm pretty sure inspec check does report the errors found by the valid? check. If not, this is a good ticket to get that specified and fixed.
