### ISSUE TITLE
mysql_conf parsing

### ISSUE THREAD

**Issue by epcim** [inspec/inspec#504]
I got the issue on parse config files, using mysql_conf and parse_config_file. 

Beside that:
**Feature req 1**, regarding the issue below, it would be handy if the comment_char in the parse_config/_file would allow specify array of comment chars or rather _re for lines exclusion.
**Feature req 2,** In the case we know what format is the config like `my.cnf`. we should parse it natively, so be able through inspec DSL address specific section against it's value - assumed in this kind of 'ini' config file - example "[client]" or "[mysqld]" for mysql.

Mty cnf file looks like:

```
[mysqld]

#
# * Basic Settings
#
user              = mysql
pid-file          = /var/lib/mysql/mysqld.pid
socket            = /var/lib/mysql/mysql.sock
port = 3306
basedir           = /usr
datadir           = /galera
tmpdir            = /tmp
slave_load_tmpdir = /tmp
# language          = /usr/share/mysql/english
character_set_server = utf8
collation_server  = utf8_unicode_ci

skip-external-locking

...
...
```

Statements:

```
  describe mysql_conf('/etc/my.cnf') do
    its('port') { should match (/3306/) }
    its('port') { should eq '3306' }
  end
```

do not fined value 'port' 
however when the config looks like, it's ok.:

```


port = 3306
[mysqld]

#
# * Basic Settings
#
user              = mysql
pid-file          = /var/lib/mysql/mysqld.pid
socket            = /var/lib/mysql/mysql.sock

basedir           = /usr

...
...
```

I have been playing with `parse_config_file` and `assigments_re` for a while but without success. The actual output from failed parse is:

```
[1] $ chef exec inspec exec inspec/percona -t ssh://vagrant@172.28.128.12 --password vagrant --sudo
............................................................FF

Failures:

  1) MySQL Configuration port should match /3306/
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected nil to match /3306/
     # inspec/percona/controls/mysql_configuration.rb:94:in `block (3 levels) in load'
     # /Users/pmichalec/.chefdk/gem/ruby/2.1.0/gems/inspec-0.14.4/lib/inspec/runner_rspec.rb:55:in `run'
     # /Users/pmichalec/.chefdk/gem/ruby/2.1.0/gems/inspec-0.14.4/lib/utils/base_cli.rb:52:in `run_tests'

  2) MySQL Configuration port should eq "3306"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "3306"
            got: nil

       (compared using ==)
     # inspec/percona/controls/mysql_configuration.rb:95:in `block (3 levels) in load'
     # /Users/pmichalec/.chefdk/gem/ruby/2.1.0/gems/inspec-0.14.4/lib/inspec/runner_rspec.rb:55:in `run'
     # /Users/pmichalec/.chefdk/gem/ruby/2.1.0/gems/inspec-0.14.4/lib/utils/base_cli.rb:52:in `run_tests'

Finished in 3.61 seconds (files took 2.25 seconds to load)
62 examples, 2 failures

Failed examples:

rspec  # MySQL Configuration port should match /3306/
rspec  # MySQL Configuration port should eq "3306"

zlib(finalizer): the stream was freed prematurely.
```

**Comment by chris-rock** [comment]
This should not happen and it has something to do with the grouping `[mysqld]`. This is similar to ini files where you group values. It looks weird, we need to have a look.

**Comment by calonso** [comment]
I've been diving into the code a bit to see if I could work around this and I found quite an elegant way. 

Just compose the key into an array. e.g: 

`its(['mysqld', 'port']) { should eq '3306' }`

**Comment by adamleff** [comment]
Additionally, you can use dot-notation in the `its` parameter:

```
inspec> describe mysql_conf('/tmp/mysql.conf') do
inspec>   its('mysqld.port') { should cmp 3306 }
inspec> end

Profile: inspec-shell
Version: (not specified)

  MySQL Configuration
     ✔  mysqld.port should cmp == 3306

Test Summary: 1 successful, 0 failures, 0 skipped
```

I'm chalking this up to a documentation issue and I'll put up a PR to address it.
