### ISSUE TITLE
Upgrade to inspec/inspec-core 4.20.6 brakes our CI 

### ISSUE THREAD

**Issue by crazymind1337** [inspec/inspec#5099]
After our CI automatically upgraded the Gems inspec and inspec-core it fails with an error:

```sh
Installing inspec-core 4.20.6 (was 4.20.2)
Installing inspec 4.20.6 (was 4.20.2)
```

```log
Caused by:
Inspec::Plugin::V2::LoadError: Plugin hooks search returned zero results for filter {:plugin_type=>:reporter, :activator_name=>:cli}
/home/someuser/.rvm/gems/ruby-2.5.5/gems/inspec-core-4.20.6/lib/inspec/plugin/v2/registry.rb:77:in `find_activator'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/inspec-core-4.20.6/lib/inspec/reporters.rb:28:in `render'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/inspec-core-4.20.6/lib/inspec/runner.rb:137:in `block in render_output'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/inspec-core-4.20.6/lib/inspec/runner.rb:136:in `each'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/inspec-core-4.20.6/lib/inspec/runner.rb:136:in `render_output'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/inspec-core-4.20.6/lib/inspec/runner.rb:161:in `run_tests'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/inspec-core-4.20.6/lib/inspec/runner.rb:130:in `run'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/kitchen-inspec-2.0.0/lib/kitchen/verifier/inspec.rb:105:in `call'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:459:in `block in verify_action'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:552:in `synchronize_or_call'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:514:in `block in action'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:513:in `action'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:451:in `verify_action'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:381:in `block in transition_to'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `each'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `transition_to'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:162:in `verify'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:191:in `block in test'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:187:in `test'
/home/someuser/source/gitlab/puppet-manifests/control/site/nrpe/Rakefile:149:in `block (3 levels) in <top (required)>'
/home/someuser/source/gitlab/puppet-manifests/control/site/nrpe/Rakefile:139:in `chdir'
/home/someuser/source/gitlab/puppet-manifests/control/site/nrpe/Rakefile:139:in `block (2 levels) in <top (required)>'
/home/someuser/.rvm/gems/ruby-2.5.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/someuser/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/home/someuser/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => kitchen:test
```

The line from our Rakefile:
```ruby
134 namespace 'kitchen' do
135   desc 'Run kitchen test for given module and suite'
136   task 'test', [:module, :suite] do |_, args|
137     require 'kitchen'
138 
139     Dir.chdir("#{__dir__}/site/#{args[:module]}") do
140       loader = Kitchen::Loader::YAML.new(
141         project_config: 'kitchen.yml',
142         local_config: 'kitchen.local.yml',
143       )
144       config = Kitchen::Config.new(loader: loader)
145       suite = config.instances.select { |i| i.name == args[:suite] }
146       raise "Cannot find suite #{args[:suite]} for module #{args[:module]}." if suite.empty?
147 
148       destroy = ENV['CI'] ? :always : :passing
149       suite[0].test(destroy)
150     end
151   end
152 end
```

The jobs are trigger via gitlab-ci with
```yaml
nrpe-ubuntu-2004:
  script:
  - bundle exec rake kitchen:test[nrpe,nrpe-ubuntu-2004]
```

Downgrade to previous version (4.20.2) helps out to fix this issue.

Aha! Link: https://chef.aha.io/features/SH-2330

**Comment by james-stocks** [comment]
Reproduction:

* Create a Gemfile with only `inspec-core`

```
source "https://rubygems.org"

gem 'inspec-core' # Bug also happens if you add `gem 'inspec'`
```

* bundle install
* `bundle exec irb`
* In `irb` run `require 'inspec'; Inspec::Runner.new.run`

```
irb(main):002:0> require 'inspec'; Inspec::Runner.new.run
Traceback (most recent call last):
       16: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
       15: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
       14: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
       13: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
       12: from /usr/bin/irb:23:in `<top (required)>'
       11: from /usr/bin/irb:23:in `load'
       10: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        9: from (irb):2
        8: from (irb):2:in `rescue in irb_binding'
        7: from /private/tmp/test/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.20.6/lib/inspec/runner.rb:130:in `run'
        6: from /private/tmp/test/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.20.6/lib/inspec/runner.rb:161:in `run_tests'
        5: from /private/tmp/test/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.20.6/lib/inspec/runner.rb:136:in `render_output'
        4: from /private/tmp/test/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.20.6/lib/inspec/runner.rb:136:in `each'
        3: from /private/tmp/test/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.20.6/lib/inspec/runner.rb:137:in `block in render_output'
        2: from /private/tmp/test/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.20.6/lib/inspec/reporters.rb:28:in `render'
        1: from /private/tmp/test/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.20.6/lib/inspec/plugin/v2/registry.rb:77:in `find_activator'
Inspec::Plugin::V2::LoadError (Plugin hooks search returned zero results for filter {:plugin_type=>:reporter, :activator_name=>:cli})
irb(main):003:0> 
```

**Comment by james-stocks** [comment]
This looks like it occurs because InSpec loads its plugins as part of the CLI class. When using InSpec as a gem, no plugin loading happens. The last change we made to put the CLI reporter into a plugin therefore breaks InSpec for those who depend on InSpec as a gem (i.e. everyone using kitchen).

We'll revert for now.

**Comment by james-stocks** [comment]
Hi @crazymind1337 we reverted the breaking change in today's 4.20.10 release; apologies for the disruption.

We want to do https://github.com/inspec/inspec/issues/5106 next to get integration testing (for example with Test Kitchen) running for every commit.

**Comment by crazymind1337** [comment]
thanks dude for that very fast fix!
