### ISSUE TITLE
InSpec fails if one check is written wrongly

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#521]
Let's say I have two tests and one uses a resource that is not available (e.g. may it be an older version of inspec):

```
cat wrong_script.rb 
describe not_available("abc") do
# nothing
end


describe file('/etc/passwd') do
 it { should be_file }
end
```

This :boom: 

```
inspec exec wrong_script.rb
wrong_script.rb:1:in `load': undefined method `not_available' for #<#<Class:0x007fa61dd59c90>:0x007fa61dd599e8> (NoMethodError)
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile_context.rb:34:in `instance_eval'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/profile_context.rb:34:in `load'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:86:in `add_content'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:60:in `block in add_profile'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:57:in `each'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:57:in `add_profile'
    from /Users/chartmann/Development/compliance/inspec/lib/inspec/runner.rb:67:in `add_target'
    from /Users/chartmann/Development/compliance/inspec/lib/utils/base_cli.rb:51:in `block in run_tests'
    from /Users/chartmann/Development/compliance/inspec/lib/utils/base_cli.rb:51:in `each'
    from /Users/chartmann/Development/compliance/inspec/lib/utils/base_cli.rb:51:in `run_tests'
    from /Users/chartmann/Development/compliance/inspec/bin/inspec:110:in `exec'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/chartmann/Development/compliance/inspec/bin/inspec:166:in `<top (required)>'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/inspec:23:in `load'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/inspec:23:in `<main>'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/chartmann/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

My expectation would be, that this test is marked as failed or skipped, but the rest continues. The same applies for the `inspec check` command. This should always return in a good state, no matter what is in the ruby file.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
