### ISSUE TITLE
LoadError: cannot load such file -- aws-sdk

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec#5254]
# Describe the problem

I'd like to use aws-sdk within profiles.
Gemfile is used to prepare the environment and aws-sdk is installed using bundle (locally).
After adding `require 'aws-sdk'` to my `default.rb` file and running the control, I get the error message:
```
$  bundle exec inspec exec test/integration/default --target aws://;
bundler: failed to load command: inspec (/tmp/inspectest/vendor/bundle/ruby/2.6.0/bin/cinc-auditor)
LoadError: cannot load such file -- aws-sdk
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/dsl_shared.rb:33:in `require'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/dsl_shared.rb:33:in `require'
  test/integration/default/controls/default.rb:5:in `load_with_context'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/profile_context.rb:170:in `instance_eval'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/profile_context.rb:170:in `load_with_context'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/profile_context.rb:154:in `load_control_file'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/profile.rb:220:in `block in collect_tests'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/profile.rb:215:in `each'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/profile.rb:215:in `collect_tests'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/runner.rb:119:in `block in load'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/runner.rb:101:in `each'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/runner.rb:101:in `load'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/runner.rb:135:in `run'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/cli.rb:279:in `exec'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/inspec-core-4.23.4/lib/inspec/base_cli.rb:35:in `start'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/gems/cinc-auditor-bin-4.23.4/bin/cinc-auditor:12:in `<top (required)>'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/bin/cinc-auditor:23:in `load'
  /tmp/inspectest/vendor/bundle/ruby/2.6.0/bin/cinc-auditor:23:in `<top (required)>'

```

**Comment by tbugfinder** [comment]
Version: 4.23.4

**Comment by tbugfinder** [comment]
I missed `aws-sdk-core` vs. `aws-sdk` for version 3.
