### ISSUE TITLE
require "inspec" fails with NameError: undefined method `parse_array' for class `Thor::Arguments'

### ISSUE THREAD

**Issue by aaron-lane** [inspec/inspec#5387]
# Describe the problem

It appears that https://github.com/inspec/inspec/pull/5358/commits/cdfb325ca325725ecaa948db7fd064decc3dfd1b broke integration with other gems which also depend on thor. In this case, kitchen-terraform depends on inspec and test-kitchen, which both depend on thor. Kitchen-Terraform started seeing the following stacktrace caused by `require "inspec"` after updating to inspec 4.24.32 (though the commit in question is from 4.24.23):

```
NameError: undefined method `parse_array' for class `Thor::Arguments'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/base_cli.rb:11:in `<class:Arguments>'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/base_cli.rb:10:in `<top (required)>'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/plugin/v2/plugin_types/cli.rb:1:in `require'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/plugin/v2/plugin_types/cli.rb:1:in `<top (required)>'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/plugin/v2.rb:38:in `require'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/plugin/v2.rb:38:in `block in <top (required)>'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/plugin/v2.rb:38:in `each'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/plugin/v2.rb:38:in `<top (required)>'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/input_registry.rb:6:in `require'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/input_registry.rb:6:in `<top (required)>'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/profile.rb:6:in `require'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec/profile.rb:6:in `<top (required)>'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec.rb:9:in `require'
/kitchen-terraform/vendor/bundle/ruby/2.7.0/gems/inspec-core-4.24.32/lib/inspec.rb:9:in `<top (required)>'
/kitchen-terraform/lib/kitchen/terraform/inspec_runner.rb:17:in `require'
/kitchen-terraform/lib/kitchen/terraform/inspec_runner.rb:17:in `<top (required)>'
/kitchen-terraform/lib/kitchen/verifier/terraform.rb:153:in `require'
```

## Possible Solution

One solution would be to revert `require "thor" unless defined?(Thor)` to just `require "thor"`. A different solution would be to reimplement `Inspec::BaseCLI` in a way that does not require monkey-patching of `Thor::Arguments`, though that is obviously much more work.

**Comment by aaron-lane** [comment]
Thanks @clintoncwolfe 🎉
