### ISSUE TITLE
Aborted (core dumped) when trying to target an SSH client

### ISSUE THREAD

**Issue by LoZZoL** [inspec/inspec#5585]
I've just installed Inspec and have loved the promise of running vulnerability scans using community driven 'recipes'. I've installed to a CentOS 8.4 machine and have:

1. Cloned the dev-sec/linux-baseline to my machine: `git clone https://github.com/dev-sec/linux-baseline`
2. Run `inspec exec linux-baseline` against the local machine - clear and concise success/failure output returned. Great.
3. Run the same command against a remote SSH client (using private key): `inspec exec linux-baseline -t ssh://user@remotecentosbox -p xxx22` or `inspec exec linux-baseline -t ssh://user@remotecentosbox -p xxx22 -i ~/.ssh/id_rsa`

Any time I try step 3, on any SSH client (Centos 8.4 or Ubuntu 20.04) I get Aborted (core dumped) and a whole lot of memory information etc.

I suppose my next step is to try installing on another Linux client, but the machine I've installed to is very basic (only has Ansible installed) so I thought I'd ask the question here in case I was doing something very silly.

CentOS Linux release 8.4.2105
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
inspec version: 4.37.30

Very happy to submit any other information that may be useful. Thanks for looking.

**Comment by ramereth** [comment]
@LoZZoL is this error similar to what's seen in this issue? https://github.com/chef/chef-workstation/issues/2090

**Comment by LoZZoL** [comment]
Similar I think, here's the backtrace:

```
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/x25519-1.0.8/lib/x25519.rb:81: [BUG] Illegal instruction at 0x00007f8de3bfae55
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0051 p:---- s:0356 e:000355 CFUNC  :scalarmult
c:0050 p:0026 s:0350 e:000349 BLOCK  /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/x25519-1.0.8/lib/x25519.rb:81 [FINISH]
c:0049 p:---- s:0345 e:000344 CFUNC  :each
c:0048 p:0020 s:0341 e:000340 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/x25519-1.0.8/lib/x25519.rb:80
c:0047 p:0061 s:0337 e:000336 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/x25519-1.0.8/lib/x25519.rb:95 [FINISH]
c:0046 p:---- s:0334 e:000333 CFUNC  :require
c:0045 p:0195 s:0329 e:000328 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0044 p:0011 s:0312 e:000311 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/curve25519_sha256.rb:3 [FINISH]
c:0043 p:---- s:0309 e:000308 CFUNC  :require
c:0042 p:0195 s:0304 e:000303 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0041 p:0005 s:0287 e:000286 CLASS  /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/curve25519_sha256_loader.rb:8
c:0040 p:0007 s:0283 e:000282 CLASS  /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/curve25519_sha256_loader.rb:6
c:0039 p:0007 s:0280 e:000279 CLASS  /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/curve25519_sha256_loader.rb:4
c:0038 p:0007 s:0277 e:000276 CLASS  /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/curve25519_sha256_loader.rb:3
c:0037 p:0007 s:0274 e:000273 CLASS  /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/curve25519_sha256_loader.rb:2
c:0036 p:0007 s:0271 e:000270 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/curve25519_sha256_loader.rb:1 [FINISH]
c:0035 p:---- s:0268 e:000267 CFUNC  :require
c:0034 p:0195 s:0263 e:000262 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0033 p:0047 s:0246 e:000245 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex.rb:8 [FINISH]
c:0032 p:---- s:0243 e:000242 CFUNC  :require
c:0031 p:0195 s:0238 e:000237 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0030 p:0041 s:0221 e:000220 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:7 [FINISH]
c:0029 p:---- s:0218 e:000217 CFUNC  :require
c:0028 p:0195 s:0213 e:000212 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0027 p:0029 s:0196 e:000195 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:6 [FINISH]
c:0026 p:---- s:0193 e:000192 CFUNC  :require
c:0025 p:0195 s:0188 e:000187 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0024 p:0140 s:0171 e:000170 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:12 [FINISH]
c:0023 p:---- s:0168 e:000167 CFUNC  :require
c:0022 p:0195 s:0163 e:000162 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0021 p:0030 s:0146 e:000145 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.7.2/lib/train/transports/ssh.rb:20 [FINISH]
c:0020 p:---- s:0143 e:000142 CFUNC  :require
c:0019 p:0195 s:0138 e:000137 METHOD /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83
c:0018 p:0045 s:0121 e:000120 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.7.2/lib/train.rb:44
c:0017 p:0005 s:0112 e:000111 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.7.2/lib/train.rb:28
c:0016 p:0013 s:0106 e:000105 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/config.rb:159
c:0015 p:0062 s:0097 e:000096 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/config.rb:121
c:0014 p:0004 s:0091 e:000090 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/backend.rb:31
c:0013 p:0018 s:0081 e:000080 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/runner.rb:86
c:0012 p:0235 s:0077 e:000076 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/runner.rb:78 [FINISH]
c:0011 p:---- s:0071 e:000070 CFUNC  :new
c:0010 p:0034 s:0066 e:000065 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/cli.rb:282
c:0009 p:0054 s:0058 e:000057 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27
c:0008 p:0040 s:0050 e:000049 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127
c:0007 p:0235 s:0043 e:000042 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392
c:0006 p:0062 s:0030 e:000029 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485
c:0005 p:0045 s:0023 e:000022 METHOD /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.30/lib/inspec/base_cli.rb:35
c:0004 p:0115 s:0017 e:000016 TOP    /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.37.30/bin/inspec:11 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:2017 s:0008 E:0018b0 EVAL   /usr/bin/inspec:259 [FINISH]
c:0001 p:0000 s:0003 E:0002f0 (none) [FINISH]
```

**Comment by ramereth** [comment]
Yup, that's the same problem.

**Comment by LoZZoL** [comment]
Is it likely specific to version 4.37.30? Worth me trying a previous version?

**Comment by ramereth** [comment]
I suspect this was introduced in https://github.com/inspec/inspec/pull/5563/commits/4c0eb932a5181873c63b02f592bfb84882912b78 so you would need to try something `< 4.37.29`.

**Comment by LoZZoL** [comment]
Thanks. I tried inspec-4.37.25-1.el8.x86_64 but, using the same command, it just hangs. I realise that it's not relevant to the current version, but the (interrupt) back trace is:

```
^CTraceback (most recent call last):
        64: from /usr/bin/inspec:258:in `<main>'
        63: from /usr/bin/inspec:258:in `load'
        62: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.37.25/bin/inspec:11:in `<top (required)>'
        61: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.25/lib/inspec/base_cli.rb:35:in `start'
        60: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        59: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        58: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        57: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        56: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.25/lib/inspec/cli.rb:285:in `exec'
        55: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.25/lib/inspec/runner.rb:136:in `run'
        54: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.25/lib/inspec/runner.rb:165:in `run_tests'
        53: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.25/lib/inspec/runner_rspec.rb:82:in `run'
        52: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
        51: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
        50: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
        49: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
        48: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
        47: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
        46: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
        45: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
        44: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
        43: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
        42: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
        41: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
        40: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
        39: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
        38: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
        37: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
        36: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
        35: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
        34: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
        33: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
        32: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
        31: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
        30: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
        29: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
        28: from linux-baseline/controls/os_spec.rb:175:in `block (3 levels) in load_with_context'
        27: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:159:in `should'
        26: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:317:in `block in let'
        25: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch_or_store'
        24: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch'
        23: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:156:in `block in fetch_or_store'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.2/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `block (2 levels) in fetch_or_store'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `fetch'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `block (3 levels) in fetch_or_store'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:317:in `block (2 levels) in let'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `block (2 levels) in its'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `inject'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `each'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:134:in `block (3 levels) in its'
        13: from libraries/suid_check.rb:26:in `diff'
        12: from libraries/suid_check.rb:22:in `permissions'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.25/lib/inspec/resources/command.rb:64:in `stdout'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.37.25/lib/inspec/resources/command.rb:53:in `result'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.7.2/lib/train/plugins/base_connection.rb:151:in `run_command'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.7.2/lib/train/transports/ssh_connection.rb:252:in `run_command_via_connection'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.7.2/lib/train/transports/ssh_connection.rb:360:in `execute_on_channel'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `block in loop'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:227:in `process'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:30:in `process'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:109:in `ev_select_and_postprocess'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:109:in `select': Interrupt
```

**Comment by LoZZoL** [comment]
I'll try an (even) older version to see if it helps.

**Comment by Vasu1105** [comment]
@LoZZoL I was not able to reproduce this issue. What is the format used for ssh key ?

**Comment by LoZZoL** [comment]
@Vasu1105 - not exactly sure how to check - I believe it's a SHA256 keypair. Does that help?

**Comment by tas50** [comment]
This new gem needs to get backed out. We had the same issue with chef/chef https://github.com/inspec/inspec/commit/4c0eb932a5181873c63b02f592bfb84882912b78

**Comment by rx294** [comment]
Experiencing same issue... last working version 4.37.25
