### ISSUE TITLE
Issue loading inspec-aws cannot load such file -- aws-sdk-batch

### ISSUE THREAD

**Issue by cbarmstrong** [inspec/inspec#5626]
### 🎛 ImportError when using inspec in docker

bug report

I'm trying to execute InSpec using docker to query aws resources to verify they are in the correct state. As we have a locked down network I'm copying in the inspec-aws zip from a local nexus repo. This works when I use v1.21.0 of inspec-aws but not a higher version such as 1.59.0 which has more resources which I'd like to use.

I notice that the train-aws plugin in the container is not the newest version and wonder if this is the issue?

```bash
docker run -e AWS_REGION=eu-west-1 --rm -v 'inspec:/share' chef/inspec plugin list --chef-license=accept
+---------------------------------------------+
✔ 1 product license accepted.
+---------------------------------------------+
┌───────────────────────────┬─────────┬──────────────┬─────────┐
├───────────────────────────┼─────────┼──────────────┼─────────┤
│ inspec-artifact           │ 4.41.2  │ core         │ 2       │
│ inspec-compliance         │ 4.41.2  │ core         │ 2       │
│ inspec-habitat            │ 4.41.2  │ core         │ 2       │
│ inspec-init               │ 4.41.2  │ core         │ 2       │
│ inspec-plugin-manager-cli │ 4.41.2  │ core         │ 2       │
│ inspec-reporter-html2     │ 4.41.2  │ core         │ 2       │
│ inspec-reporter-json-min  │ 4.41.2  │ core         │ 2       │
│ inspec-reporter-junit     │ 4.41.2  │ core         │ 2       │
│ inspec-supermarket        │ 4.41.2  │ core         │ 0       │
│ train-aws                 │ 0.1.18  │ gem (system) │ train-1 │
│ train-habitat             │ 0.2.22  │ gem (system) │ train-1 │
│ train-winrm               │ 0.2.12  │ gem (system) │ train-1 │
└───────────────────────────┴─────────┴──────────────┴─────────┘
```

train-aws at v0.2.16

I'm receiving the below trace:

```bash
docker run --env-file env.vars -e AWS_REGION=eu-west-1 --rm -v 'inspec:/share' chef/inspec exec -t aws:// bluegreen --chef-license=accept --input blue_asg_size=1 green_asg_size=0 --no-color
+---------------------------------------------+
✔ 1 product license accepted.
+---------------------------------------------+
/opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- aws-sdk-batch (LoadError)
	from /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/dsl_shared.rb:33:in `require'
	from libraries/aws_backend.rb:4:in `create'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/dsl_shared.rb:47:in `eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/dsl_shared.rb:47:in `require'
	from libraries/aws_alb.rb:3:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:170:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:170:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:159:in `load_library_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:144:in `block in load_libraries'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:143:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:143:in `load_libraries'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:310:in `load_libraries'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:303:in `block in load_libraries'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:284:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:284:in `each_with_index'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:284:in `load_libraries'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/runner.rb:108:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/runner.rb:102:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/runner.rb:102:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/runner.rb:136:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/cli.rb:287:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/base_cli.rb:35:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.41.2/bin/inspec:11:in `<top (required)>'
	from /opt/inspec/bin/inspec:252:in `load'
	from /opt/inspec/bin/inspec:252:in `<main>'

```

### 🌍 InSpec and Platform Version

Inspec version is 4.41.2 on RHEL7

### 🤔 Replication Case

To replicate create an empty aws profile, with the following depends syntax:
```yaml
depends:
  - name: inspec-aws
    path: inspec-aws-master.zip
```

Manually copy https://github.com/inspec/inspec-aws/archive/refs/tags/v1.59.0.zip to inspec-aws-master.zip

Add a basic test in the controls dir, and execute via. docker:
```bash
function inspec { docker run -e AWS_REGION=eu-west-1 -it --rm -v $(pwd):/share chef/inspec "$@"; }
inspec exec -t aws:// bluegreen --chef-license=accept
```

### 💁 Possible Solutions

Possibly needs an upgrade to the aws plugin, but not sure

### 💻 Stacktrace

Stacktrace is above

**Comment by aaronlippold** [comment]
`aws-sdk-eventbridge` also seems to be an issue as well in some cases
