### ISSUE TITLE
Issues with 'inspec compliance upload'

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#572]
```
I, [2016-03-23T07:11:51.348052 #6989]  INFO -- : Checking profile in ssg-rhel6-c2s/
I, [2016-03-23T07:11:51.348218 #6989]  INFO -- : Metadata OK.
I, [2016-03-23T07:11:51.833930 #6989]  INFO -- : Found 134 controls.
I, [2016-03-23T07:11:51.833998 #6989]  INFO -- : Verify all controls in controls/05_kernel_parameters_networking_spec.rb
I, [2016-03-23T07:11:51.834037 #6989]  INFO -- : Verify all controls in controls/04_selinux_spec.rb
I, [2016-03-23T07:11:51.834057 #6989]  INFO -- : Verify all controls in controls/07_ipv6_spec.rb
I, [2016-03-23T07:11:51.834081 #6989]  INFO -- : Verify all controls in controls/03_account_access_controls_spec.rb
W, [2016-03-23T07:11:51.834200 #6989]  WARN -- : Control account-access-controls-01.08 has no tests defined
W, [2016-03-23T07:11:51.834251 #6989]  WARN -- : Control account-access-controls-01.09 has no tests defined
I, [2016-03-23T07:11:51.834293 #6989]  INFO -- : Verify all controls in controls/02_filepermission_mask_spec.rb
I, [2016-03-23T07:11:51.834328 #6989]  INFO -- : Verify all controls in controls/09_iptables_spec.rb
I, [2016-03-23T07:11:51.834343 #6989]  INFO -- : Verify all controls in controls/01_install_maintain_software_spec.rb
I, [2016-03-23T07:11:51.834366 #6989]  INFO -- : Verify all controls in controls/06_wireless_spec.rb
I, [2016-03-23T07:11:51.834379 #6989]  INFO -- : Verify all controls in controls/08_uncommon_network_protocol_spec.rb
I, [2016-03-23T07:11:51.834396 #6989]  INFO -- : Verify all controls in controls/10_logging_spec.rb
Profile is valid
Generate temporary profile archive at /tmp/ssg-rhel6-c2s20160323-6989-qxd50t.tar.gz
I, [2016-03-23T07:11:52.182209 #6989]  INFO -- : Generate archive /home/alippold/cocreate-compliance/compliance-profiles/ssg-rhel6-c2s.tar.gz.
I, [2016-03-23T07:11:52.269373 #6989]  INFO -- : Finished archive generation.
Start upload to alippold/ssg-rhel6-c2s
Uploading to https://cocreate-aaronl.isee.mitre.org/api//owners/alippold/compliance/ssg-rhel6-c2s/tar
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!': 503 "Service Unavailable" (Net::HTTPFatalError)
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:915:in `connect'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1375:in `request'
    from /home/alippold/.chefdk/gem/ruby/2.1.0/gems/inspec-0.16.2/lib/bundles/inspec-compliance/api.rb:126:in `post_file'
    from /home/alippold/.chefdk/gem/ruby/2.1.0/gems/inspec-0.16.2/lib/bundles/inspec-compliance/cli.rb:114:in `upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/alippold/.chefdk/gem/ruby/2.1.0/gems/inspec-0.16.2/bin/inspec:9:in `<top (required)>'
    from /usr/bin/inspec:22:in `load'
    from /usr/bin/inspec:22:in `<main>'
```

**Comment by aaronlippold** [comment]
per @srenatus - I edited the ~/.inspec/compliance/config.json file to remove the extra '/' after /api but still no go.

```
Uploading to https://cocreate-aaronl.isee.mitre.org/api/owners/alippold/compliance/ssg-rhel6-c2s/tar
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!': 503 "Service Unavailable" (Net::HTTPFatalError)
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:915:in `connect'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1375:in `request'
    from /home/alippold/.chefdk/gem/ruby/2.1.0/gems/inspec-0.16.2/lib/bundles/inspec-compliance/api.rb:126:in `post_file'
    from /home/alippold/.chefdk/gem/ruby/2.1.0/gems/inspec-0.16.2/lib/bundles/inspec-compliance/cli.rb:114:in `upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/alippold/.chefdk/gem/ruby/2.1.0/gems/inspec-0.16.2/bin/inspec:9:in `<top (required)>'
    from /usr/bin/inspec:22:in `load'
    from /usr/bin/inspec:22:in `<main>'
```

**Comment by aaronlippold** [comment]
Still having issues with upload. Looks like a possible issue with the web server
