### ISSUE TITLE
undefined method `>' for nil:NilClass - official example from the Inspec website

### ISSUE THREAD

**Issue by neidiom** [inspec/inspec#5751]
There is an error in the official example that does not take into account enabled users which return nil. Also sometimes String is returned and not an Integer.

I am trying to run an official example from the Inspec website, this one https://docs.chef.io/inspec/resources/shadow/#examples 

````
# Method form, simple
# Select just the root user (direct equality)
describe shadow.where(user: 'root') do
  its ('count') { should eq 1 }
end

# Method form, with a regex
# Select all users whose names begin with smb
describe shadow.where(user: /^smb/) do
  its ('count') { should eq 2 }
end

# Block form
# Select users whose passwords have expired
describe shadow.where { expiry_date > 0 } do
  # This test directly asserts that there should be 0 such users
  its('count') { should eq 0 }
  # But if the count test fails, this test outputs the users that are causing the failure.
  its('users') { should be_empty }
end
````

I save it the file named e3.rb

and then run the command

````
 inspec exec e3.rb 
````

and get this error

````
[2021-11-29T13:29:23+01:00] ERROR: Failed to load profile tests from e3.rb: Failed to load source for e3.rb: undefined method `>' for nil:NilClass

Profile:         tests from e3.rb (tests from e3.rb)
Version:         (not specified)
Failure Message: Failed to load source for e3.rb: undefined method `>' for nil:NilClass
Target:          local://

     No tests executed.

Test Summary: 0 successful, 0 failures, 0 skipped
````

Inspec version: 4.50.3

If you read the doc at https://docs.chef.io/inspec/resources/shadow/#expiry_date you will see that expiry_date is supposed to be an integer OR nil for enabled users.

**Comment by neidiom** [comment]
when I downgrade to 3.9.3 I get this


````
inspec exec e3.rb --log-level=debug
[2021-11-29T14:01:31+01:00] DEBUG: Option backend_cache is enabled
[2021-11-29T14:01:31+01:00] DEBUG: Resolve e3.rb into cache /root/.inspec/cache
[2021-11-29T14:01:31+01:00] DEBUG: Dependency does not exist in the cache e3.rb
[2021-11-29T14:01:31+01:00] DEBUG: Starting run with targets: ["Inspec::Profile<tests from e3.rb>"]
[2021-11-29T14:01:31+01:00] DEBUG: Loading e3.rb into #<Inspec::ProfileContext:0x0000000005e553d0>
Traceback (most recent call last):
	26: from /usr/bin/inspec:123:in `<main>'
	25: from /usr/bin/inspec:123:in `load'
	24: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/bin/inspec:12:in `<top (required)>'
	23: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	22: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/cli.rb:265:in `exec'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/runner.rb:116:in `run'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/runner.rb:87:in `load'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/runner.rb:87:in `each'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/runner.rb:105:in `block in load'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/profile.rb:193:in `collect_tests'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/profile.rb:193:in `each'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/profile.rb:196:in `block in collect_tests'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/profile_context.rb:144:in `load_control_file'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/profile_context.rb:160:in `load_with_context'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/inspec/profile_context.rb:160:in `instance_eval'
	 8: from e3.rb:15:in `load_with_context'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/utils/filter.rb:363:in `block (2 levels) in install_filter_methods_on_resource'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/utils/filter.rb:363:in `call'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/utils/filter.rb:120:in `where'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/utils/filter.rb:120:in `find_all'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/utils/filter.rb:120:in `each'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/utils/filter.rb:120:in `block in where'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.9.3/lib/utils/filter.rb:120:in `instance_eval'
e3.rb:15:in `block in load_with_context': undefined method `>' for nil:NilClass (NoMethodError)
````

**Comment by neidiom** [comment]
This link https://docs.chef.io/inspec/resources/shadow/#expiry_date states `An integer reflecting the number of days` but if I run this code

````
cat e1.rb 
puts users = inspec.shadow.where { puts expiry_date.is_a?Integer }.users
puts users = inspec.shadow.where { puts expiry_date.class }.users
````

I get this

````
~# inspec exec e1.rb --log-level=debug
[2021-11-29T14:36:57+01:00] DEBUG: Option backend_cache is enabled
[2021-11-29T14:36:57+01:00] DEBUG: Resolve e1.rb into cache /root/.inspec/cache
[2021-11-29T14:36:57+01:00] DEBUG: Dependency does not exist in the cache e1.rb
[2021-11-29T14:36:57+01:00] DEBUG: Starting run with targets: ["Inspec::Profile<tests from e1.rb>"]
[2021-11-29T14:36:57+01:00] DEBUG: Loading e1.rb into #<Inspec::ProfileContext:0x00000000049845a0>
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
NilClass
String
NilClass
NilClass
String
String
NilClass
NilClass
String
NilClass
NilClass
String
FilterTable::Trace

Profile: tests from e1.rb (tests from e1.rb)
Version: (not specified)
Target:  local://

     No tests executed.

Test Summary: 0 successful, 0 failures, 0 skipped
````

**Comment by neidiom** [comment]
So since we have enabled users we need to write the example as this:

````
describe shadow.where { !expiry_date.nil? && expiry_date > 0 } do
  # This test directly asserts that there should be 0 such users
  its('count') { should eq 0 }
  # But if the count test fails, this test outputs the users that are causing the failure.
  its('users') { should be_empty }
end
````

**Comment by neidiom** [comment]
Getting this error message as well

````
Failure Message: Failed to load source for d.rb: undefined method `-' for "19057":String
````

For this example

https://docs.chef.io/inspec/resources/shadow/#expiry_date

````
# Ensure no one is disabled due to a old password
describe shadow.where { !expiry_date.nil? } do
  its('users') { should be_empty }
end

# Ensure no one is disabled for more than 14 days
describe shadow.where { !expiry_date.nil? && expiry_date - Date.new(1970,1,1) > 14} do
  its('users') { should be_empty }
end
````

**Comment by neidiom** [comment]
This does not return an error

````
# Ensure no one is disabled for more than 14 days
describe shadow.where { !expiry_date.nil? && !expiry_date.is_a?(String) && expiry_date - Date.new(1970,1,1) > 14} do
  its('users') { should be_empty }
end
````
