### ISSUE TITLE
Inspec Failing whenever trying to use SSH (Windows and Ubuntu) Train::PlatformDetectionFailed.

### ISSUE THREAD

**Issue by KodySalak** [inspec/inspec#5756]
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug Report

### Issue
The issue is I cannot get an audit that requires SSH to run, no matter the OS it seems. I have tried on both Windows and Ubuntu with the same error coming up, Train::PlatformDetectionFailed. Other InSpec profiles work, but they also don't use SSH. 

### 🌍 InSpec and Platform Version

Inspec 4.50.3 - Ubuntu 20.04 LTS, Windows 10 21H1, Windows 11 Full Patched.

### 🤔 Replication Case

All I have to do to get this to replicate is to run this: inspec exec vmware-vcsa-6.7-stig-baseline/ -t ssh://root@internal.vcenter.local --password 'REDACTED' --input syslogServer=nologging.local:514 ntpServer1=RE.DA.CT.ED --reporter=cli json:/tmp/stig/output.json

### 💁 Possible Solutions

N/A

### 💻 Stacktrace

```Windows: 
Traceback (most recent call last):
        20: from C:/opscode/inspec/bin/inspec:300:in '<main>'
        19: from C:/opscode/inspec/bin/inspec:300:in 'load'
        18: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.50.3/bin/inspec:11:in '<top (required)>'
        17: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/base_cli.rb:35:in 'start'
        16: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in 'start'
        15: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in 'dispatch'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in 'invoke_command'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in 'run'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/cli.rb:301:in 'exec'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/cli.rb:301:in 'new'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/runner.rb:79:in 'initialize'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/runner.rb:87:in 'configure_transport'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/backend.rb:38:in 'create'
         7: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh.rb:85:in 'connection'
         6: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh.rb:259:in 'create_new_connection'
         5: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh.rb:259:in 'new'
         4: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh_connection.rb:60:in 'initialize'
         3: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/extras/command_wrapper.rb:190:in 'load'
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/plugins/base_connection.rb:123:in 'platform'
         1: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/platforms/detect.rb:7:in 'scan'
C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-core-3.8.1/lib/train/platforms/detect/scanner.rb:39:in 'scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)

Linux:
Traceback (most recent call last):
        20: from /usr/local/bin/inspec:23:in '<main>'
        19: from /usr/local/bin/inspec:23:in 'load'
        18: from /var/lib/gems/2.7.0/gems/inspec-bin-4.50.3/bin/inspec:11:in '<top (required)>'
        17: from /var/lib/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/base_cli.rb:35:in 'start'
        16: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in 'start'
        15: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in 'dispatch'
        14: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in 'invoke_command'
        13: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in 'run'
        12: from /var/lib/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/cli.rb:301:in 'exec'
        11: from /var/lib/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/cli.rb:301:in 'new'
        10: from /var/lib/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/runner.rb:79:in 'initialize'
         9: from /var/lib/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/runner.rb:87:in 'configure_transport'
         8: from /var/lib/gems/2.7.0/gems/inspec-core-4.50.3/lib/inspec/backend.rb:38:in 'create'
         7: from /var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh.rb:85:in 'connection'
         6: from /var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh.rb:259:in 'create_new_connection'
         5: from /var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh.rb:259:in 'new'
         4: from /var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/transports/ssh_connection.rb:60:in 'initialize'
         3: from /var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/extras/command_wrapper.rb:190:in 'load'
         2: from /var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/plugins/base_connection.rb:123:in 'platform'
         1: from /var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/platforms/detect.rb:7:in 'scan'
/var/lib/gems/2.7.0/gems/train-core-3.8.1/lib/train/platforms/detect/scanner.rb:39:in 'scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)```

**Comment by KodySalak** [comment]
This was a vCenter issue. Because of the default shell used by vCenter not being bash, it was failing to detect. Once the shell was switched, it worked fine. Closing...
