### ISSUE TITLE
profile upload fails with a timeout error

### ISSUE THREAD

**Issue by rishichawda** [inspec/inspec#5801]
# Describe the problem

When uploading a custom profile using `inspec compliance upload` command, the command fails with a timeout. Here's the stack trace: 
```bash
I, [2022-01-18T10:29:03.530165 #5984]  INFO -- : Checking profile in cdqs-inspec-profile
I, [2022-01-18T10:29:03.530486 #5984]  INFO -- : Metadata OK.
I, [2022-01-18T10:29:03.542706 #5984]  INFO -- : Found 2 controls.
I, [2022-01-18T10:29:05.964320 #5984]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at /var/folders/77/vwmr7xt54zz5mw_hv1w8_fb4wzgkl0/T/cdqs-inspec-profile20220118-5984-860fcy.tar.gz
I, [2022-01-18T10:29:06.070855 #5984]  INFO -- : Generate archive /var/folders/77/vwmr7xt54zz5mw_hv1w8_fb4wzgkl0/T/cdqs-inspec-profile20220118-5984-860fcy.tar.gz.
I, [2022-01-18T10:29:06.078979 #5984]  INFO -- : Finished archive generation.
Start upload to admin/cdqs-inspec-profile
Uploading to Chef Automate
/opt/chef-workstation/embedded/lib/ruby/3.0.0/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1521:in `request'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1514:in `block in request'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:960:in `start'
	from /opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1512:in `request'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/inspec-core-4.50.3/lib/plugins/inspec-compliance/lib/inspec-compliance/http.rb:85:in `block in post_multipart_file'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/inspec-core-4.50.3/lib/plugins/inspec-compliance/lib/inspec-compliance/http.rb:80:in `open'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/inspec-core-4.50.3/lib/plugins/inspec-compliance/lib/inspec-compliance/http.rb:80:in `post_multipart_file'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/inspec-core-4.50.3/lib/plugins/inspec-compliance/lib/inspec-compliance/api.rb:101:in `upload'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/inspec-core-4.50.3/lib/plugins/inspec-compliance/lib/inspec-compliance/cli.rb:204:in `upload'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/inspec-core-4.50.3/lib/inspec/base_cli.rb:35:in `start'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/inspec-bin-4.50.3/bin/inspec:11:in `<top (required)>'
	from /usr/local/bin/inspec:380:in `load'
	from /usr/local/bin/inspec:380:in `<main>'
```

To reproduce: 

1. Login with `inspec compliance login` command as admin.
2. Upload profile using `inspec compliance upload`.

**Comment by rishichawda** [comment]
This isn't happening anymore. Closing it.

**Comment by rishichawda** [comment]
We're seeing this again while uploading profiles. Reopening this issue.

**Comment by Nik08** [comment]
@rishichawda Yes it seems like some issue with chef automate. Team is looking into it.

**Comment by Vasu1105** [comment]
Closing this Issue. It is fixed here https://github.com/inspec/inspec/pull/5989
