### ISSUE TITLE
sshd_config Banner not proerly parsed

### ISSUE THREAD

**Issue by YarNhoj** [inspec/inspec#584]
I've noticed that several of the sshd_config checks fail.

Comparison failures.

```
  1) File etc/ssh/sshd_config owner should eq "root"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "root"
            got: nil

       (compared using ==)
     # ./controls/6_2_config_ssh_spec.rb:30:in `block (3 levels) in load'

  2) File etc/ssh/sshd_config group should eq "root"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: "root"
            got: nil

       (compared using ==)
     # ./controls/6_2_config_ssh_spec.rb:31:in `block (3 levels) in load'

  3) File etc/ssh/sshd_config mode should eq 384
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: 384
            got: nil

       (compared using ==)
     # ./controls/6_2_config_ssh_spec.rb:32:in `block (3 levels) in load'
```

These Checks say they aren't responding to exist? or exists?

```
  4) SSH Configuration AllowUsers should exist
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected [] to exist but it does not respond to either `exist?` or `exists?`
     # ./controls/6_2_config_ssh_spec.rb:123:in `block (3 levels) in load'

  5) SSH Configuration AllowGroups should exist
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected [] to exist but it does not respond to either `exist?` or `exists?`
     # ./controls/6_2_config_ssh_spec.rb:124:in `block (3 levels) in load'

  6) SSH Configuration DenyUsers should exist
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected [] to exist but it does not respond to either `exist?` or `exists?`
     # ./controls/6_2_config_ssh_spec.rb:125:in `block (3 levels) in load'

  7) SSH Configuration DenyGroups should exist
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected [] to exist but it does not respond to either `exist?` or `exists?`
     # ./controls/6_2_config_ssh_spec.rb:126:in `block (3 levels) in load'
```

And here we get an array error.

```
  8) SSH Configuration Banner should include ["/etc/issue", "/etc/issue.net"]
     Failure/Error: return true if actual.include?(expected_item)

     TypeError:
       no implicit conversion of Array into String
     # ./controls/6_2_config_ssh_spec.rb:135:in `block (3 levels) in load'
```

Relative System Info

```
Server
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

chef-compliance 0.16.9

Node
CentOS Linux release 7.1.1503 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core) 
CentOS Linux release 7.1.1503 (Core)
```

sshd_config file

```
#   $OpenBSD: sshd_config,v 1.93 2014/01/10 05:59:19 djm Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/local/bin:/usr/bin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

# If you want to change the port on a SELinux system, you have to tell
# SELinux about this change.
# semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
#
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

# The default requires explicit activation of protocol 1
Protocol 2

# HostKey for protocol version 1
#HostKey /etc/ssh/ssh_host_key
# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Lifetime and size of ephemeral version 1 server key
#KeyRegenerationInterval 1h
#ServerKeyBits 1024

# Ciphers and keying
#RekeyLimit default none
Ciphers aes128-ctr,aes192-ctr,aes256-ctr

# Logging
# obsoletes QuietMode and FascistLogging
#SyslogFacility AUTH
SyslogFacility AUTHPRIV
LogLevel INFO

# Authentication:

#LoginGraceTime 2m
PermitRootLogin no
#StrictModes yes
MaxAuthTries 4
#MaxSessions 10

#RSAAuthentication yes
#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile  .ssh/authorized_keys

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#RhostsRSAAuthentication no
# similar for protocol version 2
HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# RhostsRSAAuthentication and HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
PermitEmptyPasswords no

# Change to no to disable s/key passwords
#ChallengeResponseAuthentication yes

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no
#KerberosUseKuserok yes

# GSSAPI options
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no
#GSSAPIEnablek5users no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
# WARNING: 'UsePAM no' is not supported in Red Hat Enterprise Linux and may cause several
# problems.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
AllowUsers
AllowGroups
DenyUsers
DenyGroups
#GatewayPorts no
X11Forwarding no
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
UsePrivilegeSeparation sandbox      # Default for new installations.
PermitUserEnvironment no
#Compression delayed
ClientAliveInterval 300
ClientAliveCountMax 0
#ShowPatchLevel no
#UseDNS yes
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
Banner /etc/issue /etc/issue.net

# Accept locale-related environment variables
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS

# override default of no subsystems
Subsystem   sftp    /usr/libexec/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#   X11Forwarding no
#   AllowTcpForwarding no
#   PermitTTY no
#   ForceCommand cvs server

PasswordAuthentication no
ChallengeResponseAuthentication no
```

**Comment by warroyo** [comment]
I also have this error, The reason it is failing is because the control is looking at `etc/ssh/sshd_config` rather than `/etc/ssh/sshd_config`. it is missing the starting `/` so the file it is describing does not exist

**Comment by YarNhoj** [comment]
So that explains the first set of problems anyway.

**Comment by warroyo** [comment]
It looks like this is happening becuase the Banner method returns a string not an array.

from inspec shell 

```
inspec> sshd_config.Banner
=> "/etc/issue"
```

the test should be 

```
 describe sshd_config do
    its('Banner') { should include ('/etc/issue') }
  end
```

this would catch both issue and issue.net

**Comment by chris-rock** [comment]
@YarNhoj I am confused why its not using `/etc/ssh/sshd_config`. It looks good from source code https://github.com/chef/inspec/blob/master/lib/resources/ssh_conf.rb#L80. Do you use the `sshd_config` resource or do you overwrite the config path manually?

**Comment by YarNhoj** [comment]
@chris-rock The checks above are straight out of the stock Compliance profiles from Chef. The first issue was a poorly written control that doesn't have an / at the beginning of the path. The 'banner' issue is because inspec returns an string not an array. Again that is a control issue. 

The exists? errors I'm still not sure about. This is all bone stock, I don't overwrite anything.

**Comment by chris-rock** [comment]
Thanks for reporting @YarNhoj At this point of time we are already improve the RHEL profiles. Those improvement will be shipped within the next weeks.

Indeed we need to improve the ssh parsing and parse banner as an array.

**Comment by aaronlippold** [comment]
I was having similar problems, the issue I found was that the tests were failing because I was running as vagrant vs 'sudo'.

We need get on that test failed due to permissions to ensure we are chatting the right dragons.

**Comment by jerryaldrichiii** [comment]
I'm seeing a few issues here:

Firstly, an incorrect path (`etc/ssh/sshd_config`) in a Compliance profile. I cannot find the incorrect path in the current profiles. @YarNhoj if you could verify if the controls that were giving you issues are fixed that would be awesome.

Secondly, not using `--sudo`. The sshd_config is only readable/writable by `root` so sudo is needed here. Usually this means passing `--sudo` in when invoking InSpec. Better error handling regarding sudo is a known issue and is being worked. @aaronlippold see: 
 https://github.com/chef/inspec/issues/1778 and https://github.com/chef/inspec/issues/1205

Lastly, InSpec's `sshd_config.Banner` returning a String. As far as I can tell this is the correct behavior. I am unable to use multiple files for that line on CentOS 7.3/Ubuntu 16.04/Ubuntu 14.04. I get the following:

```
vagrant@vagrant:~$ cat /etc/ssh/sshd_config | grep Banner
Banner /etc/issue /etc/issue.net
vagrant@vagrant:~$ /usr/sbin/sshd -f /etc/ssh/sshd_config -D
/etc/ssh/sshd_config line 72: garbage at end of line; "/etc/issue.net".
```

@YarNhoj could you verify that multiple files for the Banner line is supported?

**Comment by jerryaldrichiii** [comment]
Closing this due to its age, please reopen if this is still an issue.
