### ISSUE TITLE
Load errors for aws_plural_resource_mixin

### ISSUE THREAD

**Issue by cameronreyes** [inspec/inspec#5976]
When running the docker inspec image `FROM chef/inspec:5.10.5` we receive errors when trying to run inspec tests. 

# Describe the problem
```yaml
# inspec.yaml snippet

inspec_version: ">= 4.0"
supports:
  - platform: aws

depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/refs/tags/v1.82.1.tar.gz
```

When running `inspec exec policy -t aws:// --input-file policy/inputs.yml --waiver-file policy/waiver.yml --show-progress` we are receiving the following error, and I'm not sure why since we are using the official inspec docker image:

```
Traceback (most recent call last):
        24: from /opt/inspec/bin/inspec:290:in `<main>'
        23: from /opt/inspec/bin/inspec:290:in `load'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-5.10.5/bin/inspec:11:in `<top (required)>'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/base_cli.rb:35:in `start'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/cli.rb:311:in `exec'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/runner.rb:153:in `run'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/runner.rb:102:in `load'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/runner.rb:102:in `each'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/runner.rb:108:in `block in load'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile.rb:399:in `load_gem_dependencies'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile.rb:378:in `load_libraries'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile_context.rb:144:in `load_libraries'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile_context.rb:144:in `each'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile_context.rb:145:in `block in load_libraries'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile_context.rb:160:in `load_library_file'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile_context.rb:171:in `load_with_context'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/profile_context.rb:171:in `instance_eval'
         3: from libraries/aws_iam_policies.rb:3:in `load_with_context'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.10.5/lib/inspec/dsl_shared.rb:33:in `require'
         1: from /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- resource_support/aws/aws_plural_resource_mixin (LoadError)
```

Dockerfile for reference
```
FROM chef/inspec:5.10.5

ARG access_key
ARG secret_access_key
ARG account_id
ENV AWS_ACCOUNT_ID=${account_id}
ENV AWS_ACCESS_KEY_ID=${access_key}
ENV AWS_SECRET_ACCESS_KEY=${secret_access_key}
ENV AWS_DEFAULT_REGION=<redacted>
ENV DEBIAN_FRONTEND=noninteractive

VOLUME ["/project"]

WORKDIR /project
COPY inspec_license /etc/chef/accepted_licenses/inspec

RUN apt-get update -y &&\
    apt-get install -y \
            curl \
            unzip \
            git \
            jq && \
    apt-get clean &&\
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -f awscliv2.zip && \
    curl <redacted> && \
    chmod <redacted> && \
    inspec plugin install train-aws

COPY entrypoint.sh ./entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
```

```bash
# ./entrypoint.sh
#!/bin/bash

source <script to assume aws role>

inspec exec policy -t aws:// --input-file policy/inputs.yml --waiver-file policy/waiver.yml --show-progress
```

As a note, these tests will execute on `FROM chef/inspec:5.1.3` using the same files above.

**Comment by cameronreyes** [comment]
Found our issue was in a library I seemed to miss in the stacktrace above. Removing the library has resolved this issue.
