### ISSUE TITLE
Inspec json resource . example not working

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#631]
### Description

The json inspec resource not working with '.' as separators.
### InSpec and Platform Version

```
$ bin/inspec version
0.18.0
```

OS X 10.11.3
### Replication Case

With the following json file:

```
{
  "cookbook_locks": {
    "omnibus": {
      "version": "2.2.0",
      "identifier": "22b35f3f9273cb8d8b6ac3684cb92f960597ff2f"
    }
  }
}
```

The json inspec resource [documentation](https://docs.chef.io/inspec_reference.html#json) and [example](https://github.com/chef/inspec/blob/67251d2982c719bd3f869b820850e0194db90a41/lib/resources/json.rb#L12-L14) show this:

```
describe json('policyfile.lock.json') do
  its('cookbook_locks.omnibus.version') { should eq('2.2.0') }
end
```

On execution, it gives this error message:

```
$ bin/inspec exec /tmp/json_test.rb
F
Failures:
  1) Json /tmp/Policyfile.lock.json cookbook_locks.omnibus.version
     Failure/Error: with.run_specs(tests)

     NoMethodError:
       undefined method `omnibus' for #<Hash:0x007f8a62c817b8>
     # /tmp/json_test.rb:2:in `block (2 levels) in load'
     # ./lib/inspec/runner_rspec.rb:67:in `run'
     # ./lib/utils/base_cli.rb:70:in `run_tests'
     # ./lib/inspec/cli.rb:113:in `exec'

Finished in 0.00093 seconds (files took 1.06 seconds to load)
1 example, 1 failure

Failed examples:
rspec  # Json /tmp/Policyfile.lock.json cookbook_locks.omnibus.version
```

The workaround I found was to run it like this:

```
describe json('/tmp/Policyfile.lock.json') do
  its(['cookbook_locks','omnibus','version']) { should eq('2.2.0') }
end
```

producing the correct output:

```
$ bin/inspec exec /tmp/json_test.rb
.
Finished in 0.00086 seconds (files took 1.01 seconds to load)
1 example, 0 failures
```

**Comment by chris-rock** [comment]
Unfortunately, this is an issue with `its`. We need to update the documentation for the resource to use:

```
describe json('/tmp/Policyfile.lock.json') do
  its(['cookbook_locks','omnibus','version']) { should eq('2.2.0') }
end
```

for now
