### ISSUE TITLE
Unable to install train plugin in 5.21.29

### ISSUE THREAD

**Issue by rlakey** [inspec/inspec#6411]
I have a custom transport based on the vmware transport that is now failing to install with InSpec 5.21.29 on Windows or Ubuntu.

Getting the following error:

```
C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:360:in `rescue in install_gem_to_plugins_dir': can't activate jwt-2.7.0, already activated jwt-2.6.0 (Inspec::Plugin::V2::InstallError)
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:351:in `install_gem_to_plugins_dir'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:296:in `install_from_gem_file'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:69:in `install'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:213:in `install_from_gemfile'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:121:in `install'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/base_cli.rb:35:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-bin-5.21.29/bin/inspec:11:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:261:in `load'
        from C:/opscode/inspec/bin/inspec:261:in `<main>'
C:/opscode/inspec/embedded/lib/ruby/3.1.0/rubygems/specification.rb:2226:in `check_version_conflict': can't activate jwt-2.7.0, already activated jwt-2.6.0 (Gem::LoadError)
        from C:/opscode/inspec/embedded/lib/ruby/3.1.0/rubygems/specification.rb:1363:in `activate'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:354:in `block in install_gem_to_plugins_dir'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:352:in `each'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:352:in `install_gem_to_plugins_dir'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:296:in `install_from_gem_file'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/installer.rb:69:in `install'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:213:in `install_from_gemfile'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:121:in `install'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/base_cli.rb:35:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-bin-5.21.29/bin/inspec:11:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:261:in `load'
        from C:/opscode/inspec/bin/inspec:261:in `<main>'
```

Same plugin installs fine in prior versions.

The only dependency in the gemspec is `spec.add_dependency "train", "~> 3.8"`

**Comment by Vasu1105** [comment]
Could you please add the step to reproduce this issue?

**Comment by rlakey** [comment]
Download this custom transport from https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/7.0/vsphere/inspec/vmware-vsphere-7.0-stig-baseline/train-vmware-0.1.9.gem

Run `inspec plugin install <path to downloaded gem>`

**Comment by Vasu1105** [comment]
Which other custom plugins are installed on your system that will also help to reproduce as it seems there is a version conflict

**Comment by Vasu1105** [comment]
The `inspec plugin list` command will give a list of all plugins to you. Maybe you can post that list here.

**Comment by rlakey** [comment]
None this was a brand new system with InSpec freshly installed.

**Comment by Vasu1105** [comment]
Ok.  Thanks!! We will address this soon and update you.

**Comment by Vasu1105** [comment]
@Ryan is it possible to get access to `train-vmware` code base?

**Comment by rlakey** [comment]
It's currently not in a publicly accessible location but I can provide whatever bits are relevant. The only dependency I have listed is "spec.add_dependency "train", "~> 3.8".

**Comment by Vasu1105** [comment]
This looks to be a packaging issue. At the time of inspec packaging v5.21.29, the jwt(which is a dependency of googleauth gem) version was v2.6.0. When the Custom plugin is getting installed, it has a train as a dependency that tries to install the latest version of jwt v2.7.0 which results in conflict. In the earlier version, that worked as the `jwt` versions were the same.  So as per my observations, It should get resolved in the next release of the InSpec.

**Comment by rlakey** [comment]
Can I safely remove the train dependency then?

**Comment by aaronlippold** [comment]
Please Mark this with mitre partner

**Comment by Vasu1105** [comment]
> Can I safely remove the train dependency then?

@rlakey Sorry for the late reply, you can try building the gem after removing the dependency and install that gem using inspec plugin install if vmware train transport works properly then you probably don't need it.  Another thing you can try pinning the version to train to "~>3.10" instead of 3.8.

**Comment by Vasu1105** [comment]
Closing this as it seems to work with the latest version of the train and also after removing train dependency as mentioned here https://github.com/vmware/dod-compliance-and-automation/issues/128#issuecomment-1553706109. Reopen if required.
