### ISSUE TITLE
Why file content test fails

### ISSUE THREAD

**Issue by anniehedgpeth** [inspec/inspec#734]
### Description

I'm going through Nathen Harvey's workshop to learn more, and I came across this issue.

When I run the command from the CIS documentation with sudo...

```
sudo grep "^password" /etc/grub.conf
```

...it returns with...

```
password --md5 $1$Y8nxm$gfnWWe24KdOJThpAL1Wci/
```

But when I run the InSpec code...

``` ruby
control "cis-1-5-3" do
  impact 1.0
  title "1.5.3 Set Boot Loader Password (Scored)"
  desc "Setting the boot loader password will require that the person who is rebooting the must enter a password before being able to set command line boot parameters."
  describe file("/etc/grub.conf") do
    its(:content) { should match /^password/ }
  end
end
```

...the test fails (see below).
### InSpec and Platform Version

I'm on InSpec version 0.21.0.
I'm testing on a MacBook Pro against a CentOS 6.7.
### Replication Case

Edit grub.conf to include a password with encryption as stated in CIS remediation for CentOS Linux 6 v1.1.0 
1.5.3 Set Boot Loader Password

Then run

``` ruby
control "cis-1-5-3" do
  impact 1.0
  title "1.5.3 Set Boot Loader Password (Scored)"
  desc "Setting the boot loader password will require that the person who is rebooting the must enter a password before being able to set command line boot parameters."
  describe file("/etc/grub.conf") do
    its(:content) { should match /^password/ }
  end
end
```

I expected it to pass, and it failed.
### Possible Solutions

Is it possible that it failed because the ssh session created by InSpec doesn't have sudo privileges? 
### Stacktrace

```
.....F

Failures:

  1) File /etc/grub.conf content should match /^password/
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected nil to match /^password/
     # test/1_spec.rb:43:in `block (3 levels) in load'
     # /Users/anniehedgpeth/.chefdk/gem/ruby/2.1.0/gems/inspec-0.21.0/lib/inspec/runner_rspec.rb:65:in `run'
     # /Users/anniehedgpeth/.chefdk/gem/ruby/2.1.0/gems/inspec-0.21.0/lib/utils/base_cli.rb:68:in `run_tests'
     # /Users/anniehedgpeth/.chefdk/gem/ruby/2.1.0/gems/inspec-0.21.0/lib/inspec/cli.rb:111:in `exec'

Finished in 0.47926 seconds (files took 1.86 seconds to load)
6 examples, 1 failure

Failed examples:

rspec  # File /etc/grub.conf content should match /^password/
```

**Comment by chris-rock** [comment]
@anniehedgpeth You are right, InSpec has only the rights of the user. Since you can grab the file with sudo only, you need to pass the sudo options for each run. You see all available options via:

```
inspec help exec
Usage:
  inspec exec PATHS

Options:
  t, [--target=TARGET]                     # Simple targeting option using URIs, e.g. ssh://user:pass@host:port
  b, [--backend=BACKEND]                   # Choose a backend: local, ssh, winrm, docker.
      [--host=HOST]                        # Specify a remote host which is tested.
  p, [--port=N]                            # Specify the login port for a remote scan.
      [--user=USER]                        # The login user for a remote scan.
      [--password=PASSWORD]                # Login password for a remote scan, if required.
  i, [--key-files=one two three]           # Login key or certificate file for a remote scan.
      [--path=PATH]                        # Login path to use when connecting to the target (WinRM).
      [--sudo], [--no-sudo]                # Run scans with sudo. Only activates on Unix and non-root user.
      [--sudo-password=SUDO_PASSWORD]      # Specify a sudo password, if it is required.
      [--sudo-options=SUDO_OPTIONS]        # Additional sudo options for a remote scan.
      [--ssl], [--no-ssl]                  # Use SSL for transport layer encryption (WinRM).
      [--self-signed], [--no-self-signed]  # Allow remote scans with self-signed certificates (WinRM).
      [--json-config=JSON_CONFIG]          # Read configuration from JSON file (`-` reads from stdin).
  l, [--log-level=LOG_LEVEL]               # Set the log level: info (default), debug, warn, error
      [--profiles-path=PROFILES_PATH]      # Folder which contains referenced profiles.
      [--controls=one two three]           # A list of controls to run. Ignore all other tests.
      [--format=FORMAT]                    # Which formatter to use: progress, documentation, json
      [--color], [--no-color]              # Use colors in output.
                                           # Default: true
      [--diagnose], [--no-diagnose]        # Show diagnostics (versions, configurations)

run all test files at the specified PATH.
```

In your case, you need to run the test with the `--sudo` option. If required, we also support the `--sudo-password` option. In your case this should look like:

```
inspec exec test.rb -t ssh://root@192.168.64.2:11022 -i vagrant --sudo
```

The same is available if you use Chef Compliance, but you have to disable sudo explicitly

<img width="1148" alt="screen shot 2016-05-11 at 1 13 33 pm" src="https://cloud.githubusercontent.com/assets/1178413/15179125/3c9f6fc2-177a-11e6-8ae7-c910113a8330.png">

**Comment by aaronlippold** [comment]
I wonder if this is a good case where more specific failure feedback would be useful. i.e. should the test have failed with 'couldn't read file' or 'need escalated privilege' etc?

**Comment by anniehedgpeth** [comment]
Yes, exactly. We discussed the issue, and I believe that's the plan - to have better feedback for failed tests. Thanks!
