### ISSUE TITLE
need stricter type checking on arguments with better error messages and/or coercion

### ISSUE THREAD

**Issue by lamont-granquist** [inspec/inspec#753]
this (incorrect) inspec code:

``` ruby
describe port('22') do
  it { should be_listening }
  its('protocols') { should include 'tcp' }
  its('processes') { should eq ['sshd'] }
end
```

produces unhelpful error messages.  either the argument should be coerced to an int, or else strict type checking should be used so that if the user does not enter an integer that it raises a more useful error.

```
Failures:

  1) Port  22 should be listening
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected `Port  22.listening?` to return true, got false
     # ./test/integration/webapp/default_spec.rb:109:in `block (2 levels) in load'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/inspec-0.20.1/lib/inspec/runner_rspec.rb:67:in `run'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/kitchen-inspec-0.12.5/lib/kitchen/verifier/inspec.rb:47:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:423:in `block in verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:478:in `block in action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:477:in `action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:415:in `verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:348:in `block in transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `each'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:160:in `verify'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `public_send'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

  2) Port  22 protocols should include "tcp"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected nil to include "tcp", but it does not respond to `include?`
     # ./test/integration/webapp/default_spec.rb:110:in `block (2 levels) in load'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/inspec-0.20.1/lib/inspec/runner_rspec.rb:67:in `run'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/kitchen-inspec-0.12.5/lib/kitchen/verifier/inspec.rb:47:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:423:in `block in verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:478:in `block in action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:477:in `action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:415:in `verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:348:in `block in transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `each'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:160:in `verify'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `public_send'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

  3) Port  22 processes should eq ["sshd"]
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: ["sshd"]
            got: nil

       (compared using ==)
     # ./test/integration/webapp/default_spec.rb:111:in `block (2 levels) in load'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/inspec-0.20.1/lib/inspec/runner_rspec.rb:67:in `run'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/kitchen-inspec-0.12.5/lib/kitchen/verifier/inspec.rb:47:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:423:in `block in verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:478:in `block in action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:477:in `action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:415:in `verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:348:in `block in transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `each'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:160:in `verify'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `public_send'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

Finished in 1.56 seconds (files took 0.77539 seconds to load)
52 examples, 3 failures

Failed examples:

rspec  # Port  22 should be listening
rspec  # Port  22 protocols should include "tcp"
rspec  # Port  22 processes should eq ["sshd"]
```

**Comment by chris-rock** [comment]
We should add a warning for a non-integer type and remove the stacktrace. We are working on a new formatter that outputs better results

**Comment by kekaichinose** [comment]
@lamont-granquist apologies for the late follow-up here, but we still seeing this in the latest version of InSpec? If so, I'd like to get this prioritized in the next couple sprints. Thanks!

**Comment by clintoncwolfe** [comment]
inspec-aws uses this parameter validation method:
https://github.com/inspec/inspec-aws/blob/f46b1f38ad67980e18f81fa9cea49d9d660767e3/libraries/aws_backend.rb#L194

**Comment by kekaichinose** [comment]
I have not seen any updates on this, and the issue has aged by 4 years now. If there are any occurrences of this you are seeing in the latest versions of InSpec, please file a new issue with latest examples. Closing.
