### ISSUE TITLE
Intermittent failure in resource tests

### ISSUE THREAD

**Issue by stevendanna** [inspec/inspec#862]
### Description

When running the resource tests:

```
bundle exec rake test:resources config=test/test.yaml
```

some platforms will fail with the following:

```
Client error, can't connect to 'docker' backend: Train::Transports::Docker does not implement #connect()
/Users/sdanna/oc/code/opscode/inspec/lib/inspec/backend.rb:42:in `rescue in create'
/Users/sdanna/oc/code/opscode/inspec/lib/inspec/backend.rb:16:in `create'
/Users/sdanna/oc/code/opscode/inspec/lib/inspec/runner.rb:50:in `configure_transport'
/Users/sdanna/oc/code/opscode/inspec/lib/inspec/runner.rb:34:in `initialize'
test/docker_test.rb:44:in `new'
test/docker_test.rb:44:in `test_container'
test/docker_test.rb:30:in `block (2 levels) in run'
/Users/sdanna/oc/code/opscode/inspec/test/docker_run.rb:52:in `call'
/Users/sdanna/oc/code/opscode/inspec/test/docker_run.rb:52:in `block in run_on_target'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/safe_task_executor.rb:25:in `call'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/safe_task_executor.rb:25:in `block in execute'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/synchronization/mutex_object.rb:18:in `block in synchronize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/synchronization/mutex_object.rb:18:in `synchronize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/synchronization/mutex_object.rb:18:in `synchronize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/safe_task_executor.rb:20:in `execute'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/promise.rb:524:in `block in realize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:331:in `call'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:331:in `run_task'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (3 levels) in create_worker'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `loop'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `block (2 levels) in create_worker'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `catch'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `block in create_worker'
/Users/sdanna/oc/code/opscode/inspec/test/docker_run.rb:59:in `rescue in block in run_on_target'
/Users/sdanna/oc/code/opscode/inspec/test/docker_run.rb:50:in `block in run_on_target'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/safe_task_executor.rb:25:in `call'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/safe_task_executor.rb:25:in `block in execute'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/synchronization/mutex_object.rb:18:in `block in synchronize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/synchronization/mutex_object.rb:18:in `synchronize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/synchronization/mutex_object.rb:18:in `synchronize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/safe_task_executor.rb:20:in `execute'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/promise.rb:524:in `block in realize'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:331:in `call'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:331:in `run_task'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (3 levels) in create_worker'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `loop'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `block (2 levels) in create_worker'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `catch'
/Users/sdanna/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `block in create_worker'
```

This appears to be caused by the container taking too long to create.  Usually the subsequent run will work.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
