### ISSUE TITLE
Error when processing  certain IPv6 addresses when using port()

### ISSUE THREAD

**Issue by nvtkaszpir** [inspec/inspec#897]
### Description

For certain IP addresses I get error:

```
Could not parse fe80::4e:8bff:feba::123, bad URI(is not URI?): addr://[fe80::4e:8bff:feba:]:123
Could not parse fe80::4e:8bff:feba::123, bad URI(is not URI?): addr://[fe80::4e:8bff:feba:]:123

Could not parse fe80::4fe:6ff:fe04::123, bad URI(is not URI?): addr://[fe80::4fe:6ff:fe04:]:123
Could not parse fe80::4fe:6ff:fe04::123, bad URI(is not URI?): addr://[fe80::4fe:6ff:fe04:]:123
```

The most interesting part is that it happened only for those 2 addresses only, from the pool of 8:

```
fe80::40a:15ff:febc:3625/64
fe80::423:34ff:fe73:5159/64
fe80::46e:42ff:fecc:bb99/64
fe80::46f:52ff:fed4:6ba1/64
fe80::4c6:34ff:fe36:ffff/64
fe80::4e:8bff:feba:44c5/64
fe80::4ea:dcff:fe7a:6bb1/64
fe80::4fe:6ff:fe04:5aa7/64

```
### InSpec and Platform Version

```
InSpec version: 0.29.0
Train version: 0.16.0
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]

Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
```

full run:

```
InSpec version: 0.29.0
Train version: 0.16.0
Command line configuration:
{"color"=>true,
 "profiles_path"=>"inspec/",
 "target"=>"ssh://ubuntu@redacted",
 "key_files"=>["/home/kaszpir/.ssh/redacted"],
 "diagnose"=>true}
JSON configuration file:
{}
Merged configuration:
{"color"=>true,
 "profiles_path"=>"inspec/",
 "target"=>"ssh://ubuntu@redacted",
 "key_files"=>["/home/kaszpir/.ssh/redacted"],
 "diagnose"=>true}

Could not parse fe80::4e:8bff:feba::123, bad URI(is not URI?): addr://[fe80::4e:8bff:feba:]:123
Could not parse fe80::4e:8bff:feba::123, bad URI(is not URI?): addr://[fe80::4e:8bff:feba:]:123

Profile: InSpec Profile (jmeter-master)
Version: 0.1.0
Target:  ssh://ubuntu@redacted:22

  ✔  jmeter-xrdp-001: xrdp package should be installed
  ✔  jmeter-xrdp-002: x11rdp package should be installed
  ✖  jmeter-xrdp-003: xrdp should be listening on 3389 (1 failed)
     expected [] to include "xrdp"
  ✖  jmeter-xrdp-004: xrdp-sesman should be listening on 3350 (1 failed)
     expected [] to include "xrdp-sesman"
  ✔  jmeter-xrdp-005: xscreensaver should be disabled
  ✔  jmeter-xrdp-006: lxde package should be installed
  ✔  jmeter-xrdp-007: gedit package should be installed
  ✔  jmeter-user-001-xscreensaver-jmeter: xscreensaver should be disabled for user jmeter
  ✔  jmeter-user-002: Check installdir owner, group and permissions
  ✔  fabric-001: fabric package should be installed
  ✔  fabric-002: python package should be installed
  ✔  tools-001: screen package should be installed
  ✔  tools-002: bzip2 package should be installed
  ✔  jmeter-master-001: Check workdir owner, group and permissions
  ✔  jmeter-master-002: Check installdir owner, group and permissions

Summary: 24 successful, 2 failures, 0 skipped
```
### Replication Case

Created 8 instances in AWS EC2, 1 master, 7 slaves, only master and one slave shows this behaviour.
All machines are done from the same AMI and then puppet is applied.
Those instances will be alive up to 24h.
### Possible Solutions

No solutions.
### Stacktrace

No stacktrace.

**Comment by nvtkaszpir** [comment]
Notice that it also refers to #899

**Comment by mengesb** [comment]
I get similar results when matching against tcp6 sets:

```
  1) Port 8983 should be listening
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected `Port 8983.listening?` to return true, got false
     # ./test/integration/default/controls/chef_server_spec.rb:17:in `block (2 levels) in load_with_context'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/inspec-1.3.0/lib/inspec/runner_rspec.rb:77:in `run'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/inspec-1.3.0/lib/inspec/runner.rb:112:in `run_tests'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/inspec-1.3.0/lib/inspec/runner.rb:96:in `run'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/inspec_runner.rb:28:in `evaluate'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:44:in `block in execute'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:43:in `tap'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:43:in `execute'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/group.rb:30:in `block in evaluate'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/client.rb:54:in `each'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/client.rb:54:in `block in output_value'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/command_executor.rb:25:in `execute'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/client.rb:50:in `output_value'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:60:in `resolve_hostnames'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/group.rb:27:in `evaluate'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:38:in `block in call'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:38:in `each'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:38:in `call'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:430:in `block in verify_action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:520:in `synchronize_or_call'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:485:in `block in action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:484:in `action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:422:in `verify_action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:355:in `block in transition_to'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `each'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `transition_to'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:160:in `verify'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `public_send'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `run_action_in_thread'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'

  2) Port 8983 protocols should include "tcp"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected [] to include "tcp"
     # ./test/integration/default/controls/chef_server_spec.rb:18:in `block (2 levels) in load_with_context'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/inspec-1.3.0/lib/inspec/runner_rspec.rb:77:in `run'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/inspec-1.3.0/lib/inspec/runner.rb:112:in `run_tests'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/inspec-1.3.0/lib/inspec/runner.rb:96:in `run'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/inspec_runner.rb:28:in `evaluate'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:44:in `block in execute'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:43:in `tap'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:43:in `execute'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/group.rb:30:in `block in evaluate'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/client.rb:54:in `each'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/client.rb:54:in `block in output_value'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/command_executor.rb:25:in `execute'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/client.rb:50:in `output_value'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:60:in `resolve_hostnames'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/terraform/group.rb:27:in `evaluate'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:38:in `block in call'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:38:in `each'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/kitchen-terraform-0.3.0/lib/kitchen/verifier/terraform.rb:38:in `call'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:430:in `block in verify_action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:520:in `synchronize_or_call'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:485:in `block in action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:484:in `action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:422:in `verify_action'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:355:in `block in transition_to'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `each'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `transition_to'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:160:in `verify'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `public_send'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `run_action_in_thread'
     # /Users/<username>/.chefdk/gem/ruby/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
```

The netstat -na output that should be matched is:

```
[root@chef ~]# netstat -na | grep 8983
tcp6       0      0 127.0.0.1:8983          :::*                    LISTEN
```

Example output (snipped):

```
Port 4321
Could not parse 127.0.0.1:8983, bad URI(is not URI?): addr://[127.0.0.1]:8983
  should be listening
  protocols
    should include "tcp"

Port 8983
Could not parse 127.0.0.1:8983, bad URI(is not URI?): addr://[127.0.0.1]:8983
  should be listening (FAILED - 1)
  protocols
    should include "tcp6" (FAILED - 2)

Port 9683
Could not parse 127.0.0.1:8983, bad URI(is not URI?): addr://[127.0.0.1]:8983
  should be listening
  protocols
    should include "tcp"
```

It gives me that parsing error for every port inspec test that I run.

**Comment by miah** [comment]
Possibly related: #3962
